### ISSUE TITLE
Wrong floats deserialization on x64

### ISSUE THREAD

**Issue by rsamoilov** [ohler55/oj#181]
Hi there,

On our project, we've encountered an issue with floats deserialization. Oj incorrectly deserializes float values (only some of them).
The bug is reproduced only on machines with 64 bit OS on ruby 1.9.3 - 2.1.2 and rbx.
Oj version - 2.6.0 and 2.9.9.
OS - Ubuntu, CentOS

2.1.2 :006 >   Oj.load '1.89'
 => 1.8900000000000001 
2.1.2 :008 > Oj.load '1.82'
 => 1.8199999999999998 
2.1.2 :012 > Oj.load '1.39'
 => 1.3900000000000001 
2.1.2 :013 > Oj.load '2.28'
 => 2.2800000000000002 
2.1.2 :016 >   Oj.load '2.29'
 => 2.29

**Comment by BuonOmo** [comment]
I still get the same issue in `3.7.12` (Ruby `2.5.3`, although I guess it doesn't matter):

```rb
> Oj.strict_load("48.949268")
 => 48.949268000000004 
```

**Comment by ohler55** [comment]
This issue was closed almost 5 years ago. If you would like to open a new issue I can take a look at fixing the it as a new issue.
