### ISSUE TITLE
Need a way to detect a broken socket with the ScParser

### ISSUE THREAD

**Issue by dchelimsky** [ohler55/oj#209]
Given:

```ruby
class ParseHandler
  def add_value(v) p v end
  def hash_start() {} end
  def hash_set(h,k,v) h.store(k,v) end
  def array_start() [] end
  def array_append(a,v) a << v end
  def error(message, line, column)
    raise Exception.new(message, line, column)
  end
end

Oj.sc_parse(ParseHandler.new, connect_socket)
```

How can I detect when the socket is broken?

**Comment by ohler55** [comment]
I fixed the test to create a server and client along with a close in the middle of the parsing. As expected an exception is raised.

**Comment by dchelimsky** [comment]
What if it closes between messages (i.e. there is no parsing happening at that moment)?

**Comment by ohler55** [comment]
It will fail when it tries to read again. Give it a try. It raises an exception.

**Comment by ohler55** [comment]
No response, closing.

**Comment by dchelimsky** [comment]
Additional context: we don't see an exception when either the process on the other side of the socket or the network connection dies. This is not the same as the socket being explicitly closed.

It might be a few days (or weeks) before I can return to this, but I'll try to get you a reliably failing test case. When I get there, do you prefer to re-open this issue or start a new one?

**Comment by ohler55** [comment]
Either reopen or start a new one. Either way. You realize that there are not notification callback for when a socket dies. The only way to find out is to attempt a read and fail. Oj will never be able to provide feature that the underlying OS does not provide.
