### ISSUE TITLE
Using oj in Rails 4.1 ActionDispatch::ParamsParser

### ISSUE THREAD

**Issue by andrewbaker00** [ohler55/oj#210]
Will rails 4.1 use oj to parse json params in ParamsParser automaticall or does one have to tell rails to use oj explicitly for this case?

Gems used:
gem 'oj'
gem 'oj_mimic_json'

**Comment by ohler55** [comment]
Can this issue be closed or do you have have some additional input?

**Comment by andrewbaker00** [comment]
@ohler55 Sorry for the delayed response but was out for christmas holiday. 

I just tested this out and it does look like OJ is being used by Rails in the default params parsing for controller actions when using the 'oj_mimic_json' gem out of the box.

I am seeing about a 40 percent performance boost on ParamsParser calls for 'large' json data sets!

Thanks very much

**Comment by ohler55** [comment]
I like to hear that.
