### ISSUE TITLE
Use SIMD instructions for 68% - 90% faster parsing

### ISSUE THREAD

**Issue by ahacking** [ohler55/oj#213]
This is more a heads up than a request.

An [interesting post](http://blog.kazuhooku.com/2014/12/improving-parser-performance-using-sse.html) on using SIMD based instructions in the ultra fast PicoHTTPParser to speed up HTTP parsing by 68% - 90%.

The same technique for string scanning could potentially be adopted for use in parsing within *Oj*.

The optimisation in question boils down to the following code ([original code here](https://github.com/h2o/picohttpparser/blob/23b8a0308a540620729ce3f4c5d61db547831cad/picohttpparser.c#L92)):
```C
#include <stddef.h>
#ifdef __SSE4_2__
# include <x86intrin.h>
#endif

#if __GNUC__ >= 3
# define likely(x) __builtin_expect(!!(x), 1)
# define unlikely(x) __builtin_expect(!!(x), 0)
#else
# define likely(x) (x)
# define unlikely(x) (x)
#endif

static const char* findchar_fast(const char* buf, const char* buf_end, const char *ranges, size_t ranges_size, int* found)
{
  *found = 0;
#if __SSE4_2__
  if (likely(buf_end - buf >= 16)) {
    __m128i ranges16 = _mm_loadu_si128((const __m128i*)ranges);

    size_t left = (buf_end - buf) & ~15;
    do {
      __m128i b16 = _mm_loadu_si128((void*)buf);
      int r = _mm_cmpestri(ranges16, ranges_size, b16, 16, _SIDD_LEAST_SIGNIFICANT | _SIDD_CMP_RANGES | _SIDD_UBYTE_OPS);
      if (unlikely(r != 16)) {
        buf += r;
        *found = 1;
        break;
      }
      buf += 16;
      left -= 16;
    } while (likely(left != 0));
  }
#endif
  return buf;
}
```

Code may need to be compiled with -msse (gcc) or -x (Intel) but that may be optional depending on the optimisation level (eg if -O3 is used).

There is also an interesting [overview on SIMD for XML parsing by Intel](https://software.intel.com/en-us/articles/xml-parsing-accelerator-with-intel-streaming-simd-extensions-4-intel-sse4).

**Comment by ohler55** [comment]
Interesting point but right now the biggest bottleneck are the Ruby calls. The actual parsing is very fast as evident with the OjC parse which is a derivative work. Thanks for the posting.
