### ISSUE TITLE
Oj mimic_JSON does poor job mimicking when encoding object of Array-subclass

### ISSUE THREAD

**Issue by libc** [ohler55/oj#214]
Hi there,

The minimal repro case:
```ruby
2.2.0 :001 > require 'json'
 => true 
2.2.0 :002 > class Blah < Array; end
 => nil 
2.2.0 :003 > JSON.load(JSON.dump(Blah.new([1, 2])))
 => [1, 2] 
2.2.0 :004 > require 'oj'
 => true 
2.2.0 :005 > Oj.mimic_JSON
 => JSON 
2.2.0 :006 > JSON.load(JSON.dump(Blah.new([1, 2])))
 => {"^o"=>"Blah", "self"=>[1, 2]} 
2.2.0 :007 > Oj.load(Oj.dump(Blah.new([1, 2])))
 => {"^o"=>"Blah", "self"=>[1, 2]} 
```

Seems to encode fine before mimicking
```ruby
2.2.0 :004 > Oj.load(Oj.dump(Blah.new([1, 2])))
 => [1, 2] 
2.2.0 :005 > Oj.mimic_JSON
 => JSON 
2.2.0 :006 > Oj.load(Oj.dump(Blah.new([1, 2])))
 => {"^o"=>"Blah", "self"=>[1, 2]} 
2.2.0 :007 > Oj.load(Oj.dump(Blah.new([1, 2])))
 => {"^o"=>"Blah", "self"=>[1, 2]} 
```

Broke for us resque with composite-primary-keys gem

Cheers,

**Comment by libc** [comment]
Correction: It encodes differently from JSON before mimicking too, but doesn't fail to roundtrip.

**Comment by ohler55** [comment]
In mimic mode the compat encoding is used to match the json gem. That encoding is not a bidirectional encoding. Having said that, it looks like the default mode is not being set so I will check on that. The round trip should be the same as the json gem and return an Array as you see. Note that it is an Array and not a Blah.

**Comment by libc** [comment]
I do expect Array as the output. Thanks for checking on mimic.

**Comment by ohler55** [comment]
Oj 2.11.2 released with the fix.

**Comment by ohler55** [comment]
No response, closing as unit test indicate it is fixed.

**Comment by libc** [comment]
Thanks
