### ISSUE TITLE
Oj ignores nanoseconds in datetime

### ISSUE THREAD

**Issue by toy** [ohler55/oj#215]
```ruby
require 'oj'

time = Time.now
values = [time, time.to_date, time.to_datetime]
{
  Marshal: proc{ |data| Marshal.load(Marshal.dump(data)) },
  Oj: proc{ |data| Oj.load(Oj.dump(data)) },
}.each do |serializer_name, serializer|
  puts "=== #{serializer_name} ==="
  values.each do |original|
    piped = serializer[original]
    puts "#{original.class}: #{original == piped ? '==' : '!='}"
    p original, piped
    puts
  end
end
```
output:
```
=== Marshal ===
Time: ==
2015-01-17 21:35:41 +0100
2015-01-17 21:35:41 +0100

Date: ==
#<Date: 2015-01-17 ((2457040j,0s,0n),+0s,2299161j)>
#<Date: 2015-01-17 ((2457040j,0s,0n),+0s,2299161j)>

DateTime: ==
#<DateTime: 2015-01-17T21:35:41+01:00 ((2457040j,74141s,385318000n),+3600s,2299161j)>
#<DateTime: 2015-01-17T21:35:41+01:00 ((2457040j,74141s,385318000n),+3600s,2299161j)>

=== Oj ===
Time: ==
2015-01-17 21:35:41 +0100
2015-01-17 21:35:41 +0100

Date: ==
#<Date: 2015-01-17 ((2457040j,0s,0n),+0s,2299161j)>
#<Date: 2015-01-17 ((2457040j,0s,0n),+0s,2299161j)>

DateTime: !=
#<DateTime: 2015-01-17T21:35:41+01:00 ((2457040j,74141s,385318000n),+3600s,2299161j)>
#<DateTime: 2015-01-17T21:35:41+01:00 ((2457040j,74141s,0n),+3600s,2299161j)>
```

**Comment by ohler55** [comment]
I'll see what I can do. It would be easy of DateTime provided a method to get the seconds with fractional part. It looks like I'll have to use the :sec and :sec_fraction and add the two together. At least the construction supports seconds as floating point.

**Comment by toy** [comment]
If I understood correctly you are dumping attributes of instances of "odd" classes, so I see that it will be not straight forward. Also `sec_fraction` behaviour is different in ruby 1.8 - it returns second fraction for the day so should be multiplied by 24 * 60 * 60.

**Comment by ohler55** [comment]
I've started on a solution but it is good to know 1.8 is different. Thanks for that input. It will save me some head scratching later.

**Comment by ohler55** [comment]
I just pushed a fix to github if you'd like to check it out. I plan on releasing it tomorrow if there are no problems with it.

**Comment by toy** [comment]
Thanks for fixing this so fast Peter! Just checked — works for me.

**Comment by ohler55** [comment]
Glad I could get it fixed quickly. I'll release tomorrow.

**Comment by toy** [comment]
Ops, seems I've found a precision issue that appears only in 1.8 and 1.9.2. Works well for 1.9.3, 2.0.0, 2.1.5 and 2.2.0.
```rb
gem 'oj', '= 2.11.3b1'
require 'oj'

[
  Time.local(2000, 'jan', 1, 20, 15, 1, 1000).send(:to_datetime),
].each do |original|
  serialised = Oj.dump(original)
  piped = Oj.load(serialised)
  puts "#{original.class}: #{original == piped ? '==' : '!='}"
  p original, piped
  puts serialised
  puts
end
```
```
===[1.8.7-p375]=========================================================
DateTime: !=
#<DateTime: 211813514101001/86400000,1/24,2299161>
#<DateTime: 211813514101000999999/86400000000000,1/24,2299161>
{"^O":"DateTime","year":2000,"month":1,"day":1,"hour":20,"min":15,"sec":{"^O":"Rational","numerator":1000999999,"denominator":1000000000},"offset":{"^O":"Rational","numerator":1,"denominator":24},"start":2299161}


===[1.9.2-p330]=========================================================
DateTime: !=
#<DateTime: 2000-01-01T20:15:01+01:00 (211813514101001/86400000,1/24,2299161)>
#<DateTime: 2000-01-01T20:15:01+01:00 (14555713854634146173813/5937362789990400,1/24,2299161)>
{"^O":"DateTime","year":2000,"month":1,"day":1,"hour":20,"min":15,"sec":1.001,"offset":{"^O":"Rational","numerator":1,"denominator":24},"start":2299161}


===[1.9.3-p551]=========================================================
DateTime: ==
#<DateTime: 2000-01-01T20:15:01+01:00 ((2451545j,69301s,1000000n),+3600s,2299161j)>
#<DateTime: 2000-01-01T20:15:01+01:00 ((2451545j,69301s,1000000n),+3600s,2299161j)>
{"^O":"DateTime","year":2000,"month":1,"day":1,"hour":20,"min":15,"sec":1.001,"offset":{"^O":"Rational","numerator":1,"denominator":24},"start":2299161.0}
```

**Comment by ohler55** [comment]
I can most likely get the 1.8.7 to round off better but the 1.9.2 is going to be tough to change as all the inputs to the initializer are the same as 1.9.3 but the resulting DateTime object is different. I'd claim that is an issue with 1.9.2. You can test that by creating a DateTime as I do in the test_object.rb file. Near the bottom of the file is a DateTime test. I'll update that with one that has rounding issues and get it fixed in 1.8.7.

**Comment by ohler55** [comment]
I think I have a way to make it work. Will have it out later tonight.

**Comment by toy** [comment]
Thank you for updates. One solution I can think of is to use Rational for storing seconds, but this may be heavy.

**Comment by ohler55** [comment]
That is the plan. :-)

**Comment by ohler55** [comment]
Pushed another version with the change.

**Comment by toy** [comment]
Just checked — works for all ruby versions I have. Thank you very much Peter!
