### ISSUE TITLE
Replacing Marshal - writing/reading objects consecutively 

### ISSUE THREAD

**Issue by toy** [ohler55/oj#216]
Using `Marshal` I can dump multiple objects to an io and then load them until EOF. This helps if I have an external source/destination of data and I don't want to load all data at once.

But json doesn't have any separators, so if I dump and read multiple objects, I will get either wrong data (multiple simple values get glued) or errors (for multiple arrays, hashes). One solution is to use lines, but is there a better one using `Oj`?

Seems I can use `Oj::StreamWriter` to write to io but can't find effective way to read it.

```rb
require 'stringio'
require 'oj'

data = 'a'..'z' # consider an enumerable yielding many times from external source

puts 'Using Marshal'
io = StringIO.new
data.each do |o|
  Marshal.dump(o, io)
end
io.rewind
p Marshal.load(io) until io.eof?

puts 'Using Oj'
io = StringIO.new
data.each do |o|
  io.puts Oj.dump(o)
end
io.rewind
p Oj.load(io.gets) until io.eof?

puts 'Write using Oj::StreamWriter'
io = StringIO.new
sr = Oj::StreamWriter.new(io)
sr.push_array
data.each do |o|
  sr.push_value(o)
end
sr.pop
```

**Comment by ohler55** [comment]
I guess I should update the documentation. Try giving the Oj.load a block with a single argument. I'll update the docs for this next release.

**Comment by toy** [comment]
You mean like `Oj.load(io){ |o| p o }`? But this will read the entire array.

**Comment by ohler55** [comment]
I'm adding this test.
```
    json = %{{"a":1}
[1,2][3,4]
{"b":2}
}
    results = []
    Oj.load(json) { |x| results << x }
    assert_equal([{"a"=>1}, [1,2], [3,4], {"b"=>2}], results)
```

**Comment by ohler55** [comment]
You are correct that the entire document will be read. A callback is made for each complete JSON entity in the string or file. I use this for parsing JSON log files. I all fairness though, most of the time I use the OjC for parsing log files. It is much faster.

**Comment by toy** [comment]
Your example looks promising — so I can simply dump multiple objects and then read them.
Accidentally I found an unexpected behaviour, if I understand correctly number literal on its own is a valid json. Following code outputs `0` forever:
```rb
Oj.load(StringIO.new('0')){ |o| p o }
```

**Comment by ohler55** [comment]
Well, thats not right. a number is a valid JSON but it should not repeat forever. I'll look into that and fix it before the next release.

**Comment by ohler55** [comment]
Fixed and push to github.

**Comment by toy** [comment]
Thank you for help and fixes!

**Comment by ohler55** [comment]
It's good to have someone finding issues. Thanks.
