### ISSUE TITLE
Support for Network Streaming

### ISSUE THREAD

**Issue by sunny-tdw** [ohler55/oj#217]
I've been trying to implement stream parsing in segments from Net::HTTP. I was looking at https://github.com/ohler55/oj/blob/64cf2ec29c5157a8ba491c8030daabbb4c053eef/ext/oj/saj.c#L687 and it doesn't seem like there's any support for generic chunked file reading other than using the Ruby File class. How would I go about implementing this?

**Comment by ohler55** [comment]
I must have missed the email notification on this one. Oj has 3 different parsers. The saj parser is deprecated in favor of the scp parser which will continue reading from an IO object until the object is closed. The scp parser is a callback parser similar to saj. Note that the primary parser also supports streams and will give callbacks for each completed JSON document read.

**Comment by ohler55** [comment]
No response, closing.
