### ISSUE TITLE
UTC Time dump/load inconsistency in :object mode

### ISSUE THREAD

**Issue by crazyshot** [ohler55/oj#220]
Hi,
I found that in :object mode time is always loaded in current timezone, which is a problem when dumping UTC Time object and assuming that loaded Time object is still UTC.

[36] pry(main)> time = Time.now.utc
=> 2015-02-23 15:12:20 UTC
[37] pry(main)> Oj.load(Oj.dump(time, mode: :object), mode: :object)
=> 2015-02-23 17:12:20 +0200

Your tests are not failing because time compares its UTC timestamp:
[39] pry(main)> time = Time.now
=> 2015-02-23 17:12:51 +0200
[40] pry(main)> time2 = time.clone.utc
=> 2015-02-23 15:12:51 UTC
[41] pry(main)> time == time2
=> true

You should probably save current timezone inside serialized string.

**Comment by ohler55** [comment]
I'll check it over the next couple of days.

**Comment by crazyshot** [comment]
Thanks. In my project i currently worked around it, since all my time
fields are utc, i just force them back into utc. But ruby is slow and it
takes almost same time as parsing itself.

**Comment by ohler55** [comment]
In the near term you can use the time_format :ruby or :xmlschema option when dumping. That will preserve the time zone. I've been mulling over some options for keeping the timezone in the :unix encoding but have to consider backward compatibility so maybe another time_format option will be needed.

**Comment by crazyshot** [comment]
Still doesn't work:
[68] pry(main)> Oj.load(Oj.dump(Time.now.utc, time_format: :ruby))
=> 2015-02-26 09:17:33 +0200

**Comment by ohler55** [comment]
With Ruby 2.2.0 I get this:

irb(main):001:0> Oj.load(Oj.dump(Time.now.utc, time_format: :ruby))
=> 2015-02-26 15:04:34 +0000

Help me figure out what is different in out environments. I am using OS X Mavericks, no other gems were loaded. Can you describe what your environment is?

**Comment by crazyshot** [comment]
I'm using ruby 2.0.0. I'll install 2.2.0 and retry.

**Comment by crazyshot** [comment]
Have a look at something interesting. I don't know what you're using
internally for Time parsing, but when I manually change "+00:00" to "Z",
it's iso8601 standard and Oj loads it as it desired:

2.1.5 :003 > Oj.dump(Time.now.utc, :time_format => :xmlschema)
 => "{\"^t\":\"2015-02-26T16:25:12.232489000+00:00\"}"
2.1.5 :004 > Oj.load("{\"^t\":\"2015-02-26T16:25:12.232489000+00:00\"}")
 => 2015-02-26 18:25:12 +0200
2.1.5 :005 > Time.now.utc.iso8601
 => "2015-02-26T16:25:37Z"
2.1.5 :006 > Oj.load("{\"^t\":\"2015-02-26T16:25:12.232489000Z\"}")
 => 2015-02-26 16:25:12 UTC

**Comment by ohler55** [comment]
+00:00 should be the same as UTC. What I find unusual though is 2015-02-26T16:25:12.232489000+00:00 being parsed as having a +0200 offset. Can you try simply
Time.parse('2015-02-26T16:25:12.232489000+00:00')
and let me know the output. That is the routine used for parsing of time strings.

**Comment by crazyshot** [comment]
No, it is parsed including tz, but then converted to local tz. And that's
the difference between +00:00 and Z.

**Comment by ohler55** [comment]
Odd that I don't get the same results here. Is there some setting you are using to automatically convert time to local time when it is parsed with an offset of zero? My 2.2 environment does not do that. If Ruby is  associating some special meaning to the use of 0 offset vs Z that is definitely a problem that will have to be worked around.

**Comment by ohler55** [comment]
I did some experimenting. The behavior on 2.2.0 is different than 1.9.3 and 2.1.5. I'll have to put in some addition checks for earlier version of ruby.

**Comment by ohler55** [comment]
I just pushed a version to github that handles the string formatted time options correctly for UTC in earlier Ruby versions and also sets the UTC flag in 2.2.

I will add a numeric formatting option with utc_offset before the next release with this fix in it. I'll let you know when you can try it out. There will be a slight performance penalty for doing the UTC check on Oj.dump and load as well.

**Comment by ohler55** [comment]
ok, you can give the :unix_zone format option a try also.

**Comment by crazyshot** [comment]
ruby/xmlschema seems to work nicely, unix_zone buggy:

I'd guess that the timestamp is always loaded in current local timezone and
then *forced* to new timezone instead of change to it, and timestamp
changes.
By the way a question. Why mantissa instead of another hash field? Faster
parsing?

[69] pry(main)> time = Time.now.utc
=> 2015-02-27 17:42:29 UTC
[70] pry(main)> dump = Oj.dump(time, time_format: :unix_zone)
=> "{\"^t\":1425058949.111865000e86400}"
[71] pry(main)> Oj.load(dump)
=> 2015-02-27 19:42:29 UTC
[72] pry(main)> Oj.load(dump) == time
=> false
[73] pry(main)> Oj.load(dump) - time
=> 7200.0

**Comment by ohler55** [comment]
Using the exponent for the timezone with 86400 meaning UTC is faster. I can keep a single value and parse the number much quicker than a string.

You are right the ruby C calls to make a time time objects always create the time in the local time. The seconds are adjusted first and then the result forced to UTC. There are 3 paths the code can take, one for UTC or mantissa of 86400, if no mantissa then just the ruby C call is used so you get local time, finally if there is a mantissa other than 86400 the ruby Time.new() function is called with arguments derived from the number including the timezone offset.

**Comment by crazyshot** [comment]
Then you can do following:
if no mantissa: ruby's Time.at(ts)
else If mantissa == 86400: ruby's Time.at(ts).utc
else time = C's tm = gmtime(ts+mantissa), then ruby's Time.new(tm.year,
..., mantissa)

**Comment by ohler55** [comment]
I am trying to avoid making calls from Ruby itself as the overhead is fairly high compared to the C calls.

For the 86400/UTC path what you describe is essentially what I am doing other than the time offset for local time is needed in some environments. I have not nailed that down yet.

**Comment by crazyshot** [comment]
Didn't you say you're using ruby's Time.new anyway? I think Time.at is faster.
Ok, I guess instead of Time.at(ts).utc you save one call using gmtime and Time.utc:
tm = gmtime((time_t)ts), then ruby's Time.utc(tm->tm_year+1900, ..., tm->tm_sec+(ts-(int)ts))

**Comment by crazyshot** [comment]
Time.at(ts).utc is faster than the alternative, unless doing ruby call itself is a performance hit:
[134] pry(main)> prof(10000){Time.utc(2015,2,27,19,29,21.232322342)}
time: 2.2e-05(s), req/s: 45300, GC time: 9.2e-06
[135] pry(main)> prof(10000){Time.at(1425053029.2323222).utc}
time: 8.8e-06(s), req/s: 114000, GC time: 7.2e-06
[136] pry(main)> prof(10000){Time.at(1425053029.2323222)}
time: 1.9e-06(s), req/s: 523000, GC time: 9.0e-08

**Comment by ohler55** [comment]
Ruby calls all by themselves are expensive. Of course getting the same answer each time takes precedence. The only reason Time.new is used is to allow for the timezone offset as one of the arguments. That approach avoids having to second guess if the local time offset will be used or not. Since it does not appear to be consistent. Either that or I just don't know the conditions that effect the results. I'll work on it more tonight and try to recreate the differences.

**Comment by crazyshot** [comment]
Good luck :)
By the way, how are you parsing for time_format: :ruby? Are you parsing yourself and then using Time.new/utc or using Time.parse? I failed to find it in code.

**Comment by ohler55** [comment]
The ruby mode is strictly ruby parsing.

**Comment by crazyshot** [comment]
:xmlschema is the same as :ruby? I ask because Time.parse is really slow,
Time.iso8601 is few times faster than Time.parse, but for some reason
always return time in UTC.

**Comment by ohler55** [comment]
pulling my hair out on this. Well, okay, not hair left to pull out. Try this on your system. It gives the expected results on my systems but fails on travis. Maybe yours too.
```
    t = Time.xmlschema("2015-01-05T21:37:07.123456000-08:00")
    puts "*** time is: #{t.to_s} in test_time_xml"
    puts "*** utc? is: #{t.utc?} in test_time_xml"
    puts "*** utc_offset: #{t.utc_offset} in test_time_xml"
    puts "*** gmt_offset: #{t.gmt_offset} in test_time_xml"
    puts "*** utc - local: #{t.getutc - t.getlocal} in test_time_xml"
```

**Comment by ohler55** [comment]
On travis the Time.parse() and Time.xmlschema() fail to parse the zone and always assume the date is UTC or in some case just an offset of 0 and not UTC. Using the Time.new() function with arguments that include the offset a time with the correct offset is returned. That does not explain what you are seeing though with the loading of "{\"^t\":1425058949.111865000e86400}" so my work is not done yet.

**Comment by crazyshot** [comment]
In my system the time offset is correctly parsed in .xmlschema, the
timestamp is correct. It just sets the timezone to utc.
Time.parse doing something else. If there is TZ, it parsers it correctly
for timestamp calculation, but then moved to local. If TZ iz Z, it's loaded
as utc.

**Comment by crazyshot** [comment]
Here's my output for your code:
*** time is: 2015-01-06 05:37:07 UTC in test_time_xml
*** utc? is: true in test_time_xml
*** utc_offset: 0 in test_time_xml
*** gmt_offset: 0 in test_time_xml
*** utc - local: 0.0 in test_time_xml
Does last line give anything but 0 in your system? Then it's a bug, because
timestamp (which is the real value of time) should not be ever affected by
timezone. E.g. time == time.utc, time.to_i == time.utc.to_i.

**Comment by crazyshot** [comment]
It all got me to some test I didn't do yet:
[194] pry(main)> time = Time.new(2015,2,28,10,22,0,12345)
=> 2015-02-28 10:22:00 +0325
[195] pry(main)> dump = Oj.dump(time, time_format: :ruby)
=> "{\"^t\":\"2015-02-28T10:22:00+03:25\"}"
[196] pry(main)> Oj.load(dump)
=> 2015-02-28 08:57:00 +0200

Oj.dump/load is inconsistent in time_format: :ruby, when we're talking
about non-local and non-utc timezone of the time, because Time.parse moves
time to local (but timestamp is right).
Unless you have some principal reason to stick with Time.parse, you should
move to parsing yourself and build object using Time.new (or Time.utc in
case ot 'Z' timezone). It will also raise performance about 10 times.

**Comment by ohler55** [comment]
Time difference should indeed be zero. I want to make sure it was. In Ruby 2.2 and in all others on OS X and the version Ubuntu I am running I do no see the conversion of time to UTC in parse. I'd claim that is a bug but in the end it doesn't matter if it is. Oj still has to work around it. I changed the tests to use the Time.new() initializer and will do that in the C code if I need to.

I'll write a few more tests and decide if I can keep the Ruby C call or if that is broken as well on some systems. If it is then Time.new() will be the only choice. Should have this taken care of this weekend.

**Comment by crazyshot** [comment]
Interesting if it's osx version that does the difference or ruby build.
I'll be in the office tomorrow, I'll try few different environments.

**Comment by ohler55** [comment]
It was painful but I think a working version is now on github.

**Comment by crazyshot** [comment]
I'm ruining it for you again.
Some strange bug with TZ offset being rounded or something, might be
working ok if TZ will be real:
[1] pry(main)> time = Time.new(2015,2,28,10,22,0,12345)
=> 2015-02-28 10:22:00 +0325
[2] pry(main)> dump = Oj.dump(time, time_format: :ruby)
=> "{\"^t\":\"2015-02-28T10:22:00+03:25\"}"
[3] pry(main)> Oj.load(dump)
=> 2015-02-28 10:22:00 +0300
[4] pry(main)> Oj.load(dump) == time
=> false

unix_zone still works same as in first version:
[5] pry(main)> dump = Oj.dump(time, time_format: :unix_zone)
=> "{\"^t\":1425094230.000000000e12345}"
[6] pry(main)> Oj.load(dump)
=> 2015-02-28 03:30:30 +0325
[7] pry(main)> Oj.load(dump) == time
=> false

**Comment by ohler55** [comment]
I know what the round off error is. I thought of it as I was going to bed last night. Fixed it but also changed the exponent of the unix_zone to be in minutes instead of seconds. I realize Ruby allows timezones to be set to second precision but the string formats don't support that and there are not timezones that use second precision.

Second item, using the == operator for time is not going to work. When reconstituting time from a string or a number the fractional seconds may appear the same but the fraction itself may be different which will make the two not equal. I ran into that with tests. tv_secs, tv_nsecs, utc?, and utc_offset are the same but they times were still not equal.

On the second unix_zone test, what was the original time used? Given that the minutes and seconds were not the same as the previous it makes me suspect you were using a different time.

**Comment by crazyshot** [comment]
It was same time exactly.

**Comment by crazyshot** [comment]
Time.new(2015,2,28,10,22,0,12345)

**Comment by ohler55** [comment]
More changes made. Can you give me your thoughts on using minutes in the exponent of the unix_zone format versus using seconds?

**Comment by crazyshot** [comment]
Because Time.new accepts offset either in seconds or hour:min string, so it
makes sense to save the seconds in unix_zone format and not think about
rounding.

**Comment by ohler55** [comment]
I cut it back to minutes since the string representations to not support seconds. I suppose that is not a reason to round the offset on the unix_zone though. I make it seconds again.

Is the current version working for you other than the rounding?

**Comment by crazyshot** [comment]
Look, as I saw there, it rounds to hours not minutes so check that you
don't cut too much :)
[2] pry(main)> dump = Oj.dump(time, time_format: :ruby)
=> "{\"^t\":\"2015-02-28T10:22:00+03:25\"}"
[3] pry(main)> Oj.load(dump)
=> 2015-02-28 10:22:00 +0300

Also unix_zone didn't work at all, giving some strange result.

**Comment by ohler55** [comment]
hmm, thats a different problem. Maybe the new string parse routine. I had to give up on the Ruby parser. It was not consistent. Ok, something to look at tonight as I go back to seconds. This is taking a bit longer than I ever would have expected.

**Comment by ohler55** [comment]
I converted Oj back to using seconds in the exponent.

Also fixed the rounding error. It was in the new xmlschema parse routine. Ruby 2.2 also uses the new parse routine as well as it is 4 times faster than the ruby Time.parse even with the Time.new being called.

**Comment by crazyshot** [comment]
But you don't really need ruby's xmlschema parser. It's so strict format,
that you can easily parse in C.

**Comment by ohler55** [comment]
So did it work for you?

**Comment by crazyshot** [comment]
Hey, sorry for delayed test, was busy with my own bugs :)
So seems that :unix_zone works fine but :ruby is bugged with UTC:
2.0.0-p598 :007 > t=Time.new(2015,3,6,16,10,30,12345)
 => 2015-03-06 16:10:30 +0325 
2.0.0-p598 :030 > Oj.load(Oj.dump(t, time_format: :ruby))
 => 2015-03-06 16:10:30 +0325 
2.0.0-p598 :031 > Oj.load(Oj.dump(t.utc, time_format: :ruby))
 => 2015-03-06 12:44:45 UTC

**Comment by crazyshot** [comment]
Cool, seems to work!

**Comment by ohler55** [comment]
Excellent. I'll release today then.

**Comment by crazyshot** [comment]
Hey, I think you don't have to do different time_format "unix_zone" and just make it default functionality for "unix". Here's the test I did on your latest official version of Oj, and it works consistently:
2.0.0-p598 :025 > t=Time.now
 => 2015-03-06 19:37:01 +0200 
2.0.0-p598 :026 > Oj.dump(t)
 => "{\"^t\":1425663421.064574000}" 
2.0.0-p598 :027 > Oj.load("{\"^t\":1425663421.064574000e231232}")
 => 2015-03-06 19:37:01 +0200 
2.0.0-p598 :028 > Oj.load("{\"^t\":1425663421.064574000e231232}")==t
 => true

**Comment by ohler55** [comment]
My concern is for backward compatibility. If people have been using the unix format then the new one will break their code. If it was the early days I would have just made one format for unix instead of two but at this point preserving backward compatibility is a goal as well as getting in new or improved features.

**Comment by crazyshot** [comment]
That's the thing, that I don't think it will break the code.
Let's consider use cases (O - old version, N - new):
O dumps (without exponent), N loads in current TZ - nothing breaks
N dumps (with exponent), O ignores exponent and loads in current TZ - nothing breaks

**Comment by crazyshot** [comment]
At least that's what I see from testing it black-box. Look in code, see if I didn't think of some use case.

**Comment by ohler55** [comment]
Thats the problem, I don't know what the old code is since I have not written it. Maybe use the compat mode and then the unix format. They would have to change that to deal with the exponent. I could make compat mode with unix format different but that would not allow timezone for those who wish to go with the improvement.

**Comment by crazyshot** [comment]
Oh, I even didn't know that you dump time as timestamp in compat mode.
I thought standard is to dump it as string, because other JSON's do it:
2.1.5 :079 > Yajl.dump(Time.now)
 => "\"2015-03-06 20:04:13 +0200\"" 

Anyway, in compat mode it doesn't make sense to dump as anything not standard JSON, which would be the case for exponent i think.

**Comment by ohler55** [comment]
In mimic_JSON compat starts as outputting time as a string. The user does have the option of being non-standard though.

**Comment by crazyshot** [comment]
You can introduce "unix_zone" in addition to "unix" and just make it default in :object mode.

**Comment by ohler55** [comment]
Making unix_zone the default is best I think.

**Comment by crazyshot** [comment]
After thinking more about it and testing a bit.
unix_zone doesn't make sense in compat mode, there's no language that will
parse number with exponent usefully. Most will return Infinity (saw it in
ruby and JS), some, that have no limit for number size, will shift decimal
point anyway. So I don't think that anyone will ever use it.
And since it doesn't break anything in object mode, you can just make this
functionality for unix more in object mode and leave current functionality
in compat mode.

WDYT?

**Comment by ohler55** [comment]
I can see the argument but Ruby BigDecimal does parse the number correctly. Making sense of it after parsing is a whole different story. With two varying components of the number it would only be useful if the range was already know to some degree. I prefer to leave the option since it does no harm and people have often surprised me with unusual uses of option. That and the release went out yesterday. There is the next release though if it is compelling enough.

**Comment by crazyshot** [comment]
Ok. Don't think there will be any reason to change it next release though,
as purple might already use unix_zone explicitly.

**Comment by ohler55** [comment]
Ready to close?

**Comment by ohler55** [comment]
This is what I was thinking of although it does not currently work with Date since Date is already registered. I will have to fix that so exiting class encoding can be replaced.
```
Oj.register_odd(Date,Date, :jd, :jd)
irb(main):011:0> j = Oj.dump(Date.new(2015,3,7), mode: :object)
=> "{\"^O\":\"Date\",\"jd\":2457089}"
irb(main):012:0> Oj.load(j, mode: :object).to_s
=> "2015-03-07"
```
I ran this on a modified version where the Date was commented out and Oj recompiled.

**Comment by crazyshot** [comment]
Sorry, I have to reopen this:
Oj.load("{\"^t\":1425819728.069675000e7200}")==Oj.load("{\"^t\":1425819728.069675000}")
=> false

It might be intentional, and something that I payed attention at the beginning and not in the end.
You're saving timestamp with offset. I think to be standard and back-compatible, you have to save real timestamp and do the offset on load, just to calculate right hour/min/sec values.
This way of you load with unix, time dumped with unix_zone, you'll get same time (in current TZ) instead of different time as it happens now.

**Comment by ohler55** [comment]
If I understand correctly you would expect Oj.load to make the timezone the local zone if there is no exponent when using the unix_zone format. Correct?

**Comment by crazyshot** [comment]
Yes. I mean Oj doesn't have "time_format" for load, right? It guesses right
format, so what I would expect is for old Oj to ignore exponent and load
correct timestamp. But it can't do it right now, because current Oj dumps
with incorrect, shifted timestamp.
Technically, I mean that unix and unix_zone should save same timestamp for
same time, since that's what most matters, TZ is only for loading.

I guess for me it's more matter of standard and esthetics, than
back-compatibility as I don't have applications that would use old Oj.
Do you intend to change it? I'll then wait for next version before
switching, otherwise I'll have invalid time in cache...

**Comment by ohler55** [comment]
That does create a dilemma. I can't really change the unix_zone to local time as then changing timezones would make it impossible to load correctly. Oj already create a local time if there is no exponent. That allows old behavior to work as it used to. I'm afraid unix_zone will have to remain as UTC time to work correctly unless you can suggest some way to resolve the original timezone and also include the time object's zone. It seems like it would be more confusing to have two zones associated with a single time.

**Comment by crazyshot** [comment]
Ok, i think i don't explain myself correctly.
time.to_i is always equal to time.utc.to_i. Timestamp is always timezone
agnostic. Timezone is only informational, for presentation.

I'd expect that to be also in serialized format.

I think that same true in any language.

E.g. 12:30Z will have same timestamp as 10:30-02:00. And thus, will be
considered equal.

**Comment by ohler55** [comment]
Ah, but the older unix format always output just time.to_i and did not convert to UTC. I don't want to change that now as any existing code written by others would break if loading exiting JSON files. It would also break existing code as the loaded times would not match dumped times.

When first written I had to choose between converting all times to UTC or leaving them local. The target project in Japan did not want UTC but local time so that was why the unix mode outputs local time.

**Comment by crazyshot** [comment]
You still don't follow. time.to_i == time.utc.to_i.
Timestamp does not change with timezone.

**Comment by crazyshot** [comment]
Sorry, if I just misunderstood you and stating the obvious, but another example:
Time.new(2015,1,1,5,6,7,2*3600).to_i == Time.new(2015,1,1,2,6,7,-1*3600).to_i #true

**Comment by ohler55** [comment]
I don't think we are understanding each other. Lets start from the beginning.

Given 2015-03-07 10:30:00 local time, lets say +7200, What would expect the JSON from unix and unix_zone to look like? The assumption being load would result in the same time object with the same timezone if loaded in the same time zone.

**Comment by crazyshot** [comment]
Same timestamp, just addition of exponent 7200 in unix_zone.
Lets say that Time object has method 'force_utc_offset', the lead them
would look like Time.at(ts).force_utc_offset(7200).
Since you don't have such method, and you can only load with Time.new,
leading is more complex, it needs to offset timestamp itself to calculate
hours,min,sec. But after loading, in the final Time object, time.to_i
should be one again equal to saved timestamp.


On Mar 9, 2015 2:36 AM, "Peter Ohler" <notifications@github.com> wrote:
>
> I don't think we are understanding each other. Lets start from the
beginning.
>
> Given 2015-03-07 10:30:00 local time, lets say +7200, What would expect
the JSON from unix and unix_zone to look like? The assumption being load
would result in the same time object with the same timezone if loaded in
the same time zone.

**Comment by crazyshot** [comment]
[74] pry(main)> time = Time.parse("2015-03-07 10:30:00")
=> 2015-03-07 10:30:00 +0200
[75] pry(main)> time.to_i
=> 1425717000
[76] pry(main)> Oj.dump(time, time_format: :unix)
=> "{\"^t\":1425717000.000000000}"

I'd expect unix_zone to dump: "{\"^t\":1425717000.000000000e7200}", because "1425717000" is the absolute time. 7200 is just information for presentation only, for calculation of hour/min/sec etc. But when you do stuff like time1 == time2 or time1 - time2 it just uses timestamp, because it's absolute.

Let's say from the opposite side, I'd expect 
Oj.load("{\"^t\":1425717000.000000000e7200}") == Oj.load("{\"^t\":1425717000.000000000e3600}")
When first would result in: 2015-03-07 10:30:00 +0200
and second: 2015-03-07 09:30:00 +0100.

Do I make sense this time?

**Comment by ohler55** [comment]
Clear now. I believe unix_zone works as described. unix mode does not but I am faced with backward compatibility issues if I change the unix format now. As mentioned, there is a lot of other people's code out there that uses the unix format. Any records that have been stored would become inconsistent with new records. Three years ago I would have been glad to make this change but now the best I can do is deprecate the unix format and encourage the unix_zone format.

**Comment by crazyshot** [comment]
Sorry, no it doesn't work as described:
Here's quick test that shows that Oj unix_zone saves different timestamp dependent on timezone.
2.0.0-p598 :002 > time = Time.now
 => 2015-03-09 16:26:35 +0200 
2.0.0-p598 :003 > time.to_i #         => 1425911195 
2.0.0-p598 :004 > Oj.dump(time) #=> "{\"^t\":1425918395.706923000e7200}" 
2.0.0-p598 :005 > time.utc#           => 2015-03-09 14:26:35 UTC 
2.0.0-p598 :006 > Oj.dump(time)# =>"{\"^t\":1425911195.706923000e86400}" 
2.0.0-p598 :007 > time.to_i #          => 1425911195

**Comment by ohler55** [comment]
okay, so you are not trying to change the unix format, only the unix_zone format. You suggest that the time in the dump be the epoch time from the UTC of the original Time object instead of the current value. I can see the merit in that now that I understand the suggestion.

**Comment by crazyshot** [comment]
Yes!

But again I want you to see what I mean when I say there is not such thing as epoch time from the UTC, or epoch time from local time. Epoch time is absolute, timezone independent, that's why it's so cool, it actually represents the time, wherever you check for that time.
As long as you preserve original timestamp through all dumps/loads you'll have same time (absolutely speaking).
"unix" format already does it. Dumping different timezone than local and then loading will change the timezone, but will preserve absolute time itself.
"unix_zone" saves shifted timestamp, so if I load it with old Oj, I will not old loose timezone information, but will get wrong time.

**Comment by crazyshot** [comment]
So, what did you decide?

**Comment by ohler55** [comment]
I will make the change. Been busy though. Might have to wait until Thursday.

**Comment by ohler55** [comment]
Candidate is github.

**Comment by crazyshot** [comment]
Checked. Works great!
Thanks.

**Comment by crazyshot** [comment]
Hm... Did you intentionally made unix_zone default in compat mode also? I remembered we were talking about it, and was sure you wanted to make it default only for :object mode.
Is there a way at all, to set different time format default for different modes?

**Comment by ohler55** [comment]
The way the defaults work is that they apply to all mode, including compat. It would be a big deviation from that model to have compete more over-ride the time format. The only way to over-ride would be to specify the time format in every compete mode dump call. The choice I made was to have the mimic_JSON set the time format. (it is set to the ruby format as the JSON gem uses). If mimic is not set then what ever is in the defaults is used. It seemed like the best compromise.

**Comment by crazyshot** [comment]
Ok. It's ok, anyway dumping time in compat isn't h useful

**Comment by ohler55** [comment]
ok, released the change.

**Comment by crazyshot** [comment]
Cool, thanks.
