### ISSUE TITLE
Feature request: efficient format for Date class in object mode

### ISSUE THREAD

**Issue by crazyshot** [ohler55/oj#221]
Hi,
In my project I'm using Oj to serialize hashes containing many Date and Time values.
It's much faster and more reliable than Marshal (especially with new version that saves TimeZone :) ), but it takes about 50% more space than Marshal because of current serialization of Date objects.
Date can be saved with just one integer, e.g. today would be 20150308. It would be much faster to parse and much more space efficient.
I tried to follow the code, but only found some "Odd objects" handling. I'm guessing that you already do some kind of special work for Date, so is there a chance you'll go full way through and create special format for it?

**Comment by ohler55** [comment]
Let me look at how twisted it might be. Another way to handle that is to add a to_hash() or as_json() method to the Date class. Personally I have adding methods to core classes but JSON and Rails both do that so it is an option. I'll look at how I can do something like that cleanly as well though.

**Comment by crazyshot** [comment]
I can add anything on my side, but how the result of my as_json is that
going to be parsed back into Date?

**Comment by ohler55** [comment]
I guess that is a problem. In compat mode the json_create() class method can be used but that is not called in object mode. You can register an "odd" class with Oj.register_odd() though. I'd be curious how it performs since it would require making Ruby calls. I still plan to look at Date optimization separately but it is something you can give a try.

**Comment by ohler55** [comment]
This is what I was thinking of although it does not currently work with Date since Date is already registered. I will have to fix that so exiting class encoding can be replaced.
```
Oj.register_odd(Date,Date, :jd, :jd)
irb(main):011:0> j = Oj.dump(Date.new(2015,3,7), mode: :object)
=> "{\"^O\":\"Date\",\"jd\":2457089}"
irb(main):012:0> Oj.load(j, mode: :object).to_s
=> "2015-03-07"
```
I ran this on a modified version where the Date was commented out and Oj recompiled.

**Comment by ohler55** [comment]
Never mind, it works as is. Oj starts with the last added odd.

Oj.register_odd(Date,Date, :jd, :jd)

Should be all you need.

**Comment by crazyshot** [comment]
Thanks

**Comment by crazyshot** [comment]
Cool. Works with good performance.
The only problem that it's not back-compatible, but I'll work around it :)

[14] pry(main)> h = {x: Date.today}
=> {:x=>Sun, 08 Mar 2015}
---- Default
[15] pry(main)> hs = Oj.dump(h)
=> "{\":x\":{\"^O\":\"Date\",\"year\":2015,\"month\":3,\"day\":8,\"start\":2299161.0}}"
[17] pry(main)> prof(100000){ Oj.dump(h) }
time: 2.1e-06(s), req/s: 486000, GC time: 7.8e-07
[13] pry(main)> prof(100000){ Oj.load(hs) }
time: 2.5e-06(s), req/s: 398000, GC time: 3.4e-06
----- Custom
[19] pry(main)> Oj.register_odd(Date, Date, :jd, :jd)
[21] pry(main)> hs = Oj.dump(h)
=> "{\":x\":{\"^O\":\"Date\",\"jd\":2457090}}"
[22] pry(main)> prof(100000){ Oj.dump(h) }
time: 9.6e-07(s), req/s: 1040000, GC time: 8.7e-07
[23] pry(main)> prof(100000){ Oj.load(hs) }
time: 2.2e-06(s), req/s: 449000, GC time: 2.5e-06

**Comment by crazyshot** [comment]
Can you add 'register_odd' to Oj documentation? I think it can be useful to many people.

**Comment by ohler55** [comment]
Already there.
http://ohler.com/oj/Oj.html#register_odd-class_method

**Comment by crazyshot** [comment]
Oh, sorry, missed that :)
