### ISSUE TITLE
Documentation on whether oj can be used with Rails / ActiveRecord's serialize

### ISSUE THREAD

**Issue by pickhardt** [ohler55/oj#222]
Can you add something to the documentation about using oj with ActiveRecord's serialize (in place of yaml)? I have a need for speed!

I think it is just

    serialize :my_attr, Oj

but wanted to double check.

**Comment by ohler55** [comment]
I am not well versed on ActiveRecord. I suggest trying out what you proposed. If it works you can add a file to the samples directory or we can figure out some other place to put notes like that. Maybe a Rails/Active notes file.

**Comment by ohler55** [comment]
Are you interested in continuing or should I close this issue?

**Comment by pickhardt** [comment]
Hey, thanks for the reminder.

For those in the future, turns out all you have to do is what I said above.

Also, it doesn't hurt to mimic JSON as well:

    Oj.mimic_JSON()

**Comment by ohler55** [comment]
ok, thanks.

**Comment by pickhardt** [comment]
Yeah, the default serialization method for ActiveRecord's serialize is YAML, which seems crazy to me. It's optimizing for readability over performance. I think that in most cases, you'd want to optimize for performance instead, so I recommend using Oj for that.

**Comment by ohler55** [comment]
If all it took was the serialize :my_attr, Oj I can add that to the read me.

**Comment by pickhardt** [comment]
Yeah, that's all it took.
