### ISSUE TITLE
Oj::Doc.open does not unescape unicode sequences

### ISSUE THREAD

**Issue by oestrich** [ohler55/oj#224]
Hello, I started using `Oj::Doc.open` to parse JSON files and didn't have an issue until I came across JSON that had unicode inside of it. Regular `Oj.load` does not have this problem as it parses the string correctly. Below is a simple example of how it is failing. This is on ruby 2.2.0.

```ruby
[23] pry(main)> body
=> "{\"name\": \"T-Shirt \\u00ae\"}"
[24] pry(main)> Oj::Doc.open(body) { |doc| doc.fetch("/name") }
=> "T-Shirt \xAE"
[25] pry(main)> Oj.load(body)
=> {"name"=>"T-Shirt ®"}
[26] pry(main)> JSON.parse(body)
=> {"name"=>"T-Shirt ®"}
```

**Comment by ohler55** [comment]
I should be able to look at it this week. I am interested in your feedback after using Oj::Doc, other than the problem with the encoding that is.

**Comment by oestrich** [comment]
We used Oj::Doc to reduce huge memory issues we were having (while loading >1MB of JSON). We only need a few fields from this huge amount of JSON so Oj::Doc looked like the ideal solution. I only have one minor gripe with it, the rest is great. I'll show with an example:

```ruby
Oj::Doc.open("json") do |doc|
  doc.each_child do |child|
    child.fetch("/name")
  end
end
```

In the above example I expected the `child.fetch("/name")` to be relative, but I had to do `child.fetch("#{child.where?}/name")` for it to pull out the data I expected. Other than that I really like it and it showed to be very promising for fixing memory issues.

**Comment by ohler55** [comment]
Did you try just child.fetch("name") ?

I'm glad to work with you to improve the API and behavior.

**Comment by oestrich** [comment]
Calling `child.fetch("name")` throws a ruby c level stack trace. [An example triggering the stacktrace.](https://gist.github.com/oestrich/7bcec7e01f795a3fc4bf)

I like fetching with just to key to show it's relative, instead of passing the path like I tried previously.

**Comment by ohler55** [comment]
I'll work on it tonight and get it working.

**Comment by ohler55** [comment]
Checked in a version that fixes the crash. Working on encoding still though. Might be another day for that.

**Comment by ohler55** [comment]
Checked in a fix for the encoding as well. Please test. If it works for you I will do a release.

**Comment by oestrich** [comment]
Looks good, thanks for the quick updates! I definitely like the relative fetch.

**Comment by ohler55** [comment]
I'll make a release then. Not sure if performance of memory use is more important to you but another option is the scp callback parser using a stream. The Oj::Doc is much faster though. Not as fast as OjC but you have to expect straight C to be faster.

**Comment by ohler55** [comment]
Ok to close this issue?

**Comment by oestrich** [comment]
Yeah, everything looks good. Thanks again.
