### ISSUE TITLE
Issues with Oj::Saj#errors

### ISSUE THREAD

**Issue by trevorrowe** [ohler55/oj#226]
I've been working with `Oj::Saj` to improve the performance of parsing some large XML documents. I've run into a couple of issues with the handling of malformed JSON documents. I've illustrated them in the example below.

```ruby
require 'oj'
require 'stringio'

class Parser < Oj::Saj

  def parse(json)
    Oj.saj_parse(self, StringIO.new(json))
  end

  def hash_start(key)
    puts "START: #{key}"
  end

  def error(message, line, column)
    puts "Error callback: #{message}"
  end

end

parser = Parser.new

# truncated JSON, Oj.saj_parse raises, #error not called
parser.parse('{"foo{"bar":')

# invalid JSON, doesn't raise an error
parser.parse('{"foo":{"bar":}')
```

My first issue is that I can't seem to get `Oj::Saj` to trigger the `#error` method at all. I'm not sure if I am doing something wrong. Errors will raise from the `Oj.saj_parse` method, but not trigger `#error`. 

The second issue is not significant. I have not encountered this in the wild. I created what I thought was an invalid JSON document but no errors were raised at all. 

Thoughts?

**Comment by ohler55** [comment]
If an exception is raised the error method should be called. Unit tests pass. Let me try out your example later tonight and see what is going on.

The second should raise and error as well so I will look into that also.

**Comment by ohler55** [comment]
I made a slight modification to the parse calls only to grab the exception.

```
begin
  # truncated JSON, Oj.saj_parse raises, #error not called
  parser.parse('{"foo{"bar":')
rescue Exception => e
  puts "*** #{e.class}: #{e.message}"
end
puts "\n\n"
begin
  # invalid JSON, doesn't raise an error
  parser.parse('{"foo":{"bar":}')
rescue Exception => e
  puts "*** #{e.class}: #{e.message}"
end
```

This produces the following output.
```
START:
Error callback: invalid format, expected : at line 1, column 8 [saj.c:258]
*** Oj::ParseError: invalid format, expected : at line 1, column 8 [saj.c:260]


START:
START: foo
Error callback: invalid format, expected , or } while in an object at line 1, column 16 [saj.c:271]
*** Oj::ParseError: invalid format, expected , or } while in an object at line 1, column 16 [saj.c:273]
```
It looks right to me. The callback is made and the exception is thrown. I was using Ruby 2.2.2 and Oj 2.12.2.

What results to you see?

**Comment by trevorrowe** [comment]
I'm getting the same results you just posted.   I'm not sure what the issue was previously, but I'm unable to reproduce currently. Thanks for taking a look at this! If I encounter an issue again, I'll re-open.

**Comment by ohler55** [comment]
Sounds like a plan.
