### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by collimarco** [ohler55/oj#228]
I'm using Oj to parse each line of a large Wikidata dump. My Ruby program first extracts the Json object that is present in each line, then passes the single Json object of the line (not the entire dump) to Oj to be parsed.

The dump is the following:
 http://dumps.wikimedia.org/other/wikidata/20150406.json.gz

However I frequently get a **segmentation fault** caused by a line that calls Oj's `#fetch`.

Here's the error:
https://gist.github.com/collimarco/677e059206854932f1c4#file-gistfile1-txt

And some extracts of the code that produces it:
https://gist.github.com/collimarco/677e059206854932f1c4#file-gistfile2-rb

In practice for each entity in the dump I do something like:

```
  @entity = Oj::Doc.open(@line_without_comma_at_the_end)
  # ...
  fetch('/id')[1..-1]
  @entity.close
  
  def fetch(path)
    @entity.fetch(path) # this line often causes the segmentation fault
  rescue ArgumentError
  end
```

The segmentation fault occurs with different lines.

Furthermore I never managed to complete the parsing because (when there isn't a segmentation fault) at 90% of the file I **always** get:
```
Killed: 9
```

When I used the default Ruby JSON parser instead of Oj I could complete the parsing and everything worked fine (except for the time! 3h instead of about 20 minutes).

PS thanks for the great gem!

**Comment by ohler55** [comment]
I will look into it tonight. I think it will take that long to download the dump. :-)

Other options for parsing are the Oj::load with a file argument as input and then getting a callback when each JSON document is read and parsed from the file. Not sure if overall this will be faster than Ol::Doc though.

If you are after raw speed and don't care about the language, OjC is very fast. I use it for parsing multiple GB log files and reformatting and it can rip through a 1G file in seconds.

**Comment by ohler55** [comment]
It may be tomorrow before I can look. That is a 4.4G file. It will take 15 hours to download.

**Comment by ohler55** [comment]
It looks like my ISP is cutting back bandwidth. Another 24 hours to download now. I have set up two simple tests from what I think was the intent of the code snippet you provided. Let me know if they are what you intended.
```
require 'oj'

def create_item(doc)
  item_id = doc.fetch('/id')
  # ...
end

File.open('log.json') { |f|
  f.each { |line|
    Oj::Doc.open(line) { |doc|
      begin
        create_item(doc) if doc.fetch('/type') == 1
      rescue Exception => e
        puts "*** #{e.class}: #{e.message}"
      end
    }
  }
}
```
and the Oj::Doc version...
```
require 'oj'

def create_item(doc)
  item_id = doc['id']
  # ...
  puts item_id
end

File.open('log.json') { |f|
  Oj::load(f, mode: :compat) { |doc|
    begin
      create_item(doc) if doc['type'] == 1
    rescue Exception => e
      puts "*** #{e.class}: #{e.message}"
    end
  }
}
```

**Comment by collimarco** [comment]
Thanks for the support! The script is more like this:
https://gist.github.com/collimarco/677e059206854932f1c4#file-gistfile3-rb

I'm trying to reproduce the segmentation fault with it...

**Comment by ohler55** [comment]
Very little progress last night. Comcast is definitely doing some traffic shaping and reducing the bandwidth of the download. At this point the download will take 2 more days. Is there a smaller file you could post that I could just duplicate several times to get the errors to show up?

You have given me something to look at. I have to figure out why the close does not free memory while the proc does.

**Comment by collimarco** [comment]
Here's the first 10k lines of the dump:
https://drive.google.com/file/d/0BwxNgHA35rLbOHNkeUZPSDZ5QjQ/view?usp=sharing

However if the memory leak is easily reproducible, even parsing of the whole dump 2 times I was not able to reproduce this segmentation fault  - maybe, even if it is unlikely, the workaround for the memory leak has an influence on `#fetch`?

**Comment by ohler55** [comment]
It could be the segfault was related to the out of memory failure. When memory is not available it is not unusual to get a segfault.

**Comment by ohler55** [comment]
Found the memory leak and fixed it. Release 2.12.4 pushed.

**Comment by collimarco** [comment]
@ohler55 Great ;)

**Comment by ohler55** [comment]
reopened. Still have a memory leak or crash?

**Comment by collimarco** [comment]
I noticed that this issue is about the segmentation fault, not the memory leak (which is solved and can be certainly closed). 

IMHO a segmentation fault should never occur even if the OS refuse to allocate the space (as I may expect in this case, since I've never encountered segfaults any more after the memory leak was fixed). Do you agree?

**Comment by ohler55** [comment]
In an ideal world I would agree that lack of memory should not cause a segfault. In practice I have found that not to be the case. I could put additional checks in Oj but there is still the chance that there would be a segfault as other libraries don't deal well with memory exhaustion.

**Comment by collimarco** [comment]
Ok :)

**Comment by ohler55** [comment]
So close?
