### ISSUE TITLE
Documentation clarrification about Oj::Doc.open

### ISSUE THREAD

**Issue by cdwijayarathna** [ohler55/oj#231]
Why does the same method documentation available in two different places?
Are they same?
http://www.rubydoc.info/gems/oj/Oj/Doc.open
http://www.rubydoc.info/gems/oj/Oj/Doc.parse

**Comment by cdwijayarathna** [comment]
I think in the second link, it accidentally uses the same content as the Oj::Doc.open,

**Comment by ohler55** [comment]
That is because Oj::Doc.parse is an alias for Oj::Doc.open or rather they call the same C function. It is not a mistake.

**Comment by cdwijayarathna** [comment]
Ahha, same function called under both names?

**Comment by cdwijayarathna** [comment]
Anyway, then I believe in
http://www.rubydoc.info/gems/oj/Oj/Doc.parse, in
    open(json) {|doc| ... } ⇒ Object
and in the example open should be replaced with 'parse'.
What do you think?

**Comment by ohler55** [comment]
yes, that is correct

**Comment by cdwijayarathna** [comment]
I'd like to create a patch for this if required, what is the way of doing that?

**Comment by ohler55** [comment]
I dig into to see how yardoc can be forced to use the correct code comments.

**Comment by ohler55** [comment]
The file is fast.c. I do not want to change the code to correct for documentation but if you can figure out the correct comment that yardoc will pick up that would be great.

**Comment by cdwijayarathna** [comment]
It seems like yard is looking at the same comment at https://github.com/ohler55/oj/blob/master/ext/oj/fast.c#L1069
for both functions.

**Comment by ohler55** [comment]
Correct, and not #1166 as intended.

**Comment by cdwijayarathna** [comment]
Similar issue at http://www.rubydoc.info/gems/oj/Oj/StreamWriter:push_json and http://www.rubydoc.info/gems/oj/Oj/StreamWriter:push_value.

**Comment by ohler55** [comment]
Thank you.
