### ISSUE TITLE
test_odd_datetime fails on several non 64bits architectures

### ISSUE THREAD

**Issue by boutil** [ohler55/oj#233]
Hi,

I've just built a Debian package for oj 2.12.5. It built perfectly on my amd64 machines but I got several build failures on various architectures, because of the test test_odd_datetime not passing (the second statement). The message is the following:
```
  1) Failure:
ObjectJuice#test_odd_datetime [./test/test_object.rb:685]:
--- expected
+++ actual
@@ -1 +1 @@
-#<DateTime: 2012-06-19T13:05:07+00:00 ((2456098j,47107s,123456789n),+0s,2299161j)>
+#<DateTime: 2012-06-19T13:05:00+00:00 ((2456098j,47100s,681005845n),+0s,2299161j)>
```
and is the same accross the failing architectures: armel, armhf, hppa, i386, mips, mipsel, powerpc, sparc, x32. It built successfully on alpha, amd64, arm64, ppc64, ppc64el, s390x.

Please let me know if I can test something to help debugging this.

Cheers,

Cédric 
It success

**Comment by ohler55** [comment]
I am going to guess that there is someplace not using an int64_t but a long and that the JSON is not the same. Can you try this and tell me what you get?

Oj::dump(DateTime.new(2015,5,4,13,25,Rational(4, 3)), :mode => :object)

I expect this with a different offset.

=> "{\"^O\":\"DateTime\",\"year\":2015,\"month\":5,\"day\":4,\"hour\":13,\"min\":25,\"sec\":{\"^O\":\"Rational\",\"numerator\":4,\"denominator\":3},\"offset\":{\"^O\":\"Rational\",\"numerator\":0,\"denominator\":1},\"start\":2299161.0}"

**Comment by boutil** [comment]
For the one you mention, on powerpc, I get:
```
"{\"^O\":\"DateTime\",\"year\":2015,\"month\":5,\"day\":4,\"hour\":13,\"min\":25,\"sec\":{\"^O\":\"Rational\",\"numerator\":4,\"denominator\":3},\"offset\":{\"^O\":\"Rational\",\"numerator\":0,\"denominator\":1},\"start\":2299161.0}"
```
which is exactly the one you get. However, the problematic one is the other one:
`Oj::dump(DateTime.new(2012, 6, 19, 13, 5, Rational(7123456789, 1000000000)), :mode => :object`
which gives:
```
"{\"^O\":\"DateTime\",\"year\":2012,\"month\":6,\"day\":19,\"hour\":13,\"min\":5,\"sec\":{\"^O\":\"Rational\",\"numerator\":136201169,\"denominator\":200000000},\"offset\":{\"^O\":\"Rational\",\"numerator\":0,\"denominator\":1},\"start\":2299161.0}"
```
on powerpc

and
```
"{\"^O\":\"DateTime\",\"year\":2012,\"month\":6,\"day\":19,\"hour\":13,\"min\":5,\"sec\":{\"^O\":\"Rational\",\"numerator\":7123456789,\"denominator\":1000000000},\"offset\":{\"^O\":\"Rational\",\"numerator\":0,\"denominator\":1},\"start\":2299161.0}"
```
on amd64.

**Comment by ohler55** [comment]
how about 
Rational(7123456789,1000000000)
or just
7123456789

**Comment by ohler55** [comment]
I pushed a change to github. Can you try it? Just Oj.dump(Rational(7123456789,1000000000), :mode => :object) should be enough to tell if it works. If so I will need to go through the code and make sure other places are correct as well.

**Comment by boutil** [comment]
The strange thing is that  Oj.dump(Rational(7123456789,1000000000), :mode => :object) gives the correct ouptut: 
```
"{\"^O\":\"Rational\",\"numerator\":7123456789,\"denominator\":1000000000}"
```
without the patch, on powerpc (like on amd64)

**Comment by boutil** [comment]
The same test fails with the same error with the patch on powerpc.

**Comment by ohler55** [comment]
I'm going to make a pass over the code and make sure 64 bit int (long long) is used in places it should be. After that another test would be helpful. If the test continue to fail it will be time for me to get a 32 bit VM set up.

**Comment by ohler55** [comment]
Feel free to try again. I've started setting up a VM with a 32bit ubuntu image for testing.

**Comment by boutil** [comment]
With the last commit, all the tests pass on powerpc and mips.

**Comment by ohler55** [comment]
Thats good news. How about on the others? In any case it looks like a release candidate.

**Comment by boutil** [comment]
I'm uploading a new version of the package with the patches. I will let you know later the result of the builds.

**Comment by ohler55** [comment]
thanks

**Comment by boutil** [comment]
It's all green for the official Debian architectures!
https://buildd.debian.org/status/package.php?p=ruby-oj&suite=sid
(except hurd, but for another reason: JSON too deeply nested)
Other ports haven't received the new package yet.
 http://buildd.debian-ports.org/status/package.php?p=ruby-oj&suite=sid
but it should be fine!

**Comment by ohler55** [comment]
ok, tonight I will make a release.

**Comment by ohler55** [comment]
done

**Comment by ohler55** [comment]
good to close?

**Comment by boutil** [comment]
yes, thanks. I'm closing the issue.
