### ISSUE TITLE
Anonymous classes may not parse the same way they're dumped

### ISSUE THREAD

**Issue by ajvondrak** [ohler55/oj#242]
I suspect it's not easy to overcome this limitation, but I discovered this behavior in some particularly meta code that was constructing `Array` subclasses on the fly:

```
[1] pry(main)> require 'oj'
=> true
[2] pry(main)> Oj.dump( Class.new(Array).new << 1 )
=> "{\"^o\":\"#<Class:0x007fc104c27c80>\",\"self\":[1]}"
[3] pry(main)> Oj.load(_)
=> {"self"=>[1]}
[4] pry(main)> Oj.dump ( Object.const_set(:Foo, Class.new(Array)).new << 1 )
=> "{\"^o\":\"Foo\",\"self\":[1]}"
[5] pry(main)> Oj.load(_)
=> [1]
```
With a name (introduced via `const_set`), OJ can reconstruct the instance. But without, I suppose it doesn't really stand a chance. Thoughts?

**Comment by ohler55** [comment]
At this point I have to say it is behind the current scope of Oj. The class definition would have to be passed since the receiving ruby environment would not have the class definition.

**Comment by ajvondrak** [comment]
Figured as much. Thanks for following up! I'll go ahead and close this issue.

**Comment by ohler55** [comment]
Glad to see you using it though.
