### ISSUE TITLE
oj causes `as_json` to behave differently from `to_json`

### ISSUE THREAD

**Issue by nornagon** [ohler55/oj#244]
Without oj + oj_mimic_json:

```
$ rails c
irb(main):001:0> MyModel.as_json(include:{}, only:[], methods:[])
{}
irb(main):002:0> MyModel.to_json(include:{}, only:[], methods:[])
"{}"
```

With oj + oj_mimic_json

```
$ rails c
irb(main):001:0> MyModel.as_json(include:{}, only:[], methods:[])
{}
irb(main):002:0> MyModel.to_json(include:{}, only:[], methods:[])
"{\"id\":12345,\"name\":\"aoeu\",...}"
```

`to_json` includes a bunch of information that it shouldn't be including.

I'm overriding `serializable_hash` in `MyModel`:

```
  def serializable_hash(opts = {})
    opts = DefaultJsonOpts.merge(opts || {})
    super(opts)
  end
```

**Comment by ohler55** [comment]
I'm a little slow getting to this. Vacation does that sometimes. Anyway, Oj does not consider any of the arguments to to_json(). I would guess that you do not have a to_json() method defined for your class and Oj is using the default which is to include each attribute of the object in the resulting JSON. I have not attempted to mimic the extra opt argument behavior in Oj. I will consider that though if you can explain what you expect and what the arguments to to_json are used for.

**Comment by ohler55** [comment]
Is this a dead issue for you?

**Comment by chancedowns** [comment]
I'm currently running into the same issue. We're removing attributes if their value is nil (and doing so recursively) by overriding serializable_hash like above.

Is there a better way to remove nil values?

**Comment by ohler55** [comment]
I am not a rails expert or even fluent with rails. I'll need some help figuring out what you are doing. When does serializable_hash get called?

**Comment by chancedowns** [comment]
It looks like it's getting called from as_json (here's 4.1, but 4.2 is the same https://github.com/rails/rails/blob/4-1-stable/activemodel/lib/active_model/serializers/json.rb#L99 )

I'm not too familiar with the inner workings of the gem, but I'm guessing that the overwriten to_json is calling as_json, which in turn calls serializable_hash

**Comment by ohler55** [comment]
I think I know what is going on. I'll have to think about the best work around. Oj replaces the JSON injected to_json method which does not check to see if there is an as_json() method. I have to check if there is any problem doing that other than a performance overhead.

**Comment by ohler55** [comment]
I looked into it a bit more. The only thing I could come up with is the as_json() method is returning the itself instead of a Hash. If you want to do some experimenting I'd be glad to help with that. Otherwise I'm not sure what else to try.

**Comment by chancedowns** [comment]
What would you need? Is the issue because of this PR https://github.com/ohler55/oj/pull/9 ? I see YAJL had a similar issue in https://github.com/brianmario/yajl-ruby/commit/c938954e0e977fe346e9b4dd526c897f76d8f30b

**Comment by ohler55** [comment]
I expect it is the same issue. Oj catches that condition and does it's best to guess what is expected but there is not enough info to do anything better.

**Comment by ohler55** [comment]
Is this fixed in the latest release?

**Comment by chancedowns** [comment]
I believe it is, but have not had adequate time to fully test it

**Comment by chancedowns** [comment]
We actually had to revert using OJ again as something we're doing is causing an infinite recursion loop. I'm not sure if it's with the patch or something we're doing and will have to diagnose it some more.

cc: @asurin

**Comment by ohler55** [comment]
Sorry to hear that.
