### ISSUE TITLE
Multiple object definitions don't raise an error

### ISSUE THREAD

**Issue by bowsersenior** [ohler55/oj#245]
Oj does not raise an error when parsing invalid JSON where multiple objects are defined like the following:

```json
{}

{
  "a" : "b"
}
```

The following irb session illustrates the issue. Note that `JSON.parse` does throw an error in this case:
```ruby
irb(main):001:0> require 'oj'
true
irb(main):002:0> Oj::VERSION
"2.12.9"
irb(main):003:0> Oj.load '{} {"a" : "b"}'
{
    "a" => "b"
}
irb(main):004:0> require 'json'
true
irb(main):005:0> JSON.load '{} {"a" : "b"}'
JSON::ParserError: 795: unexpected token at '{"a" : "b"}'
	from /Users/mtadayon/.rbenv/versions/2.1.1/gemsets/wiggles/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
	from /Users/mtadayon/.rbenv/versions/2.1.1/gemsets/wiggles/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
	from /Users/mtadayon/.rbenv/versions/2.1.1/gemsets/wiggles/gems/json-1.8.2/lib/json/common.rb:334:in `load'
	from (irb):5
	from /Users/mtadayon/.rbenv/versions/2.1.1/bin/irb:11:in `<main>'
```

Also, for reference here is how the Safari javascript engine handles the same bad JSON:
```
> JSON.parse('{} {"a":"b"}')
< SyntaxError: JSON Parse error: Unable to parse JSON string
column: 107
line: 1
message: "JSON Parse error: Unable to parse JSON string"
stack: "parse@[native code]↵eval code↵eval@[native code]↵_evaluateOn↵_evaluateAndWrap↵evaluate"
__proto__: Error
```

**Comment by ohler55** [comment]
Oj by default will continue to parse and callback for each JSON element in a string. I suppose I could make it raise an exception is there is more than one and no callback (proc) is provided when in mimic JSON mode. What you are seeing is the intended behavior for Oj though. It is very useful when parsing a file with multiple JSON elements in it.

**Comment by bowsersenior** [comment]
I actually had a mistake in my JSON file when I discovered this. I would expect strict validation of strings. My suggestion is to use a separate method for loading multiple JSON elements in the same file. In my example above, I am not even using a file, and I would like to be able to count on my JSON parser to raise errors when dealing with invalid JSON like `{} {"a":"b"}`. In fact, I switched from Yajl to Oj largely because of the improved error handling (Yajl accepts invalid JSON with unclosed curly braces like `{{{`).

**Comment by ohler55** [comment]
I don't want to do away with the option of multi-element parsing. Maybe in strict mode it could raise an error if no proc is provided. What are your thoughts on that? Another options would be to add a flag that disallowed multiple elements.

**Comment by bowsersenior** [comment]
Raising an error in strict mode is a good idea. Thanks for the quick response!

**Comment by ohler55** [comment]
I figured any time there is no callback it is reasonable to raise an exception. See what you think of the latest on github. If it looks right I'll do a release.

**Comment by bowsersenior** [comment]
Looks good. Thanks for addressing this!
