### ISSUE TITLE
Rubinius 2.5.2 LoadError::InvalidExtensionError, undefined symbol: rb_struct_s_members when require 'oj' (version 2.12.9)

### ISSUE THREAD

**Issue by mxvanzant** [ohler55/oj#247]
Details:

mxvanzant@tg-mv-toshiba ~/bin/rubinius/bin $ gem list oj

*** LOCAL GEMS ***

oj (2.12.9)
mxvanzant@tg-mv-toshiba ~/bin/rubinius/bin $ irb
no such file to load -- bond
rbx-2.5.2 :001 > require 'oj'
LoadError::InvalidExtensionError: Could not open library /home/mxvanzant/.rvm/gems/rbx-2.5.2/gems/oj-2.12.9/ext/oj/oj.so - /home/mxvanzant/.rvm/gems/rbx-2.5.2/gems/oj-2.12.9/ext/oj/oj.so: undefined symbol: rb_struct_s_members
	from kernel/common/native_method.rb:26:in `load_extension'
	from kernel/delta/code_loader.rb:234:in `load_library'
	from kernel/common/code_loader.rb:130:in `require'
	from kernel/common/code_loader.rb:241:in `require'
	from kernel/common/kernel.rb:755:in `gem_original_require (require)'
	from /home/mxvanzant/.rvm/rubies/rbx-2.5.2/site/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/mxvanzant/.rvm/gems/rbx-2.5.2/gems/oj-2.12.9/lib/oj.rb:42:in `__script__'
	from kernel/common/code_loader.rb:247:in `require'
	from kernel/common/kernel.rb:755:in `gem_original_require (require)'
	from /home/mxvanzant/.rvm/rubies/rbx-2.5.2/site/rubygems/core_ext/kernel_require.rb:128:in `require'
	from (irb):1
	from kernel/common/block_environment.rb:53:in `call_on_instance'
	from kernel/common/eval.rb:176:in `eval'
	from kernel/common/kernel.rb:510:in `loop'
	from kernel/bootstrap/proc.rb:20:in `call'
	from kernel/common/throw_catch.rb:30:in `catch'
	from kernel/common/throw_catch.rb:8:in `register'
	from kernel/common/throw_catch.rb:29:in `catch'
	from kernel/bootstrap/proc.rb:20:in `call'
	from kernel/common/throw_catch.rb:30:in `catch'
	from kernel/common/throw_catch.rb:8:in `register'
	from kernel/common/throw_catch.rb:29:in `catch'
	from /home/mxvanzant/.rvm/gems/rbx-2.5.2@global/gems/rubysl-irb-2.1.1/bin/irb:12:in `__script__'
	from kernel/common/kernel.rb:497:in `load'
	from /home/mxvanzant/.rvm/gems/rbx-2.5.2@global/bin/irb:23:in `__script__'
	from kernel/common/block_environment.rb:53:in `call_on_instance'
	from kernel/common/eval.rb:176:in `eval'
	from /home/mxvanzant/.rvm/gems/rbx-2.5.2/bin/ruby_executable_hooks:15:in `__script__'
	from kernel/delta/code_loader.rb:66:in `load_script'
	from kernel/delta/code_loader.rb:152:in `load_script'
	from kernel/loader.rb:655:in `script'
	from kernel/loader.rb:809:in `main'rbx-2.5.2 :002 >

**Comment by ohler55** [comment]
I'll work with the Rubinius team to get this fixed.

**Comment by mxvanzant** [comment]
Thank you!!!

**Comment by ohler55** [comment]
I am not able to build rbi on my machines but I have a binary for rubinius 2.5.5 that brixen was kind enough to build for me. It still shows no errors with Oj 2.12.9. Can you try on a move recent version of rubinius?

> ruby --version
rubinius 2.5.5 (2.1.0 433d9b8c 2015-05-15 3.5.1 JI) [x86_64-darwin14.4.0]
eye-3 test (master)> irb
irb(main):001:0> require 'oj'
=> true

**Comment by mxvanzant** [comment]
Yes, I'll see if I can get a newer version. Thanks!

**Comment by ohler55** [comment]
Any updates?

**Comment by mxvanzant** [comment]
Sorry. This is on the back burner for now. I'll let you know when I get 
to it, but it may be a while. Thanks for checking!

**Comment by ohler55** [comment]
Seems to build on travis. Closing for now unless someone can provide a test case that fails.
