### ISSUE TITLE
How to use Oj :symbol_key in ActiveRecord attributes

### ISSUE THREAD

**Issue by ozeron** [ohler55/oj#248]
Hello, 
I store big json with repeating keys in Postgres and I'm using Oj as defaut JSON serializer in Rails 4.2.2. I want to save memory, and use symbols as keys. When I override default option to `symbol_key: true` globally, Rails fails.
Is there any way to specify `symbol_key:` true for loading attributes in Rails model?

**Comment by ohler55** [comment]
What mode are you serializing the object with? :object or something else? Is Oj being used to load the objects?

**Comment by ozeron** [comment]
@ohler55 I use `gem 'oj_mimic_json'` in Rails with default options, mode is set to `compat`.
I have model `CurrentData` with attributes `all_data_records` type json. Now I have to use for every json attribute smth like:
``` ruby
def all_data_records_symbolized
  Oj.load(all_data_records_before_type_cast, symbol_keys: true)
end
```
Is there other way to load all json attributes from db with Oj option `symbol_keys: true`? 

P.S. Oj is great! Thank you for this library!

**Comment by ohler55** [comment]
The Oj default options should be honored. Have you tried setting that in the default options?

**Comment by ozeron** [comment]
@ohler55 Yes, I use them and Oj return original json with string for keys.
Probably I'll close issue and will use workaround with `attribute_before_type_cast`

**Comment by ohler55** [comment]
ok, I'll look into the default setting and make sure there is not a problem there. There may be some other rails action that is breaking it that I don't know about though.
