### ISSUE TITLE
Oj.load raises SyntaxError instead of Oj::ParseError

### ISSUE THREAD

**Issue by fxfilmxf** [ohler55/oj#249]
It looks like a recent release started raising a SyntaxError instead of an Oj::ParseError on some kinds of bad input. Is there a reason for this change?

Example:

Previous Behavior (version 2.10.4):
`Oj.load('somejunk') => # Oj::ParseError`
`Oj.load('1234otherjunk') => # Oj::ParseError`

New Behavior (version 2.12.10):
`Oj.load('somejunk') => # Oj::ParseError`
`Oj.load('1234otherjunk') => # SyntaxError`

**Comment by croeck** [comment]
+1

**Comment by ohler55** [comment]
You can verify that it does what you want in the github version. I wanted to try and address one more issue before releasing.

**Comment by ohler55** [comment]
Release made.

**Comment by croeck** [comment]
Perfect, thanks a lot!
