### ISSUE TITLE
oj cannot parse specific number in scientific notation properly

### ISSUE THREAD

**Issue by mmkhmk** [ohler55/oj#253]
It looks like oj cannot handle specific number in scientific notation.

```
irb(main):008:0> Oj.object_load('3.28E7')
=> 32799999.999999996
```

This issue can be seen on '2.28E7'. There is no problem on other numbers.

This was found using oj 2.12.12.

**Comment by ohler55** [comment]
I'll look into it.

**Comment by mmkhmk** [comment]
Thank you!

**Comment by ohler55** [comment]
Please check the latest version on github. If it looks good I will make a release.

**Comment by mmkhmk** [comment]
Thank you for the handling.
I checked it but it didn't solve the issue.
Could you check it again?

**Comment by mmkhmk** [comment]
Thank you for the quick handling!
I checked it and it solved the issue.
