### ISSUE TITLE
oj.so built in ext looks like it's being copied to wrong directory in lib

### ISSUE THREAD

**Issue by mkillianey** [ohler55/oj#255]
When the oj gem is built on a Linux machine, the ext/oj/oj.so file is incorrectly copied to lib/oj.so, instead of lib/oj/oj.so, and so it isn't being up correctly.  This looks to be because the Makefile is being created in "oj" instead of "oj/oj", which seems to be what [the RubyGems "gems with extensions"](http://guides.rubygems.org/gems-with-extensions/) page suggests.

The gem seems to be compensating by adding 'ext' to the require_paths, but this shouldn't be necessary, if I'm reading [the RubyGems specification](http://guides.rubygems.org/specification-reference/#require_paths=) correctly.

**Comment by ohler55** [comment]
With your changes in the current branch can this be closed? I will be making a release as soon as I get confirmation 2 other bugs are closed.

**Comment by mkillianey** [comment]
Absolutely...thanks!

**Comment by ohler55** [comment]
Your change is release 2.12.13. I think this can be closed.
