### ISSUE TITLE
Cloned/dup-ed objects are closed

### ISSUE THREAD

**Issue by pmontrasio** [ohler55/oj#257]
I have this code

    url = "https://to.some/json/api/returning/paginated/data"
    results = []
    while url
      response = HTTParty.get(url, headers: @headers)
      Oj::Doc.open(response_body) do |doc|
         results << doc.dup # or doc.clone, same issue
         url = parse_doc_to_get_the_url_of_the_next_page
      end
    end
    do_something_on_results

doc get closed at the end of the block but my understanding is that doc.dup and doc.clone should be left open because they are different objects. I verified they have different object_id

To my surprise ```results[0].fetch("/")``` returns ```IOError: Document already closed or not open```.
It's either some issue with Oj or with my understanding of Ruby.

I can work around it by storing the String response body into ```results``` but I'd like not to have to parse the strings twice. What I can't do is to process the data inside the loop because I need all of them.

**Comment by pmontrasio** [comment]
A simpler way to reproduce the issue

    doc = Oj::Doc.open('{"some": "thing"}')
    doc1 = doc.dup
    doc2 = doc.clone
    doc.fetch("/some") # "thing"
    doc1.fetch("/some") # IOError: Document already closed or not open.
    doc2.fetch("/some") # IOError: Document already closed or not open.
    doc.close # nil
    doc1.close # IOError: Document already closed or not open.
    doc2.close # IOError: Document already closed or not open.

Apparently Oj closes the document in the process of cloning/duping it.

**Comment by ohler55** [comment]
I will look into it this weekend and include the fix in the next release.

**Comment by ohler55** [comment]
I had a chance to look at the issue. First, the dup() and clone() methods are not implemented in the Doc object so the default Object dup and clone are used. In both cases the specs call for a shallow copy.  That would mean that the data portion of the Doc, the string is not copied. While this does not present a problem for strings it does for something like a file or stream as input.

Your solution of taking the result string and then calling Doc open on that is the best short term solution. If I implement the dup() or clone() methods I would do something like that anyway. I will look more closely at the feasibility of either that or something similar but make sure it works across all input types.

**Comment by pmontrasio** [comment]
If cloning the object would require to parse again the string I think we can do without it and implement that ourselves. You could add to the README a warning about dup and clone returning a closed object.

Maybe a method to reopen a closed Doc would be handy but I think I can close this issue now, unless you want to keep it open for reference. Thanks.

**Comment by ohler55** [comment]
Lets leave the issue open for now. Dup and clone might not be the correct approach but I'll come up with something. The string would not be re-parsed in any case.

**Comment by ohler55** [comment]
So stepping back a bit, in the original code snippet you call Doc.open() with a block. Is there a reason you can't call Doc.open() without the block and then push the returned value onto the results array? Each Doc would remain open. Seems simpler than cloning when there really is no need to close the Doc in the loop.

**Comment by pmontrasio** [comment]
I did that to work around another problem. I'll probably open another issue for that as soon as I go back working on the project I'm using Oj for and I make sure it's not an issue with my script.

**Comment by ohler55** [comment]
I've looked at the code a bit more and supporting either dup() or clone() does not really seem worth the effort. I would have to add a lot of flags to note what memory is shared between the two objects. The approach I will take for now it to raise and exception if either is called.

**Comment by ohler55** [comment]
Oj 2.13.0 released. Exceptions are no raised.
