### ISSUE TITLE
Default to_s behavior when nothing works

### ISSUE THREAD

**Issue by jondeandres** [ohler55/oj#260]
Hi,

is there anyway to just serialize the value returned by `#to_s` when, in `object` mode, nothing works?

I know this is a strange behavior, but in some scenarios I'll have strange payloads that may contain things like a `Redis::Connection::TCPSocket` object, causing this:

```ruby
options = { :mode=> :object, :use_to_json => false,
            :circular => false }

Oj.dump(obj, options)

# NotImplementedError:
#       Failed to dump 'Redis::Connection::TCPSocket' Object (0b)
```

I think it'd be nice allow an option to just serialize the `#to_s` in some cases.

How this idea looks for you?

**Comment by ohler55** [comment]
The idea behind object mode is to be able to serialize and then deserialize back the an equivalent object. A string would not allow that. If you do not want to write custom to_json or similar then I could add an option to ignore object that can not be serialized instead of raising an exception. I would not want to create a string though as that would create other problems when loading.

From a philosophical perspective I generally try to keep data object separate from behavioral ones or at least when it comes to something like storing object to redis.

**Comment by jondeandres** [comment]
@ohler55 catched

in https://github.com/rollbar/rollbar-gem we are thinking on migrate to Oj instead using JSON. Our main problem comes cause some bugs between JSON and ActiveSupport.

The payloads our customer will send are very different, and there are strange things sometimes. Like this I've presented before.

Using `compat` mode with `use_to_json: false` and `circular: false` is becoming in a infinite loop I think.

Here a test:

```ruby
require 'redis'
require 'oj'
# require 'active_support/json'

redis = Redis.new

redis.set('foo', 'bar')

payload = {
            :key => {
              :value => redis
            }
}

options = { :mode=> :compat, :use_to_json => false,
            :circular => false }

result = Oj.dump(payload, options)
```

If I descomment the require for active_support/json it just doesn't finish never. If I comment it I have the above exception.

We need a way to serialize always something, even it's just a string. The problem it'd be better if we don't monkey patch objects or wrap them with a delegator and reimplement `#to_json`.

An option to avoid exceptions would be interesting. Maybe an option to define a "fallback` serialization method too, don't know.

**Comment by ohler55** [comment]
That description helps me understand what you are trying to do.

Active support does monkey patch objects unfortunately so it is not surprising you run into problems with circular references.

If you can accept using compete mode with the options you described in the last comment I think we can get something to work. I like the idea of a fallback function. Let me experiment a little with that idea and get something to you in the next day or two.

**Comment by jondeandres** [comment]
@ohler55 awesome :smile: . Let me know if you need any testing or help with this.

Thanks!

**Comment by ohler55** [comment]
The quick fix would be to output to_s in combat mode. I pushed that to github if you want to try it.

**Comment by jondeandres** [comment]
I've tested it, it works great :smile:. Will you release a new gem version soon?

Just one thing. Isn't suposed `use_to_json: false` to avoid calling that method? Included active support definitions?

Thanks.

**Comment by ohler55** [comment]
I can release shortly.

You are correct. With use_to_json: false the to_json method should not be called.

**Comment by jondeandres** [comment]
@ohler55 the problem is that, having that option to `false` and `active_support/json` loaded, the above script never finishes.

**Comment by jondeandres** [comment]
I think those are the calls from `dump.c` to `#as_json`. Finally ActiveSupport's `#as_json` is called.

**Comment by ohler55** [comment]
That would make sense. Oj does call the as_json or to_hash methods if they exist. Right now there is no flag to turn off those methods.

**Comment by jondeandres** [comment]
yah, this is obviously an ActiveSupport bug, I think it's with circular references or something like that.

It's happening with objects inheriting from `BasicSocket`. We are actually monkey patching `#as_json` there to just execute `#to_s`.

Anyway, thanks @ohler55 for look at this. We'll wait for your new release :smile:

**Comment by ohler55** [comment]
Released it hours ago. :-)

**Comment by jondeandres** [comment]
Awesome! Thanks!
