### ISSUE TITLE
Cannot use object mode with use_to_json

### ISSUE THREAD

**Issue by minor6th** [ohler55/oj#261]
I have a ruby hash with integer keys and I can use object mode to keep these keys as number when the hash is loaded.
Now I want to save some google/protobuf records into this hash, which will become null in the generated json string. 
I notice that the protobuf record class has a :to_json method, so I change the mode of Oj to :compat, and the output string will have the record serialized correctly.
Now the problem is that the integer hash keys are converted to string keys. 
I tried to set :use_to_json to true but that doesn't work in compat mode.

Is there a way to both serialize the protobuf and keep the integer hash keys?

**Comment by ohler55** [comment]
This gets a bit tricky but there is a way to do what you want. Compaq mode is meant to be compatible with the JSON gem. Object mode serializes objects so they can be reconstituted correctly. Using the to_json method could do all sorts of things that would break deserialization. There is a way around this problem though. Oj has the register_odd() method. Take a look at that. You can register functions for serializing and deserializing google protobufs what should allow you to continue using the object mode.

Take a look at the test_object.rb file and the test_odd_date_replaced() function. If it is not clear after that I can help get things working.

**Comment by minor6th** [comment]
I find that all my protobuf classes (generated by google protoc, and the number is less than 20) are in a module and are all direct subclass of Object.
I can manually register all the class in the module, but according to the document, register_odd is not optimized for large numbers of classes.

So how many classes are OK for register_odd?
Is it possible to register just the module instead of each class in it?

**Comment by minor6th** [comment]
I have tried register_odd and found that the result is not quite as expected.
The reason may be that register_odd is meant for reconstituted the original object, and what I expect is a dump mode:
1) works as object mode when the object has no to_json method
2) use the string generated by to_json as the raw output when there is a to_json method

In fact what I want is to serialize the google photobuf object and deserialize it to a pure ruby Hash.

Could you add a mode like that?
Thank you.

**Comment by ohler55** [comment]
I think I need to look at google protobuf for ruby and see why it is not a normal ruby object first.

I can not have serialization use the to_json method in object mode as not enough information is typically contained in the output to reconstruct the object. I'm sure we can come up with a solution but I need to think about it a bit after looking at the ruby protobuf.

**Comment by minor6th** [comment]
Thank you for the quick reply!

I think the google/protobuf stores its record in some C struct for performance and implement some ruby method such as :[] to access the key/value in the record. This makes the protobuf object just likes an ordinary ruby Hash.

It also implement a to_json method which will serialize the C struct into a standard json string.
In fact there is a to_hash method, but it cannot convert nested record, and for the performance reason, I don't want to first convert the record to ruby hash then dump it to json.

In my occasion, I don't need to reconsturct the protobuf object because I only used the protobuf as a ruby Hash and don't care it's class)

**Comment by ohler55** [comment]
Let me bounce some thoughts around with you.

So the idea is to use the protobuf to_json method but I don't want that kicking in for other classes. That means we Oj can not check just for the to_json method. Better not to anyway as it slows down the serialization.

Next is figuring out when to call the to_json method. Maybe some kind of option or list of classes that should use the to_json method or possibly any class in a module module.

My first thought is to extend the odd functionality to support modules and then let you do what ever you want with that. That would take minimal changes in the code, keep things fast, and provide a more general solution.

**Comment by minor6th** [comment]
I think that would be a perfect solution for me.
The point is to use the result of to_json as raw output.

For example, I have a dict: {"key" => <a ProtobufClass object>}.

 If I use register_odd, it will wrap the result in a dict:
 {"key": {"^O":"ProtobufClass","to_json": <return of :to_json escaped>}}

What I want is:
 {"key": <return of :to_json not escaped>}

Wish you could add some functionality for this kind of serialization. 
Thank you!

**Comment by ohler55** [comment]
In object mode you do not get to pick the format. In combat mode you do. The end result when deserialized should be what you expect though. That I can make happen. I can not give you both the JSON format and also the expected result.

**Comment by minor6th** [comment]
It possible to add a function like register_odd that call to_json at some class when dump in object mode?

**Comment by ohler55** [comment]
yes, I would change register_odd to also take a module. The generated JSON would contain the something other than just the to_json return value but with the correct creation function registered it should return a Hash as you asked for. Remember that the to_json returns a string and not a Hash so some conversion would be necessary.

**Comment by minor6th** [comment]
OK, I think that should works, but with a little overhead.
Because the to_json method should generate a standard JSON string with only the basic data type, which should be safe to be merged into the result of either object or compat mode.

**Comment by ohler55** [comment]
I'll see what I can do next week.

**Comment by ohler55** [comment]
I've been tied up but am back on the case now. I have an approach that I think will work but wanted to run it past you first.

The change is to modify register_odd to allow registration of modules and also add an option to odd to allow raw JSON text to be placed in the JSON output.

That will not give you exactly what you asked for since there will still be a wrapper around the JSON but when recreating the JSON will be parsed as a Hash or what ever it was and be handed to the create function registered with odd. That function could be a trivial pass through.

**Comment by minor6th** [comment]
Thank you ohler55! I think your approach should be working!
Only one more request, could you also make a option that allow recursively registration of modules? (i.e. when registering a module, all the sub-modules will also be registered.)

**Comment by ohler55** [comment]
I've been a bit busy but this is still on my list.

**Comment by ohler55** [comment]
I have a potential solution on github now. Please give it a try. I also added two unit test in test_object.rb near the end of the file. test_odd_mod and test_odd_raw.

**Comment by ohler55** [comment]
Oj 2.13.0 released. Unit tests indicate the problem is solved. No response here so closing.

**Comment by minor6th** [comment]
Sorry for the late response, I've been busy refactoring the project that uses Oj and cannot test the new feature until now.

**Comment by minor6th** [comment]
I have tested register_odd_raw with object mode and it worked as expected, the raw json was inserted into the output correctly.
The code I used is:

    class Object
        def pass_through(x)
            x
        end
    end
    Oj.register_odd_raw(SomeProtobufCls, Object, :pass_through, :to_json)

But here I have a new problem.

The Oj output will be read by another program, which doesn't have the definition of SomeProtobufCls. So is it possible to include Object, and :pass_through in the output? This will allow the reader program to re-create the object without knowing SomeProtobufCls. (I can extend Object in both program, but SomeProtobufCls cannot be determined until writer program start running.)

**Comment by ohler55** [comment]
If you look at the JSON output you should see the classname as the value of "^O". Since you can extend Object in both places there is no reason you can't add what ever other information you like in the contents of the pass_through. Just as a general note, it's really not a good idea to extend Object. I know it is something Rails does and it causes all sorts of problems when that behavior is not what is desired in a different class.

**Comment by minor6th** [comment]
I've looked into the JSON output, it looks like:

    {"field":{"^O":"MyClass","to_json":{"x":1}}}

I think if this can be extended to something like:

    {"field":{"^O":"MyClass","to_json":{"x":1},"create_cls":"Object","create_method":"pass_through"}}

or even:

    {"field":{"^O":null,"to_json":{"x":1},"create_cls":"Object","create_method":"pass_through"}}

then any program that loads this JSON string using Oj can decode the "field" object without having to write:

    Oj.register_odd_raw(MyClass, Object, :pass_through, :to_json)

and MyClass doesn't have to be defined in advance. because Oj can infer from {"^O":null} that the object is created using raw output of to_json.

The Object and :pass_through arguments in Oj.register_odd_raw may also be omitted so that Oj can just return the hash object without having to create a new object.

**Comment by ohler55** [comment]
The ^O field can not be null or the parser does not know what unmarshal function to use. I do not want to provide a second set of class and methods that could conflict with the ones registered with the register_odd function. Passing the class and method to invoke on the receiver side would make Oj an extreme security hole. It is one thing to pass around data but to have Oj invoke what could potentially be a random function is not something I want to jump into.

**Comment by minor6th** [comment]
Ok, I can understand the security risk and I will try to get my two programs working under the current Oj framework. If I have any other problem I will open a new issue.
Thank you for the release of the new version that support raw to_json output!

**Comment by ohler55** [comment]
Sounds good. I you need any suggestions you can email me as well.
