### ISSUE TITLE
Splicing Oj::Doc into Oj.dump(Hash) output

### ISSUE THREAD

**Issue by aidansteele** [ohler55/oj#262]
I have a use-case wherein I parse some JSON from a webservice, pull out a top level `"results": [...]` array, wrap it in my own object and serialize that. In pseudo-code:

```ruby
data = data_from_webservice()
hash = Oj.load(data)
results = hash['results']
output = {some: "metadata", other: ["keys"], results: results}
Oj.dump(output)
```

It's quite inefficient (and unnecessary) to parse the huge amount of data (~ megabytes) in `results`, only to re-encode it to JSON a moment later. A hack work-around is this:

```ruby
data = data_from_webservice()
doc = Oj::Doc.open(data)
results = doc.dump('/results')
output = {some: "metadata", other: ["keys"], results: "xxx"}
Oj.dump(output).sub('"xxx", results)
```

This works and is much faster, but I can't help but feel a little uneasy about string manipulation for generating JSON. 

Would it be possible for `Oj::dump` (or another method) to recognise an `Oj::Doc` instance and splice it into the output? e.g. Instead of the above, we could have:

```ruby
data = data_from_webservice()
doc = Oj::Doc.open(data)
doc.move('/results')
output = {some: "metadata", other: ["keys"], results: doc}
Oj.dump(output)
```

Would you find value in this? If so, I could potentially write a pull request for your review. Let me know your thoughts either way. :smile:

**Comment by ohler55** [comment]
Have you tried this:
```ruby
data = data_from_webservice()
doc = Oj::Doc.open(data)
doc.move('/result')
result = doc.fetch
output = {some: 'metadata', other: ['keys'], results: result}
Oj.dump(output)
```

Seems like that might be what you want. That or I have misunderstood what you need.

**Comment by aidansteele** [comment]
Thanks for the quick response. My aim is to avoid the round trip JSON -> Hash -> JSON as I'm not modifying the contents of the hash, just sticking it into another document. 

Does that make sense? I suppose this is a bit of a corner case, but for large documents this can have a substantial performance improvement.

**Comment by ohler55** [comment]
With the Oj::Doc use only a minimal set of parts are loaded. The conversion to a Hash happens only when fetch is called. Thats what makes it fast.

Something else to try would be to use the Oj::Doc dump to take the JSON for that element and then wrap it in an object that returns the string when to_json() is called. I have not checked the performance but it might be a bit faster depending on how large the Hash would be.

**Comment by aidansteele** [comment]
That's perfect! I created a wrapper class and the `#to_json` method returns the output of `Oj::Doc#dump` - it works flawlessly and the performance improvement is superb.

Thanks for the great gem and support :+1:

**Comment by ohler55** [comment]
Great, glad it worked for you.
