### ISSUE TITLE
Cannot serialise non-array descendants

### ISSUE THREAD

**Issue by mklocek** [ohler55/oj#263]
Oj is not able to serialize a class that is not an Array descendant but still returns an Array on to_hash. 

This is a problem when you're trying to serialize an ActiveRecord::Relation object (or Foo::ActiveRecord_Relation in our case) which is not a subclass of Array but still returns [] when serialized.

This only happens in `mode: :compat`.

```
class NotArrayDescendant
  def to_hash
    []
  end  
end  

class ArrayDescendant < Array
  def to_hash
    []
  end  
end

::Oj.dump ArrayDescendant.new, mode: :compat
=> "[]"

::Oj.dump NotArrayDescendant.new, mode: :compat
TypeError: #<Class:0x00000009298db8>::NotArrayDescendant.to_hash() did not return a Hash.
```

**Comment by ohler55** [comment]
You have provided a to_hash function that returns an array and not a hash. The type error is correct. to_hash() as the name implies should return a Hash. Use the to_json or as_json methods if you want to return something other than a Hash.

**Comment by ohler55** [comment]
Any reason not to close this?

**Comment by mklocek** [comment]
The problem occurs when I try to do `to_json` on collection represented by 'roar-rails' collection representers. Roar makes my ActiveRecord_Relation (not array descendant) object respondable for `to_hash` method and returns... array. Then I see what I described in code sample above.

**Comment by ohler55** [comment]
I can make a change to Oj to accept any value returned. It is not correct but I don't think it should break anything for anyone else. The correct fix is to get the ActiveRecord object to return a Hash when the to_hash method is called. A to_s does not return an Array nor does to_i. It is a bug in roar-ruby or ActiveRecord if it implements to_hash to return anything other than a Hash.

I know you are caught in the middle and just want to get your stuff working. I'll put in a change to Oj but please create an issue with either roar-ruby or ActiveRecord, which ever is returning something other than a Hash.

**Comment by ohler55** [comment]
Try the version on github and see if it fixes the problem.

**Comment by ohler55** [comment]
Oj 2.13.0 released. Unit tests indicate the problem is solved. No response here so closing.
