### ISSUE TITLE
:xss_safe mode escapes non English characters?

### ISSUE THREAD

**Issue by yijia-zhan** [ohler55/oj#266]
I understand `xss_safe` mode is to escape characters like `<`, `>` and `&`, but it also escapes other non-English UTF-8 characters. For example:

```ruby
str = "morning おは صباح الخير matinée 早上"

Oj.dump(str, escape_mode: :json)
# => "\"morning おは صباح الخير matinée 早上\""

Oj.dump(str, escape_mode: :xss_safe)
# => "\"morning \\u304a\\u306f \\u0635\\u0628\\u0627\\u062d \\u0627\\u0644\\u062e\\u064a\\u0631 matin\\u00e9e \\u65e9\\u4e0a\""
```

Shouldn't `xss_safe` only escape xss sensitive characters, the keep it UTF-8 for everything else?

Thanks.

**Comment by ohler55** [comment]
The reason the hi-bit characters are escaped is for the older IE browsers that defaulted to UTF-7. The intent was to make the mode as paranoid as possible.

I have never found a need to use the mode myself. I don't put JSON directly into web pages but instead feed JSON to Javascript when it is needed through something like websockets. (www.piperpushcache.com)

**Comment by ohler55** [comment]
Any reason not to close this?

**Comment by yijia-zhan** [comment]
This doesn't cause us any real issues but I was just curious of the intent of the escaping all high-bit characters. Thanks @ohler55 for your answer! This can be close now.
