### ISSUE TITLE
second_precision with compat mode

### ISSUE THREAD

**Issue by smanolloff** [ohler55/oj#267]
Hi,

just FYI
a minor issue, not worth fixing, which could be listed as a known compatibility issue. 

```ruby
RUBY_VERSION
# => "2.1.5"

Oj::VERSION
# => "2.13.0"

t = Time.new(2015, 1, 5, 21, 37, 7.123456, -8 * 3600)

# unexpected -- precision is 3
Oj.dump(t, mode: :compat, time_format: :xmlschema, second_precision: 6)
# => "\"2015-01-05T21:37:07.123-08:00\""

# expected -- precision is 6
Oj.dump(t, mode: :object, time_format: :xmlschema, second_precision: 6)
# => "{\"^t\":\"2015-01-05T21:37:07.123456-08:00\"}"
```

this is on OSX 10.8 *only*; I tried Linux and OSX 10.10 and it works as expected.

**Comment by ohler55** [comment]
I'll take a look.

**Comment by ohler55** [comment]
I'm afraid I don't have the ability to set up a test to confirm. OS X 10.8 is old as is Ruby 2.1.5. I can use rebind to get Ruby set up but I don't have any machines running OS X 10.8. As you pointed out newer version of OS X work correctly. I don't think this is worth chasing and fixing.

**Comment by smanolloff** [comment]
:+1:
