### ISSUE TITLE
Memory consumption over time compared to Yajl

### ISSUE THREAD

**Issue by carlosantoniodasilva** [ohler55/oj#269]
Hello!

I've been looking into Oj as a possible replacement for Yajl, and I'm happy with how fast it is parsing things, great job! :)

I have setup a 7MB json file just for testing purposes, with these results on my machine:

```ruby
require 'benchmark/ips'
require 'json'
require 'oj'
require 'yajl'

json = File.read('json.json')

if ENV['NO_GC']
  GC.disable
  puts 'GC Disabled...'
end

Benchmark.ips do |b|
  b.time = 10
  b.warmup = 5

  b.report('json') { JSON.parse json }
  b.report('yajl') { Yajl::Parser.parse json }
  b.report('oj') { Oj.load json }
  b.compare!
end

=begin
Press ENTER or type command to continue
Calculating -------------------------------------
                json     1.000  i/100ms
                yajl     1.000  i/100ms
                  oj     1.000  i/100ms
-------------------------------------------------
                json      4.218  (±23.7%) i/s -     39.000
                yajl      3.559  (±28.1%) i/s -     35.000
                  oj      5.749  (±17.4%) i/s -     54.000

Comparison:
                  oj:        5.7 i/s
                json:        4.2 i/s - 1.36x slower
                yajl:        3.6 i/s - 1.62x slower


Press ENTER or type command to continue
=> GC Disabled...
Calculating -------------------------------------
                json     1.000  i/100ms
                yajl     1.000  i/100ms
                  oj     1.000  i/100ms
-------------------------------------------------
                json      2.493  (± 0.0%) i/s -     25.000
                yajl      2.654  (± 0.0%) i/s -     27.000
                  oj      3.023  (± 0.0%) i/s -     30.000

Comparison:
                  oj:        3.0 i/s
                yajl:        2.7 i/s - 1.14x slower
                json:        2.5 i/s - 1.21x slower
=end
```

After that I decided to benchmark Oj hitting one test application, and I was again happy to see it was performing faster, however I noticed increased memory usage, and I wanted to understand a little bit more about it.

The following graphs should help illustrate the point. I ran the `perf:mem_over_time` task from [derailed](https://github.com/schneems/derailed_benchmarks) against this application, which parses a small JSON payload on input, and a bigger payload returned from the database, then generates the JSON response from that db payload. The change between the perf runs was only removing Yajl  and adding `oj` and `oj_mimic_json` to the Gemfile.

### 2k requests 
![screen shot 2015-10-27 at 1 06 37 pm](https://cloud.githubusercontent.com/assets/26328/10762462/4ebcf782-7cad-11e5-9c73-fae11970d590.png)

### 10k requests
![screen shot 2015-10-27 at 1 08 48 pm](https://cloud.githubusercontent.com/assets/26328/10762461/4ebb54ea-7cad-11e5-8fcf-9397b5b6814d.png)

I haven't tried to identify if the memory increase is due to parsing or generation. Is it known that Oj consumes more memory than others like Yajl? Or maybe I am missing something? I'll dig a bit more and try different things, but wanted to share my findings so far, maybe someone will be able to give some direction / help.

Thanks!

**Comment by ohler55** [comment]
Can you explain the drop off in memory use at the end?

I'd have to get a better understanding of the JSON being used to say for sure but there are some options in Oj that improve performance that may cause more memory use. The symbol_keys is one such option. If you have an expanding set of hash keys in the data the memory use will increase. If you have a relatively homogeneous set of JSON then I would not expect to see it expand.

**Comment by carlosantoniodasilva** [comment]
The drop off shows when the performance task has finished performing the requests (2k or 10k requests against this Rails app in these graphs) - which shows that with Oj it has finished considerably faster than with Yajl apparently. Sorry I should've used a better graph that didn't have that.

I believe the set of hash keys being used should not expand, as the performance test is hitting the same Rails action over and over, with the same request params, and it should be receiving back pretty much the same payload from the database every time, as the database records should not be changing over time (considering this is the single action being hit).

I'll see if I can do some more tests around that and provide extra information as possible. Thanks.

**Comment by ohler55** [comment]
More info would be great. I have checked Oj for memory leaks but if you have found a situation where there are some I want to fix them. Odd that it hold pretty steady until the last 20% or so.

**Comment by ohler55** [comment]
Any updates?

**Comment by carlosantoniodasilva** [comment]
@ohler55 I'm sorry, I haven't had time to circle back and do more detailed benchmarks. We did deploy Oj to production even if it'd trade a bit more memory for the performance gain, and so far I haven't seen any big issues.

Please feel free to close this for now, once I have time (early next year I'm imagining) I'll do some more tests and in case I find anything I'll post back here.

**Comment by ohler55** [comment]
Ok, thanks.
