### ISSUE TITLE
Oj compatibility with AMS

### ISSUE THREAD

**Issue by erlandsona** [ohler55/oj#270]
I know this is a repeat of #138 but I wanted to get an update...

I'm working in a project where for the past couple weeks I've unimplemented AMS because of the difficulty of implementing it with Oj... that said I'm starting to need the capability to nest associations in the JSON output and it would be really nice to have AMS back.

I'm running...
Rails 4.2.4
Ruby 2.2.2
Latest Oj
AMS versions [0.8, 0.9, 0.10]...

The main issues I'm having are that AMS adds the most latency to response times out of the three JSON options... those being Oj.dump... raw to_json as implemented by the render method... and AMS's overriding of the as_json method I think???

The last commit I had with AMS that was sort of working with OJ looked like this...
```ruby
def index
...
  render json: Oj.dump(
    ActiveModel::ArraySerializer.new(@brands, each_serializer: BrandSerializer)
  )
end
```

The issue with this was that there was no root key in the JSON enabling me to add a meta key into the json output... I could solve that like this...

```ruby
def index
...
  render json: Oj.dump({
    pagination: pagination(@brands, params[:per_page]),
    brands: ActiveModel::ArraySerializer.new(@brands, each_serializer: BrandSerializer)
  )
end
```
But that just looks wrong given that I should be able to just write something along the lines of...

```ruby
def index
...
  render json: @brands, meta: pagination(@brands, params[:per_page]), meta_key: pagination
end
```

The end goal being that AMS can be used to create the appropriate JSON format but Oj's version of the as_json / to_json method would be called by the render method in rails...

Unfortunately I can't figure out how to get this right without hacks and even without AMS I don't know how to tell whether the Oj_mimic_json gem is actually overriding the rails to_json method or not?

The only indicator that Oj is doing anything is when I check the server logs and the output for the controller actions says that the views take 0.2ms as opposed to when I don't have Oj and the views take 150ms or 90ms or whatever... What's wierd is that I can't figure out why even when I have Oj "turned on" the actual response times don't change? Regardless of how many ms the views metric shows the response times are generally the same?

Any thoughts?

**Comment by ohler55** [comment]
My knowledge of rails and the active components is pretty limited. I think you assumption that the as_json method is being called though. If you are willing we can do some experimenting though. Right now it is not possible to turn off the use of as_json in Oj. to_json can be turned off but not as_json. I can add an option for that. If that works for you I'll make a release.

As for over-riding, the as_json method get priority over to_json so the mimic version is most likely not being reached.

**Comment by ohler55** [comment]
Are you still interested or should I close this issue?
