### ISSUE TITLE
Ruby default float_precision (0) issue

### ISSUE THREAD

**Issue by thibaudgg** [ohler55/oj#274]
Hey,

We're using Oj with MultiJson with the following settings:

``` ruby
require 'oj'
require 'oj_mimic_json'

MultiJson.use :oj
Oj.default_options = { float_precision: 0 } # Use Ruby default
```

It was working great on `2.13.0` but since the `2.13.1` it breaks with float with a lot of precision (lat, lng), rspec diff:

``` patch
-  :lat=>40.492962029838964,
+  :lat=>40.49296202983896,
```

Any ideas?

**Comment by ohler55** [comment]
There was a bug in that part of the code and I did some refactoring. I guess I trimmed off too many places. I'll get it fixed.

**Comment by thibaudgg** [comment]
Great, thanks Peter!

**Comment by ohler55** [comment]
I just pushed a potential fix to github. Can you try it out? It turns out that 40.0 + 0.492962029838964 in C strips off the last digit. The fix is to convert to BigDecimal. Depending on the options that may be converted back to a Float.

**Comment by thibaudgg** [comment]
Just tried with oj master and it seems to have fix our issue, thanks for the update! :clap: 
Please let me know when a new oj release it out.

**Comment by ohler55** [comment]
The release was made.

**Comment by thibaudgg** [comment]
:+1: Thanks!
