### ISSUE TITLE
mimic_JSON is very slow

### ISSUE THREAD

**Issue by brandonweiss** [ohler55/oj#275]
I was profiling the boot time of our application and I discovered that a huge percentage of the startup time  is in an initializer where we call `Oj.mimic_JSON`. It seems to take about five seconds (although it varies). I'm just curious why it takes so long and if there's any way it can be improved? Thanks!

**Comment by brandonweiss** [comment]
Sorry, that was misleading. The actual call to `mimic_JSON seems to take ~1s. But afterwards we do this:

```
suppress Exception do
  require 'json'
end
```

It seems like there's an issue where if we happen to require json elsewhere it causes conflicts, so we have to immediately require it here in order to prevent them. And the combination of the two takes ~5s.

Do these conflicts happen to be a known issue? If they are, are they still an issue?

**Comment by ohler55** [comment]
I have not seen that myself but will do some checks here. Why would you require 'json' after calling mimic_JSON? mimic_JSON should have already replaced the JSON functions at that point. You can also check to see if JSON is defined like this:
``` ruby
Object::const_defined?('JSON')
```

**Comment by ohler55** [comment]
I just ran a super simple test that fires up Ruby, requires oj, and then calls mimic_JSON. All of that on my PowerBook took just over 0.1 seconds. Can you provide more information on how you are determining you time figures?
```
> time ruby -roj -e "Oj.mimic_JSON()"

real	0m0.122s
user	0m0.075s
sys	0m0.044s
```

**Comment by brandonweiss** [comment]
I'm not totally sure why the require was/is necessary. The explanatory comment wasn't particularly helpful. I'm going to remove the require and see if any issues crop up.

I'm using a gem called [`Bumbler`](https://github.com/nevir/Bumbler) to benchmark it. It benchmarks bundle load time and also initializer load time (`bumbler --initializers`).

**Comment by ohler55** [comment]
I have not tried bumbler yet. Do you get similar results when not using it and just taking the difference in time before and after?

The way I usually approach something like this is to simplify as much as possible and the add parts back in until the problem shows up again.

**Comment by brandonweiss** [comment]
If I execute the mimic method and nothing else (like you did), it's about 170ms for me.

I removed the require json hack, and now if I time the initializer it's about 400ms. So there's probably a little overhead there related to the initializer, but the bulk of the issue was just the require json hack we were doing :disappointed: Sorry about the trouble!

**Comment by ohler55** [comment]
Glad you got it figured out.

**Comment by brandonweiss** [comment]
Actually, maybe you can help me understand this a little better. If you require json, then minic it, then require it again, what happens? Normally when you require a gem a second time nothing happens, right? It's essentially a no-op? So why does requiring json a second time take ~3s? Is it overriding the replaced methods (un-mimicking)?

**Comment by brandonweiss** [comment]
I'm definitely missing something here. Maybe this is a crap way to do this, but I created several benchmarks (in separate files, run individually), to try and see what the effect is.

```ruby
require "benchmark"

Benchmark.bmbm do |x|
  x.report("require json once") do
    require "json"
  end
end
```
```
Rehearsal -----------------------------------------------------
require json once   0.010000   0.000000   0.010000 (  0.010176)
-------------------------------------------- total: 0.010000sec

                        user     system      total        real
require json once   0.000000   0.000000   0.000000 (  0.000036)
```

```ruby
require "benchmark"

Benchmark.bmbm do |x|
  x.report("require json twice") do
    require "json"
    require "json"
  end
end
```

```
Rehearsal ------------------------------------------------------
require json twice   0.010000   0.000000   0.010000 (  0.008135)
--------------------------------------------- total: 0.010000sec

                         user     system      total        real
require json twice   0.000000   0.000000   0.000000 (  0.000030)
```

```ruby
require "benchmark"
require "oj"

Benchmark.bmbm do |x|
  x.report("require json and mimic") do
    require "json"
    Oj.mimic_JSON
  end
end
```

```
Rehearsal ----------------------------------------------------------
require json and mimic   0.010000   0.010000   0.020000 (  0.020478)
------------------------------------------------- total: 0.020000sec

                             user     system      total        real
require json and mimic   0.010000   0.010000   0.020000 (  0.015620)
```

```ruby
require "benchmark"
require "oj"

Benchmark.bmbm do |x|
  x.report("require json and mimic and require json") do
    require "json"
    Oj.mimic_JSON
    require "json"
  end
end
```

```
Rehearsal ---------------------------------------------------------------------------
require json and mimic and require json   0.010000   0.010000   0.020000 (  0.026099)
------------------------------------------------------------------ total: 0.020000sec

                                              user     system      total        real
require json and mimic and require json   0.010000   0.010000   0.020000 (  0.018640)
```

The difference between requiring once and twice is basically nothing, which I would expect. And the difference between mimicking and mimicking and then requiring again is basically nothing, which I would expect.

If I try to time the actual calls in the initializer I get about 350ms for mimicking and 100ms for re-requiring. I guess that makes sense—there's a lot more going on then when a Rails app boots then when I benchmark it in isolation, so it's possible there's a garbage collection pause or something that's adding a bit of time.

I think I'm finally satisfied :grin:

**Comment by ohler55** [comment]
Sounds like you have it figured out while I was sleeping. :-)

**Comment by brandonweiss** [comment]
So I removed that `require "json"` after mimicking and totally broke our app in production :disappointed: 

```
[ 2015-12-03 17:16:18.9424 3070/7f84f7c0c700 Pool2/Implementation.cpp:271 ]: Could not spawn process for application /apps/intercom/current: An error occured while starting up the preloader.
  Error ID: 87dbeeb9
  Error details saved to: /tmp/passenger-error-X2k2n9.html
  Message from application: uninitialized constant JSON (NameError)
  /apps/intercom/releases/intercom-ede9b1e19a4b77a3d9798fa3673353d68b21df6d-2015-12-03-1703/config/environment.rb:2:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /apps/intercom/releases/intercom-ede9b1e19a4b77a3d9798fa3673353d68b21df6d-2015-12-03-1703/vendor/bundle/ruby/2.1.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
  /apps/intercom/releases/intercom-ede9b1e19a4b77a3d9798fa3673353d68b21df6d-2015-12-03-1703/vendor/bundle/ruby/2.1.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/local/lib/ruby/gems/2.0.0/gems/passenger-enterprise-server/helper-scripts/rack-preloader.rb:96:in `eval'
  /usr/local/lib/ruby/gems/2.0.0/gems/passenger-enterprise-server/helper-scripts/rack-preloader.rb:96:in `preload_app'
  /usr/local/lib/ruby/gems/2.0.0/gems/passenger-enterprise-server/helper-scripts/rack-preloader.rb:142:in `<module:App>'
  /usr/local/lib/ruby/gems/2.0.0/gems/passenger-enterprise-server/helper-scripts/rack-preloader.rb:13:in `<module:PhusionPassenger>'
  /usr/local/lib/ruby/gems/2.0.0/gems/passenger-enterprise-server/helper-scripts/rack-preloader.rb:12:in `<main>'
```

I'm definitely out of my depth here. It seems like the issue only happens when the app boots in Passenger, which is threaded, I believe?

**Comment by ohler55** [comment]
I'm pretty sure Passenger is threaded. Odd that it would require loading the json gem again after mimic. I'm grasping at straws but have you tried calling mimic_JSON multiple times?

**Comment by ohler55** [comment]
I hope you can test this outside production. ouch

**Comment by brandonweiss** [comment]
Calling it multiple times doesn't seem to be a problem. I created a tiny rack app and tried various configurations of calling `mimic_JSON` and then using the JSON gem, but couldn't get it to break.

**Comment by ohler55** [comment]
It must have something to do with Passenger. Let me look at that code and see if I can figure what it does.

**Comment by brandonweiss** [comment]
Thanks!

**Comment by ohler55** [comment]
I was looking for a place that might spawn multiple Ruby environments. Didn't see it but lets try something. Can you place a print statement right after each call to mimic_JSON and the require json? That is when using passenger. Not in production. :-)

**Comment by brandonweiss** [comment]
I tried to recreate it as closely as possible by creating a Rails app and booting it with Passenger. But that also works fine. It's possible I'm not recreating it properly, though, because we have passenger settings tweaked in production, and we're passenger enterprise server, which might be a different version than the latest passenger I'm trying with :disappointed:

**Comment by ohler55** [comment]
That makes it really difficult. Were you able to drop in some print statements anyway? I'm curious whether that spot in the code is hit more than once. Like have more than one thread calling the same code.

**Comment by brandonweiss** [comment]
Hey! I'm back 😞 

We got rid of our weird require hacks and whatnot so that issue is out of the way, but I'm back now to the issue of calling `Oj.mimic_JSON` and it taking a strangely long amount of time. It takes between 4 seconds and sometimes as long as 9 seconds, and this is in a normal Rails console. I'm not sure exactly how the mimicking works, but we have a very large Rails application… could that make mimicking take more time somehow?

**Comment by brandonweiss** [comment]
If I just boot IRB, require the oj, and then mimic, it's super fast, as I'd expect it to be. Maybe the issue only happens when there's a lot in memory or if there's a lot of constants?

**Comment by brandonweiss** [comment]
```ruby
require "benchmark"
require "oj"

Benchmark.bmbm do |x|
  x.report("mimicking JSON") do
    Oj.mimic_JSON
  end
end
```

IRB:

```
Rehearsal --------------------------------------------------
mimicking JSON   0.000000   0.000000   0.000000 (  0.003552)
----------------------------------------- total: 0.000000sec

                     user     system      total        real
mimicking JSON   0.010000   0.000000   0.010000 (  0.003577)
```

Rails console:

```
Rehearsal --------------------------------------------------
mimicking JSON   0.130000   0.870000   1.000000 (  3.250750)
----------------------------------------- total: 1.000000sec

                     user     system      total        real
mimicking JSON   0.170000   0.520000   0.690000 (  3.976923)
```

The 9 seconds appears to be an unusual, very occasional aberration, but it's regularly between 2 and 4 seconds.

**Comment by ohler55** [comment]
mimic_JSON defines some classes and methods on those classes but really doesn't do that much. It might do enough to trigger a GC though. Can you call GC.start() before running the benchmark? If it is much faster then I would guess a GC is being triggered by the call to mimic_JSON. If not we have some more detective work to do.

**Comment by brandonweiss** [comment]
Hmm, that didn't seem to make a difference.

```ruby
require "benchmark"
require "oj"

GC.start

Benchmark.bmbm do |x|
  x.report("mimicking JSON") do
    Oj.mimic_JSON
  end
end
```

```
Rehearsal --------------------------------------------------
mimicking JSON   0.120000   1.310000   1.430000 (  2.909455)
----------------------------------------- total: 1.430000sec

                     user     system      total        real
mimicking JSON   0.170000   0.910000   1.080000 (  3.226434)
```

**Comment by ohler55** [comment]
One other thing mimic_JSON does is to look at the $LOADED_FEATURES. If you have a very large project maybe that is causing the problem. You can try that out separately by calling Oj.mimic_loaded(). Try benchmarking that. If it take a while that is something I'll look at changing if possible.

**Comment by brandonweiss** [comment]
Aha!

```ruby
require "benchmark"
require "oj"

Benchmark.bmbm do |x|
  x.report("mimicking loaded") do
    Oj.mimic_loaded
  end
end
```

```
Rehearsal ----------------------------------------------------
mimicking loaded   0.240000   0.620000   0.860000 (  3.845216)
------------------------------------------- total: 0.860000sec

                       user     system      total        real
mimicking loaded   0.270000   0.410000   0.680000 (  3.821173)
```

**Comment by brandonweiss** [comment]
```ruby
$LOADED_FEATURES.count
=> 4075
```

**Comment by ohler55** [comment]
ok, I'll look at optimizing that code.

**Comment by brandonweiss** [comment]
Thanks so much! We really appreciate all your effort/help on this ❤️ This is going to save us a crazy amount of time.

**Comment by ohler55** [comment]
Give the "floats" branch a try. I made some changes to mimic.rb that may be faster.

**Comment by brandonweiss** [comment]
```
Rehearsal --------------------------------------------------
mimicking JSON   0.020000   0.010000   0.030000 (  0.027486)
----------------------------------------- total: 0.030000sec

                     user     system      total        real
mimicking JSON   0.020000   0.000000   0.020000 (  0.023751)
```

**Comment by brandonweiss** [comment]
![anigif_enhanced-2318-1404332198-8](https://cloud.githubusercontent.com/assets/4727/16631830/06ec4fe4-4376-11e6-9d66-d1c0aa2cf6c5.gif)

**Comment by ohler55** [comment]
That certainly looks better. Did the rest of the applications work as expected? Just to make sure nothing else broke.

**Comment by brandonweiss** [comment]
Everything is green!

**Comment by ohler55** [comment]
Excellent. I am shooting for a release in the next day or two.

**Comment by brandonweiss** [comment]
:tada::tada::tada:
