### ISSUE TITLE
Floats with negative exponents get interpreted as BigDecimal

### ISSUE THREAD

**Issue by ryanbalsdon** [ohler55/oj#276]
You need to use enough digits to stop it from using e notation and then a negative exponent large enough to get past the 15-digit limit and:
```
Oj.load Oj.dump({"test"=>0.000123456789012})
{"test"=>#<BigDecimal:7f361bddf5b0,'0.1234567890 12E-3',18(27)>}
```
If this is the right loop, it looks like it isn't ignoring leading zeros: https://github.com/ohler55/oj/blob/e9d7514a0acd7e6c2b939f80ea19444802cd007e/ext/oj/parse.c#L453

**Comment by ohler55** [comment]
You are correct. Leading zeros should not be counted. I'll get a fix in.

**Comment by ryanbalsdon** [comment]
Thank you!

**Comment by dylanahsmith** [comment]
I tested this with 2.14.0 and got

```
irb> Oj.load Oj.dump({"test"=>0.000123456789012})
=> {"test"=>0.000123456789012}
```

so I think this bug was already fixed.

**Comment by ryanbalsdon** [comment]
:+1: Works in 2.14.0 because Oj is more aggressive about using e notation:
```
Oj.dump({"test"=>0.0000012345})
=> "{\"test\":1.2345e-06}"
```

Also, 2.14.0 clips at one more decimal:
```
Oj.load("{\"test\":0.000123456789012}")
=> {"test"=>0.000123456789012}
Oj.load("{\"test\":0.0000123456789012}")
=> {"test"=>#<BigDecimal:7fe18c8486c0,'0.1234567890 12E-4',18(27)>}
```

Closer but not quite enough to parse our test data:
```
Oj.load("{\"test\":-0.1038534590217073}")
=> {"test"=>#<BigDecimal:7fe18c8516f8,'-0.1038534590 217073E0',18(27)>}
```

**Comment by dylanahsmith** [comment]
`Oj.load(Oj.dump({"test" => -0.1038534590217073}))` doesn't produce a big decimal because it seems to round off the last digit during serialization, so it turns into `{"test"=>-0.103853459021707}` instead.  I think that is acceptable.

**Comment by ohler55** [comment]
In any case there is an issue with leading zeros after the decimal that I will fix. Of course for precise decimal numbers BigDecimal is the way to assure no change from the original.

**Comment by dylanahsmith** [comment]
We found a test case that occurs even with version 2.14.0, the latest commit

```
irb> Oj.load(Oj.dump(-0.0778085304664757))
=> #<BigDecimal:7f4cd6328690,'-0.7780853046 64757E-1',18(27)>
```

**Comment by ohler55** [comment]
candidate releases is on github

**Comment by ohler55** [comment]
Released 2.14.1.

**Comment by ohler55** [comment]
Okay to close?

**Comment by ohler55** [comment]
No response. Problem identified, fixed and unit tested.

**Comment by dylanahsmith** [comment]
Yes, looks good.  Thanks!

**Comment by ryanbalsdon** [comment]
It works beautifully:
```
> Oj.load("-0.0000000000000000000000778085304664757").class
=> Float
```

Thank you!

**Comment by ohler55** [comment]
:+1:
