### ISSUE TITLE
Compiling on alpinelinux ruby-2.2.3p173

### ISSUE THREAD

**Issue by thebeefcake** [ohler55/oj#277]
https://gist.github.com/thebeefcake/0c6f8a0e6d10f9d2aee1

**Comment by ohler55** [comment]
I haven't tried Alpine Linux myself but it looks like you do not have the C libraries and headers installed.

**Comment by thebeefcake** [comment]
Thanks for the heads up Peter I suspected operator error

**Comment by ohler55** [comment]
Let me know how it is going. Alpine Linux looks interesting.

**Comment by thebeefcake** [comment]
All good after adding clib, Thanks for the hint

**Comment by ohler55** [comment]
Cool, closing the issue then.
