### ISSUE TITLE
2.7.1 - undefined method 'to_json'

### ISSUE THREAD

**Issue by jgrosso** [ohler55/oj#278]
U

**Comment by ohler55** [comment]
No worries.

**Comment by jgrosso** [comment]
Turns out, I had created a file in lib/ called json.rb and autoloaded the whole directory, so that `require 'json'` inside `~/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/core_ext/object/json.rb` was getting clobbered.

**Comment by ohler55** [comment]
Sneaky. Glad you got it figured out.

**Comment by jgrosso** [comment]
Thanks... needless to say, Rails stacktraces aren't always the nicest.

Thank you,
Blessings,

Joshua Grosso
