### ISSUE TITLE
Encoding conversions are not properly handled

### ISSUE THREAD

**Issue by Blargel** [ohler55/oj#279]
I have a case where the json I'm consuming is encoded in a different way from the way Oj is expecting. Oj appears to be changing the encoding without changing the actual byte sequence to match the new encoding.

```
2.2.2 :001 > require 'oj'
 => true 
2.2.2 :002 > json = '{"foo":"è"}'.encode(Encoding::ISO8859_1)
 => "{\"foo\":\"\xE8\"}" 
2.2.2 :003 > data = Oj.load json
 => {"foo"=>"\xE8"} 
2.2.2 :004 > data['foo']
 => "\xE8" 
2.2.2 :005 > data['foo'].encoding
 => #<Encoding:UTF-8> 
```

I believe the correct behavior would be to either preserve the inputted byte sequence *and* encoding or to change the encoding while also actually re-encoding the string.

**Comment by ohler55** [comment]
To be pedantic, according to the RFC 7159 KSON strings must be either UTF-8, UTF-16, or UTF-32. Oj supports UTF-8. I can also see how it would be nice to automatically fix an invalid put if possible. I that regard, I can update Oj to attempt to convert a non-UTF-8 string into UTF-8 before parsing (Oj.load). You should still expect that parsed strings to be UTF-8 though.

Does that sound reasonable to you?

**Comment by Blargel** [comment]
That would actually be exactly what I need. Thanks!

**Comment by Blargel** [comment]
Also, I didn't know about the standards, but that's good to know. I normally to use UTF-8 anyways but the data I'm consuming (and have little control over) is using Latin-1 for some reason. The resulting bug started causing errors further down the stack and threw me for a loop so I thought it'd be a good idea to report it.

**Comment by ohler55** [comment]
I pushed a change that converts input string to UTF-8 if they are not UTF-8 to begin with. Please give it a try. I will release if it works for you.

**Comment by Blargel** [comment]
It's working with the previously failing case I had. Yay!

**Comment by ohler55** [comment]
Great, I will release tomorrow.

**Comment by ohler55** [comment]
Would like to verify and close this issue? If not I will close.

**Comment by Blargel** [comment]
Everything's good. Thanks again.

**Comment by ohler55** [comment]
:+1:
