### ISSUE TITLE
Stack level too deep

### ISSUE THREAD

**Issue by shlima** [ohler55/oj#281]
My puma server stops handling requests after a few minutes with the following exceptions: 

```
2015-12-24 20:36:51] ERROR SystemStackError: stack level too deep
    /Users/alex/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.2/lib/active_support/core_ext/object/json.rb:159
[2015-12-24 20:36:51] ERROR SystemStackError: stack level too deep
    /Users/alex/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.2/lib/active_support/core_ext/object/json.rb:159
[2015-12-24 20:36:51] ERROR SystemStackError: stack level too deep
    /Users/alex/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.2/lib/active_support/core_ext/object/json.rb:159
[2015-12-24 20:36:51] ERROR SystemStackError: stack level too deep
    /Users/alex/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.2/lib/active_support/core_ext/object/json.rb:159
```

All works good after removing `oj_mimic_json` out of the Gemfile.

oj (2.12.14)

**Comment by ohler55** [comment]
It is a constant game of catch up with Active Support. If you can give me a sample or test program I can recreate and work around. The problem centers around Active support expecting the to_json method to be honored yet then it calls the encoder again causing an endless loop. Oj has a check for that but not for all possible variations on that theme.

**Comment by shlima** [comment]
Also I found this situation take a place with rack-mini-profiler enabled

**Comment by ohler55** [comment]
If you can not provide an example, can you objects you are trying to convert yo JSON?

**Comment by edalford11** [comment]
I got this same error and realized that calling to_json on the hash produced a circular reference error. I was accidentally building a hash with a circular reference. User error and fixed by calling deep_dup on the object that I was circular referencing.

**Comment by ohler55** [comment]
There is an option in Oj to check for circular references. set :circular to true and that should catch those. It does add some overhead though. Maybe not much compared to other Ruby calls though.

**Comment by ohler55** [comment]
Good to close?

**Comment by edalford11** [comment]
Yup all good. Turns out this was a user error and not related to OJ.

**Comment by ohler55** [comment]
thanks
