### ISSUE TITLE
Raise JSON::ParserError when Oj::ParseError would be raised for mimic_JSON?

### ISSUE THREAD

**Issue by RST-J** [ohler55/oj#290]
Hello,
I encountered an issue when using Oj as replacement for the default JSON parser via `mimic_JSON` which is that error handlers in other code (e.g. other gems) which assume that they have to handle a `JSON::ParserError` error won't be able to handle the situation as they receive an `Oj::ParseError`.
So my question is: Wouldn't it be reasonable to raise a `JSON::ParserError` when `mimic_JSON` was called instead of Oj's error class? Or, as I don't know about internals, somehow ensure that the raised error is a subclass of `JSON::ParserError` in this situation?

**Comment by ohler55** [comment]
That does make sense. I'll look at it today or tomorrow and see what I can do.

**Comment by ohler55** [comment]
I just checked in a release candidate with the parser error changes. Please give it a try.

**Comment by RST-J** [comment]
@ohler55 I think this works fine. :+1:

**Comment by ohler55** [comment]
Release 2.14.5 completed. Good to close?

**Comment by RST-J** [comment]
Yes. Thanks for the quick reaction.

**Comment by ohler55** [comment]
My pleasure.
