### ISSUE TITLE
JSON::ParserError is not descendant of StandardError after calling mimic_JSON

### ISSUE THREAD

**Issue by RST-J** [ohler55/oj#291]
It seems like my 'everything is fine' response to #290 was a bit too quick, because I only checked for the parse error to be `JSON::ParserError` rather than `Oj::ParseError`. For code explicitly handling `JSON::ParserError` it is actually fine, but for a generic rescue-Clause which handles `StandardError` and children, it is not. Here is a gist to illustrate my observations:
```ruby
require 'json'
require 'oj'

data = '"invalid"'

begin
  JSON.parse(data)
rescue => e
  puts 'Caught a StandardError'
  puts e.class
end

Oj.load(data)
Oj.mimic_JSON
Oj.load(data)

begin
  JSON.parse(data)
rescue => e
  puts 'Caught a StandardError in non-quirks mode'
  puts e.class
rescue Exception => e
  puts 'Caught an Exception in non-quirks mode'
  puts e.class
end

begin
  JSON.parse(data, quirks_mode: true)
rescue => e
  puts 'Caught a StandardError in quirks mode'
  puts e.class
rescue Exception => e
  puts 'Caught an Exception in quirks mode'
  puts e.class
end
```
The output of this is:
```
Caught a StandardError
JSON::ParserError
Caught an Exception in non-quirks mode
JSON::ParserError
```
First observation is that for oj's `load` method everything remains unchanged, but when using `mimic_JSON` there are two changes:
* the default setting for `quirks_mode` is not applied any more (which was at least the case for 2.14.2, don't know whether this change was intentionally - by intuition I'd say it isn't)
* The class hierarchy for `JSON::ParserError` changes, it is not a descendant of `StandardError` any more which makes it fall through all anonymous rescue-clauses

**Comment by ohler55** [comment]
I'll look into the quirks mode issue.

As for the JSON::ParseError, it inherits from Exception. I can change it to StandardError though.

**Comment by RST-J** [comment]
How do you mean, "it inherits from Exception" - the latest patch introducing it made it to inherit from `Exception`?
I'd say it needs to inherit from StandardError to ensure the same behaviour, because the original error from the json module is a descendant of StandardError (respectively what I exactly mean is `error.is_a?(StandardError)` yields true for the json module).

**Comment by ohler55** [comment]
Before the latest patch JSON::ParserError was an alias (pointed to) Oj::ParseError. The latest patch made JSON::ParserError a separate class. I was not aware the real JSON::ParserError inherited from StandardError. I will change that as indicated in my previous comment.

**Comment by RST-J** [comment]
Is it safe to expect `json` to be loaded when `mimic_JSON` can be called successfully or does this work independently of the standard library being loaded?
If it must be loaded, then I'd suggest to let it inherit from [JSON::JSONError](http://docs.ruby-lang.org/en/2.2.0/JSON/ParserError.html) - if this is possible within a native extension - as this is also the parent in the standard library.

**Comment by ohler55** [comment]
The JSON gem will not be loaded. Oj is mimic-ing that gem. I just checked in a version that sets up the class hierarchy as you suggested. Please let me know if it looks reasonable.

**Comment by RST-J** [comment]
Thanks again. I played around with it and think its both fine now, the error class hierarchy and using quirks mode by default. :+1:

**Comment by ohler55** [comment]
Great, I'll make a release today.

**Comment by ohler55** [comment]
released
