### ISSUE TITLE
Comment at start of json string causes parse error

### ISSUE THREAD

**Issue by garjust** [ohler55/oj#292]
Related to https://github.com/ohler55/oj/issues/6

The following raises `Oj::ParseError`:
```
/* comment */
{
  "a": "b"
}
```

Playing around the following is accepted:
```
{
  /* comment */
  "a": "b"
}
```

Given the discussion on supporting comments has already happened, is this expected behavior? Version of OJ is `2.12.14` in `:compat` mode.

**Comment by ohler55** [comment]
If one works they both should. I'll make it consistent. Thanks.

**Comment by ohler55** [comment]
Please checkout the latest push to github. I believe it fixes the problem. I updated the unit test as well.

**Comment by garjust** [comment]
Awesome! Thanks so much for the expedient reply!

**Comment by garjust** [comment]
Confirmed my issue is resolved.
