### ISSUE TITLE
Failure to parse JSON string

### ISSUE THREAD

**Issue by mheffner** [ohler55/oj#293]
I'm seeing intermittent failures to parse what I believe is a valid JSON string. Our tests are parsing many strings of the format:

`{"m":0,"i":0,"u":57,"t":"g","v":248.6}`

But about half the time I run our unit tests, Oj will throw a parse exception on a string like the above. It is able to parse hundreds of strings of the same format and when I copy the string into `irb` and try parsing just the broken one it'll work fine. This is the error I get from the above string:

`Oj::ParseError: Hash/Object not terminated at line 1, column 12 [parse.c:888]`

We are parsing the string using:

`Oj.load(str, :mode => :strict, :bigdecimal_load => :float)`

This is on ruby-1.9.3-p547.

When I revert our parser to Yajl I don't see parse failures.

**Comment by mheffner** [comment]
Forgot to add that we are on oj version 2.14.6.

**Comment by ohler55** [comment]
Any chance you can share the unit test? It is a very simple JSON so I'd like to see what other conditions might contribute to the failure so I can fix it.

**Comment by mheffner** [comment]
@ohler55 Unfortunately I can't share the unit test as it is part of a large internal repo. This is an output of the JSON strings the test was parsing before it hit an exception on the last one `{"m":0,"i":0,"u":338,"t":"g","v":53.900000000000006}`. I did a quick test with just the strings in the gist but was unable to hit the particular condition: https://gist.githubusercontent.com/mheffner/6deb0925057691509fc0/raw/a8984730df0da0c2f77c9a13ebd93a1e6eaf2e9f/bad-json.1

Is there a way I can log debug output in my test to print the internal state of the parser at time of failure? It would seem like something is corrupted when it hits the parse failure.

**Comment by ohler55** [comment]
Would a simple loop that read each line from the gist file and call Oj.load emulate the unit test well enough? Are you using threads?

Having the error message like you gave earlier for the exact line it failed on might help as well.

**Comment by mheffner** [comment]
The error msg on that set had rolled off the screen, here's a another log with the error msg:

https://gist.githubusercontent.com/mheffner/724ed09b69ceb99d6695/raw/e5a8017318d1e6a37718486060a0184c02cc4c2b/test.json
https://gist.githubusercontent.com/mheffner/724ed09b69ceb99d6695/raw/e5a8017318d1e6a37718486060a0184c02cc4c2b/test.log

**Comment by ohler55** [comment]
Thanks. I just ran the first file 1000 times with no errors. That and the error message makes me wonder if the string is being corrupted during the parse attempt but it looks like you printed out the string after the failure so that doesn't seem likely.

If you can try setting the :allow_gc option to false. This is not a long term solution but it might give us some additional info to work with.

**Comment by mheffner** [comment]
@ohler55 Yes, if I set allow_gc=false I don't see the failure and the test passes every time.

`Oj.load(str, :mode => :strict, :bigdecimal_load => :float, :allow_gc => false)`

**Comment by ohler55** [comment]
That gives me something to work with. It seems the string passed to Oj.load is being garbage collected while still in the function. Let me explore some possible solutions. I'll create a branch and do some experimenting if you are willing to run your test to help out.

**Comment by ohler55** [comment]
I have another test for you with the current Oj release. Don't use the allow_gc on this one. Instead do this:

``` ruby
Oj.load(str.encode('utf-8'), :mode => :strict, :bigdecimal_load => :float)
```

**Comment by mheffner** [comment]
Yes, this version works as well:

`Oj.load(str.encode('utf-8'), :mode => :strict, :bigdecimal_load => :float)`

And yes, I'm happy to test some additional patches if needed.

**Comment by ohler55** [comment]
I haven't made any patches yet. I will soon though. What that last tests me is that encoding a string in C is not safe as is so I need to do some additional trickery.

**Comment by ohler55** [comment]
I just push a branch called 'encoding'. Please pull and give it a try. I think it might keep the encoded string from being GCed.

**Comment by mheffner** [comment]
@ohler55 Yep, the *encoding* branch appears to work!

**Comment by mheffner** [comment]
@ohler55 Any idea when the next gem release will be cut so we can update to fixed version?

**Comment by ohler55** [comment]
I'm waiting on feedback from the new nan option. If I don't hear from the fellow by the end of the day I'll just do the release without a response.

**Comment by ohler55** [comment]
released
