### ISSUE TITLE
Create hashes with indifferent access

### ISSUE THREAD

**Issue by thedrow** [ohler55/oj#294]
It be useful to have an option to create hashes with indifferent access like the ones provided by ActiveSupport.
The HashWithIndifferentAccess class allows you to access a hash using either a symbol or a string.
If you don't want to add an option for that specifically maybe it's possible to provide Oj with the hash class to use.

**Comment by ohler55** [comment]
This is along the same lines as a discussion on one of the closed issues. My thoughts were to either provide a faster object/hash or allow the caller to specify a hash creation function. There are tradeoffs for each.

A built in one would be faster but depending on implementation might require a close much like a file. Maybe.

A supply your own would be more flexible but much slower as all the loading calls would be Ruby and not C.

**Comment by thedrow** [comment]
Whatever you pick is fine for this usecase. Right now I'm recursively converting the Hash to a HashWithIndifferentAccess so I'm already much slower than the second option.

**Comment by thedrow** [comment]
Sounds good to me :+1:

**Comment by ohler55** [comment]
Is this still an issue? Memory fails me but I thought we resolved this.

**Comment by thedrow** [comment]
Yes it is.
I don't see a way to tell Oj to create a dictionary with indifferent access.

**Comment by ohler55** [comment]
ok, wasn't sure if you had found a work around.

**Comment by ohler55** [comment]
Please give the latest on github a try. The test_hash.rb file has a trivial example of use.

**Comment by ohler55** [comment]
Are you still interested in this feature?

**Comment by thedrow** [comment]
Yes I am. I haven't had the time to test it yet. I'll give it a shot tomorrow.

**Comment by ohler55** [comment]
The additions are in the latest release. Will close this issue if no response in a few days.
