### ISSUE TITLE
Value converted to symbol.

### ISSUE THREAD

**Issue by rkl74** [ohler55/oj#297]
Problem: Value gets converted to a symbol if the value starts with a colon.
Ex: 
require 'oj'
s = %Q({"key":": value"})
data = Oj.load(s)

returns:
=> {"key"=>:" value"}

**Comment by ohler55** [comment]
This has been mention in a previous issue. Checkout the Readme. Oj has different modes. The default is a marshaling mode that generates JSON that can be used to reconstitute and object. If you want a different mode then either set the default options or use Oj.load(s, mode: :strict).
