### ISSUE TITLE
Parsing the Unicode "invalid character" raises a `Oj::ParseError`

### ISSUE THREAD

**Issue by filterfish** [ohler55/oj#300]
The following snippet will cause `Oj::ParseError` to be raised.

```ruby
Oj.load('{"key": "Fashion inspo!Special edition\ud83d"}')
```

The Unicode character ["\ud83d"](http://www.charbase.com/d83d-unicode-invalid-character) is the invalid character (oh the irony!).

```ruby
Yajl.load('{"key": "Fashion inspo!Special edition\ud83d"}')
```

doesn't raise a parse error.

**Comment by ohler55** [comment]
As the reference you gave indicates the \ud83d is no a valid unicode character. I have to assume yagl does not raise an exception only because it does not check or replaces invalid unicode with some default character. So the question really is are you asking for a feature that replaces invalid unicode with some special character or did you have something else in mind?

**Comment by ohler55** [comment]
Any comments?

**Comment by filterfish** [comment]
Sorry, I didn't see your comment. 

\ud83d is a valid Unicode character. It *represents* an invalid character. We are consuming an external feed and, I assume, the original data had an invalid Unicode character so it was replaced by: � (\ud83d).

So technically it is valid Unicode but it represents a bad character.

**Comment by ohler55** [comment]
Took me a while to get back here. \ud83d by itself is no valid though it is used as the first part of a surrogate pair for things such as smiley faces. The use of it as a replacement for other invalid unicode characters is not uncommon but not correct. After some thought I think the best option for Oj would be to have an option to not complain about invalid UTF-8 Unicode sequences and to just leave them as they are and let Ruby deal with them as it sees fit.

**Comment by filterfish** [comment]
Ok.

> …though it is used as the first part of a surrogate pair for things such as smiley faces

That actually makes sense in the context of what I saw.

**Comment by ohler55** [comment]
Please give the current candidate on github a try.

**Comment by ohler55** [comment]
Okay to close this?

**Comment by ohler55** [comment]
No response, closing.

**Comment by filterfish** [comment]
@ohler55 that works a treat.  Thanks for sorting that out.

**Comment by ohler55** [comment]
Great!
