### ISSUE TITLE
ActiveSupport 5 breaks DateTime dumping.

### ISSUE THREAD

**Issue by nomoon** [ohler55/oj#306]
I'm trying to figure out how, but it appears that Rails 5/ActiveSupport 5 causes DateTime dumping to hang forever. It works fine in base Ruby 2.3, but once `require 'oj/active_support_helper'` is called (which itself requires `active_support/time`) then everything stops working.

**Comment by nomoon** [comment]
Both Oj.dump(Date.new) and Oj.dump(Time.new) appear to be unaffected.

**Comment by nomoon** [comment]
If I run something like `Oj.register_odd(DateTime, DateTime, :parse, :inspect)` it seems to work.

**Comment by ohler55** [comment]
I'll see what they did this time. For some reason active support like to call to_json when in to_json and cause an infinite recursion. Maybe they did the same this time for date and time.

**Comment by ohler55** [comment]
I've been trying to reproduce this without success. Can you give me a short test that demonstrates the hang?

**Comment by nomoon** [comment]
I'm running Ruby 2.3.1p112 on OSX via rvm. This test-case works for me:

```
require "active_support" # v5.0.0
require "oj" #v2.17.1


puts "ActiveSupport + OJ. dump(DateTime.new)"
puts
puts Oj.dump(DateTime.new)
puts

require "oj/active_support_helper"

puts "ActiveSupport + OJ + active_support_helper dump(DateTime.new)"
puts
puts Oj.dump(DateTime.new)
puts
```

**Comment by ohler55** [comment]
I am looking at it now. It looks like this is enough to trigger the hang.
```ruby
require 'active_support/time'
```

**Comment by ohler55** [comment]
Odd indeed. Once activesupport/time is required DateTime methods of 'hour', 'min', and 'sec' are no longer valid methods when called from C. They still seems to exist when called from irb or ruby. The lack of those method is consistent with the activesupport documentation for DateTime. Its like the methods have been remove in some manner for the C extensions.

**Comment by ohler55** [comment]
I put a candidate release on github. The oj/active_support_helper.rb file was changed. It is kind of a hack. I'm working on submitting a bug report to the ruby team as I think it is something in Ruby itself that is the core problem.

**Comment by nomoon** [comment]
Cheers!

**Comment by ohler55** [comment]
The problem was worked around for Oj. A bug report was submitted to the Ruby bug tracker at https://bugs.ruby-lang.org/issues/12649.
