### ISSUE TITLE
Omit keys with nil values

### ISSUE THREAD

**Issue by ebenoist** [ohler55/oj#307]
Is it currently possible with Oj to omit keys with nil values while marshalling to JSON?

ie. 
```Ruby
Oj.dump({ foo: nil, bar: 'baz' })
=> '{ "bar": "baz" }'
```

If not would such an implementation be welcome and could you point me to where in the marshal library it would be most appropriate to add such an option?

**Comment by ohler55** [comment]
There is not currently an option to omit nils. Before attempting to add that option there are a few places that would need to be modified. The first being the code that handles the options. If an omit_nil option were to be added the oj.h and oj.c would need to be updated. The unit tests would also have to be updated. Finally the dump.c file would have to skip object members that had nil values.

There are 4 different modes to handle. The most difficult part will be looking ahead to see if any non-nil values are present to determine the last entry as it must not have a trailing comma. That look ahead must not impact the current performance so it may be that an omit_nil option follows a different code path earlier on.

**Comment by ebenoist** [comment]
Thank you for the quick and detailed reply! I'll see if I can whip something up.

**Comment by ohler55** [comment]
If not I can put it on my to-do list. The list gets processed fairly quickly.

**Comment by ebenoist** [comment]
Well, between you and I, while it would be fun to dive into the C extension here, it would be waters I haven't waded for many many years. I'm happy to give it a try, but if you have bandwidth for it, I'd love to see what that implementation looks like.

**Comment by ohler55** [comment]
I'll get something together over the next day or two.

**Comment by ohler55** [comment]
I just pushed a branch named "floats" with the omit_nil option for dump. There is a unit test for it as well. Please give it a try.

**Comment by ebenoist** [comment]
This is incredible, I'll check it out! So many cheers! Twitter dm @erikbenoist on twitter there are some folks @reverbdotcom that would like to say thank you.

**Comment by ohler55** [comment]
Glad to help.

**Comment by ebenoist** [comment]
The code that hit master works great for my use case. Thank you so much for putting the time in to help me out. Don't hesitate to reach out on twitter, we've got lots of thanks to go around. And if you're ever in Chicago, beer is on me.

I'll close this issue as its now been completely resolved.

**Comment by ohler55** [comment]
Glad I could help.
