### ISSUE TITLE
Invalid value for BigDecimal Infinity (v 2.17.1)

### ISSUE THREAD

**Issue by wojciecheu** [ohler55/oj#309]
When i was trying to generate json on RoR application (using jbuilder), in which there was Infinity value of BigDecimal on one of objects, I found strange error - returns bare Infinity value instead of NaN or null. Thats why webrowser throws json parse error.

**Comment by ohler55** [comment]
You mentioned jbuilder and a browser. Where does Oj fit in that arrangement?

**Comment by wojciecheu** [comment]
Just replaced Multijson as json generator with faster oj. Webbrowser is unable to parse json response because of Infinity value on json object attribute ( invalid value ).

**Comment by ohler55** [comment]
Can you tell me what mode Oj is using for parsing? Oj.default_options[:mode].

Anything except :strict should handle "Infinity".

**Comment by wojciecheu** [comment]
* JSON instead of Multijson , maybe its multijson's edgecase bug like this https://github.com/intridea/multi_json/issues/163
Value of Oj.default_options[:nan] = :auto and Oj.default_options[:mode] = :object
It seems that the best way is to avoid Infinity values on result being passed into json response.

**Comment by ohler55** [comment]
I would have expected a values of
Oj.default_options[:nan] = :word
Oj.default_options[:mode] = :compat
for MultiJson. I can check MultiJson but in the mean time, try setting those values yourself and see if that helps. Set them like this:
```ruby
Oj.default_options = { :mode => :compat, :nan => :word }
```

**Comment by ohler55** [comment]
Did those setting work for you?

**Comment by wojciecheu** [comment]
I've tried this without success.

**Comment by ohler55** [comment]
It is still not clear to me if you are loading or dumping JSON. Since values did not work for you I will assume that you are dumping JSON and no loading. In that case set the options like this:
```ruby
Oj.default_options = { :nan => :null }
```
That should place a null in the JSON when dumped.

**Comment by ohler55** [comment]
Is this a dead issue?

**Comment by navied** [comment]
Not sure if this is a similar issue but I am having an issue where BigDecimal NaN are turning into NaN and are not adhering to the :nan => :null option. This specifically is happening when using the json.extract! option in jbuilder.

**Comment by ohler55** [comment]
Great.
