### ISSUE TITLE
BigDecimal loading broken in ActiveRecord 5

### ISSUE THREAD

**Issue by mlarraz** [ohler55/oj#310]
I have a table with a JSON column, but sometimes the value is just a decimal literal (which is still valid JSON).

I have the following option enabled:
```ruby
Oj.default_options = { bigdecimal_load: :bigdecimal }
```
so the values are stored as JSON, but read and written as BigDecimals.

In Rails 5, this is no longer the case, and now the decimals are coerced to strings as before, so the option doesn't really do anything.

I belive this change started the issue:
https://github.com/rails/rails/commit/efaa6e4f79d457c2cdd08cbc56d63bc972a6993c#diff-d1683eeee99d07019a6dd8d9ca8aa50e

**Comment by ohler55** [comment]
A couple things to check first.

1. Are you sure Oj is being used?
2. Is the JSON the same or is the serialized form different than before?

**Comment by mlarraz** [comment]
1. Not 100% sure, but commenting out the options hash above reliably causes the same failure on Rails 4. 
2. The input hasn't changed, it's part of a unit test that passes on Rails 4 but not Rails 5.

**Comment by ohler55** [comment]
1. Are you referring to the Oj.default_options or something else?

If you have a sample JSON that is failing that would help. I can make sure Oj is doing what is expected. If it is the next step is figuring our what Rails is doing.

**Comment by mlarraz** [comment]
Yes, I meant `Oj.default_options`.

The test is essentially:
```ruby
model.value = BigDecimal.new('1.0')
expect(model.value).to be_a BigDecimal
```
where `value` is a JSON column.

On Rails 4.2, this fails by default. With OJ and the above `default_options` set, it passes.
On Rails 5, it always fails.

**Comment by ohler55** [comment]
It seems unlikely the change was due to the issue you mentioned as it only changes the encoding and not the decoding unless the stored JSON is different but you indicated it was the same. I verified that the Oj option does work as you did by testing with Rails 4.2. It appears as if something in Rails 5 that is modifying the returned value.

Another possibility is that the Oj options are being reset. After the test are the Oj options the same as what you set them to?

If they are the next step is to trace through the rails code and see where the change is taking place. Are you able to get into the code and place some print statements in it for debugging? You might know your way around the Rails code better than I do.

**Comment by mlarraz** [comment]
So I made some progress on this issue.

Essentially, `ActiveSupport::JSON.encode` calls `as_json` on objects before passing them to `JSON.generate`. ActiveSupport defines `BigDecimal#as_json` to return a String, which is what actually gets serialized, and any Oj settings for decimals are totally bypassed.

This is true even in Rails 4. The only reason my tests pass on Rails 4 is because (as linked in the first post) serialization for JSON columns is defined as:

```ruby
def serialize(value)
  if value.is_a?(::Array) || value.is_a?(::Hash)
    ::ActiveSupport::JSON.encode(value)
  else
    value
  end
end
````
which completely skips the serialization and writes the raw decimal value to the db (which can then be correctly deserialized as a BigDecimal). In Rails 5 this is no longer the case, and everything goes through `as_json`.

The only solution I've come up with is monkey-patching `BigDecimal#as_json` to return `self`. This fixes my tests, but is obviously less than ideal.

The following snippet highlights the issue (and my hacky resolution):

```ruby
require 'oj'

Oj.default_options = {
  bigdecimal_load:       :bigdecimal,
  bigdecimal_as_decimal: true
}

Oj.mimic_JSON

d = BigDecimal.new('1.0')

puts "Without ActiveSupport:"

# All return "0.1E1"
puts JSON.dump(d).inspect
puts Oj.dump(d).inspect
puts d.to_json.inspect

require 'active_support/json'

puts
puts "With ActiveSupport:"

# All return "\"1.0\""
puts JSON.dump(d).inspect
puts Oj.dump(d).inspect
puts d.to_json.inspect

class BigDecimal
  def as_json(*)
    self
  end
end

puts
puts "With ActiveSupport + monkey patch:"

# All return "1.0"
puts JSON.dump(d).inspect
puts Oj.dump(d).inspect
puts d.to_json.inspect
```

**Comment by ohler55** [comment]
So it was in the encoding and not decoding. From your detective work it doesn't look like there is anything Oj can do about it. The conversion occurs before calling Oj as you noted. I'm not sure why Active Support tries so hard to break previous versions. Glad you found a work around.

**Comment by ohler55** [comment]
Any reason not to close this?
