### ISSUE TITLE
"NoMethodError: undefined method `json_create' for Regexp:Class" trying to deserialize json regex (conflict with Pact gem).

### ISSUE THREAD

**Issue by galori** [ohler55/oj#311]
We're using the Pact gem as more and more teams are for testing micro-services: https://github.com/realestate-com-au/pact

I get this error if Pact is loaded after oj but not if Pact is loaded before oj:

*** Loading Pact before oj ***
```
|ruby-2.3.1@test_oj| Gals-MacBook-Pro-2 in ~/workspace/test_oj
○ → irb
2.3.1 :001 > require 'json'
 => true
2.3.1 :002 > require 'pact'
 => true
2.3.1 :003 > require 'oj'
 => true
2.3.1 :004 > require 'oj_mimic_json'
 => true
2.3.1 :005 > /1/.to_json
 => "{\"json_class\":\"Regexp\",\"o\":0,\"s\":\"1\"}"
2.3.1 :006 > JSON.load(/1/.to_json)
 => /1/
2.3.1 :007 > exit
```

**Loading oj before pact***

```
|ruby-2.3.1@test_oj| Gals-MacBook-Pro-2 in ~/workspace/test_oj
○ → irb
2.3.1 :001 > require 'json'
 => true
2.3.1 :002 > require 'oj'
 => true
2.3.1 :004 > require 'oj_mimic_json'
 => true
2.3.1 :005 > require 'pact'
 => true
2.3.1 :006 > /1/.to_json
 => "{}"
2.3.1 :007 > JSON.load(/1/.to_json)
 => {}
2.3.1 :008 > JSON.load("{\"json_class\":\"Regexp\",\"o\":0,\"s\":\"1\"}")
NoMethodError: undefined method `json_create' for Regexp:Class
Did you mean?  json_creatable?
	from (irb):8:in `load'
	from (irb):8
	from /Users/gal/.rvm/rubies/ruby-2.3.1/bin/irb:11:in `<main>'
2.3.1 :009 >
```

^^^ This is the error I'm getting in my Pact Test suites currently, if I use a regex matcher.

Pact does some overriding of Regexp json serializer, and it does seem to fix a real problem:

https://github.com/bethesque/pact-support/blob/master/lib/pact/shared/active_support_support.rb#L23

**Active Support without Pact**

```
○ → irb
2.3.1 :001 > require 'rails/all'
 => true
2.3.1 :002 > /1/.to_json
 => "\"(?-mix:1)\""
2.3.1 :003 > JSON.load(/1/.to_json)
 => "(?-mix:1)"
```

(it deserializes the regex into a weird string).  Note that plain ruby, with just `require 'json'` behaves the same way as `require 'rails/all'`. So maybe thats the correct or at least "standard" behavior but it doesn't seem like a good one:

**ruby with json**

```
|ruby-2.3.1@test_oj| Gals-MacBook-Pro-2 in ~/workspace/test_oj
○ → irb
2.3.1 :001 > require 'json'
 => true
2.3.1 :002 > require 'multi_json'
 => true
2.3.1 :003 > /1/.to_json
 => "\"(?-mix:1)\""
2.3.1 :004 > JSON.load(/1/.to_json)
 => "(?-mix:1)"
```

**Active Support With Pact**

```
○ → irb
2.3.1 :001 > irb
2.3.1 :001 > ^C
2.3.1 :001 > require 'rails/all'
 => true
2.3.1 :002 > require 'pact'
 => true
2.3.1 :003 > /1/.to_json
 => "{\"json_class\":\"Regexp\",\"o\":0,\"s\":\"1\"}"
2.3.1 :004 > JSON.load(/1/.to_json)
 => /1/
```

Works right! I guess Pact's patch is necessary.  

At this point I'm not even sure what is the expected correct behavior.   

This is the actual line in Pact that throws the error:

https://github.com/bethesque/pact-mock_service/blob/aadbb8dd5fb9f91ed0d5b1c7ed07006d1282350e/lib/pact/mock_service/request_handlers/interaction_post.rb#L24

(the `JSON.load`).

Finally, I realize you might tell me that this is a problem with Pact and that they shouldn't patch the way they're patching, and if thats the case, thats fine. But I wanted to check in here to at least find out what is the expected behavior, and to see if you have any suggestions. (or at the very least some thoughts on the correct way to handle in the ideal case both in `oj` and in `pact`)

**Comment by ohler55** [comment]
The json_class is used to decode an object from a hash in the JSON gem world. It can be changed but json_class is the default. What is expected on load is that the value for the json_class is used to create an instance and then the other key value pairs are used to set attributes on that object. From the error you are getting it looks like the process is also using the json_class key value pair as an attribute. The question is where and then how to fix it or work around it.

By the way, when using Oj and mimic_JSON there is no need to require the JSON gem.

Do you know where the Interaction class is defined?

**Comment by ohler55** [comment]
Let me clarify a bit since my previous description was a light on details.

When adding the to_json method to the Regex class a json_create method should also be defined. The json_create class method should take a single argument that is the hash created from the JSON document.

The problem is that the spec for the json_create method is not well documented. It does not mention wether the hash json_class field should be stripped or not. Most implementors look for specific key value pairs in the hash and ignore the rest. Apparently the json_create method used by Pact does not expect any other key value pairs in the hash other than the attributes. I am not aware of what impact there may be on other implementation if the json_class key is removed but yet another option in Oj could be set to strip that field if necessary. If you can find the location of the Pact json_create method maybe we can see how to fix it on that end.

**Comment by galori** [comment]
Thanks for the detailed & quick response.

> Do you know where the Interaction class is defined? 

https://github.com/bethesque/pact-support/blob/master/lib/pact/consumer_contract/interaction.rb

However, note that it never gets that far. The exception is raised from the JSON.load() part and it never gets to Interaction.from_hash on the line in question. I included a link to a quick debug session below to show this.

> Are you able to do some tracing or put in a print statement near the json_create methods in Active Support?

Definitely. I spent some time stepping via debugger through the internals of active-support and pact to get to the information I provided here.

However - do you mean the `json_create` method that is supposed to be added on to Regexp for it to be able to instantiate a json object from a hash?  I think that is the problem - it does not exist in the error case:

```
|ruby-2.3.1@test_oj| Gals-MacBook-Pro-2 in ~/workspace/test_oj
○ → irb
2.3.1 :001 > require 'json'
 => true
2.3.1 :002 > require 'oj'
 => true
2.3.1 :003 > Oj.mimic_JSON()
 => JSON
2.3.1 :004 > require 'pact'
 => true
2.3.1 :005 > Regexp.json_create
NoMethodError: undefined method `json_create' for Regexp:Class
Did you mean?  json_creatable?
       	from (irb):5
       	from /Users/gal/.rvm/rubies/ruby-2.3.1/bin/irb:11:in `<main>'
2.3.1 :006 >
```

If I reverse the order:

```
|ruby-2.3.1@test_oj| Gals-MacBook-Pro-2 in ~/workspace/test_oj
○ → irb
2.3.1 :001 > require 'json'
 => true
2.3.1 :002 > require 'pact'
 => true
2.3.1 :003 > require 'oj'
 => true
2.3.1 :004 > Oj.mimic_JSON
 => JSON
2.3.1 :006 > Regexp.json_create
ArgumentError: wrong number of arguments (given 0, expected 1)
       	from /Users/gal/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/json/add/regexp.rb:12:in `json_create'
       	from (irb):6
       	from /Users/gal/.rvm/rubies/ruby-2.3.1/bin/irb:11:in `<main>'
```

And that is the exact error I'm getting in the test suite.

Here is a quick debug session, setting a break point in the code running within the test suite:

https://gist.github.com/galori/4e8d8c44b88c5b868844d2399450069b

FWIW I opened the same issue in the Pact issues list https://github.com/realestate-com-au/pact/issues/110 

So - we were able to get past our immediate problem by moving `pact` before `oj` in Gemfile.  Of course its not ideal because there is an implied order where there shouldn't be one - for now we're solving that just by a big comment in the Gemfile.

I think it would be good to figure out what the correct thing to do is...Pact does admit in its code that its patch to Active Record is not ideal and they even asked for PR's with better ideas:

https://github.com/bethesque/pact-support/blob/master/lib/pact/shared/active_support_support.rb#L23

Which I would be happy to try to do...if I knew what the correct thing to do is. However, as demonstrated in the original post above - without this patch Regex's don't ever serialize or deserialize correctly with JSON. (I'm assuming they're supposed to be able to).

**Comment by galori** [comment]
Follow up:

Here is a debug session showing the line in question and demonstrating the error:

https://gist.github.com/galori/4e8d8c44b88c5b868844d2399450069b

ALSO FYI the `Oj` maintainer has responded with a few ideas and questions on the `Oj` project issue tracker: https://github.com/realestate-com-au/pact/issues/110 - with some questions about Pact related to this.

**Comment by galori** [comment]
Just to restate, this is my understanding of whats happening:

1. Pact overrides `regexp.as_json` to create a more useful serialization that actually works
2. Pact has a hash with a regexp as one of its keys
3. Pact serializes it into JSON using JSON.parse. 
4. This calls into `oj`, and `oj` calls `regexp.as_json` method to get the JSON representation
4. Later, Pact tries to deserialize this same json string using `JSON.load`, which goes to `oj`
5. In turn, `oj` sees the `json_class` and infers that this is a Regexp object. 
6. `oj` tries to to call `regexp.json_create` which doesn't exist. (depending on the gem require order)

Does that sound right?

**Comment by ohler55** [comment]
To clear some items off your list, steps 1 thru 4 are working as expected. There is no default JSON serialization of any but the core classes that map directly to JSON equivalents. Steps 5 and 6 are also as expected. Step 7 is where the trouble lies. Sadly, an approach taken by Active Support is to monkey patch base classes by adding things such as as_json as well as a bunch of other stuff. Serving as a model for others such as Pact the same approach is taken. Now there is a conflict depending on what module is loaded last. I'm not sure why the order of Oj makes a difference though.

Here are some things to try.

1. Do not require json. Just oj and then call mimic_JSON. See what happens with that approach.
2. Monkey patch Regexp with your own json_create and see if it gets called. Check the arguments it gets called with.

**Comment by bethesque** [comment]
Hey guys, trying to work through this problem. There's something going on here, but I don't think it's caused by the monkey patch of `as_json`. Here is the code snippet.

```ruby
    # ActiveSupport JSON overwrites (i.e. TRAMPLES) the json methods of the Regexp class directly
    # (beneath its destructive hooves of destruction).
    # This does not seem to be able to be undone without affecting the JSON serialisation in the
    # calling project, so the best way I've found to fix this issue is to reattach the
    # original as_json to the Regexp instances in the ConsumerContract before we write them to the
    # pact file. If anyone can find a better way, please submit a pull request ASAP!
    def fix_regexp regexp
      def regexp.as_json options = {}
        {:json_class => 'Regexp', "o" => self.options, "s" => self.source }
      end
      regexp
    end

```
Firstly, the code fixes the `as_json` method on specific *objects* (not the class, because that would be all sorts of rude *stares meaningfully at ActiveSupport*) in order to serialise them *to json* properly. It's not about loading from JSON to a class, which is where the problem seems to be.

I haven't worked out why the `json_create` method doesn't exist when the gems are loaded in a certain order. What would be useful would be to do some debugging after each gem require and see when the method appears/disappears in each scenario. Can you do this @ohler55?

**Comment by ohler55** [comment]
I think we all agree it is not the as_json method. That is fine. It is the loading that is the issue. I was hoping for a response from the early question but I will try to recreate the issue independently.

**Comment by ohler55** [comment]
I ran a few tests. I never saw json_create defined no matter what order I can the tests in. I suspect there were some steps before running the indicated lines. Probably loading rails which fails for me right now as nokogiri expects some different version of libxml.

Anyway a standalone test as shown works but it is obviously not the same as what you are experiencing.
```ruby
require 'oj'
Oj.mimic_JSON()
require 'pact'

class Regexp
  def as_json(options = {})
    {:json_class => 'Regexp', "o" => self.options, "s" => self.source }
  end
  def self.json_create(h)
    Regexp.new(h['s'], h['o'])
  end
end
j = /1/.to_json
puts "json: #{j}"
puts "regexp: #{JSON.load(j)}"
```

It works the same no matter what order the require pact vs oj. I did notice that the lines after the require 'pact' are called twice so something odd is happening there.

That leaves us needing a full standalone test that demonstrates the problem without defining the as_json and json_create method. Can either of you provide that?

**Comment by bethesque** [comment]
Sorry, I'm a bit stretched today - which early question?

**Comment by bethesque** [comment]
Sorry, I meant to ask @galori to do the debugging of when the json_create is defined, as it's his code that has surfaced the issue. Trying to juggle gem support and 6 month old twins at the moment.

```ruby

$ pry
[1] pry(main)> require 'json'
=> true
[2] pry(main)> Regexp.respond_to?(:json_create)
=> false
[3] pry(main)> require 'pact'
=> true
[4] pry(main)> Regexp.respond_to?(:json_create)
=> true

$ Regexp

From: /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/json/add/regexp.rb @ line 7:
Class name: Regexp
Number of monkeypatches: 2. Use the `-a` option to display all available monkeypatches
Number of lines: 25

class Regexp

  # Deserializes JSON string by constructing new Regexp object with source
  # <tt>s</tt> (Regexp or String) and options <tt>o</tt> serialized by
  # <tt>to_json</tt>
  def self.json_create(object)
    new(object['s'], object['o'])
  end

  # Returns a hash, that will be turned into a JSON object and represent this
  # object.
  def as_json(*)
    {
      JSON.create_id => self.class.name,
      'o'            => options,
      's'            => source,
    }
  end

  # Stores class name (Regexp) with options <tt>o</tt> and source <tt>s</tt>
  # (Regexp or String) as JSON string
  def to_json(*)
    as_json.to_json
  end
end
```

So it looks like something in pact requires 'json/add/regexp.rb', but it is not loaded by json by default.

**Comment by bethesque** [comment]
Ok, lib/pact/consumer/consumer_contract_builder.rb:2

```ruby
require 'json/add/regexp'
```

**Comment by bethesque** [comment]
Is there something in oj that matches the path 'json/add/regexp'? Is it being loaded in preference to the default json one?

**Comment by ohler55** [comment]
Oj does not have a similar path.

**Comment by ohler55** [comment]
I wonder why I get different results with pact. Are you using the version in ruby gems or something different?

**Comment by ohler55** [comment]
Maybe you can explain why when I run the example I listed earlier it executes twice. In the first pass pact has not added the as_json method. In the second pass it has.

**Comment by ohler55** [comment]
Looks like I should monkey path the following to mimic JSON completely.
Range
Rational
Regexp
Struct
Symbol
Time

**Comment by ohler55** [comment]
I updated Oj on github so that mimic_JSON monkey patches the core classes like the JSON gem. Please give it a try and see if it fixes the problems.

**Comment by galori** [comment]
> Sorry, I meant to ask @galori to do the debugging of when the json_create is defined, as it's his code that has surfaced the issue. 

Gladly - but how? Like your example code using Pry to display information about the method or did you mean something else?

> I updated Oj on github so that mimic_JSON monkey patches the core classes like the JSON gem. Please give it a try and see if it fixes the problems.

Will do tomorrow.

> That leaves us needing a full standalone test that demonstrates the problem without defining the as_json and json_create method. Can either of you provide that?

I'll do that if it still doesn't work after your changes

> I wonder why I get different results with pact. Are you using the version in ruby gems or something different?

Latest versions of everything from rubygems. Using bundler and a brand new Gemfile for the tests.

**Comment by galori** [comment]
The new version works! Thank you!

Before upgrading I did all the tests described above out of curiosity, I'll post a cleaned up gist of all of that later today when I get another few minutes.

But once I used the new version of `oj` from master, the same pattern that didn't work before worked just fine:

```ruby
○ → bundle exec irb
> require 'json'
 => true
> require 'oj'
 => true
> Oj.mimic_JSON()
 => JSON
> require 'pact'
 => true
> /1/.to_json
 => "{\"json_class\":\"Regexp\",\"o\":0,\"s\":\"1\"}"
> JSON.load("{\"json_class\":\"Regexp\",\"o\":0,\"s\":\"1\"}")
 => /1/
```

Thanks for the quick turnaround!

**Comment by ohler55** [comment]
Great, I'll release later tonight.

**Comment by bethesque** [comment]
👍  Thanks for the quick turnaround!

**Comment by ohler55** [comment]
Well, not making the release today. Unit tests fail for good reason. Both the JSON gem and Active Support monkey patch Time and others but with different methods that are not compatible. I might update tests but then document is bold that rails has to be required after if you want the rails patches and not the JSON ones. What a mess.

**Comment by ohler55** [comment]
If you don't mind trying the latest changes that would be great.

**Comment by ohler55** [comment]
Updated tests and released.

**Comment by galori** [comment]
I saw the new gem version come in, thank you.

> If you don't mind trying the latest changes that would be great.

I just `bundle update oj`'d the project that was having the issue, and moved the `oj_mimic_json` line back where it was in the Gemfile, and now everything works great.

Thank you again!!

Going to close this issue unless you wanted any other info (hadn't had time to look into the pre-change tests, but I think they are irrelevant now? unless you are still curious).

**Comment by ohler55** [comment]
Thanks. I think I understand what was going on to some extent. It boils down to the JSON gem monkey patching as_json and Rails doing the same thing. I changed Oj to take the approach that if it sees an existing as_json it leaves it alone. Basically it backs away from the conflict.

**Comment by galori** [comment]
Ok here are some tests on my end with the previous version of the `oj` gem (not the new one you just released).

Note: This is just as an FYI to learn more about the problem. As I commented earlier, the new version of the gem fixed the problem.

https://gist.github.com/galori/8d0e43b3b43c469914b075b42faf1187

This gist contains the following 4 scenarios:

1. No `require 'json'`, `oj` before `pact`
2. No `require 'json'`, `oj` after `pact`
3. With `require 'json'`, `oj` before `pact`
4. With `require 'json'`, `oj` after `pact`

Let me know if there are any other tests you would like me to try!

Thanks.

**Comment by ohler55** [comment]
Please treat it as an FYI. I don't want you to extra work if you are busy.

**Comment by galori** [comment]
> Please treat it as an FYI. I don't want you to extra work if you are busy.

Thank you! I found the time and thats what I posted earlier.  LMK if there is anything else.

...its the least I can do for how great & responsive you've been.
