### ISSUE TITLE
Difference in the way JSON and OJ parse NaNs

### ISSUE THREAD

**Issue by StuartHadfield** [ohler55/oj#312]
I noticed that when switching from JSON to OJ - all my unit tests started to fail (which are testing massively nested hashes for equivalence).  The reason is I was comparing, somewhere in these hashes, `NaN` values, and comparisons between these values passed when using JSON, but failed with OJ.  I investigated.

JSON does this:
`CNaN = rb_const_get(mJSON, rb_intern("NaN"));`

OJ does this:
```
if (ni->nan) {
  rnum = rb_float_new(0.0/0.0);
}
```

So Ruby compares the same object to itself and results in a true in unit tests (which I actually don't think is right, because `NaN != NaN`), whereas Oj creates a new object each time for a NaN, therefore the unit tests fail. perhaps in the spirit of compatibility Oj should do the same, rather than create a new object with each 'parse'?

I am happy to do the PR to change this - I just thought perhaps I should open an issue first to give some context and hear opposing views.
Thanks!
Stuart

**Comment by ohler55** [comment]
I'd have to agree that the comparing that the objects are the same and not that the values are the same is different than the definition of the == for the Float class. In IRB NaN is alway != NaN even if they are the same object.

Before I make changes can you do a simple check. See what class the returned NaN is. Is it a Symbol or a Float. If it is a Symbol and not a Float that would certainly be a problem.

**Comment by StuartHadfield** [comment]
Hi @ohler55, 
Thanks for a speedy response.  Yes, that's the debate I've been having with myself.  It's a curious case - when I parse `{:foo => Float::NAN}` with JSON and compare it for equivalence with another hash parsed by JSON, `{:foo => Float::NAN}` it returns true.  I've been struggling with this concept.

The NaN returned is indeed a float.

This is why I wanted to open the discussion up - I can't decide whether compatibility or _correctness_ takes precedence.  The more I look at it, the more I think ruby's default JSON parser is wrong.

**Comment by ohler55** [comment]
Of course NaN is not valid JSON anyway so I guess they can do what ever the want. What is odd is that 
```ruby
X = 0.0/0.0
X == X
```
Will return false so there is something special about the JSON gem return value. I'll experiment when I get home later.

**Comment by ohler55** [comment]
With a little experimenting, Float::NAN is never equal to itself. Hash comparisons are different though. Apparently the Hash comparison has an optimization to check object identify so it never calls the NaN comparison.

Honestly, if your test rely on not the value of a returned element but having the objects be the same it seems like the test is not correct unless of course your do expect all object with the same value to be the same object. You are kind of tricking Ruby by using the Hash comparison instead of instead of comparing values. Understandably but still a trick to get around Ruby thinking that the Float::NAN value is not equal to it's own value.

It would be possible to modify Oj to use Float::NAN but it is kind of a special case for Hash comparison.

**Comment by StuartHadfield** [comment]
Yeah - that's rather what I thought was happening with hash comparisons.

I'm quite happy to accept that answer - my two ways to solve my problem were to either change Oj in the spirit of consistency with the default JSON parser or rewrite my tests.  I don't think I gave enough thought to the fact that they were comparing NaNs and passing until now!

I don't know if creating a constant NaN would even improve performance of Oj - I thought it might stop the `/` from happening and thereby eliminate a few calls, but the more I think about it the more I don't think it would make a significant difference.  In the end, I guess this change would be catering for a very special edge case that, if we want to be _pure_ about it, probably isn't entirely correct. I don't think, heuristically speaking, a small improvement in speed in this case would be justifiable.

Thanks for talking this through with me Pete, I thought it was worth bringing up the issue!
I think Oj probably does act in the correct manner in any case. 👍

**Comment by ohler55** [comment]
It would make an insignificant improvement in speed most due to the fact that NaN is not used very often as it really is outside the JSON specification.

Glad you are pleased with Oj. Getting feedback like that is a good motivator. Thanks.
