### ISSUE TITLE
Inconsistent to_json behavior when using Oj.mimic_JSON

### ISSUE THREAD

**Issue by jcarvalho** [ohler55/oj#313]
Consider the following code:

``` ruby
require 'oj'

Oj.mimic_JSON()

class Foo
  def as_json
    { foo: 'bar' }
  end
end

opts = {}

puts Foo.new.to_json
puts Foo.new.to_json(opts)
```

When running with the latest version of Oj (in particular, any one after `2.12.12`, versions prior to this worked as expected), the second `to_json` invocation fails with the following error:

```
$ bundle exec ruby oj-issue.rb 
{"foo":"bar"}
oj-issue.rb:6:in `as_json': wrong number of arguments (given 1, expected 0) (ArgumentError)
    from oj-issue.rb:14:in `to_json'
    from oj-issue.rb:14:in `<main>'
```

This stems from the fact that `as_json` does not expect any arguments, and as such, it blows up when trying to invoke `to_json` with any arguments (namely, an empty options hash).

I would expect there to be a consistent behavior, either having it fail in both cases, or ideally, having it recognize the target does not take any arguments, and invoke it without them.

**Comment by ohler55** [comment]
I'll look into it and figure out what has changed and how to make it support both.

**Comment by jcarvalho** [comment]
I believe this issue was introduced when #252 was merged.

**Comment by ohler55** [comment]
That merge added the ability to pass options to as_json which is what rails expects. I can change Oj to check the as_json signature. It is expensive though so I might make it an option. Still exploring. I suppose performance isn't really an issue if using active support though. With as_json on every class only a small portion is relegated to Oj.

**Comment by ohler55** [comment]
I just pushed a version with additional check for arity. Even before that my unit tests has tests that included as_json() methods with no arguments so I'm not sure what your were seeing. Please let me know if the changes make any difference for you. Can you tell me what the to_json() implementation is on your class assuming you have some other gems required. Maybe some active support code?

**Comment by jcarvalho** [comment]
Hi. The following `Gemfile` contains all that's necessary to replicate the issue:

```ruby
source 'https://rubygems.org'
ruby '2.3.1'

gem 'oj'
```

Associated `Gemfile.lock`:
```
GEM
  remote: https://rubygems.org/
  specs:
    oj (2.17.4)

PLATFORMS
  ruby

DEPENDENCIES
  oj

RUBY VERSION
   ruby 2.3.1p112

BUNDLED WITH
   1.13.2
```

I'll check with the latest version and report back.

**Comment by jcarvalho** [comment]
Running against the `master` branch fixes the issue, thanks!

**Comment by ohler55** [comment]
Great, as soon as I get some feedback from the rails folks on another issue I'll make a release.

**Comment by stereobooster** [comment]
I did some test to check compatibility with Rails `to_json` ([source](https://github.com/stereobooster/ruby-json-benchmark)). Here are results (for default settings, will check how to improve compatibility with options):

```
+---------------------------------+---------------+---------+
| class                           | JSON.generate | Oj.dump |
+---------------------------------+---------------+---------+
| Regexp                          | 👌            | ❌      |
| FalseClass                      | 👌            | 👌      |
| NilClass                        | 👌            | 👌      |
| Object                          | ❌            | ❌      |
| TrueClass                       | 👌            | 👌      |
| String                          | 👌            | 👌      |
| StringChinese                   | 👌            | 👌      |
| Numeric                         | 👌            | 👌      |
| Symbol                          | 👌            | ❌      |
| Time                            | ❌            | ❌      |
| Array                           | 👌            | 👌      |
| Hash                            | 👌            | 👌      |
| HashNotEmpty                    | 👌            | ❌      |
| Date                            | 👌            | ❌      |
| DateTime                        | ❌            | ❌      |
| Enumerable                      | ❌            | ❌      |
| BigDecimal                      | 👌            | ❌      |
| BigDecimalInfinity              | ❌            | ❌      |
| Struct                          | ❌            | ❌      |
| Float                           | 👌            | 👌      |
| FloatInfinity                   | 💀            | ❌      |
| Range                           | 👌            | ❌      |
| Process::Status                 | ❌            | ❌      |
| ActiveSupport::TimeWithZone     | ❌            | ❌      |
| ActiveModel::Errors             | ❌            | 💀      |
| ActiveSupport::Duration         | ❌            | ❌      |
| ActiveSupport::Multibyte::Chars | 👌            | ❌      |
| ActiveRecord::Relation          | ❌            | ❌      |
+---------------------------------+---------------+---------+
```

**Comment by ohler55** [comment]
I looked at your site. I like the benchmark results. I'd like to 
understand the compatibility tests a bit more. You are comparing JSON to 
JSON and get failures, how is that possible? I think I must not 
understand the results.

-Peter

**Comment by stereobooster** [comment]
@ohler55 I'm comparing **Rails** `to_json` implementation with everything else. See http://apidock.com/rails/ActiveResource/Base/as_json

**Comment by ohler55** [comment]
Please check the Oj 3.0 release.

**Comment by ohler55** [comment]
The original issue as fixed and acknowledged. The additional comments are addressed in other issues opened explicitly for those concerned.
