### ISSUE TITLE
efficient memory consumption

### ISSUE THREAD

**Issue by khoan** [ohler55/oj#317]
I'm using OJ::Saj to parse json (100MB - 200MB) to minimize memory usage. Correct me if I'm wrong, the whole json is slurped into memory https://github.com/ohler55/oj/blob/master/ext/oj/saj.c#L723.

Is there a way to parse a chunk at a time until finish with OJ::Saj?

**Comment by ohler55** [comment]
I haven't been updating the saj parser. Instead I'd suggest the scp parser. It supports stream parsing and is faster than the older saj parser.

**Comment by khoan** [comment]
coolies, will do.
