### ISSUE TITLE
Will OJ be used by default?

### ISSUE THREAD

**Issue by krzkrzkrz** [ohler55/oj#321]
So by just having In Gemfile:
```
gem 'oj'
gem 'oj_mimic_json'
```

The following will use oj:
```
{foo: ‘bar'}.as_json
```
Is my understanding correct?

**Comment by ohler55** [comment]
I don't think Hash is one of the classes given an as_json method. You can try it and see what you get though. If you have not required any other gems that should give you our answer.

**Comment by krzkrzkrz** [comment]
`{foo: 'bar'}.as_json` in `rails c` works. But how can I verify that the parsing is done via the OJ gem ?

**Comment by ohler55** [comment]
If you don't have any other son parser installed then it is Oj. Also try changing the Oj options and see if the output changes.

**Comment by krzkrzkrz** [comment]
What options are you referring to specifically?

In `config/initializers/oj.rb`, I have

```
Oj.default_options = { :mode => :compat, :symbol_keys => true, :use_to_json => true }
```

In `rails c`, doing:
```
h = { 'one' => 1, 'array' => [ true, false ] }
h.as_json
```

Returns:
```
{
      "one" => 1,
    "array" => [
        [0] true,
        [1] false
    ]
}
```
How exactly do I know if the OJ gem is being used?

**Comment by ohler55** [comment]
If you want to check if Oj is used to generate JSON then make changes to the default indentation setting. Then you can check based on if the setting change the output. For all but a few classes Oj using mimic_JSON does not define an as_json method.

**Comment by ohler55** [comment]
Ballin Oj.dump(h) explicitly does cut out some overhead. It would be more clear and faster.

**Comment by ohler55** [comment]
Can this be closed?

**Comment by krzkrzkrz** [comment]
Sure thing. Thanks for feedback
