### ISSUE TITLE
Odd behavior when specifying `:mode` and using `to_hash`

### ISSUE THREAD

**Issue by evanleck** [ohler55/oj#322]
I'm running this code on Oj version 2.18.0 and it seems like it should behave differently:

```ruby
require 'oj'

Oj.default_options = Oj.default_options.merge(mode: :object)

class Person
  def initialize(name)
    @name = name
  end

  def to_hash
    { 'name' => 'Bob' }
  end
end

sue = Person.new('Sue')

puts Oj.dump(sue)                 # {"^o":"Person","name":"Sue"}
puts Oj.dump(sue, mode: :compat)  # {"name":"Sue"}
```

Shouldn't `Oj.dump(sue, mode: :compat)` output `{ "name": "Bob" }`? Am I totally missing something?

Thank you!

**Comment by ohler55** [comment]
The use of the default options is incorrect. This is is what you want.
```ruby
Oj.default_options = { mode: :object }
```
The default to honoring to_json is false and to_hash is tied to that option. Add that option to the args or the defaults and it should work better.

**Comment by evanleck** [comment]
Ah, that doesn't overwrite the other defaults? And it sounds like I need both `mode: :compat` and `use_to_json: true` to get the behavior I was expecting. That's starting to make sense, thank you! I thought `mode: :compat` triggered the use of `to_hash` without having to add `use_to_json`

Thank you!

**Comment by ohler55** [comment]
I believe the latest rails/active thinking is that to_json is deprecated in favor of as_json.

**Comment by evanleck** [comment]
Makes sense, I was just confused because based on the docs (emphasis mine):

> :compat mode attempts to be compatible with other systems. It will serialize any Object, but **will check to see if the Object implements an to_hash or to_json method**. If either exists, that method is used for serializing the Object. Since as_json is more flexible and produces more consistent output, it is preferred over the to_json method. If neither the to_json or to_hash methods exists, then the Oj internal Object variable encoding is used.

It looks like this:

```ruby
Oj.dump(sue, mode: :compat)
```

should return:

```json
{"name":"Bob"}
```

But it doesn't. Does that make sense? Shouldn't just using `:compat` mode trigger the use of `to_hash`?

**Comment by ohler55** [comment]
I'll update the docs. When it was first written that statement was true. It is no longer as the options had to be added to be compatible with rails changes.

**Comment by evanleck** [comment]
So then the only way to trigger the use of `to_hash` is the use `:compat` mode with `:use_to_json` as `true`, right?

**Comment by ohler55** [comment]
correct

**Comment by evanleck** [comment]
Got it, thanks for the clarification!
