### ISSUE TITLE
Allow symbol_keys: true in strict mode

### ISSUE THREAD

**Issue by Nowaker** [ohler55/oj#327]
I've been recently experimenting with `JSON.dump` and realized it calls `.to_s` on any non-"primitive" object it tries to dump after I found elements like `"blah": "<#ClassName: 1234>"` inside my app's JSONs. That's quite bad. I've been looking for alternative JSON parsers/dumpers that will dump primitive types and nothing more. Oj's strict mode is exactly what I've been looking for, so kudos for you.

However, I think strict mode should still accept symbol keys - at least via an option. Symbol keys is a standard in Ruby so penalizing its usage in strict mode is very limiting. Please consider allowing something like this to happen: `Oj.dump(hash, mode: :strict, symbol_keys: true)`.

**Comment by ohler55** [comment]
That sounds reasonable. I'll take a look at dump and load over the next couple of days.

**Comment by Nowaker** [comment]
Thank you sir, I appreciate that. Have a great weekend.

**Comment by ohler55** [comment]
Decided Symbols should always be valid. Please try whats on github.

**Comment by ohler55** [comment]
Did you give the version on github a try or the released version?

**Comment by Nowaker** [comment]
@ohler55 Thanks for implementing this. I was recently working on a different part of the system that doesn't involve JSON but once I'm back to it, I'll give it a try. But hey, if it's works then it works, right? :) Thanks for taking care of it. Have a good one.
