### ISSUE TITLE
Prevents assets from compiling when using handlebars

### ISSUE THREAD

**Issue by weilandia** [ohler55/oj#328]
I added 'oj' and it caused an issue where our assets would not compile on this line: ``` var theTemplate = Handlebars.compile (tableTemplate);  ```.

This is the error:
`rake assets:precomile
Interrupt:
/Users/weilandia/.rvm/gems/ruby-2.0.0-p648@airbo/gems/actionpack-3.2.22.1/lib/sprockets/assets.rake:12:in ruby_rake_task'
/Users/weilandia/.rvm/gems/ruby-2.0.0-p648@airbo/gems/actionpack-3.2.22.1/lib/sprockets/assets.rake:21:in invoke_or_reboot_rake_task'
/Users/weilandia/.rvm/gems/ruby-2.0.0-p648@airbo/gems/actionpack-3.2.22.1/lib/sprockets/assets.rake:29:in block (2 levels) in <top (required)>'
/Users/weilandia/.rvm/gems/ruby-2.0.0-p648@airbo/gems/airbrake-5.6.1/lib/airbrake/rake/task_ext.rb:19:in execute'
/Users/weilandia/.rvm/gems/ruby-2.0.0-p648@airbo/gems/rake-12.0.0/exe/rake:27:in <top (required)>'
/Users/weilandia/.rvm/gems/ruby-2.0.0-p648@airbo/bin/ruby_executable_hooks:15:in eval'
/Users/weilandia/.rvm/gems/ruby-2.0.0-p648@airbo/bin/ruby_executable_hooks:15:in <main>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
rake aborted!`

We are using the Handlebars source code directly (not a gem nor npm).  

Just wanted to make a note. Thanks!

**Comment by ohler55** [comment]
I tok a quick look at Handlebars but other than a few JSON files I did not see and Ruby files. Can you explain a bit more about how Oj is used with Handlebars? Maybe point me at the correct project on git hub too. I was looking at daaain/Handlebars.

**Comment by weilandia** [comment]
Thanks for the quick response!

We aren't using oj with handlebars specifically.  Just when I added oj to the Gemfile we could no longer compile our assets and the precompile was breaking specifically when calling Handlebars in the our js files.  Not an issue when I remove oj.

**Comment by ohler55** [comment]
Which handlebars repo are you using? I'd like to figure out what is going on and resolve it if possible but I need more information to do that. Are you willing to provide some of that?

**Comment by weilandia** [comment]
http://builds.handlebarsjs.com.s3.amazonaws.com/bucket-listing.html?sort=lastmod&sortdir=desc

The most recent

**Comment by weilandia** [comment]
And yep! Let me know if you need anything else from me. I can also take a deeper look this evening.

**Comment by weilandia** [comment]
Also, here's the commit that fixed the issue.  At first I thought it was some dependency that installing oj bumped up, but doesn't look like it.
![screen shot 2017-01-17 at 11 21 09 am](https://cloud.githubusercontent.com/assets/13652979/22036100/311a7a82-dca7-11e6-9fb1-7bb3524629b2.png)

**Comment by ohler55** [comment]
Am I to understand that the most recent Oj works okay? If not I still need to know which handlebar project is being used.

**Comment by weilandia** [comment]
No, it does not work with the most recent OJ.

The handlebar project was linked above:

http://builds.handlebarsjs.com.s3.amazonaws.com/bucket-listing.html?sort=lastmod&sortdir=desc

We are using the most recent build.

**Comment by ohler55** [comment]
Is that CKGrafico/jQuery_HandlebarsJS on github?

**Comment by ohler55** [comment]
Are you able to confirm that the handlebars you are referring to is the one I mentioned?

**Comment by ohler55** [comment]
No response and not enough information to continue.
