### ISSUE TITLE
Parsing loosing data randomly

### ISSUE THREAD

**Issue by kikonen** [ohler55/oj#330]
I've spend sometime racing strange random NPE in Rails app. I've now reduced context into Oj json parsing.

```ruby
data = Oj.load(json, { symbol_keys: true, mode: :object })
```

Problem: It seems that randomly Oj is loosing data from the parsed json

json data
```json
{
  "data" : [ {
    "action" : "xx",
    "event" : "yyy"
   },
   ....
   ],
   "info": { "result_count": 10 }
}
```

Randomly one of the entries in "data" array is empty, which triggers naturally unexpected NPE elsewhere when trying to handle data. I've verified that incoming json data truly doesn't have empty entries in array.

Thus randomly parsed result is like this:
json data
```ruby
{
  data: [ {
     # data lost from some random entry in array
   },
   ....
   ],
   info: { result_count: 10 }
}
```

Has anyone encountered such issue?

Using Oj "2.18.1" ruby "2.3.3", and issue has been seen in both Linux and OSX environment.

**Comment by kikonen** [comment]
IMO, this is rather odd issue; doesn't occur often, but occasionally. I wonder if another library (like "curb") could be corrupting memory via C code and trigger issue in Oj also.

**Comment by kikonen** [comment]
Trying now with "allow_gc: false" in parsing to see if issue is appears

**Comment by kikonen** [comment]
So far, after "allow_gc: false" hack I haven't been able to see issue. So there's change that it's related into ruby GC hitting in bad time during parsing.

**Comment by ohler55** [comment]
Those are tough to debug especially when multiple gems are involved. Let me do a check on the handling of objects in an array and see if I've missed something.

**Comment by ohler55** [comment]
I created a branch named 'gcx' for GC experimental. It is not a fix so much as a test of an assumption. Please give it a try. If it works then I have a more permanent fix I will try. This version just lock up variables that used to be picked up ok by the Ruby GC.

**Comment by kikonen** [comment]
Without your branch in my first recent attempt, I managed to still encounter issue with

```ruby
  OJ_PARSE_OPT = { symbol_keys: true, allow_gc: false, mode: :strict }.freeze
  def self.parse_json(json)
    Oj.load(json, OJ_PARSE_OPT)
  end
```
Noteworthy is that I had changed also mode to be :strict instead of :object in attempt to see if result would be better.

I'm going to "gcx" branch next

**Comment by kikonen** [comment]
Didn't manage to see real improvement in situation with "gcx" branch. Still, mysteriously some map entry in array becomes empty randomly.

Trying to next troubleshoot with trying to eliminate other gems, and see if I can make problem disappear (still tricky to confirm since issue doesn't happen every time, but only after doing transferring/parsing reasonable large json blobs (~300KB in size) for a while over rest api).

**Comment by kikonen** [comment]
Good news; I managed to create test case where I'm able to reproduce issue. More good news is that so far based into that test, bug is not related to "oj" but instead "curb" is somehow corrupting memory and causing random bugs in "oj". Of course, due to randomness of error I cannot be 100% sure, but I know that in my test case I was able to see on every test run with "oj + curb", but not with "oj + httpclient". While I cannot proof possible non existence of issue in "oj" I can at at least confirm that likehood of issue is significantly lower when "curb" is not used for REST.

Did this testing with Oj "2.18.1" ruby "2.3.3", with options  "Oj.load(data, { symbol_keys: true, mode: :strict })"

**Comment by ohler55** [comment]
Can you provide the data you are using for the test? Maybe put it in a gist.

**Comment by kikonen** [comment]
Did one additional test with basically following kind of structure

```ruby
while true
  curl = Curl::Easy.new("url")
  curl.ssl_verify_host = false
  curl.http_get
  GC.disable
  data = Oj.load(curl.response_body, symbol_keys: true, mode: :strict)
  GC.enable
  raise "FAILED" if data[:data].any? { |e| e.empty? }
end
```
and issue doesn't occur any longer. When removing "GC.disable/GC.enable" lines issue occurs.


JSON data structure in testing is (just random 1+N entries in "data" array should do the trick).
```json
{
  "data" : [ {
    "action" : "login",
    "event" : "user",
    "field" : "login",
    "value" : "foobar",
    "info" : "Authenticated \"Foo Bar\"",
    "id" : "585929918297f2740ed9f5f0",
    "_metadata" : {
      "version" : "1"
    },
    "timestamp" : "2016-12-20T07:52:33",
    "key_id" : "4"
  } ],
  "info" : {
    "view" : "partial",
    "limit" : 500,
    "offset" : 2000,
    "results" : 500,
    "ordering" : "timestamp desc,id",
    "previous" : "https://api.server.com/some/path/event?calculate_total=false&draft=base&order_by=timestamp_desc&order_by=id&subdraft=none&offset=1500&limit=500",
    "next" : "https://api.server.com/some/path/event?calculate_total=false&draft=base&order_by=timestamp_desc&order_by=id&subdraft=none&offset=2500&limit=500",
    "draft" : "base",
    "subdraft" : "none",
    "total_results" : 100000
  }
}
```

**Comment by ohler55** [comment]
Ok, I'll try three things. All without the GC disabled. First case without curl and just the JSON body you listed. Second I'll set up a server, piper as in http://piperpushcache.com and have it serve up that JSON and include curl. Third, with the server but making a copy of the response_body. I'll let you know later today if I can reproduce the issue.

**Comment by ohler55** [comment]
What curl gem are you using? I tried ```gem install curl``` and seem to have something completely different. Painfully slow as well.

**Comment by ohler55** [comment]
Update on the status with the curl gem (probably not the one you are using). 150,000 with no errors. Thats after more than 3 hours.

**Comment by kikonen** [comment]
"curb" is the gem (i think I mentioned it). It uses libcurl library internally with C bindings. In comparison, by my understanding "curl"  gem is simple wrapper for executing curl as shell command (so it is surely slow).

**Comment by ohler55** [comment]
I saw that but thought it was a typo. My mistake.

I installed curb but had to change the ```curl.response_body``` to ```curl.body``` as there is no ```response_body``` in a Curl::Easy. At least not in the most recent. The test I used is
```ruby
require 'curb'
require 'oj'

$cnt = 0
  
while true
  curl = Curl::Easy.new("localhost:7660/data.json")
  curl.ssl_verify_host = false
  curl.http_get

  data = Oj.load(curl.body, symbol_keys: true, mode: :strict)
  if data[:data].any? { |e| e.empty? }
    puts "body: #{curl.body}\ndata: #{data}"
    raise "FAILED" 
  end
  $cnt += 1
  print "\r #{$cnt}" if 0 == ($cnt % 10)
end
```
Running I got this.
```
> curl_oj.rb 
 190/Users/ohler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/curb-0.9.3/lib/curl/easy.rb:67:in `add': No URL supplied (Curl::Err::CurlError)
	from /Users/ohler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/curb-0.9.3/lib/curl/easy.rb:67:in `perform'
	from /Users/ohler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/curb-0.9.3/lib/curl/easy.rb:296:in `http'
	from /Users/ohler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/curb-0.9.3/lib/curl/easy.rb:296:in `http_get'
	from ./curl_oj.rb:18:in `<main>'
```
Basically it did about 190 iterations and then decided the string handed to the Curl::Easy.new was no longer valid. I suspect that is related and Suspect it has something to do with the curb gem but I'm not sure how yet. I'll keep digging.

**Comment by ohler55** [comment]
If GC is disabled for either the curl calls or the Oj call the corruption no longer occurs. That seems odd but doesn't help get to the core of the problem. I looked over the curb code and it is not at all GC safe. I'll pull it and make some modifications and see if that makes a difference.

**Comment by ohler55** [comment]
I have not been able to identify the exact problem but the following simple script will either fail or hang. It does not use Oj.
```ruby
require 'curb'

$cnt = 0
$url = "localhost:7660/data.json"

begin
  while true
    before = GC.count
    curl = Curl::Easy.new($url)
    curl.ssl_verify_host = false
    curl.http_get
    if before != GC.count
      puts " did a GC in curl #{GC.count}"
      before = GC.count      
    end
    $cnt += 1
    print "\r #{$cnt}"
  end
rescue Exception => e
  puts "#{e.class}: #{e.message}"
  puts "url: #{$url}"
end
```
After spending a significant amount of time looking at this I am very confident the issue is not in Oj but in curb. I was not able to locate and the the curb issue but from going over the code it is not at all GC safe. If you are using it I would disable GC while it is running and enable when it is complete.

**Comment by ohler55** [comment]
If all you need to do is get a JSON string from a server something like this performs as well as curb, is less complicated, and does not have GC issue.

```ruby
require 'net/http'
require 'uri'
require 'oj'

$url = URI.parse("http://localhost:7660/data.json")
$cnt = 0

while true
  response = Net::HTTP.get_response($url)
  data = Oj.load(response.body, symbol_keys: true, mode: :strict)
  raise "FAILED" if data[:data].any? { |e| e.empty? }
  $cnt += 1
  print "\r #{$cnt}"
end
```

30K fetches and parses in 4 minutes.

**Comment by kikonen** [comment]
Thx for your effort on investigating this. Your findings are certainly useful.

**Comment by ohler55** [comment]
Any new information? Can this be closed?

**Comment by kikonen** [comment]
Well, all knowledge points into issue in curb side. I have done some running with GC turned off for it, and haven't encountered lost data issue with such setup. Lets' close this one; there is nothing what can be done in oj side.

**Comment by ohler55** [comment]
Thanks.
