### ISSUE TITLE
With upgrade to OJ 2.18 from 2.17.5, expires_at returns an invalid date

### ISSUE THREAD

**Issue by wfried** [ohler55/oj#331]
Our application has a couple DB fields called expires_at.

We recently updated from OJ 2.17.5 to OJ 2.18, and now these values are being returned as

expiresDate: {utc: Infinity, time: null, time_zone: {name: "Pacific Time (US & Canada)", utc_offset: null,…},…}

When we change nothing else, but revert to OJ 2.17.5, this issue is fixed, and the values return as valid dates, like

expiresDate: "2017-01-27T13:41:50.000-08:00"

I'm hoping someone who works on this project may spot the reason why this happened, if you need more information just let me know.

**Comment by ohler55** [comment]
Take a loot at the release notes from 2.18. I suspect the issue is new use_as_json option. Try setting it to true in the defaults and see if that fixes the issue.

**Comment by wfried** [comment]
Thanks for the quick response.
To clarify, do you mean put the following line in application.rb, for example:

`Oj.default_options = {:use_as_json => true}`

**Comment by ohler55** [comment]
yes

**Comment by wfried** [comment]
Thanks very much, that did the trick.

**Comment by ohler55** [comment]
I like the easy ones.
