### ISSUE TITLE
JSON is too deeply nested (SystemStackError)

### ISSUE THREAD

**Issue by majormoses** [ohler55/oj#333]
I have seen several closed issues that relate to this: 
https://github.com/ohler55/oj/issues/50
https://github.com/ohler55/oj/issues/69

I wish to open as fresh as its using a much newer code base. I originally reported this here: https://github.com/PagerDuty/jsonlint/issues/27

Here are the gists for testing:
https://gist.github.com/majormoses/721d610a1a11c0ffde9e1a1aa594cba1
https://gist.github.com/majormoses/e3245bf85ec2b1d1248ea2159f6b11f0

Unfortunately I  have a very hard time reproducing it myself except in jenkins.

**Comment by ohler55** [comment]
The two issues you mentioned were both caused by active model calling itself recursively. Oj detects most of those cases now but there might be others if the classes are set up incorrectly. Can you tell me if this is a rails application? How about an example of what the call looks like that causes the failure?

**Comment by majormoses** [comment]
This is run in jenkins everything is executed by make but thats moreso for standard contract than anything else. Basically I am calling `jsonlint data_bags/users/babrams.json` the contents of the json do not seem to matter. I originally opened it up against the jsonlint repo but they suggested it might be something upstream. As I have a hard time reproducing outside of jenkins. The gist should have the information about gems installed etc

**Comment by ohler55** [comment]
I can run Oj.saj_parse on the JSON provided without issues. Having just the gems listed does not tell me what is being called or even which gems are required in the code that is having problems. Unlike the rails and active support which does not seem to be relevant here the SAJ parser does not call to_json nor as_json.

The are to look at is what handler is being given to the SAJ parser and what JSON is being given to it. That comes down to what the jsonlint team can provide.

**Comment by ohler55** [comment]
Can this be closed?

**Comment by majormoses** [comment]
I think so, I still think there is an issue but I am not convinced its here.

**Comment by ohler55** [comment]
Thanks.
