### ISSUE TITLE
Convert certain objects to hash

### ISSUE THREAD

**Issue by FWMatt** [ohler55/oj#334]
Hi,

I'd like to use Oj in object mode, but treat certain object types as a Hash, i.e. HashWithIndifferentAccess (or anything that extends Hash).

  1) Oj.dump HashWithIndifferentAccess should eq "{\"a\":1}"
     Failure/Error: it { expect(Oj.dump(ActiveSupport::HashWithIndifferentAccess.new(a: 1))).to eq "{\"a\":1}"}
     
       expected: "{\"a\":1}"
            got: "{\"^o\":\"ActiveSupport::HashWithIndifferentAccess\",\"self\":{\"a\":1}}"
     
Is this possible?

Thanks!
Matt

**Comment by ohler55** [comment]
The difficulty is in know what initializer the Hash subclass uses. There is a feature in Oj that allows you to be creative though. Take a look at the Oj.register_odd() method. You will have to write your own serializer and de-serializer. There are some examples in the test/test_object.rb file.

**Comment by ohler55** [comment]
Did this answer your question?

**Comment by FWMatt** [comment]
Hi, I couldn't get this to work. Let me just clean up my test code and Ill post it here. I'm sure I'm missing something simple.

**Comment by ohler55** [comment]
ok

**Comment by ohler55** [comment]
Is this still an issue or did you get it resolved?

**Comment by FWMatt** [comment]
Hi - I couldn't get it working, but have put in place a work around. Thanks for getting back in touch.
