### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by slavestys** [ohler55/oj#335]
Hi!
Oj.dump consumes twice as much memory than the JSON.fast_generate
This is a consequence of productivity growth?
```ruby
require 'json'
require 'oj'
require 'get_process_mem'

repeat = 10

puts "json before: #{mem.mb}"
repeat.times do
  JSON.fast_generate(hash)
end
puts "json after: #{mem.mb}"

puts "oj before: #{mem.mb}"
repeat.times do
  Oj.dump(hash)
end
puts "oj after: #{mem.mb}"
```

Result:

json before: 10.7265625
json after: 11.55859375
oj before: 11.55859375
oj after: 13.66015625

**Comment by slavestys** [comment]
if repeat == 1

json before: 10.9453125
json after: 11.26171875
oj before: 11.26171875
oj after: 11.72265625

if repeat == 100

json before: 10.98046875
json after: 11.5546875
oj before: 11.5546875
oj after: 31.02734375

Memory leaks&

**Comment by ohler55** [comment]
I'll check tonight. The approach that the get_process_mem uses will only give you the peak memory and not memory actually in use so reported results may not be what you think. I'll try with higher repeats also making sure GC is called between runs.

**Comment by ohler55** [comment]
I ran some tests and and saw no increase in memory size when doing a GC before each dump. If you can share the hash you are using maybe that will help. Any change in the Oj.default_options would be worth knowing as well.

**Comment by slavestys** [comment]
Thanks for the answer.
Hash: 

```ruby
size = 10000
hash = Hash[size.times.map{|i| [i, i]}]
```
I disabled gc before performing tests:

```ruby
GC.disable
```
Result:

json before: 10.8984375
json after: 20.96875
oj before: 20.96875
oj after: 23.0703125

It seems everything is fine.

**Comment by ohler55** [comment]
Good. I actually tested in the other direction and did a GC after each dump. With that approach there was no change at all.

**Comment by ohler55** [comment]
Ok to close?
