### ISSUE TITLE
Allocation of string objects

### ISSUE THREAD

**Issue by kikonen** [ohler55/oj#336]
Is it technically feasible to avoid allocating ruby string objects inside Oj for repeating key values when parsing JSON? Especially when using "symbol_keys: true".

**Comment by ohler55** [comment]
In order to create a symbol a string has to be created first, encoded to UTF-8, then interned. The strings and the symbols will be GCed when no longer used. At one point OJ cached symbols since they were immutable. That is no longer true so the symbol caching was removed a while back.

**Comment by ohler55** [comment]
Did that answer your question? Is it consistent with what you are seeing?

**Comment by kikonen** [comment]
This Q came up due to need to parse lot of json coming from trusted rest api. Often somewhat large, repeative json blobs are passed over, which naturally causes lot of string allocs (which are symbolized via "symbolize_keys: true").

Continuation Q: What was tbe problem with internal symbol caching? I see that it could br problem if random data received from non-trustworthy source is parsed. In this my case source is well trusted, and wont ever generate unexpected data elements in json.

So do I presume correctly that problem is symbol gc introduced in ruby 2.x?

**Comment by ohler55** [comment]
You presume correctly. The overhead of locking in a symbol is not worth the caching and caused more problems than it solved.

**Comment by kikonen** [comment]
ok, closing this for now
