### ISSUE TITLE
omit_nil option is ignored by Oj.to_stream

### ISSUE THREAD

**Issue by ysmazda** [ohler55/oj#337]
I encountered a mysterious behavior of Oj.to_stream as to omit_nil option.

The code below reproduces the behavior (Gem parallel is required to run the code).

```ruby
require 'oj'
require 'stringio'
require 'parallel'

h = { a: 1, b: nil, c: 3 }
outputs = Parallel.map((0...30).to_a, in_process: 30) do |i|
  io = StringIO.new('wb+')
  Oj.to_stream(io, h, omit_nil: false)
  io.string
end

outputs.each do |output|
  puts output
end
```
## Running environment
**OS**: OS X 10.11.6
**Ruby version**: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
**oj version**: 2.18.0

## Expected result

{"a":1,"b":null,"c":3} is output 30 times.

## Actual result

{"a":1,"c":3} and {"a":1,"b":null,"c":3} are output randomly.

In [oj_write_obj_to_stream](https://github.com/ohler55/oj/blob/master/ext/oj/dump.c#L2320) and [oj_write_leaf_to_file](https://github.com/ohler55/oj/blob/master/ext/oj/dump.c#L2549) omit_nil value is assigned **after** oj_dump_obj_to_json invocation while omit_nil value is assigned before oj_dump_obj_to_json invocation in [dump](https://github.com/ohler55/oj/blob/master/ext/oj/oj.c#L950) and [oj_write_obj_to_file](https://github.com/ohler55/oj/blob/master/ext/oj/dump.c#L2284).

Is this an intentional or just a mistake?

Thanks!

**Comment by ohler55** [comment]
An embarrassing mistake. Thank you. I fixed it in the master branch but will test before releasing.

**Comment by ysmazda** [comment]
Thanks for your prompt action!

**Comment by ohler55** [comment]
Released. I was a little slow on the test. Thanks for the catch.

**Comment by ysmazda** [comment]
Thanks!
