### ISSUE TITLE
Parsing small Floats

### ISSUE THREAD

**Issue by fnordfish** [ohler55/oj#339]
Sorry for beeing a bit late to the party, but while trying to get another project ready for ruby 2.4 and thus upgrading Oj from 2.10.
After some poking, I've found that Oj 2.12.13 introduced a small error when parsing very small Floats.

```
bundle exec ruby -e 'require "oj"; p Oj::VERSION, Oj.load("6.626E-34")'
"2.12.12"
6.626e-34
```

versus: 

```
bundle exec  ruby -e 'require "oj"; p Oj::VERSION, Oj.load("6.626E-34")'
"2.12.13"
6.626000000000001e-34
```

This behaviour is consistent between different versions of ruby.
Ruby `JSON` is consistently correct:

```
bundle exec ruby -e 'require "json"; p JSON.load("6.626E-34")'
6.626e-34
``` 

Using `compat_load` with `float_precision: 0` does not help either (also, said project uses the `sc_parse` api, which does not support option overrides(?)):

```
bundle exec ruby -e 'require "oj"; p Oj::VERSION, Oj.compat_load("6.622E-34", float_precision: 0)'
"2.12.13"
6.622000000000001e-34
```

Some more interesting edge cases: 

```
"1E-34" => 1.0000000000000001e-34
"1.0E-34" => 1.0e-34
"6.621E-34" => 6.621e-34
"6.622E-34" => 6.622000000000001e-34
```

**Comment by ohler55** [comment]
I changed the parsing to use long doubles which seems to take care of the issue. Checking now to make sure compilers don't have an issue. Please let me know if it works for you and if so I'll make a release.

**Comment by fnordfish** [comment]
Thanks! That seems to work.
