### ISSUE TITLE
Update 2.10.2 to latest issue

### ISSUE THREAD

**Issue by JulienItard** [ohler55/oj#352]
Hello,
I use ruby 2.3.1, rails 4.2.7.1 and mimic json gem

i try to update my gem 2.10.2 to the latest but I have a issue with version 2.14.4. 
this version does : `When not in quirks mode strings are now raise an exception if they are the top level JSON value.`

Indeed i pass a string that why I have `Oj::ParseError: unexpected non-document value`

I try to set quirk mode true in initializer with `Oj.default_options = {:quirks_mode => true}` but nothing change. I restarted nginx and spring but nothing change. I'm sure my initializer is called. It's weird because quirk mode should be true by default.

Thanks for your help

**Comment by ohler55** [comment]
An example would help.

I tried this and it worked fine.
```ruby
Oj.load('"hello"')
=> "hello"
```
Of course if you try
```ruby
Oj.load("hello")
```
You will and should get an error since the string "hello" without quotes is not valid JSON.

**Comment by ohler55** [comment]
Whats the status of this issue?

**Comment by ohler55** [comment]
No response, closing.
