### ISSUE TITLE
Oj.dump includes object metadata when used with ActiveModelSerializers

### ISSUE THREAD

**Issue by patbl** [ohler55/oj#359]
I recently tried upgrading Oj from 2.12.14 to 2.18.5. The specs failed on CI with an OOM error, apparently because an infinitely long JSON string was being generated by `Oj.dump`.

I don't know what causes the infinite loop, but I noticed another problem that may be related. When running `Oj.dump` in the Rails console, the database-schema information is included.

```
# 2.12.14
> puts Oj.dump(ActiveModel::Serializer.new(Ad.new))
{"serializer":{}}
=> nil

# 2.18.5
> puts Oj.dump(ActiveModel::Serializer.new(Ad.new))
{"options":{},"object":{"attributes":{"attributes":{"types":{"id":{"precision":null,"scale":null,"limit":null,"range":"-2147483648...2147483648"},"title":{"precision":null,"scale":null,"limit":255},"url":{"precision":null,"scale":null,"limit":255},"image":{"precision":null,"scale":null,"limit":255},"created_at":{"delegate_dc_obj":{"precision":null,"scale":null,"limit":null}},"updated_at":{"delegate_dc_obj":{"precision":null,"scale":null,"limit":null}}},"values":{"id":null,"title":null,"url":null,"image":null,"created_at":null,"updated_at":null},"additional_types":{},"materialized":false,"delegate_hash":{}}},"aggregation_cache":{},"association_cache":{},"readonly":false,"destroyed":false,"marked_for_destruction":false,"destroyed_by_association":null,"new_record":true,"txn":null,"_start_transaction_state":{},"transaction_state":null,"reflects_state":[false],"current_shard":"master"}}
=> nil
```

This is what the output looks like for a non–Active Record object:

```
> class Foo; end
=> nil
# 2.12.14
> Oj.dump(ActiveModel::Serializer.new(Foo.new))
=> "{\"serializer\":{}}"
# 2.18.5
> Oj.dump(ActiveModel::Serializer.new(Foo.new))
=> "{\"options\":{},\"object\":{}}"
```

I don't know whether it's an ActiveModelSerializers bug or an Oj bug, but it did appear after I upgraded Oj, without any other changes.

I'm using ActiveModelSerializers 0.8.3.

**Comment by ohler55** [comment]
It is important with active record to have :use_as_json turned on. ActiveSupport has a lot of circular references so taking all the attributes of an object will cause problems. In the upcoming 3.0 release there is a special Rails mode that deals specifically with ActiveSupport compatibility. That should address the issue with ActiveSupport. You can also try turning on the circular check in Oj.

**Comment by patbl** [comment]
Turning on `:use_as_json` fixed it. Thanks!
