### ISSUE TITLE
Parsing multiple documents from a socket

### ISSUE THREAD

**Issue by rfestag** [ohler55/oj#360]
I was playing with the OJ Saj parser, and noticed it doesn't appear to like the case where multiple JSON documents are sent serially over the same IO. In my case, I am making a TCP connection to a server I don't own, and it periodically sends me complete JSON documents (so I might see something like {"k1":"v1"}{"k1":"v2"}{"k1":"v3"}). Unfortunately, I'm not guaranteed that any read from the socket will be a full JSON object, so I need a parser that can handle many independent documents over the same IO.

So far, the only streaming parser I've found that supports this case is Yajl. Does OJ already support this (and I'm doing something wrong), or would it be feasible to (optionally) support this case? If so, where would I look to start adding it? I'd be happy to submit a PR if somebody could point me in general direction of where to begin.

**Comment by rfestag** [comment]
Update:

I found a silly mistake on my end, and now I'm not sure this is the issue. Now I'm wondering if there some other problem behind the scenes in how the data is read from a TCPSocket. I am passing a Celluloid::IO::TCPSocket object as the second argument to Oj.saj_parse. It seems like it is doing a single read of the available data, and it complains:

 Oj::ParseError: quoted string not terminated at line 1, column 2881 [saj.c:576]

Which makes sense if it isn't reading all of the available data, or if not all of a given JSON object is available on the socket Oj first reads it.

**Comment by ohler55** [comment]
I have tested and used On were partial reads are normal. There might be something else going on. I'm happy to debug with you though.

**Comment by ohler55** [comment]
I didn't notie you were using the saj parser. The sc_parse() would be a better choice. It does partial reads as you expect. The SAJ parser use is discouraged. I should probably deprecate it instead of just suggesting the sc_parse is a better choice.

**Comment by rfestag** [comment]
Ah, that makes sense. Sorry, I missed the recommendation to use sc_parse. I switched over to that, and it looks like my original intuition is correct...after parsing the first document correctly, it gets a parse error. I'm trying to put together a simpler example of what I'm doing, but having some weird (unrelated) issues. The full code I have is here:

```ruby
require 'oj'
require 'yajl'
require 'msgpack'
require 'celluloid/current'
require 'celluloid/io'
require 'celluloid/zmq'
Celluloid::ZMQ.init
module AdsbExchange
  class Parser < ::Oj::ScHandler
    def hash_start 
      {}
    end

    def hash_set(h,k,v)
      h[k] = v
    end

    def array_start
      []
    end

    def array_append(a,v)
      a << v
    end

    def add_value v
      p v
    end
  end
  class Live
    include Celluloid::IO
    include Celluloid::ZMQ

    finalizer :stop
    attr_accessor :running

    def initialize host: 'pub-vrs.adsbexchange.com', port: 32010, publish: 'ipc:///tmp/adsb_updates'
      @host = host
      @port = port
      @endpoint = publish
      async.run
    end
    def stop
      @running = false
      @stream.close if @stream
      @publish.close if @publish
      @parser = nil
    end
    def run
      return if @running
      @running = true
      @parser = Yajl::Parser.new
      @parser.on_parse_complete = method(:on_data)
      @stream = TCPSocket.new(@host, @port)
      @publish =Socket::Pub.new
      @publish.bind(@endpoint)

      Oj.sc_parse(Parser.new, @stream)
      #while true 
      #  @parser << @stream.recv(1024)
      #end
    end
  private
    def on_data msg
      now = Time.now.to_i*1000
      selected = msg['acList'].select do |update|
        update['PosTime'] = now
        update.length > 1
      end
      @publish << selected.to_msgpack
      #@publish << selected.to_json
    end
  end
end
AdsbExchange::Live.supervise as: :adsb_source
sleep
```

**Comment by ohler55** [comment]
I'll put together a unit test for multiple json documents in a stream and make sure that works. I have a few parsers including OjC so I may be confusing one with another. If so I can certainly get Oj to handle multiple jsons in a stream with a callback parser.

**Comment by rfestag** [comment]
Great sounds good. I'll be happy to pull master and test it out whenever you think you have a fix. Not sure why I didn't think to do this before, but I beleive I can confirm it doesn't with this:

```ruby

require 'oj'
class Parser < ::Oj::ScHandler
  def hash_start
    {}
  end

  def hash_set(h,k,v)
    h[k] = v
  end

  def array_start
    puts "Started array"
    []
  end

  def array_append(a,v)
    a << v
  end
  def array_end
    puts "Ended array"
  end

  def add_value v
    p v
  end
  def error(message, line, column)
    p "ERROR: #{message}"
  end
end
Oj.sc_parse(Parser.new, %Q{{"a": 1}{"b":2}})
````

**Comment by ohler55** [comment]
I had a unit test for multiple json in a string for scp but added tests for StringIO and for socket. Both pass. I checked in the new tests on master in test/test_scp.rb. I tried you test and it fils. I realized the problem it is a bit quirky. Change the last line to 

```ruby
Oj.sc_parse(Parser.new, %Q{{"a": 1}{"b":2}}) {|j| j}
```

The problem is that some people wanted the parser to exit after reading one JSON do and others wanted it to continue. The core parser is used for non-callback parsers as well so the indicator that Oj looks for is a block to call with the result of the parsing. If there is none it thinks it should stop at one. If there is a block it keep going. I'll update the docs to reflect that.

**Comment by rfestag** [comment]
Interesting, yep, that works. I like the block syntax better anyways, so that's nice to know I can do that. Strange somebody would want the streaming processor to exit after one document (rather than relying on EOF), but as long as it works I'm happy. Thanks for looking into it!

**Comment by ohler55** [comment]
You might be happy to note that in the 3.0 release coming soon the sc_parse will continue all the time even without the proc. I added a flag to have it behave differently than the non-callback parsers.
