### ISSUE TITLE
Time format changes when using Oj::Rails::Encoder

### ISSUE THREAD

**Issue by tomasv** [ohler55/oj#373]
Hey! 👋 

I've been giving `oj` a try on my Rails 4.2.8 project and after running my test suite noticed a weird discrepancy with regards to how dates are encoded.

I setup `oj` this way:

```
# Gemfile
gem 'oj'

# config/initializers/json.rb
Oj::Rails.set_encoder
Oj::Rails.set_decoder
Oj::Rails.optimize(Array, BigDecimal, Hash, Range, Regexp, Time)
```

Then I noticed that running `some_model.to_json` serializes dates differently than the stock JSON serializer:

```
# Stock
{"id":1,"created_at":"2017-05-01T08:18:23.736Z","updated_at":"2017-05-01T08:18:23.736Z"}

# Oj
{"id":1,"created_at":"2017-05-01 08:18:23 UTC","updated_at":"2017-05-01 08:18:23 UTC"}
```

After tweaking with `oj` initialisation methods I managed to narrow it down to `Oj::Rails.set_encoder`:

```
irb(main):003:0> User.last.to_json
  User Load (0.2ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" DESC LIMIT 1
=> "{\"id\":1,\"created_at\":\"2017-05-01T08:18:23.736Z\",\"updated_at\":\"2017-05-01T08:18:23.736Z\"}"
irb(main):004:0> Oj::Rails.set_encoder
=> nil
irb(main):005:0> User.last.to_json
  User Load (0.2ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" DESC LIMIT 1
=> "{\"id\":1,\"created_at\":\"2017-05-01 08:18:23 UTC\",\"updated_at\":\"2017-05-01 08:18:23 UTC\"}"
```

Is there a way to get xmlschema dates when using `oj` and `.to_json`?

Rails version: 4.2.8
Oj version: 3.0.3

Thanks!

**Comment by ohler55** [comment]
Oj was tested agains Rails 5 but that difference should not cause the time to be exported as the Time.to_s format. Lets see if we can figure out what is going on. Can you provide the code for User class? Is it safe to assume the encoding method is ActiveSupport::JSON.encode()?

**Comment by tomasv** [comment]
@ohler55 

It's an empty Rails app where I simply ran `rails g scaffold User`. This generates an empty User model with timestamps, purely for this test.

Afterwards it's just:
```
# shell
rake db:migrate
rails c

# in rails console
user = User.create!
user.to_json
ActiveSupport::JSON.encode(user)
```

I've also tested it with Rails 5.0.2. Same thing unfortunately.

Is there any more info I can provide? Can you reproduce this?

**Comment by ohler55** [comment]
I'll try to reproduce it tonight and see what is going on.

**Comment by ohler55** [comment]
Should be fixed now.

**Comment by tomasv** [comment]
@ohler55 huge thanks, it works now. 👏
