### ISSUE TITLE
Oj.mimic_JSON() changes JSON.pretty_generate output for HashWithIndifferentAccess

### ISSUE THREAD

**Issue by palexvs** [ohler55/oj#374]
Hi, 
After upgrading OJ gem from v2.18.1 on v3.0.5 in Rails 5.0.2 I got unexpected behavior change if enable `mimic_JSON`:
```
[1] pry(main)> puts JSON.pretty_generate({a:1,b:2}.with_indifferent_access)                                                                                                                                 
{
  "a": 1,
  "b": 2
}

[2] pry(main)> Oj.mimic_JSON()                                                                                                                                                                              

[3] pry(main)> puts JSON.pretty_generate({a:1,b:2}.with_indifferent_access)                                                                                                                                 
{"a":1,"b":2}
```

**Comment by ohler55** [comment]
It looks like the pretty options we not picked up. I'll take a look.

**Comment by ohler55** [comment]
Where is the with_indifferent_access defined? What is returned from it?

**Comment by palexvs** [comment]
```
> {a:1,b:2}.with_indifferent_access.class                                                                                                                                                      
=> ActiveSupport::HashWithIndifferentAccess
```

**Comment by palexvs** [comment]
https://github.com/rails/rails/blob/5-0-stable/activesupport/lib/active_support/hash_with_indifferent_access.rb#L56

**Comment by ohler55** [comment]
That helps, thanks. So the as_json() method is called. My guess is the JSON formatting parameters are not being used. I check why tomorrow.

**Comment by palexvs** [comment]
```
pry(main)> puts JSON.method(:pretty_generate).source_location
=> /Users/..../.rvm/gems/ruby-2.3.0@talkable/gems/json-2.0.3/lib/json/common.rb

pry(main)> Oj.mimic_JSON

pry(main)> puts JSON.method(:pretty_generate).source_location   
=> nil
```

**Comment by ohler55** [comment]
Please try release 3.0.6.

**Comment by palexvs** [comment]
@ohler55 I got the same behavior for `oj (3.0.6)`:
```
Loading development environment (Rails 5.0.2)
[1] pry(main)> puts JSON.pretty_generate({a:1,b:2}.with_indifferent_access)                                                                                                                                 
{
  "a": 1,
  "b": 2
}
=> nil
[2] pry(main)> require 'oj'                                                                                                                                                                                 
=> true
[3] pry(main)> puts JSON.pretty_generate({a:1,b:2}.with_indifferent_access)                                                                                                                                 
{
  "a": 1,
  "b": 2
}
=> nil
[4] pry(main)> Oj.mimic_JSON                                                                                                                                                                                
=> JSON
[5] pry(main)> puts JSON.pretty_generate({a:1,b:2}.with_indifferent_access)                                                                                                                                 
{"a":1,"b":2}
=> nil
[6] pry(main)>                                
```

**Comment by ohler55** [comment]
Ok, I've run into a problem. You have found a place where the json gem does one thing and Rails does another. With just the json gem the formatting arguments used by pretty_generate are honored. I just Rails or Rails after the json gem then the formatting is not used. Of course to get the with_indifferent_access you need to require 'active_support/core_ext/hash/indifferent_access' which implies the use of Rails. I'm not sure if Oj will be able to handle the various combinations of the json gem and rails combinations. Can you tell me how you are using the two to make sure we are seeing the same behavior?

**Comment by palexvs** [comment]
> Can you tell me how you are using the two to make sure we are seeing the same behavior?

Sorry, I don't understand the question

I created a test env to reproduce the issue: https://github.com/palexvs/oj_test
```
git clone git@github.com:palexvs/oj_test.git
bundle install
rails console
development >> puts JSON.pretty_generate({a:1,b:2}.with_indifferent_access)
{
  "a": 1,
  "b": 2
}

development >> require 'oj'
development >> Oj.mimic_JSON  

development >> puts JSON.pretty_generate({a:1,b:2}.with_indifferent_access)
{"a":1,"b":2}
```

**Comment by ohler55** [comment]
That should be enough to reproduce the order things are loaded in. Thanks.

**Comment by ohler55** [comment]
I push a fix on the args2 branch. Instead of using a Hash for options a State instance is used. That seems to make the to_json method used by the with_indifferent_access object format as expected.

**Comment by palexvs** [comment]
Hi @ohler55 , 
it's great, I really appreciate it. I checked `args2` and it works for me

Thank you

**Comment by palexvs** [comment]
There is just one issue: OJ does not convert `ActionController::Parameters` into `json` anymore. 
Was:
```
> params.to_json
  {
    "api_key": "....",
    "api_version": "...",
    ....
  }
```

Now:
```
> params.to_json
"#\u003cActionController::Parameters:0x007fdd8ef26a20\u003e"
```

I will create test env tomorrow if you need.


Thank you

**Comment by ohler55** [comment]
If the original issue is resolved I will make a release so this issue can be closed. If there is another issue then there should be a new issue created. Please include the steps to reproduce as I tried creating an ActionController::Parameters and it seems to work find with Oj.mimic_JSON and after calling Oj::Rails.set_encoder. If you try to optimize the output is different but still a JSON object and not a string.

**Comment by palexvs** [comment]
Ok. Thank you. Should I wait till 3.0.7 is released or close now?

I will not create a new issue, it's just for your information:
`JSON.pretty_generate` and `ActionController::Parameters` with different OJ and RoR versions:
```
puts JSON.pretty_generate ActionController::Parameters.new({person: {name: "Francesco", age:  22, role: "admin"} })

# Rails 5.0.2
=> JSON::GeneratorError: only generation of JSON objects or arrays allowed
# Rails 5.0.2 + OJ 3.0.7
=> "#\u003cActionController::Parameters:0x007fb2a2bb5290\u003e"
# Rails 5.0.2 + OJ 3.0.6
=> {"person":{"name":"Francesco","age":22,"role":"admin"}}
# Rails 5.0.2 + OJ 2.18.5
=> {
  "person": {
    "name": "Francesco",
    "age": 22,
    "role": "admin"
  }
}

# Rails 5.1.0
=> JSON::GeneratorError: only generation of JSON objects or arrays allowed
# Rails 5.1.0 + OJ 2.18.5
ActionController::UnfilteredParameters: unable to convert unpermitted parameters to hash
# Rails 5.1.0 + OJ 3.0.6
{"person":{"name":"Francesco","age":22,"role":"admin"}}
# Rails 5.1.0 + OJ 3.0.7
puts JSON.pretty_generate params
"#\u003cActionController::Parameters:0x007f8019d9cf10\u003e"
```

**Comment by ohler55** [comment]
Wait until the release to close. I'll do it tonight.

The rails, json gem combination can create completely different results depending on many factors. Quite a mess. I've been thinking about setting up an alternative. Keep on eye on out in the next month or so. I might start an effort to come up with a simpler, faster, and more consistent framework. I do have some ideas and code to jump start that.

**Comment by palexvs** [comment]
Thanks!
