### ISSUE TITLE
Add optimize_rails

### ISSUE THREAD

**Issue by stereobooster** [ohler55/oj#378]
As discussed in https://github.com/stereobooster/ruby-json-benchmark/pull/2

Additionally I would discourage from using `Oj::Rails.encode`. From my POV this expose unnecessary entry point (as of speed Oj::Rails.encode and Oj.dump pretty close). What do you think?

**Comment by ohler55** [comment]
Glad to add the optimize_rails method. IMHO Oj::Rails::encode more clearly describes that rails encoding should be used as apposed to dump. If it was a clean slate I would say that all rails related calls would be in the Oj::Rails module for cleanliness and there would be no mode option exposed to the user. But it is not a clean slate and others such as yourself have different options. At this stage two entry points to rails encoding seem like a pretty minor difference of opinion. Lets leave that alone for now.

**Comment by ohler55** [comment]
Added so it should go into the next release.

**Comment by ohler55** [comment]
Just released 3.0.6.

**Comment by stereobooster** [comment]
Thanks
