### ISSUE TITLE
RuntimeError for Activerecord encode

### ISSUE THREAD

**Issue by stereobooster** [ohler55/oj#379]
Rails 4.1.16, ruby 2.2.6, Oj 3.0.6

```
START gemfile: gemfiles/4.1.16.gemfile rvm: 2.2.6
bundle install --deployment --path /ruby-json-benchmark/vendor/bundle --quiet
bundle exec ruby compatibility_test.rb

Comparing Rails to_json with other JSON implementations
+---------------------------------+--------------+---------+------------------+------------+-----------------+
| class                           | JSON to_json | Oj.dump | Oj::Rails.encode | Oj to_json | msgpack "rails" |
+---------------------------------+--------------+---------+------------------+------------+-----------------+
| ToJson                          | 👌           | ❌      | ❌               | 👌         | ❌              |
| ActiveRecord                    | ❌           | 💀      | 👌               | 👌         | 👌              |
+---------------------------------+--------------+---------+------------------+------------+-----------------+
```

```
/projects/ruby-json-benchmark/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.16/lib/active_record/serialization.rb:14:in `serializable_hash': can't modify frozen Hash (RuntimeError)
  from /projects/ruby-json-benchmark/vendor/bundle/ruby/2.2.0/gems/activemodel-4.1.16/lib/active_model/serializers/json.rb:99:in `as_json'
  from /projects/ruby-json-benchmark/lib/helper.rb:51:in `dump'
  from /projects/ruby-json-benchmark/lib/helper.rb:51:in `block in test_oj_dump'
  from /projects/ruby-json-benchmark/lib/helper.rb:48:in `each'
  from /projects/ruby-json-benchmark/lib/helper.rb:48:in `test_oj_dump'
```

**Comment by stereobooster** [comment]
From https://github.com/ohler55/oj/issues/378
> MHO Oj::Rails::encode more clearly describes that rails encoding should be used as apposed to dump. If it was a clean slate I would say that all rails related calls would be in the Oj::Rails module for cleanliness and there would be no mode option exposed to the user. But it is not a clean slate and others such as yourself have different options. At this stage two entry points to rails encoding seem like a pretty minor difference of opinion. Lets leave that alone for now.

My argument is that `Oj::Rails.encode` is another entry point and this is potential source of bugs. I expect (other developers? or I'm alone on this) that `Oj.dump(mode: rails)` is the same as `Oj::Rails.encode`. This is the second bug where behaviour deviates.

**Comment by ohler55** [comment]
The reason the two tests are different is that you are not passing the OJ_RAILS options to Oj::Rails.encode() but you are to Oj.dump().

It does bring up an interesting observation. It appears that the ActiveSupport serializable_hash does not follow the ActiveSupport JSON guidelines as it modifies the options hash.

**Comment by stereobooster** [comment]
I didn't expect that options passed to `Oj.dump` will be passed to `as_json` function. I know about the specification, but those options are not intended for as json from my POV. Not sure on this

**Comment by ohler55** [comment]
They kind of have to be passed. That is the only way to get them to the as_json or to_json.

**Comment by ohler55** [comment]
To be clear, the exception raised was due to ActiveSupport 4 not following the guidelines and attempting to modify the passed in options hash.

**Comment by ohler55** [comment]
I'd like to get this closed. Since the failure was due to different arguments being passed in to the respective functions the test as it was originally is not a reasonable comparison.

The failure in ActiveSupport 4 was due to a failure of the ActiveSupport as_json methods to follow the as_json guidelines and is fixed in ActiveSupport 5. The work around is not to pass in frozen options.

Also related to this is https://github.com/stereobooster/ruby-json-benchmark/issues/3.

**Comment by stereobooster** [comment]
I do understand that `Oj::Rails.encode(obj, params)` is to equivalent to `obj.to_json(params)`.
It is counterintuitive that `Oj.dump(params)` is not equivalent to `obj.to_json`. This is one of the edge cases when this is not a bug, but it seems to be one

**Comment by ohler55** [comment]
Yeah, still have to pass the parameters somehow. There is some twists and turns getting Oj, json gem, and Rails to all play together.
