### ISSUE TITLE
Oj.optimize_rails changes precision of Float#to_json

### ISSUE THREAD

**Issue by obrie** [ohler55/oj#383]
Oj's float precision doesn't appear to match ActiveSupport's.  This has been tested on AS 4.x / 5.x and Oj 3.0.7.  Example:

```ruby
$ irb
2.3.0 :001 > require 'json'
 => true 
2.3.0 :002 > 1494506397.4445422.to_json
 => "1494506397.4445422" 
2.3.0 :003 > require 'active_support/all'
 => true 
2.3.0 :004 > 1494506397.4445422.to_json
 => "1494506397.4445422" 
2.3.0 :005 > require 'oj'
 => true 
2.3.0 :006 > Oj.optimize_rails
 => nil 
2.3.0 :007 > 1494506397.4445422.to_json
 => "1494506397.444542" 
```

As an additional data point, `Oj.mimic_JSON` doesn't have this problem:

```ruby
2.3.0 :001 > require 'json'
 => true 
2.3.0 :002 > 1494506397.4445422.to_json
 => "1494506397.4445422" 
2.3.0 :003 > require 'oj'
 => true 
2.3.0 :004 > Oj.mimic_JSON
 => JSON 
2.3.0 :005 > 1494506397.4445422.to_json
 => "1494506397.4445422" 
```

**Comment by ohler55** [comment]
Just pushed the 'details' branch with the fixes for this and the Hash issue. If looks okay I'll make a new release.

**Comment by obrie** [comment]
That branch appears to fix this issue after running the above test against it -- thanks!

**Comment by julian-berbel** [comment]
Sorry for commenting on an old issue, but I'm observing this exact behavior on oj 3.16.10 and rails 7.0.8.1.
Has there been a regression?

**Comment by ohler55** [comment]
This issue re-appears with every new version of Ruby and Rails. If you are using the latest Oj::Parser you can set the parser to use Ruby for float parsing which will give you exactly what Ruby would return. If using the original parsers then there isn't much that can be done to get more than 16 place precision out of a 64 bit float.
