### ISSUE TITLE
JSON.dump changes behavior of handling invalid UTF-8 characters

### ISSUE THREAD

**Issue by obrie** [ohler55/oj#384]
Oj's handling of invalid UTF-8 characters doesn't appear to match JSON's when using `Oj.mimic_JSON`.  

Ruby 2.4.0:
```
2.4.0 :001 > require 'json'
 => true 
2.4.0 :002 > JSON.generate("Test L\xE4nder/16")
JSON::GeneratorError: source sequence is illegal/malformed utf-8
	from /home/aaron/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/json/common.rb:224:in `generate'
	from /home/aaron/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/json/common.rb:224:in `generate'
	from (irb):2
	from /home/aaron/.rvm/rubies/ruby-2.4.0/bin/irb:11:in `<main>'
```

Oj.mimic_JSON:
```
2.3.0 :001 > require 'json'
 => true 
2.3.0 :002 > require 'oj'
 => true 
2.3.0 :003 > Oj.mimic_JSON
 => JSON 
2.3.0 :004 > JSON.generate("Test L\xE4nder/16")
 => "\"Logo Quiz nach L\xE4nder/16\"" 
```

Note that in Ruby 2.4.0 and with Oj.mimic_JSON, both are able to parse Oj's generated json.

Since an exception is no longer being raised on `generate`, the data is getting passed into other applications in our infrastructure and causing issues when they attempt to re-generate the json (since they don't use `oj`).

Any suggestions as a workaround / fix?

**Comment by obrie** [comment]
As an additional data point, ActiveSupport's JSON is capable of generating the JSON:

```
[1] pry(main)> "Test L\xE4nder/16".to_json
=> "\"Test L\xE4nder/16\""
```

-- so this logic would only apply to `mimic_JSON`.

**Comment by ohler55** [comment]
I'll take a look. The behavior of the son gem varies depending on the method used to encode so I'll make sure tests are added over and above the gems unit tests.

**Comment by ohler55** [comment]
Ready for testing on the details branch.

**Comment by obrie** [comment]
Looks great!  This was the last blocker to swapping in oj in our app.  Thanks for the quick turnaround!

**Comment by ohler55** [comment]
Released

**Comment by obrie** [comment]
:clap: Nicely done!

**Comment by ohler55** [comment]
Thanks for the help tightening up Oj.

**Comment by obrie** [comment]
@ohler55 we just ran into some more invalid UTF-8 characters that Ruby's JSON catches but Oj doesn't on v3.0.8.  Example:

```
2.3.0 :001 > require 'json'
 => true 
2.3.0 :002 > JSON.dump("L\xE2m ")
JSON::GeneratorError: source sequence is illegal/malformed utf-8
	from /home/aaron/.rvm/gems/ruby-2.3.0/gems/json-1.8.6/lib/json/common.rb:223:in `generate'
	from /home/aaron/.rvm/gems/ruby-2.3.0/gems/json-1.8.6/lib/json/common.rb:223:in `generate'
	from /home/aaron/.rvm/gems/ruby-2.3.0/gems/json-1.8.6/lib/json/common.rb:394:in `dump'
	from (irb):2
	from /home/aaron/.rvm/rubies/ruby-2.3.0/bin/irb:11:in `<main>'
2.3.0 :003 > require 'oj'
 => true 
2.3.0 :004 > Oj.mimic_JSON
 => JSON 
2.3.0 :005 > Oj::VERSION
 => "3.0.8" 
2.3.0 :006 > JSON.dump("L\xE2m ")
 => "\"L\xE2m \"" 
```

**Comment by obrie** [comment]
Actually I just realized that the `master` branch doesn't appear to have the utf-8 fixes.  I tested this against both the `details` branch and v3.0.8 to verify and they both exhibit the same behavior.

**Comment by ohler55** [comment]
Odd, master passes the tests added to test_compat.rb. I'll dig into it and see what is going on. I see you are using \xE2 and not \xE4 so maybe that has something to do with it.

**Comment by ohler55** [comment]
I can verify it was an issue with E2 which is a special case for unicode U+2048 and U+2049. I will release a fix tonight.

**Comment by ohler55** [comment]
The E2 codes are covered in the latest master. If they work for you I'll do a release.

**Comment by obrie** [comment]
Thanks!  I'm on vacation until Monday, so we'll try the latest master changes in our app at that point and evaluate for 24h (that's about how long it took for one the E2 scenario to show up).

**Comment by ohler55** [comment]
I'll release tomorrow regardless then. Just waiting for a heck on another issue.

**Comment by ohler55** [comment]
Released

**Comment by ohler55** [comment]
Can this be closed?

**Comment by obrie** [comment]
We started an evaluation this morning and will be running a test for 24 hours to see if we experience another occurrence of the error.  Happy to close now or tomorrow morning when the test completes.

**Comment by ohler55** [comment]
Might as well see the results on completion first.

**Comment by obrie** [comment]
Looks good to us!

**Comment by ohler55** [comment]
Great, thanks.
