### ISSUE TITLE
Explicit type check on parse parameter

### ISSUE THREAD

**Issue by paradox460** [ohler55/oj#386]
Currently, when running in `mimic_json` or `rails` mode, Oj appears to do a hard-check on the argument passed to `JSON.parse`, and raises an `ArgumentError` if it is not a `String` or `IO` object.

This is a deviation from the standard lib `JSON.parse`, which allows for any string-like or IO-like object. Many gems and libraries have used (abused?) this feature.

----

Test case:

```ruby
require 'oj'

Oj.mimic_JSON
Oj.add_to_json

class StringPlus
  
  def initialize(str)
    @str = str
  end
  def to_str
    @str
  end
  alias to_s to_str
end

test_str = StringPlus.new('{"testing": 123}')
JSON.parse(test_str)
```

**Comment by ohler55** [comment]
Ouch, ok, I'll test the json gem and update Oj in mimic mode to handle that with a call to ```to_s``` and check for what ever IO methods are needed before that.

**Comment by paradox460** [comment]
Great! Thanks for the fast response!

**Comment by ohler55** [comment]
Might take a day or two.

**Comment by jklimke** [comment]
I guess this is more ore less the same issue i experienced when a library tried to encode nil to json, a TypeError was raised instead of returning 'null' as the standard implementation does.

**Comment by ohler55** [comment]
or maybe less. :-) please try the latest master.

**Comment by ohler55** [comment]
3.0.9 released

**Comment by paradox460** [comment]
Checking it now, preliminary test seem to indicate success

**Comment by ohler55** [comment]
Can this be closed?

**Comment by paradox460** [comment]
Yep, sorry, it works perfectly!
