### ISSUE TITLE
Does the 3.0.9 gem need to be pushed?

### ISSUE THREAD

**Issue by Jehops** [ohler55/oj#387]
I last version I see on rubygems.org is 3.0.8.  Does something need to be pushed?

**Comment by Jehops** [comment]
Now I see that 3.0.9 is just referenced in the Changelog, but no 3.0.9 release has been made.

**Comment by ohler55** [comment]
You are too impatient. I pushed it last night and am waiting for feedback on two issues. It will be pushed tonight.

**Comment by Jehops** [comment]
No intention to rush you.  I was just confused by the 3.0.9 note in the Changelog.
