### ISSUE TITLE
Oj.add_to_json() not taking effect with Rails 5.0 & 5.1

### ISSUE THREAD

**Issue by mipearson** [ohler55/oj#388]
A fairly wild goose chase of debugging why my JSON generation was so slow despite using Oj led me here.

`Oj.add_to_json` does not appear to replace the ActiveSupport::JSON `.to_json` methods as expected, according to my benchmarks. I had a look at the source but my C (especially Ruby C binding knowledge) isn't strong enough to work out why.

I've created a repository to demonstrate this, more info there: https://github.com/mipearson/jsontest

**Comment by ohler55** [comment]
I'll check it tomorrow and see what is going on. I am suspicious though since ActiveSupport usually skips the to_json methods in favor of as_json. Also for rails look at setting the active support encoded and decoder. http://ohler.com/oj/doc/file.Rails.html

**Comment by mipearson** [comment]
Diving further, it's not limited to Rails - it doesn't seem to be using Oj's version of to_json if the JSON gem is loaded at all, regardless of whether I call add_to_json.

Will try additional versions of Ruby to see if it's that ..

**Comment by ohler55** [comment]
If you load the json gem after Oj.mimic_JSON the json gem will over-write the to_json methods. Either don't load the json gem or call Oj.mimic_JSON after.

If you are using Rails then it uses ActiveSupport::JSON.encode so setting the ActiveSupport encoder by calling Oj.optimize_rails will make calls to ActiveSupport::JSON.encode will use Oj. That is the normal way Rails encodes objects into JSON.

**Comment by ohler55** [comment]
BTW, I am very willing to work with you to get the benchmarks working so lets keep going.

**Comment by mipearson** [comment]
Hi,

Thanks for looking in to this - have a look at the `benchmark_json.rb` script in the repo linked: JSON is being required before `Oj.mimic_JSON` is called, and `Oj.optimize_rails` is being called.

**Comment by ohler55** [comment]
Some comments:

1. Line 15. It would be better to just call ```Oj::Rails.set_encoder()```
2. Line 50 and 51, both those should be calling Oj.
3. Benchmark runs multiple times. Once Oj.mimic_JSON is called it is the one being called for the JSON gem is not getting exercised.

**Comment by mipearson** [comment]
(1) This was a deliberate test of the exact code mentioned at the linked blog post. Also, it was my understanding that `Oj.optimize_rails` would call that for you
(2) I wanted to confirm that calling `Oj.mimic_JSON` affected the performance of `JSON.dump` and `.to_json`. If I load the JSON gem first, it improves the performance of `JSON.dump` but not `.to_json`. If the JSON gem is not loaded at all it works as expected.
(3) You might be thinking of `bmbm` - from the docs `.bm` only runs once

I might need to rewrite the benchmark to be more explicit and be able to be run once. As I've been exploring the problem space I've been adding more and more options which has made it much harder to follow what's happening.

**Comment by ohler55** [comment]
1. By doing the steps you take starting at line 15 you force the calling of value.as_json. You also force more ruby calls making it slower. So in line 59 you remove the optimized Oj encoder.
2. I see line 45 calling to_json before Oj.mimic_JSON is called and line 51 being called after mimic. Are you seeing line 51 not using Oj?
3. Ok, I haven't used Benchmark enough I guess.

**Comment by ohler55** [comment]
I forgot to mentions, Oj.add_to_json is similar to the json gem require 'json/add/Rational' (or some other class) so since you are not doing that it is better not to call Oj.add_to_json since the output will be different.

**Comment by mipearson** [comment]
Closing in favour of #391
