### ISSUE TITLE
Oj.mimic_JSON don't work

### ISSUE THREAD

**Issue by yosiat** [ohler55/oj#390]
Hi,

Looks like I am doing something wrong, but I can't understand it.

In my rails code, I have initializers who calls `Oj.mimic_JSON` and a `byebug` in active support `to_json` alias.
In my rails console I do the next:
```
> [1,2,3].to_json
.. byebug opens up in active support json encoder ..
> Oj.mimic_JSON
> [1,2,3].to_json
.. byebug opens up in active support json encoder ..
```
What am I doing wrong?

- Rails 4.2.8
- Ruby 2.3.3
- Oj 2.18.1

**Comment by ohler55** [comment]
I'm not sure what the issue is. It appears as if Oj in mimic mode is doing the same as the json gem.

If you are looking for compatibility Oj 3.0.9 is a far better choice.

**Comment by yosiat** [comment]
@ohler55 I expect that when I call `Oj.mimic_JSON` any further calls after that to `to_json` will pass through Oj and not in active support.

In the example I show:

1. I call `to_json` on array and active support serializers it
2. I call `to_json` on array after Oj.mimic_JSON and still active support serializers it and not Oj

**Comment by ohler55** [comment]
Very important that you use the 3.x version of Oj and 3.0.9 is the most recent with 3.0.10 today or tomorrow depending on issues. The 2.x versions will not mimic nearly as well and there are cases where rails encoders will be used and not Oj in the older versions.

Once using Oj 3.0.9, the guidelines for an ActiveSupport encoder is that it runs the as_json methods if they exist. The Oj Rails encoder does that unless Oj::Rails.optimize is called for that class or optionally the class is one of the default supported and then a call to Oj::Rails.optimize with argument will include it. What that means is Oj lets you decide which class to not use the as_json method.

I wish it weren't so horribly twisted but that is the nature of the json gem and Rails.

**Comment by yosiat** [comment]
@ohler55 just to make sure Oj 3.0.9 and Rails.optimize works with Rails 4.2.8? I thought they are rails 5 related

**Comment by ohler55** [comment]
It will work but the unit tests are the Rails 5 unit tests. Rails changed a little from 4 to 5 so some of the tests don't pass in 4. Not something most people would notice.

**Comment by yosiat** [comment]
@ohler55 Thanks, so I will try to upgrade to the new Oj.

**Comment by ohler55** [comment]
How did th upgrade go? Still having issues?

**Comment by yosiat** [comment]
@ohler55 it actually didn't work.. haven't had the time to investigate this.
I am using active_model_serializers (0.9.7) and instead of returning an array I got to_s of ArraySerializer.

**Comment by ohler55** [comment]
When you are ready the next step is seeing what calls you are making to setup Oj. Oj.optimize_rails should be all you need.

**Comment by yosiat** [comment]
@ohler55 AMAZING!
Looks like I did something too silly over there =X

Upgraded :)

**Comment by yosiat** [comment]
@ohler55 The only problem I see is activerecord object `to_json` goes to -
```
=> ["/Users/yosi/code/backend/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/core_ext/object/json.rb", 31]
```

**Comment by ohler55** [comment]
If you are calling to_json and want to use Oj then call Oj.mimic_JSON after requiring Oj. Al call Oj.optimize_rails.

**Comment by yosiat** [comment]
@ohler55 use `mimic_JSON` with `optimize_rails` ?
If I do this I get this as response -
 `"#\u003cActiveModel::ArraySerializer:0x007fb0bb303630\u003e"`

And If I use only `mimic_JSON` the `to_json` still goes to active support -
```
> MyModel.last.method(:to_json)
=> #<Method: MyModel(Object)#to_json(to_json_with_active_support_encoder)>
```

**Comment by ohler55** [comment]
Did just calling Oj.optimize_rails() works as you expected?

**Comment by yosiat** [comment]
@ohler55
`Oj.optimize_rails` does work.

But it dosesn't help me if `to_json` / `JSON.parse` don't go to Oj

**Comment by ohler55** [comment]
The rails to_json call the active support encoder so you lose a little due to the handover from active support to Oj but that is not that large.

The parse is tricker. I think rails calls ActiveSupport::JSON.decode most of the time which will use Oj. If you are calling JSON.parse directly then you are correct, no Oj without mimic being called.

How are you set up? Rails or JSON calls directly?

**Comment by yosiat** [comment]
I am using both:

- API responses that uses ActiveModelSerializers (0.9.7)
- Serializing ActiveRecord object with `to_json` for redis
- Using `JSON.parse` to parse payload from message queue

**Comment by ohler55** [comment]
For the message queue can you just use Oj directly?

**Comment by yosiat** [comment]
@ohler55 let's say I use Oj directly for message queue, and I only call `Oj.optimize_rails` how do I solve ActiveRecord `to_json`?

**Comment by ohler55** [comment]
ActiveRecord should use ActiveSupport.encode which should use Oj after calling Oj.optimize_rails.

**Comment by yosiat** [comment]
@ohler55 Oh, I see thanks!

**Comment by ohler55** [comment]
Keep me up to date. One way or another we will get this working.

**Comment by yosiat** [comment]
@ohler55 I use `optimize_rails` and I see ActiveRecord is indeed using Oj encoder.
But I want `JSON.parse` to go to Oj - since I am using third party libraries that I can't control.

It would be great to use `Oj.mimic_JSON` and `Oj.optimize_rails` together.

**Comment by ohler55** [comment]
Let me see if I can describe this correctly.

1. The to_json should not use the json gem version of to_json but should use the rails version that calls Oj.
2. JSON.parse should use the Oj rails decoder which is pretty close to the json gem behavior. Basically JSON.parse should be the same as ActiveSupport::JSON.decode.

Correct?

**Comment by yosiat** [comment]
@ohler55 sounds correct. to sum it all - everything should use Oj :)

**Comment by ohler55** [comment]
The tricky part is when Oj should be like rails and when it should be like the json gem.

**Comment by ohler55** [comment]
Maybe Oj.optimize_rails should also mimic JSON but not change the to_json monkey patches.

**Comment by ohler55** [comment]
I am working on a de-3.1.0 branch now. I haven't added tests but you are welcome to try it out. If you call just Oj.optimize_rails it should also set up JSON correctly.

**Comment by yosiat** [comment]
@ohler55 did simple testing, which failed before and now it works :)
once 3.1.0 will be out I'll upgrade in my prod :)

**Comment by ohler55** [comment]
Ok, a few unit tests and then a release later tonight.

**Comment by ohler55** [comment]
Ok, released.

**Comment by ohler55** [comment]
Ok to close?

**Comment by yosiat** [comment]
@ohler55 Yes, deployed 3.1.0 to my production and it works great!

**Comment by ohler55** [comment]
The JSON gem and Rails encode and decode JSON differently. Both change the `to_json` methods. Oj attempts to get all the combination correct but there are edge cases where it might not when both are used. In general, if using rails just call `optimize_rails`.

**Comment by KelseyDH** [comment]
@ohler55  It seems like this might be the reason?  https://precompile.com/2015/07/25/rails-activesupport-json.html

**Comment by ohler55** [comment]
That is a valid way to force the use of Oj. People have taken a number of approaches. Nice to see Oj in use.
