### ISSUE TITLE
Oj::Rails.optimize does not include Hash

### ISSUE THREAD

**Issue by mipearson** [ohler55/oj#391]
Found this while investigating #388 further and during direct discussion with @ohler55.

If you run Rails and you call `Oj::Rails.optimize`, then `Oj::Rails.encode`, `.to_json` and `ActiveSupport::JSON.encode` remain about 20 times slower when using a 168kb heavily nested example:

```
# require 'config/application'
# Oj.rails_optimize

 Oj.dump(X, :object)    989.980  (± 9.2%) i/s -      1.034k in   1.053496s
 Oj::Rails.encode(X)     37.770  (± 5.3%) i/s -     39.000  in   1.035666s
           X.to_json     35.860  (± 8.4%) i/s -     36.000  in   1.011829s
  AS::JSON.encode(X)     37.480  (± 5.3%) i/s -     39.000  in   1.043320s
```

However, if I manually add `Hash` to the list of optimized classes, this improves significantly:

```
# require 'config/application'
# Oj.rails_optimize
# Oj::Rails.optimize(Hash)

 Oj.dump(X, :object)    996.154  (± 6.0%) i/s -      1.078k in   1.086334s
 Oj::Rails.encode(X)    821.916  (± 2.9%) i/s -    840.000  in   1.022892s
           X.to_json    822.809  (± 6.2%) i/s -    830.000  in   1.012849s
  AS::JSON.encode(X)    832.649  (± 5.4%) i/s -    891.000  in   1.073304s
```

@ohler55 is aware of this issue and has a fix for it. I'm creating this issue so that others seeing this behaviour know that there's a workaround.

Please note, you also need to call `Oj.mimic_JSON` if you want `JSON.encode(x)` to use Oj, even if `.rails_optimize` is called, but I believe that this is by design and is working as intended.

If you'd like to reproduce my results and see my test example, see https://github.com/mipearson/jsontest

**Comment by obrie** [comment]
Is there an issue with optimizing `Hash` (i.e. any reason to not manually do this for the time being)?

**Comment by ohler55** [comment]
There was an issue with Hash and Array not being optimized when Oj::Rails.optimize was called with no arguments. With release 3.0.10 that is fixed. In any case calling Oj::Rails.optimize(Hash) works as intended.

**Comment by ohler55** [comment]
Can this be closed?

**Comment by mipearson** [comment]
Just ran 3.0.10 against my benchmark - confirmed fixed. Thank you! :)

**Comment by ohler55** [comment]
Thanks
