### ISSUE TITLE
Question: is GIL released while parsing?

### ISSUE THREAD

**Issue by prdn** [ohler55/oj#392]
Hello

really nice work with Oj.
Does Oj release the GIL while performing the parsing/encoding?
If so does it make sense to parse/encode in a separate thread?

Thanks

**Comment by ohler55** [comment]
Oj does not grab the lock so it would be possible. I have done some testing with that. It turns out the C part that can be in a different thread amounts 10% to 15% of the total and the overhead of passing data between the threads is greater than that. So possible but there is no advantage to it.

**Comment by prdn** [comment]
thanks for the infor @ohler55
