### ISSUE TITLE
Upgrade guide for 3.0.9 (from 2.8.15) ?

### ISSUE THREAD

**Issue by kapso** [ohler55/oj#393]
Is there such a guide/docs?

**Comment by ohler55** [comment]
There is not. What do you imagine it would cover? The changes are really an addition of the rails mode and making compat mode be more compatible. The only things I could think of are "don't use none-json-gem features with compat mode". Maybe, use rails mode for rails.

If you have some ideas let me know.

**Comment by ohler55** [comment]
Are you interested in pursuing this?

**Comment by ohler55** [comment]
Question answered. No responses since. Closing.
