### ISSUE TITLE
Nil not Allowed error

### ISSUE THREAD

**Issue by khelal** [ohler55/oj#394]
Hi, since upgrading to OJ 3.0.x, I've been having this consistent failure in my tests:

````
     Failure/Error: %li=link_to 'All', '#', class: 'document-filter', data: { filter_name: :category, filter_value: nil }

     ActionView::Template::Error:
       nil not allowed.
````

Any idea what's going on?

PS: I'm using Rails 4.2.6 and Ruby 2.3.4

**Comment by khelal** [comment]
Reverting to OJ 2.18.5 solved the problem.

````
./spec/controllers/v4/document_sets_controller_spec.rb:21
Run options: include {:locations=>{"./spec/controllers/v4/document_sets_controller_spec.rb"=>[21]}}
.
Finished in 3.46 seconds (files took 25.63 seconds to load)
1 example, 0 failures
````

**Comment by ohler55** [comment]
From the looks of the stack it appears you are not using Oj. To go much further we need to start either looking at the code for active support or try some different values in your test and see what works and what does not.

**Comment by khelal** [comment]
Hmm that's weird as the only change between the pass & fail in the test
suite is using OJ 3.0.9 or 2.18.5

**Comment by ohler55** [comment]
Could be that Oj is returning a nil value somewhere further upstream that causes the failure of active support fails. To help you debug I need more information though. All I know now is that you are using active support in some way. Do you have a test case you can share?

**Comment by brauliobo** [comment]
same here, very annoying, to reproduce just used `nil.to_json`

**Comment by brauliobo** [comment]
reverting to version 2.x also fixed here

**Comment by ohler55** [comment]
That nil.to_json helped a lot. In most combinations Oj returned "null" but is the steps are 

1. require 'rails' and require 'oj'
2. Oj.mimic_JSON
3. nil.to_json

If Oj.optimize_rails is called then Oj return "null". If rails is not required but just Oj.mimic_JSON is called the "null" is returned.

In the short term call Oj.optimize_rails and that should take care of the issue. I'll get a fix in place shortly.

**Comment by ohler55** [comment]
Please try the dev_3.0.11 branch.

**Comment by ohler55** [comment]
Well guys, does it work for you? If I don't hear in the next day I'll make the release anyway.

**Comment by ohler55** [comment]
Release has been made. Please verify.

**Comment by khelal** [comment]
Works for me now.i Thanks!
