### ISSUE TITLE
malloc error on 3.0.10

### ISSUE THREAD

**Issue by zarqman** [ohler55/oj#396]
I stumbled across a particular combination of instructions that trigger a malloc error and crashes ruby (using irb).

Oj 3.0.10 on Ruby 2.4.1 on macOS 10.12.5.

```
2.4.1 :001 > require 'oj'
 => true 
2.4.1 :002 > Oj.mimic_JSON
 => JSON 
2.4.1 :003 > Oj.default_options = {create_id: nil}
irb(8249,0x7fffa29923c0) malloc: *** error for object 0x10da97a90: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

If `create_id` is set to some other string first and then changed to nil, no error occurs.

**Comment by ohler55** [comment]
I'll get that fixed.

**Comment by ohler55** [comment]
Released a fix.

**Comment by zarqman** [comment]
Fix confirmed working here. Thanks for getting this resolved so quickly!

**Comment by ohler55** [comment]
Hard to leave something like that open. :-)
