### ISSUE TITLE
pretty_generate error on 3.1.x

### ISSUE THREAD

**Issue by trebor8x** [ohler55/oj#398]
Running `pretty_generate` on 3.0.10 works as expected:
```
JSON.pretty_generate({ 'a' => 1, 'b' => [true, false]})
=> "{\n  \"a\": 1,\n  \"b\": [\n    true,\n    false\n  ]\n}"
```

Switching to oj version 3.1.0 the following error is thrown:
```
JSON.pretty_generate({ 'a' => 1, 'b' => [true, false]})
NoMethodError: undefined method `new' for false:FalseClass
```

The current master throws an error as well. I am using oj in a rails project.
The file `config/initializers/oj.rb` contains:
```
Oj.optimize_rails
```

**Comment by ohler55** [comment]
Please try the dev-3.1.2 branch. If it works for you I will release later today.

**Comment by trebor8x** [comment]
Thanks for the prompt reply.
The dev-3.1.2. does indeed solve the issue.
Looking forward to the 3.1.2 release.
