### ISSUE TITLE
Oj.optimize_rails doesn't support symbolize_names

### ISSUE THREAD

**Issue by rzane** [ohler55/oj#400]
Is this the expected behavior?

```ruby
[1] pry(main)> Oj::VERSION
=> "3.1.3"
[1] pry(main)> Oj.optimize_rails
=> nil
[2] pry(main)> JSON.parse('{"foo": 1}', symbolize_names: true)
=> {"foo"=>1}
```

**Comment by ohler55** [comment]
The json gem supports :symbolize_names. Oj supports :symbol_keys or :symbolize_names.

**Comment by rzane** [comment]
Right, so if that's true shouldn't I see `{foo: 1}` instead of `{"foo"=>1}` above?

**Comment by ohler55** [comment]
Brain fart. Right. I looked quick and saw symbolize_keys.

**Comment by ohler55** [comment]
I'll get it fixed tonight

**Comment by rzane** [comment]
Awesome. Thanks!

**Comment by ohler55** [comment]
Forgot to initialize a variable when Oj::Rails.mimic_JSON was created. Master has the fix. I'll release shortly assuming tests pass.

**Comment by ohler55** [comment]
Released.

**Comment by rzane** [comment]
👍
