### ISSUE TITLE
Oj::StringWriter#push_value with ActiveRecord::Relation

### ISSUE THREAD

**Issue by nulty** [ohler55/oj#401]
Hi,

We've just upgraded our Oj version from `2.11.0` to `3.1.4`

We've come across one issue that we don't seem to be able to understand.

```
[1] pry(main)> sw = Oj::StringWriter.new    
=> #<Oj::StringWriter:0x00564c01f5c4d8>
[2] pry(main)> sw.push_object    
=> nil
[4] pry(main)> sw.push_key 'key'
=> nil
[6] pry(main)> tasks = Task.limit 1
  Task Load (0.3ms)  SELECT  `tasks`.* FROM `tasks` LIMIT 1
=> [#<Task:0x00564c01cb4438
  id: 1,
  person_id: 1,
  created_by_id: 2,
  body: "Add another Task",
  created_at: Tue, 07 Oct 2014 13:52:16 BST +01:00,
  updated_at: Wed, 08 Oct 2014 09:08:33 BST +01:00>]
[7] pry(main)> sw.push_value tasks
=> nil
[8] pry(main)> sw.pop
=> nil
[9] pry(main)> sw.to_s
=> "{\"key\":\"#<Task::ActiveRecord_Relation:0x00564c01de6518>\"}\n"
```
It appears that the `StringWriter` `#push_value` call `to_s` on the value.
```
[13] pry(main)> tasks.to_s
=> "#<Task::ActiveRecord_Relation:0x00564c01de6518>"
```

In previous versions of Oj this would have returned a correctly json serialized array containing the serialized Task class within.

```
"{\"key\":[{\"id\":1,\"person_id\":1,\"created_by_id\":2,\"body\":\"Add another Task\",\"created_at\":\"2014-10-07T13:52:16+01:00\",\"updated_at\":\"2014-10-08T09:08:33+01:00\"}]}"
```

Rails version: 4.2.8
Oj config: 
```
Oj.default_options = {:mode => :compat }
Oj.optimize_rails
```
Our temporary fix is to serialize the Relation before passing it to `#push_json`
```
tasks_json = tasks.to_json
sw.push_key 'tasks'
sw.push_json(tasks_json)
```

Any help would be appreciated.

**Comment by nulty** [comment]
Ps. thanks for your work on this library, well done on the progress so far!

**Comment by ohler55** [comment]
The bump from 3.0 to 3.1 was for a breaking change in the StringWriter and StreamWriter. It used to be that the :custom mode was used by default. Now the default is what ever the default mode is. Try either passing in the mode you want or setting the mode in the default_options.

**Comment by nulty** [comment]
Thanks @ohler55, I've initalized the StringWriter with `Oj::StringWriter.new(mode: :rails)` and the collection is serialized as expected

**Comment by ohler55** [comment]
Thanks.
