### ISSUE TITLE
Dump Date and DateTime objects as a string in custom mode

### ISSUE THREAD

**Issue by yolk** [ohler55/oj#402]
First of all thanks for your hard and much appreciated work!

When using v3.2.0 of Oj and dumping date and time objects I get the following output:

    >> Oj.dump(Date.today, mode: :custom, time_format: :xmlschema)
    => "{\"s\":\"2017-06-26\"}"
    >> Oj.dump(DateTime.now, mode: :custom, time_format: :xmlschema)
    => "{\"s\":\"2017-06-26T23:43:57+02:00\"}"
    >> Oj.dump(Time.now, mode: :custom, time_format: :xmlschema)
    => "\"2017-06-26T23:44:02.047807000+02:00\""

Is it possible to format the `Date` and `DateTime`-Object just as a string (like the `Time`)? I tried all the options, but it seems there isn't any to disable the output as a nested hash.

Thanks for any help!

**Comment by ohler55** [comment]
Time is a Ruby core class while Date and DateTime are not so they are treated like any other object class. There are two ways to get the Date and DateTime to be strings.

The easier way is to add an as_json method and turn on the :use_as_json option. Of course that means as_json will be called for all classes if they exist. With Rails they will.

An alternative approach is to use the ```Oj.register_odd()``` method. This performs better but I would not use it for hundreds of classes. A few or 10s should be fine.

**Comment by yolk** [comment]
Thanks for your quick help!

**Comment by ohler55** [comment]
If you still have problems let me know or shoot me an email.
