### ISSUE TITLE
Differences in NaN/Infinity handling in compat mode

### ISSUE THREAD

**Issue by GUI** [ohler55/oj#403]
In compat mode, Oj generates `NaN` and `Infinity` values in the JSON, which seems to differ from how the JSON gem's own `to_json` behaves (which raises an error).

Here's a quick demonstration in IRB of JSON's default behavior:

```ruby
> require "json"
=> true
> JSON::VERSION
=> "2.1.0"
> { "nan" => Float::NAN }.to_json
JSON::GeneratorError: 865: NaN not allowed in JSON
> { "infinity" => Float::INFINITY }.to_json
JSON::GeneratorError: 862: Infinity not allowed in JSON

# Interestingly, JSON.dump and JSON.generate behave differently, but from
# what I understand of the "compat" mode docs in Oj, it's aiming for "to_json"
# compatibility. But just for reference:
> JSON.generate({ "nan" => Float::NAN })
JSON::GeneratorError: 865: NaN not allowed in JSON
> JSON.generate({ "infinity" => Float::INFINITY })
JSON::GeneratorError: 862: Infinity not allowed in JSON
> JSON.dump({ "nan" => Float::NAN })
=> "{\"nan\":NaN}"
> JSON.dump({ "infinity" => Float::INFINITY })
=> "{\"infinity\":Infinity}"
```

And here's how Oj behaves in compat mode. Note that it doesn't raise an error:

```ruby
> require "oj"
=> true
> Oj::VERSION
=> "3.2.0"
> Oj.default_options = { :mode => :compat }
=> {:mode=>:compat}
> Oj.dump({ "nan" => Float::NAN })
=> "{\"nan\":NaN}"
> Oj.dump({ "infinity" => Float::INFINITY })
=> "{\"infinity\":Infinity}"

> Oj.mimic_JSON
=> JSON
> Oj.add_to_json
=> nil
> { "nan" => Float::NAN }.to_json
=> "{\"nan\":NaN}"
> { "infinity" => Float::INFINITY }.to_json
=> "{\"infinity\":Infinity}"
```

So does this seem like a bug in the "compat" mode of Oj, or am I mis-understanding the [compat docs](https://github.com/ohler55/oj/blob/master/pages/JsonGem.md), and is this correct (since it does seem to match JSON's `JSON.dump` behavior)?

I also tested this against JSON 2.0.3 (referenced in the docs as target compatibility version) with the same results.

**Comment by ohler55** [comment]
When using the :compat mode without having called Oj.mimic_JSON the default options are used. In particular the :nan option which is what you saw for one of your calls.

You did notice that the json gem is not consistent in behavior from one method to another. Oj attempts to mimic that behavior even if it does not seem correct. 

Calling to_json on an object without calling Oj.mimic_JSON will use the json gem code. Just something to keep in mind.

Finally, you did discover a bug. Even though the json gem unit tests passed that was not in the tests. I just pushed a dev3.2.1 branch to GitHub. Please give it a try. If it works for you I'll make a new release.

**Comment by ohler55** [comment]
Have you tried out the changes?

**Comment by GUI** [comment]
@ohler55, thanks for the super quick response!

This looks more consistent with the JSON gem now, although I'm still bumping into some slight issues, but they might be more related to MutliJson (I originally uncovered this due to a Rails app that used a Jbuilder template which was returning invalid JSON--and it looks like Jbuilder internally uses MultiJson). So I can take this up with the MultiJson folks, if you think it's more in their domain now, but this is what I'm seeing:

```ruby
> require "json"
=> true
> JSON::VERSION
=> "2.1.0"
> require "multi_json"
=> true
> MultiJson::VERSION
=> "1.12.1"
> MultiJson.adapter
=> MultiJson::Adapters::JsonGem
> MultiJson.dump({ "nan" => Float::NAN })
JSON::GeneratorError: 865: NaN not allowed in JSON

> require "oj"
=> true
> MultiJson.adapter = :oj
=> :oj
> Oj.mimic_JSON
=> JSON
> Oj.add_to_json
=> nil
> MultiJson.dump({ "nan" => Float::NAN })
=> "{\"nan\":NaN}"
```

So basically, out of the box, MultiJson might generate invalid JSON when used with Oj. I think this is because of the default options [they set](https://github.com/intridea/multi_json/blob/v1.12.1/lib/multi_json/adapters/oj.rb#L9) which amounts to calling `MultiJson.dump(obj, :mode => :compat, :time_format => :ruby, :use_to_json => true)`. It seems like the `:use_to_json` should possibly trigger this new behavior of raising an error, but according to the [option docs](https://github.com/ohler55/oj/blob/6ba8b8995170329e9709a2a7571b7096ebf11974/pages/Options.md#use_to_json-boolean) this isn't even a valid option for `:compat` mode.

I can make MultiJson raise an error on NaN/Infinity by flipping to a different mode (strict or custom):

```ruby
> MultiJson.dump_options = { :mode => :custom }
=> {:mode=>:custom}
> MultiJson.dump({ "nan" => Float::NAN })
```

But I haven't really dug around to then figure out what options I might need to set to better emulate `:compat` mode.

**Comment by ohler55** [comment]
The ```:use_to_json``` is an option for ```:compat``` mode. Try setting the ```:nan``` option to ```:raise```.

**Comment by GUI** [comment]
Oh, and I guess one further note/discovery, is that the JSON gem and MultiJson behave differently under Rails (at least Rails 4.2), where it seems to return null values instead of raising an errors. I never realized there were so many variations in behavior in all these libraries! But it does look like if I force Oj into Rails mode, then I do get similar outputs to what I get consistent outputs between Rails's default JSON handling and Oj (which I think might meet my specific use case):

```ruby
> require "json"
> require "active_support"
> require "active_support/core_ext/object/json"
> require "multi_json"
> JSON::VERSION
=> "2.1.0"
> ActiveSupport::VERSION::STRING
=> "4.2.9"
> MultiJson::VERSION
=> "1.12.1"
> MultiJson.adapter
=> MultiJson::Adapters::JsonGem
> { "nan" => Float::NAN }.to_json
=> "{\"nan\":null}"
> MultiJson.dump({ "nan" => Float::NAN })
=> "{\"nan\":null}"

> require "oj"
> Oj::VERSION
=> "3.2.1"
> Oj.dump({ "nan" => Float::NAN }, :mode => :rails)
=> "{\"nan\":null}"
> MultiJson.adapter = :oj
=> :oj
> MultiJson.dump_options = { :mode => :rails }
=> {:mode=>:rails}
> MultiJson.dump({ "nan" => Float::NAN })
=> "{\"nan\":null}"
```

**Comment by GUI** [comment]
> The :use_to_json is an option for :compat mode. Try setting the :nan option to :raise.

Hm, the [docs](https://github.com/ohler55/oj/blob/v3.2.0/pages/Options.md) seem to indicate not: "The option is ignored in the :compat and :rails mode." The docs also seem to indicate that the `:nan` option is ignored under compat mode: "Default is :auto but is ignored in the :compat and :rails mode."

These options don't seem to have any effect for me in compat mode on some quick tests:

```ruby
> require "oj"
=> true
> Oj.dump({ "nan" => Float::NAN })
=> "{\"nan\":3.3e14159265358979323846}"
> Oj.dump({ "nan" => Float::NAN }, :mode => :compat)
=> "{\"nan\":NaN}"
> Oj.dump({ "nan" => Float::NAN }, :mode => :compat, :use_to_json => true)
=> "{\"nan\":NaN}"
> Oj.dump({ "nan" => Float::NAN }, :mode => :compat, :use_to_json => true, :nan => :raise)
=> "{\"nan\":NaN}"
> Oj.mimic_JSON
=> JSON
> Oj.dump({ "nan" => Float::NAN }, :mode => :compat, :use_to_json => true)
=> "{\"nan\":NaN}"
> Oj.dump({ "nan" => Float::NAN }, :mode => :compat, :use_to_json => true, :nan => :raise)
=> "{\"nan\":NaN}"
```

**Comment by ohler55** [comment]
Honestly it took a lot of work to get Oj to mimic correctly with all the combinations. I used the unit tests for ActiveSupport and the json gem and still there are case such as the one you found that were not covered.

**Comment by ohler55** [comment]
The :use_to_json option just tells Oj to use the to_json method. It does not change the method. I would not expect much changes there unless you monkey patch Float.

I just pushed an update. I was setting the default after parsing the dump options. Give it another try. 
```Oj.dump({nan: Float::NAN}, mode: :compat, nan: :raise)```

**Comment by ohler55** [comment]
If you have not found any other issues I'd like to make a release today.

**Comment by ohler55** [comment]
Oj 3.2.1 released.

**Comment by ohler55** [comment]
Can this be closed?

**Comment by ohler55** [comment]
No response but unit tests for changes pass.
