### ISSUE TITLE
NoMethodError: undefined method `json_encoder=' for ActiveSupport:Module

### ISSUE THREAD

**Issue by stereobooster** [ohler55/oj#406]
Will try to track down error. Most likely happens due to order of loading

``` ruby
require "oj"
Oj.optimize_rails
```

**Comment by stereobooster** [comment]
Solution is to do like this:

```ruby
require "oj"
require "active_support/json/encoding"

Oj.optimize_rails
```

**Comment by ohler55** [comment]
Thanks @stereobooster.

**Comment by partounian** [comment]
This did not fix my issue

**Comment by ohler55** [comment]
@partounian if you have an issue, please open a new issue. This one has been closed for more than a year. Are you seeing the same `json_encoder` not being defined in the ActiveSupport module?
