### ISSUE TITLE
Object mode dumps a large TimeWithZone object in Rails

### ISSUE THREAD

**Issue by AlexCharlton** [ohler55/oj#409]
In a bare Rails 5.0.2 project (with ActiveSupport 5.0.2) and Oj 3.3.2

```
> Oj.dump(1.day.ago, mode: :object)
{"^o":"ActiveSupport::TimeWithZone","time":{"^t":"2017-07-26T18:43:04.864Z"},"time_zone":{"^o":"ActiveSupport::TimeZone","name":"UTC","utc_offset":null,"tzinfo":{"^o":"TZInfo::TimezoneProxy","identifier":"Etc/UTC","real_timezone":{"^o":"TZInfo::DataTimezone","info":{"^o":"TZInfo::ZoneinfoTimezoneInfo","identifier":"Etc/UTC","offsets":{"^#1":[0,{"^o":"TZInfo::TimezoneOffset","utc_offset":0,"std_offset":0,"abbreviation":":UTC","utc_total_offset":0}]},"transitions":[],"previous_offset":{"^o":"TZInfo::TimezoneOffset","utc_offset":0,"std_offset":0,"abbreviation":":UTC","utc_total_offset":0},"transitions_index":null}}}},"utc":null,"period":{"^o":"TZInfo::TimezonePeriod","start_transition":null,"end_transition":null,"offset":{"^o":"TZInfo::TimezoneOffset","utc_offset":0,"std_offset":0,"abbreviation":":UTC","utc_total_offset":0},"utc_total_offset_rational":null}}
```

This seems to happen no matter what combination of options I set, including different permutations of `:use_as_json`, `:use_to_json`, `:use_to_hash`, and `:time_format`.

I would hope that this would dump as a time object:

```
> Oj.dump(Time.now, mode: :object)
{"^t":"2017-07-27T11:45:39.075-07:00"}
```

What's worse is that, depending on other dependancies that are pulled in (which I have not fully identified), the resulting dumped object can grow as large as 40 kB!

**Comment by ohler55** [comment]
1.day.ago returns an ActiveSupport::TimeWithZone object not a Time object. Oj.dump() in :object mode has a specific format and dumps all attributes of the object being serialized. Pulling in additional gems that add to the TimeWithZone could make the number of attributes and what they point to very large and in some case could even create reference loops. That is the nature of ActiveSupport and associated gems. Monkey patching is the primary means of extending and it does make the system unpredictable. I would not recommend using the Object mode with ActiveSupport objects. Instead use the Oj rails related methods or only using :object mode on your own objects.

If you really want to get what you asked for then ```Oj.dump(1.day.ago.time, mode: :object)``` might be what you are looking for.

**Comment by AlexCharlton** [comment]
Ah, I had thought there may be some special handling of TimeWithZone. Thanks!
