### ISSUE TITLE
How can you tell if Oj is being used with active record or not?

### ISSUE THREAD

**Issue by lalitkapoor** [ohler55/oj#410]
Hi,

We're requiring the gem and we've called `Oj.optimize_rails()`. How can we confirm that calling `to_json` on an ActiveRecord object uses Oj?

Thanks!

**Comment by ohler55** [comment]
I haven't tried it but I think the Tracer (http://ruby-doc.org/stdlib-2.4.1/libdoc/tracer/rdoc/Tracer.html) looks like it should tell you what is called.

**Comment by ohler55** [comment]
Did that help? Can this be closed?

**Comment by lalitkapoor** [comment]
Hi Peter,

Sorry I didn't follow up sooner. Yes that helped! Thank you!

Yours,
Lalit
