### ISSUE TITLE
Oj::Rails.mimic_JSON() not compatible with standard JSON behavior?

### ISSUE THREAD

**Issue by sschepens** [ohler55/oj#412]
While parsing long floats, eg `'[1501775320000.0,0.16666582791856197]'`
JSON gem parses the second element as a `Float`, while after calling `Oj::Rails.mimic_JSON()` it begins parsing them as `BigDecimal`.

```ruby
j = '[1501775320000.0,0.16666582791856197]'
JSON.parse(j) 
#[1501775320000.0, 0.16666582791856197]
Oj::Rails.mimic_JSON()
JSON.parse(j) 
#[1501775320000.0, 0.16666582791856197e0]
```

**Comment by ohler55** [comment]
And what does the JSON gem do in that case? As soon as you mix both the JSON gem and Rails the results are likely to change. In addition, different version of the JSON gem or Rails will result in differences.

**Comment by sschepens** [comment]
The example shows it, whitouth including Oj, JSON gem returns a `Float`, when including Oj it starts returning BigDecimals

**Comment by ohler55** [comment]
Knowing you had already loaded Rails was helpful. Oj.mimic_JSON follows the JSON gem behavior but with Rails it reverts to using BigDecimal if the precision is too high unless Oj.mimic_JSON is also called. I'll change that so that calling Oj::Rails.mimic_JSON also makes that change. In the short term, just call Oj.mimic_JSON as well.

**Comment by ohler55** [comment]
Or you can try the master branch. If the unit tests pass I will make a release.

**Comment by sschepens** [comment]
I tried calling `Oj.mimic_JSON` as well but seemed o break everything somehow.
Will try from master

**Comment by ohler55** [comment]
Or the release 3.3.4

**Comment by sschepens** [comment]
Seems to work with `3.3.4`, thanks!

**Comment by ohler55** [comment]
👍
