### ISSUE TITLE
The : symbol parsing at the text beginning

### ISSUE THREAD

**Issue by mandarin6b0** [ohler55/oj#431]
The `:` symbol at the text beginning treated as symbol aka `:sym`
```ruby
[4] pry(main)> a = %q{ {"a": ":)"} }
=> "{\"a\": \":)\"}"
[5] pry(main)> Oj.load(a)
=> {"a"=>:")"}
[6] pry(main)> JSON.parse(a)
=> {"a"=>":)"}
[7] pry(main)> Oj.load(a)["a"]
=> :")"
[8] pry(main)> JSON.parse(a)["a"]
=> ":)"
```

version: 3.3.5

**Comment by ohler55** [comment]
If I were to guess, you are using the Oj :object mode. There is a description of the different Oj modes here: http://ohler.com/oj/doc/file.Modes.html

**Comment by mandarin6b0** [comment]
@ohler55 oh, you are right. Changing to another mode done the trick!
