### ISSUE TITLE
Hash.new with a block breaks after dumping and loading

### ISSUE THREAD

**Issue by evanleck** [ohler55/oj#443]
This may be too much of an edge case but I ran into it recently thought it might be worth mentioning.

I'm using Oj to dump objects into session and load them back out in a Rack application. One of those objects has a hash with a block to default values to empty arrays instead of `nil` but that behavior seems to get dropped after dumping and loading the hash. Check it out:

```ruby
require 'oj'

# A new hash that returns a new array by default.
h = Hash.new { |hash, key| hash[key] = [] }

# Check that our behavior is right.
puts h['a'].inspect # => []

# Dump and load.
x = Oj.load(Oj.dump(h))

# Behavior is now broken.
puts x['b'].inspect # => nil
```

I'm not even sure this is something you can detect but, like I said, I thought it was worth mentioning. Thanks for reading!

**Comment by ohler55** [comment]
There are several issues surrounding hash defaults. First is that the common hash to JSON mapping has no room for a default value. Thats not just with Oj but virtually all encoders. The second is tougher to get around. Even if there was some way of encoding the proc used in you example into JSON the `Hash#default=` method does not allow proc to be used as an argument.

I don't think the current behavior caan or should be changed at this point. It is an interesting observation though.

**Comment by evanleck** [comment]
Makes sense, and I kinda figured that there wasn't much to do about it. Thanks for responding anyway!

**Comment by sobrinho** [comment]
Can this be closed?

**Comment by evanleck** [comment]
I think so, yeah.
