### ISSUE TITLE
Dump of symbol[], each symbol element hash a :colon prefix.

### ISSUE THREAD

**Issue by mjacobus** [ohler55/oj#444]
The dump has a unexpected output IMO:

Version: oj-3.3.8

```ruby
Oj.dump([:foo]) # => "[\":foo\"]"
```

Instead of 

```ruby
Oj.dump([:foo]) # => "[\"foo\"]"
```

Is this the correct behaviour?

More info:

```ruby
[:foo].to_json              #=> "[\"foo\"]" # on rails
Oj.dump([:foo])          #=> "[\":foo\"]"
Oj.dump(:foo)             # => "\":foo\""
Oj.dump({ foo: :foo})  #=> "{\":foo\":\":foo\"}"
```

**Comment by ohler55** [comment]
It depends on the mode you are using. In the object mode that is expected. Change to strict or some other and it will probably be what you expect. Object mode is for encoding and decoding back to the same object type so it has a specific encoding. There is a page on that in the docs if you are interested.

**Comment by mjacobus** [comment]
Strict mode seems to have done it:

```ruby
Oj.dump([:foo], mode: :strict) # => "[\"foo\"]"
```

Thank you @ohler55 !
