### ISSUE TITLE
oj 3 mode compat and indent cause crash with nested Sequel::Postgres::JSONBHash

### ISSUE THREAD

**Issue by fdr** [ohler55/oj#446]
Took me a while to minimize this when upgrading OJ to version 3 from version 2, but here it is:

Sequel version is 4.49.0, but I think this may have more to do with use of `delegate.rb`....the `JSONBHash` object doesn't do a whole lot of stuff.

```ruby
Oj.dump({hello: Sequel::Postgres::JSONBHash.new({})}, {:mode=>:compat, :indent=>2})
TypeError: wrong argument type Integer (expected String)
from /home/fdr/.rbenv/versions/2.4.2/lib/ruby/2.4.0/delegate.rb:341:in `initialize'
```
However, these do not crash:
```ruby
> Oj.dump({hello: Sequel::Postgres::JSONBHash.new({})}, {:mode=>:compat})
=> "{\"hello\":{}}"

> Oj.dump({hello: Sequel::Postgres::JSONBHash.new({})}, {:indent => 2})
=> "{\n  \":hello\":{\n    \"^o\":\"Sequel::Postgres::JSONBHash\",\n    \"delegate_dc_obj\":{}\n  }\n}\n"
```

Finally, here are some comparisons between different versions and options to OJ doing the right or wrong thing.

```ruby
# Works perfectly on 2.x
puts Oj.dump({a: Sequel::Postgres::JSONBHash.new({hello: 'world'})}, {:mode=>:compat, :use_to_json => true, indent: 2 })
{
  "a":{
    "hello":"world"
  }
}

# Crashes on 3.x
puts Oj.dump({a: Sequel::Postgres::JSONBHash.new({hello: 'world'})}, {:mode=>:compat, :use_to_json => true, :indent => 2})
TypeError: wrong argument type Integer (expected String)
from /home/fdr/.rbenv/versions/2.4.2/lib/ruby/2.4.0/delegate.rb:341:in 'initialize'

# Works perfectly on 3.x. :indent => 2 has been removed.
puts Oj.dump({a: Sequel::Postgres::JSONBHash.new({hello: 'world'})}, {:mode=>:compat, :use_to_json => true})
{"a":{"hello":"world"}}
```

**Comment by ohler55** [comment]
When you say Oj crashes do you mean an exception is raised?

In 3.x the :compat mode more closely follows the JSON gem. The JSON gem will raise a TypeError when given an indent value that is not a string so Oj does the same when in :compat mode. It would not be compatible with the JSON gem if it did not.

When not in :compat mode indent can and should be a number. The default mode is not :compat.

What you are seeing is exactly the behavior that is expected.

**Comment by fdr** [comment]
I see. I didn't glean the change in type from the documentation, and `MultiJson` doesn't handle that. I'll file a bug over there.

**Comment by ohler55** [comment]
I did not see the use of MultiJSON in your example. I'm surprised MultiJSON does not handle it though since it supports the JSON gem. Maybe the drive just needs an update.

**Comment by fdr** [comment]
I didn't, because I read through the implementation and minimized through it, trying to remove layers.

**Comment by fdr** [comment]
Thanks for the correspondence. I'm sure it'll inform the MultiJson maintainers. Closing.
