### ISSUE TITLE
ActiveSupport.encode_big_decimal_as_string is ignored by Oj

### ISSUE THREAD

**Issue by ncr** [ohler55/oj#449]
I need to encode the decimals as floats in json and without Oj, I set the `ActiveSupport.encode_big_decimal_as_string` to `false` and I'm good to go. Oj seems to ignore this setting. Is there some other way to change this setting?

BTW. Oj is fantastic, memory footprint went 50% down and speed went an order of magnitude up in the app I'm working on :)

```
[4] pry(main)> ActiveSupport.encode_big_decimal_as_string
false
[5] pry(main)> {a: 1.1.to_d}.to_json
"{\"a\":1.1}"
[6] pry(main)> ActiveSupport.encode_big_decimal_as_string = true
true
[7] pry(main)> {a: 1.1.to_d}.to_json
"{\"a\":\"1.1\"}"
[8] pry(main)> require 'oj'; Oj.optimize_rails
nil
[9] pry(main)> {a: 1.1.to_d}.to_json
"{\"a\":\"1.1\"}"
[10] pry(main)> ActiveSupport.encode_big_decimal_as_string = false
false
[11] pry(main)> {a: 1.1.to_d}.to_json
"{\"a\":\"1.1\"}"
[12] pry(main)> Oj.default_options = { bigdecimal_as_decimal: true }
{
    :bigdecimal_as_decimal => true
}
[13] pry(main)> {a: 1.1.to_d}.to_json
"{\"a\":\"1.1\"}"
```

**Comment by ohler55** [comment]
Glad to hear of the performance improvements.

I just tried the option and you are correct. It did not use a string with either a true or false value. Oj should honor that option when in :object or :custom mode.

I'll get it fixed over the next week and do a release after you can confirm it is fixed.

**Comment by ohler55** [comment]
I've been digging into the issue and have some questions for you.

Will you be using this option with rails? It seems the attribute was removed or deprecated in rails 5. 

What Oj mode are you using? I've updated the custom mode in the 'bigdecimal' branch. Please see if it works for you.

**Comment by ncr** [comment]
Yes, I'm using it with Rails (4.x, but will move to 5.x at some point).
I do "Oj.optimize_rails" in Rails' initializers, and then
"ActiveSupport.encode_big_decimal_as_string = false".
I don't explicitly set any mode, should I?
If this option is deprecated and will disappear, then how would I control
the decimal encoding behavior? I use .as_json/.to_json directly and also
indirectly through AM::Serializers. I can of course do Oj.dump manually,
but it seems a bit cumbersome.



wt., 26 gru 2017 o 18:03 użytkownik Peter Ohler <notifications@github.com>
napisał:

**Comment by ohler55** [comment]
I was afraid you were using rails. The option is deprecated in rails 5 from what I can tell. Let me think about what issues might occur if I broke compatibility by making that option available.

**Comment by ohler55** [comment]
Ok, the default for Rails, as before is BigDecimals as a string. That can be over-ridden by setting the bigdecimal_as_decimal  to true. If it works for you I will make a new release.

**Comment by ncr** [comment]
I checked out the "bigdecimal" branch, I have the following in the Gemfile.lock, just to make sure I actually use the branch.

```
GIT
  remote: git://github.com/ohler55/oj.git
  revision: 69e0de7cb66f0f782b0ffd2ddeb0df133372f86c
  branch: bigdecimal
  specs:
    oj (3.3.10a2)
```

And the behavior:

```
Loading development environment (Rails 4.2.8)
[1] pry(main)> {a: 1.1.to_d}.to_json
"{\"a\":\"1.1\"}"
[2] pry(main)> ActiveSupport.encode_big_decimal_as_string = false
false
[3] pry(main)> {a: 1.1.to_d}.to_json
"{\"a\":1.1}"
[4] pry(main)> Oj.optimize_rails
nil
[5] pry(main)> {a: 1.1.to_d}.to_json
"{\"a\":\"1.1\"}"
[6] pry(main)> Oj.dump({a: 1.1.to_d})
"{\":a\":1.1}"
[7] pry(main)> Oj.default_options = { mode: :custom, bigdecimal_as_decimal: true }
{
                     :mode => :custom,
    :bigdecimal_as_decimal => true
}
[8] pry(main)> {a: 1.1.to_d}.to_json
"{\"a\":\"1.1\"}"
[9] pry(main)> Oj.dump({a: 1.1.to_d})
"{\"a\":1.1}"
```

I expected that in line  `[6]` or at least in `[8]` I would get .to_json spit out a decimal, not a string.
Am I doing something wrong in the setup?

**Comment by ohler55** [comment]
It looks line 6 did output a number and not a string. Line 7 should not set the mode. There is no need to. I’ll verify that the to_json is calling Oj late today. On the road driving today.

**Comment by ncr** [comment]
Yes, but I would like the .to_json to behave like this too so I don’t need
to do any changes to the rails code. No hurry btw. :)
W dniu czw., 28.12.2017 o 15:21 Peter Ohler <notifications@github.com>
napisał(a):

**Comment by ohler55** [comment]
That was and is the intent. Should get it over the next couple of days.

**Comment by ohler55** [comment]
Ok, another try please. The `Oj.optimize_rails` was not optimizing all the classes it was supposed to when given no arguments.

**Comment by ncr** [comment]
Works as expected :) Thanks a lot!

```
Loading development environment (Rails 4.2.8)
[1] pry(main)> Oj.optimize_rails
nil
[2] pry(main)> Oj.default_options = { bigdecimal_as_decimal: true }
{
    :bigdecimal_as_decimal => true
}
[3] pry(main)> {a:1.1.to_d}.to_json
"{\"a\":1.1}"
[4] pry(main)> Oj.default_options = { bigdecimal_as_decimal: false }
{
    :bigdecimal_as_decimal => false
}
[5] pry(main)> {a:1.1.to_d}.to_json
"{\"a\":\"1.1\"}"
```

**Comment by ohler55** [comment]
Great I'll get the release out today.

**Comment by ohler55** [comment]
ok to close?

**Comment by ncr** [comment]
Yes, and thank you for the fix!
