### ISSUE TITLE
Ignoring attributes in object mode

### ISSUE THREAD

**Issue by jrfaller** [ohler55/oj#452]
Hi all!

Since Oj new versions I have trouble to serialize objects that contains attributes having as value stuff coming from libraries. In old versions of Oj, it used to ignore such attributes when dumping (I do not know if it was a bug or a feature) but now I have the Too deeply nested error (I use :object mode).

Is there a way to tell Oj to avoid serializing some attributes?

Thanks.

**Comment by ohler55** [comment]
Depending on the mode you are using the answer will be different. I am guessing that you have circular references in that an object refereneces another which references the first object.

 * Which mode are you using?
 * What Oj version are you using?
 * Can you provide a simple example?

**Comment by jrfaller** [comment]
I use :object mode, and yes I have problem with circular references because when I set `circular: true`, serialization work, unfortunately unserialization do not work. Moreover, in fact, I really do not want to have some attribute values to go into the serialized format because they make sense at runtime, but not so much on the disk. Here is an example to outline the problem 

```
require "rugged"
require "oj"

class Test
	def initialize
		@unwanted_attr = Rugged::Repository.clone_at('https://github.com/ohler55/oj', 'tmp') 
		@wanted_attr = 'https://github.com/ohler55/oj'
	end
end

test1 = Test.new
Oj.default_options.merge(mode: :object)
Oj.to_file('test.json', test)
test2 = Oj.load_file('test.json')
```

Here the serialization works (even with no circular) but unserialization do not work because of an unloaded class that get serialized because unwanted_attr is serialized even tough is should not.

I found a work around using register_odd, when I encounter a Rugged::Repository object it serializes a dummy empty object instead, but I am not totally satisfied with it, I would prefer the attribute not to be present at all in the json.

Cheers!

**Comment by ohler55** [comment]
Okay, this sounds like a new feature request and a good addition to Oj. Let me propose that the ignored attributes would be based on just the attribute names and not a full path. If that works for you then there would be an option called :ignore that is an array of strings or symbols that will be ignored on dump.

**Comment by jrfaller** [comment]
Yes it is indeed a feature request :)

Another take on this could also be to provide a list of types that do not require serialization, it would perfectly fit my use case (in my case I would blacklist Rugged::Repository), and I think most use cases. I feel like providing attribute names could lead to tricky problems (for instance the id attribute is necessary in one class but not in an other).

**Comment by ohler55** [comment]
That makes sense. So a list of classes instead. Lets start with that. I may be able to do a combination of the class an/or attributes. I should be able to put a first cut together over the weekend. I've got another porject I hope to release this month that is a replacement for sinatra and webrick which is taking my time.

**Comment by jrfaller** [comment]
Very nice! Thanks a lot!

Let me know if you need some help to test the solution and good luck with your other project!

**Comment by ohler55** [comment]
I will ask for you to test before making a release. Thanks.

**Comment by ohler55** [comment]
I added an ignore option. It master . My mistake there but please see if it works for you.

**Comment by jrfaller** [comment]
Tested this morning, works like a charm! Thanks a lot.

**Comment by ohler55** [comment]
Great. I'll add docs and a unit test and then make a release.

**Comment by ohler55** [comment]
Can this be closed?

**Comment by jrfaller** [comment]
Yes, I am using it and perfectly happy!

Thanks a lot.
