### ISSUE TITLE
Unable to install gem oj version 3.3.10 on Windows Server 2008r2

### ISSUE THREAD

**Issue by craigerock** [ohler55/oj#453]
Problem was encountered while trying to upgrade a Redmine application.  I had previously tried oj gem versions 3.1.4 and 3.3.2 with the same make exit code.  Below is the gem_make.out file resulting from the attempt to install oj version 3.3.10.  This version came from rubygems.org.

D:/Bitnami/redmine-3.0.3-0/ruby/bin/ruby.exe -r ./siteconf20180118-6592-ncn9p0.rb extconf.rb
>>>>> Creating Makefile for ruby version 2.2.6 on i386-mingw32 <<<<<
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
generating oj-i386-mingw32.def
compiling cache8.c
In file included from d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/defines.h:163:0,
                 from d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/ruby.h:36,
                 from d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby.h:33,
                 from cache8.c:8:
d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/win32.h:319:44: warning: 'struct timespec' declared inside parameter list
d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/win32.h:319:44: warning: its scope is only this definition or declaration, which is probably not what you want
d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/win32.h:320:43: warning: 'struct timespec' declared inside parameter list
compiling circarray.c
In file included from d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/defines.h:163:0,
                 from d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/ruby.h:36,
                 from d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby.h:33,
                 from circarray.h:9,
                 from circarray.c:6:
d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/win32.h:319:44: warning: 'struct timespec' declared inside parameter list
d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/win32.h:319:44: warning: its scope is only this definition or declaration, which is probably not what you want
d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/win32.h:320:43: warning: 'struct timespec' declared inside parameter list
compiling code.c
In file included from d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/defines.h:163:0,
                 from d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/ruby.h:36,
                 from d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby.h:33,
                 from code.h:9,
                 from code.c:6:
d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/win32.h:319:44: warning: 'struct timespec' declared inside parameter list
d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/win32.h:319:44: warning: its scope is only this definition or declaration, which is probably not what you want
d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/win32.h:320:43: warning: 'struct timespec' declared inside parameter list
compiling compat.c
In file included from d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/defines.h:163:0,
                 from d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/ruby.h:36,
                 from d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby.h:33,
                 from oj.h:18,
                 from compat.c:8:
d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/win32.h:319:44: warning: 'struct timespec' declared inside parameter list
d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/win32.h:319:44: warning: its scope is only this definition or declaration, which is probably not what you want
d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/win32.h:320:43: warning: 'struct timespec' declared inside parameter list
compiling custom.c
In file included from d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/defines.h:163:0,
                 from d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/ruby.h:36,
                 from d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby.h:33,
                 from code.h:9,
                 from custom.c:8:
d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/win32.h:319:44: warning: 'struct timespec' declared inside parameter list
d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/win32.h:319:44: warning: its scope is only this definition or declaration, which is probably not what you want
d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/win32.h:320:43: warning: 'struct timespec' declared inside parameter list
compiling dump.c
In file included from d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/defines.h:163:0,
                 from d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/ruby.h:36,
                 from d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby.h:33,
                 from oj.h:18,
                 from dump.c:18:
d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/win32.h:319:44: warning: 'struct timespec' declared inside parameter list
d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/win32.h:319:44: warning: its scope is only this definition or declaration, which is probably not what you want
d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/win32.h:320:43: warning: 'struct timespec' declared inside parameter list
compiling dump_compat.c
In file included from d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/defines.h:163:0,
                 from d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/ruby.h:36,
                 from d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby.h:33,
                 from code.h:9,
                 from dump_compat.c:6:
d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/win32.h:319:44: warning: 'struct timespec' declared inside parameter list
d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/win32.h:319:44: warning: its scope is only this definition or declaration, which is probably not what you want
d:/Bitnami/redmine-3.0.3-0/ruby/include/ruby-2.2.0/ruby/win32.h:320:43: warning: 'struct timespec' declared inside parameter list
dump_compat.c: In function 'time_alt':
dump_compat.c:467:12: error: variable 'ts' has initializer but incomplete type
dump_compat.c:467:12: error: invalid use of undefined type 'struct timespec'
dump_compat.c:467:21: error: storage size of 'ts' isn't known
dump_compat.c:467:21: warning: unused variable 'ts'
make: *** [dump_compat.o] Error 1

make failed, exit code 2

**Comment by ohler55** [comment]
It looks like a windows related issue yet the appveyor tests for Oj are passing. I am not that familiar with windows but it looks like you are missing some of the time header files. I can suggest looking at the appveyor setup or making sure you have a full development environment for Ruby and Ruby extensions.

**Comment by craigerock** [comment]
Peter, thank you for your speedy response.  I need someone else who reads this to be able to help with this, probably from the Redmine open source community.  I am not a developer, but an Windows administrator who was trying to get an application upgraded.  It didn't work, so I rolled back the version to one that works.  The above "make" was launched using this command:
bundle install --without development test --binstubs --no-deployment
Bundler will fetch all remote sources, resolve dependencies and install all needed gems ... but instead I got the above make failure.

**Comment by ohler55** [comment]
Please put me in touch with the Redmine community. I am a fan of Redmine and would be glad to help.

**Comment by craigerock** [comment]
The place to start is here:
http://www.redmine.org/account/register

Thanks,
Doug

-----Original Message-----

**Comment by ohler55** [comment]
I have an account as 'peterohler'

**Comment by ohler55** [comment]
Is this still an issue after the 3.6.3 release?

**Comment by ohler55** [comment]
No response, closing.
