### ISSUE TITLE
rubinius support

### ISSUE THREAD

**Issue by danleyden** [ohler55/oj#454]
According to the compatibility page, rubinius is supported. I'm having trouble getting OJ installed on rubinius.

It may well be my issue (I've not much experience with rbx and am trying to test our app under it for performance).

I've tried installing using rvm under rbx-2 and rbx-3 and found similar results.

I've tried gem installing OJ at versions 3.0.0, 3.3.4 and 3.3.10 and all failed with a stack trace like:

```
>>>>> Creating Makefile for rubinius version 2.3.1 on x86_64-darwin16.7.0 <<<<<
creating Makefile

current directory: ~/.rvm/gems/rbx-3.70/gems/oj-3.0.0/ext/oj
make "DESTDIR=" clean

current directory: ~/.rvm/gems/rbx-3.70/gems/oj-3.0.0/ext/oj
make "DESTDIR="
compiling cache8.c
compiling circarray.c
compiling code.c
compiling compat.c
compiling custom.c
custom.c:373:15: error: use of undeclared identifier 'rb_eEncodingError'
            rb_raise(rb_eEncodingError, "Invalid type for raw JSON.\n");
                     ^
custom.c:590:16: warning: implicit declaration of function 'rb_ivar_count' is invalid in C99 [-Wimplicit-function-declaration]
    cnt = (int)rb_ivar_count(obj);
               ^
custom.c:603:5: warning: implicit declaration of function 'rb_ivar_foreach' is invalid in C99 [-Wimplicit-function-declaration]
    rb_ivar_foreach(obj, dump_attr_cb, (VALUE)out);
    ^
2 warnings and 1 error generated.
make: *** [custom.o] Error 1

make failed, exit code 2
```

When I tried an older version of OJ (2.14.6) it installed cleanly.

Also, is there merit in adding a rubinius build to travis?

**Comment by ohler55** [comment]
Compatibility with RBX used to be true but I haven't been able to install RBX for several years now. I should remove that note or try the latest and see if I can get it installed. I'll take a look this week.

**Comment by danleyden** [comment]
I had issues getting rbx installed too... using RVM on osx with homebrew `rvm install rbx-3 -C --with-lib-dir=$(brew --prefix openssl)/lib --with-include-dir=$(brew --prefix openssl)/include` worked for me

**Comment by ohler55** [comment]
Thanks. I'm on a linux machine until the weekend so will try that first.

**Comment by sreuss** [comment]
This is probably not related to OSX as it can be reproduced on a linux machine (using the official rbx docker image):

```
docker pull rubinius/docker
docker run -it rubinius/docker
sudo apt install ca-certificates build-essential
gem install oj
...
>>>>> Creating Makefile for rubinius version 2.3.1 on x86_64-linux-gnu <<<<<
creating Makefile

current directory: /opt/rubinius/3.99/gems/gems/oj-3.4.0/ext/oj
make "DESTDIR=" clean

current directory: /opt/rubinius/3.99/gems/gems/oj-3.4.0/ext/oj
make "DESTDIR="
compiling dump_compat.c
dump_compat.c: In function ‘dump_float’:
dump_compat.c:607:5: warning: implicit declaration of function ‘isnan’ [-Wimplicit-function-declaration]
     } else if (isnan(d)) {
     ^
compiling odd.c
compiling fast.c
compiling code.c
compiling sparse.c
sparse.c: In function ‘oj_sparse2’:
sparse.c:780:7: warning: implicit declaration of function ‘rb_yield_values2’ [-Wimplicit-function-declaration]
       rb_yield_values2(3, args);
       ^
compiling mimic_json.c
compiling rxclass.c
compiling dump.c
compiling dump_strict.c
compiling circarray.c
compiling parse.c
parse.c: In function ‘oj_parse2’:
parse.c:706:7: warning: implicit declaration of function ‘rb_yield_values2’ [-Wimplicit-function-declaration]
       rb_yield_values2(3, args);
       ^
compiling saj.c
compiling val_stack.c
compiling compat.c
compiling oj.c
compiling scp.c
compiling custom.c
custom.c: In function ‘dump_odd’:
custom.c:388:15: error: ‘rb_eEncodingError’ undeclared (first use in this function)
      rb_raise(rb_eEncodingError, "Invalid type for raw JSON.\n");
               ^
custom.c:388:15: note: each undeclared identifier is reported only once for each function it appears in
custom.c: In function ‘dump_obj_attrs’:
custom.c:610:5: warning: implicit declaration of function ‘rb_ivar_count’ [-Wimplicit-function-declaration]
     cnt = (int)rb_ivar_count(obj);
     ^
custom.c:623:5: warning: implicit declaration of function ‘rb_ivar_foreach’ [-Wimplicit-function-declaration]
     rb_ivar_foreach(obj, dump_attr_cb, (VALUE)out);
     ^
make: *** [custom.o] Error 1

make failed, exit code 2
...
```

The problem seems to be that `custom.c` does not have the block
```
#if !HAS_ENCODING_SUPPORT || defined(RUBINIUS_RUBY)
#define rb_eEncodingError	rb_eException
#endif
```
which other source files like `oj.c` and  `dump_strict.c` have.

**Comment by ohler55** [comment]
I'm afraid there are other issues as well. I was not able to build RBX on either OS X or Ubuntu 17.04. Without that I can't debug and fix any of the issues. I'll try the latest suggestion for OS X using RVM at the end of the month unless someone can give me a login on a box with RBX installed. Or point me to an image I can download and run.

**Comment by ohler55** [comment]
Compiling now but failing later in an rbx branch.

**Comment by bf4** [comment]
RBX has a philosophy that it will break compatibility with CRuby if it thinks CRuby is doing it wrong... I've stopped supporting it in my own gems as it's become a pain.

**Comment by ohler55** [comment]
It does seem to be painful. Just getting it to build is painful.

**Comment by ohler55** [comment]
Giving up on RBX. It is no longer supported.
