### ISSUE TITLE
"bigdecimal_as_decimal: true" doesn't seem to work when rendering JSON in controller

### ISSUE THREAD

**Issue by michaltrzcinka** [ohler55/oj#455]
Hello,

I've prepared a very simple Rails 5 app demonstrating a problem with the `bigdecimal_as_decimal` setting: https://github.com/michaltrzcinka/oj-issue

In oj.rb initializer here https://github.com/michaltrzcinka/oj-issue/blob/master/config/initializers/oj.rb I set this option to true, and in controller here https://github.com/michaltrzcinka/oj-issue/blob/master/app/controllers/welcome_controller.rb I render a very simple hash with a BigDecimal value. When I test it, the code renders the following:
```
{"x":"10.0"}
```

I would expect:
```
{"x":10.0}
```

I've also found an interesting difference when playing in `pry`:
```
[2] pry(main)> Oj::Rails::Encoder.new.encode({x: 10.to_d})
=> "{\"x\":10.0}"
[3] pry(main)> Oj::Rails::Encoder.new({}).encode({x: 10.to_d})
=> "{\"x\":\"10.0\"}"
```

`Oj::Rails::Encoder` is called with an options hash here https://github.com/rails/rails/blob/master/activesupport/lib/active_support/json/encoding.rb#L22 and it seems to break this setting?

**Comment by ohler55** [comment]
I'm going to guess that you are using Oj in rails or combat mode. In those modes Oj attempts to mimic either rails or the JSON gem. I think you will find that rails outputs BigDecimals as strings and Oj is behaving the same. Check out the modes page at http://www.ohler.com/oj/doc/file.Modes.html to see what options are available in each mode.

I didn't follow the point you were trying to make about the active support encoder breaking some setting. Can you explain?

**Comment by michaltrzcinka** [comment]
Thanks for a quick reply!
I tried all modes and commenting out `Oj.optimize_rails` call, but the problem persists.
Concerning the active support encoder - I was debugging this issue and found that Rails reaches the mentioned code ( https://github.com/rails/rails/blob/master/activesupport/lib/active_support/json/encoding.rb#L22 ) when rendering from controller. I put a `binding.pry` statement there and played with it and found that when I call `Encoding.json_encoder.new(options).encode(value)`, the returned JSON has BigDecimal surrounded with quotes. But if I omit `options` and do just `Encoding.json_encoder.new.encode(value)`, the JSON looks correct. Here's the output from my `pry` session:

```
    19: def self.encode(value, options = nil)
 => 20:   binding.pry
    21:   Encoding.json_encoder.new(options).encode(value)
    22: end

[1] pry(ActiveSupport::JSON)> Encoding.json_encoder.new(options).encode(value)
=> "{\"x\":\"10.0\"}"
[2] pry(ActiveSupport::JSON)> Encoding.json_encoder.new.encode(value)
=> "{\"x\":10.0}"
[3] pry(ActiveSupport::JSON)> options
=> {:prefixes=>["welcome", "application"],
 :template=>"index",
 :layout=>
  #<Proc:0x007fb1323017c8@/Users/michal/.rvm/gems/ruby-2.3.3/gems/actionview-5.1.4/lib/action_view/layouts.rb:390>}
[4] pry(ActiveSupport::JSON)> Encoding.json_encoder
=> Oj::Rails::Encoder
```

**Comment by ohler55** [comment]
The Oj modes are only for calling Oj directly. If you are calling the rails encoder then Oj will always be in rails mode.

Interesting that you were able to get around have BigDecimals as a string. I believe that is a bug but I'd have to check the rails test cases. You probably don't want me to fix it though. :-)

I'll dig deeper tonight. Just to help my understanding, why are you trying to work around the normal rails behavior?

**Comment by ohler55** [comment]
Well, good news and bad news. Rails used to support an option referred to as `encode_big_decimal_as_string` but that has been removed. Doing a search it seems there are a lot of people not happy with that change. I'll propose this for Oj, support `encode_big_decimal_as_string` as well as the Oj `bigdecimal_as_decimal` option. I'll add a notation in the docs indicating it is a deviation from the rails normal behavior.

What do you think?

**Comment by michaltrzcinka** [comment]
So, setting the old `encode_big_decimal_as_string` setting would cause Oj in rails mode to render BigDecimals without quotes? If that's the case, that would be great! Even if it deviates from normal Rails behavior, I think it's just pragmatic.

**Comment by ohler55** [comment]
Ok, I'll get that done over the next week or so. I'm a little backed up right now.

**Comment by michaltrzcinka** [comment]
Thank you very much for help 👍

**Comment by ohler55** [comment]
Okay, I looked into the issue a bit more. I don't think there are any changes necessary. The steps to take that should work or at least work for me in tests is to do this.

```ruby
Oj::Rails.set_encoder()
Oj::Rails.optimize()
Oj.default_options = { bigdecimal_as_decimal: true }
```
The calls to Oj::Rails.set_encoder and Oj::Rails.optimize should be called first and they will reset the defaults to match those for rails. After that the bigdecimal_as_decimal can be reset to true.

**Comment by michaltrzcinka** [comment]
I tried the fix, but it doesn't seem to work. I pushed it to the repo of my test app: 
https://github.com/michaltrzcinka/oj-issue/blob/master/config/initializers/oj.rb

**Comment by ohler55** [comment]
How would I run a test with your repo?

**Comment by michaltrzcinka** [comment]
I added a readme: https://github.com/michaltrzcinka/oj-issue/blob/master/README.md#readme

**Comment by ohler55** [comment]
That was very helpful. My findings are that Rails is encoding a Hash but when it gets to Oj the hash already contains a string instead of a BigDecimal. The conversion is happening somewhere deeper in rails. I'll let you do some digging to find where. If you can find where maybe I can help you with a work around.

**Comment by ohler55** [comment]
I added a trace option that might help when tracing.

**Comment by ohler55** [comment]
Is this an Oj issue or just the way Rails works?

**Comment by ohler55** [comment]
Is there a reason to keep this open?

**Comment by ohler55** [comment]
No response, closing.

**Comment by Jakanapes** [comment]
Has there ever been any resolution here? 

We're finding that `Oj.dump x, mode: :rails, bigdecimal_as_decimal: true` is still returning strings, when trying to upgrade from 2.17 to 3.7.8

**Comment by ohler55** [comment]
In `:rails` mode the `bigdecimal_as_decimal` is not available. The `:rails` mode is mean to be as close as possible to Rails which returns a string and there is no option to change that.
