### ISSUE TITLE
Unable to install OJ-3.4.0 in Ubuntu with jruby

### ISSUE THREAD

**Issue by orry42** [ohler55/oj#456]
Hi Peter,

I'm running into the following issue when trying to install OJ-3.4.0 on Ubuntu 14.04 for a project that is using Jruby.

Here is the stacktrace:
`
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
current directory:
/home/travis/build/zendesk/zendesk_indexer_transform/vendor/bundle/jruby/2.3.0/gems/oj-3.4.0/ext/oj
/home/travis/.rvm/rubies/jruby-9.1.15.0/bin/jruby -r
./siteconf20180208-5307-ehtoof.rb extconf.rb
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
`
`
#>>>>> Creating Makefile for jruby version 2.3.3 on java #<<<<<
creating Makefile
current directory:
/home/travis/build/zendesk/zendesk_indexer_transform/vendor/bundle/jruby/2.3.0/gems/oj-3.4.0/ext/oj
make "DESTDIR=" clean
`
`
current directory:
/home/travis/build/zendesk/zendesk_indexer_transform/vendor/bundle/jruby/2.3.0/gems/oj-3.4.0/ext/oj
make "DESTDIR="
make: *** No rule to make target
'/home/travis/.rvm/rubies/jruby-9.1.15.0/lib/ruby/include/ruby/ruby.h', needed
by 'cache8.o'.  Stop.
make failed, exit code 2
`

I was wondering if there is a version of OJ 3.x.x that is supported by jruby?
I tried to use it with jruby-9.1.7.0 but I got the same error with 3.4.0.

Thanks,

**Comment by ohler55** [comment]
As far as I know JRuby stopped supporting C extensions years ago.

**Comment by orry42** [comment]
thanks for your answer. it looks like it has finally been removed with 9.1.15. Interestingly, it's still available for 9.1.7 with truffle in jruby-9.1.7.0/lib/ruby/truffle/cext.

**Comment by brauliobo** [comment]
how to make the code works with both `JSON` and `Oj` so that it works with jruby?

**Comment by ohler55** [comment]
Since JRuby does not support C extensions there is nothing that can be done to the Oj code to make it work with JRuby.

**Comment by brauliobo** [comment]
Code to make Oj optional:

```ruby
if RUBY_ENGINE == 'ruby'

  Oj.default_options = {
    mode: :compat,
  }

  module JSON

    def self.parse json
      Oj.load json
    rescue Oj::ParseError => e
      raise JSON::ParserError, e
    end

  end

end
```

**Comment by ohler55** [comment]
I see, you are offering a method of not using Oj when running with something other than MRI. That approach looks fine.

**Comment by brauliobo** [comment]
now also patching dump, created a wiki page for the monkey patch https://github.com/ohler55/oj/wiki/Flexible-usage-with-MRI-and-JRuby

**Comment by brauliobo** [comment]
@ohler55 it seems `Oj.mimic_JSON` does what I tried to do manually?

**Comment by ohler55** [comment]
Ruby does not support C extensions. Nothing I can do.
