### ISSUE TITLE
Documentation around Rails Mode is a bit ambiguous

### ISSUE THREAD

**Issue by skatenerd** [ohler55/oj#457]
In the [rails documentation](https://github.com/ohler55/oj/blob/master/pages/Rails.md#oj-rails-compatibility), there is a reference to "rails mode":

> The :rails mode mimics the ActiveSupport version 5 encoder

Then, what follows is a snippet of code, describing how to tell `Oj` to monkey-patch all of the existing Rails serialization.

As a reader, it's tempting for me to omit the "rails mode" configuration, and simply write an initializer that says:
```
require 'oj'
Oj.optimize_rails()
```

It took me a little while to realize that I in fact should probably write:
```
require 'oj'
Oj.default_options = { mode: :rails }
Oj.optimize_rails()
```

So, I'm wondering: should we include the `default_options` invocation inside of [rails.md](https://github.com/ohler55/oj/blob/master/pages/Rails.md), or is it redundant?

**Comment by ohler55** [comment]
The default options don't need to be set if you are just using rails. If you want to use Oj directly and have act like rails then you can set the default options. It is only needed if thats what you want though. I can add a comment to explain that.

**Comment by ohler55** [comment]
Added to the rails page.

**Comment by skatenerd** [comment]
thanks!
