### ISSUE TITLE
Tracer.display_c_call doesn't show OJ

### ISSUE THREAD

**Issue by nateberkopec** [ohler55/oj#459]
```ruby
require 'oj'
Oj.mimic_JSON()
require 'tracer'
Tracer.display_c_call = true
Tracer.on

Math::PI.to_json
Oj.dump(Math::PI)
```

Output is:
```
#0:oj_verify.rb:7::-: Math::PI.to_json
#0:oj_verify.rb:7:Object:}: Math::PI.to_json
#0:oj_verify.rb:7:Float:}: Math::PI.to_json
#0:oj_verify.rb:7:Float:{: Math::PI.to_json
#0:oj_verify.rb:7:Object:{: Math::PI.to_json
#0:oj_verify.rb:8::-: Oj.dump(Math::PI)
#0:oj_verify.rb:8:Oj:}: Oj.dump(Math::PI)
#0:oj_verify.rb:8:Float:}: Oj.dump(Math::PI)
#0:oj_verify.rb:8:Float:{: Oj.dump(Math::PI)
#0:oj_verify.rb:8:Oj:{: Oj.dump(Math::PI)
```

I came upon this when trying to verify if OJ was being used for `to_json` in a Rails app. Unfortunately I can't think of anything to verify that now, as it looks like `:compat` mode basically locks all of OJ's settings up (my idea was to modify settings on OJ like the time format to see if that changed to_json output).

**Comment by ohler55** [comment]
As far as I know Tracer traces Ruby calls and not C calls. Since Oj is a C extension to Ruby calls internal to Oj will not be traced.

Check out the page on Oj options at http://ohler.com/oj/doc/file.Modes.html. Compat mode is indented to be compatible with the JSON gem which means you do not get options for time formats. The custom mode does provide that feature.

**Comment by bf4** [comment]
Related #460 (really, me an @nateberkopec were chatting about it)

**Comment by nateberkopec** [comment]
> As far as I know Tracer traces Ruby calls and not C calls. Since Oj is a C extension to Ruby calls internal to Oj will not be traced.

Well, I guess that `Tracer.display_c_call = true` isn't very accurate then, is it? It should probably be removed from your docs, then.

**Comment by ohler55** [comment]
It does help identify that Oj is being called just not the internals. @bf4 did a great job updating the docs.

**Comment by nateberkopec** [comment]
I guess I don't understand where in the original output I posted shows that OJ is being called.

**Comment by ohler55** [comment]
Did you try what @bf4 suggested? If not I'll look at it tonight.

**Comment by ohler55** [comment]
Well, results are not ideal but it is possible to tell the difference between the JSON gem and Oj. Here is the file I used. Comment out `Oj.mimi_JSON` or the `require 'json'`.

```ruby
require 'oj'
#require 'json'
Oj.mimic_JSON()
require 'tracer'
tracer = TracePoint.new(:c_call) { |tp| puts "--- #{tp.lineno} #{tp.event} #{tp.defined_class} #{tp.method_id}" }
tracer.enable { Math::PI.to_json }
```

Oj is:
```
razer tmp> ruby foo.rb 
--- 10 c_call Object to_json
--- 10 c_call Float to_s
```
The JSON gem is:
```
razer tmp> ruby foo.rb 
--- 10 c_call JSON::Ext::Generator::GeneratorMethods::Float to_json
--- 10 c_call Kernel dup
--- 10 c_call Kernel initialize_dup
--- 10 c_call JSON::Ext::Generator::State initialize_copy
--- 10 c_call Float to_s
```
I'm afraid thats as good as it gets for tracer. Is that enough, knowing that a C call was made?

**Comment by bf4** [comment]
@ohler55 ( `Tracer` is actually different from TracePoint.  Tracer uses the older Kernel#set_trace_func

**Comment by ohler55** [comment]
Is there something else that is being requested here? I am not able to modify Trace or TracePoint. Are you looking for some kind of trace option for Oj itself?

**Comment by ohler55** [comment]
Update: Implementation of a trace option for Oj is now in the works.

**Comment by ohler55** [comment]
Released 3.5.0 with trace option.

**Comment by ohler55** [comment]
With the new trace option can this be closed?

**Comment by ohler55** [comment]
No response. Closing.
