### ISSUE TITLE
Rails serializable_hash retrieves nil argument when using Oj

### ISSUE THREAD

**Issue by espen** [ohler55/oj#461]
This might be related to https://github.com/ohler55/oj/issues/244 but I'm not sure.

I can override as_json but as our API also returns XML we have to override serializable_hash so both json/xml is the same.

The problem it seems is due to serializable_hash getting passed an argument (nil) while as_json it not (and thus is able to my default value for the argument). This results in serializable_hash choking when merging the hash (nil object).

So this is solvable by doing `options ||= {}` but I guess this is a bug? Just started implementing Oj so not sure what the expected usage here is.

Works:
```ruby
def as_json(options={})
  options = { :only => [:id] }.deep_merge(options)
  super(options)
end
```

Does not work:
```ruby
def serializable_hash(options={})
  options = { :only => [:id] }.deep_merge(options)
  super(options)
end
```

The latter does work without using Oj.

**Comment by ohler55** [comment]
It is not clear to me where Oj comes into play with serializable_hash. It sounds like Oj is returning a nil instead of `{}` somewhere but I'm not sure what calls are being made in your situation nor what mode you are using. I'm guessing rails mode, right?

**Comment by ohler55** [comment]
Once you call `Oj.optimize_rails` the rails encoder becomes an Oj encoder so you should not have to explicitly call `to_json`. By calling `to_json` directly you force the use of more ruby code which will be slower.

**Comment by espen** [comment]
Great, thanks.

If you don't mind I will keep this issue open. Will provide a failing test for it later.

**Comment by ohler55** [comment]
ok

**Comment by ohler55** [comment]
Any reason to keep this open?

**Comment by espen** [comment]
Upgraded to Rails v6 and running into this again. Was working fine on Rails v5. When not using Oj `serializable_hash` will give me `{}` as argument. With Oj I get `nil`.

With code `def serializable_hash(options={})` in model.

**Comment by ohler55** [comment]
I'll take a look but it will take a bit before I can get to it.

**Comment by espen** [comment]
This seems to be fixed. I upgraded to Rails 6 now and no longer seeing this error.

**Comment by ohler55** [comment]
Excellent!
