### ISSUE TITLE
Setting time_format when using mode: compat

### ISSUE THREAD

**Issue by indrekj** [ohler55/oj#462]
https://github.com/ohler55/oj/blob/master/ext/oj/oj.c#L226 says
```
 * - *:time_format* [_:unix_|_:unix_zone_|_:xmlschema_|_:ruby_] time format when dumping in :compat and :object mode
```

However when I do:
```
Oj.dump({x: Time.now}, mode: :compat, time_format: :xmlschema)
=> "{\"x\":\"2018-03-03 13:30:01 +0200\"}"
```
I don't get the time formatted as iso8601.

https://github.com/ohler55/oj/blob/master/pages/Modes.md here it also seems that it is not configurable.

Can we make it configurable? Or what's the way to go if I want to use compat settings with iso8601 timestamps?

**Comment by ohler55** [comment]
Compat mode is meant to mimic the JSON gem. The JSON gem does not offer that option so making the time format configurable in compat mode means Oj is no longer mimicking the JSON gem. Using the custom mode you should be able to change the time format.

**Comment by indrekj** [comment]
Ok thanks. I guess the comment in the oj.c should be changed.

**Comment by ohler55** [comment]
Which comment? If I missed something I am glad to fix it. The current state of Oj and strict JSON gem mimic in compat more is a result of many issues around why Oj did things differently from the JSON gem in mimic (compat) mode. You can do almost everything to mimic the JSON gem with the correct options set in custom mode.

**Comment by indrekj** [comment]
> Which comment?

https://github.com/ohler55/oj/blob/master/ext/oj/oj.c#L226 Line 226 says that time_format can be changed in compat mode.

**Comment by ohler55** [comment]
Thanks. I'll clean that up.
