### ISSUE TITLE
Should `Oj.load` support `tainted?`?

### ISSUE THREAD

**Issue by sdemjanenko** [ohler55/oj#467]
I realize that the stock JSON module in ruby doesn't do the right thing:
```
str = '{"a": {"b": "cats"}}'
str.taint
json = JSON.parse(str)
json.tainted? # false
```
I would argue that if the input for JSON parsing is tainted, then all levels of the output should be marked as tainted.

I'm open to a discussion on this. For more information see [wikipedia](https://en.wikipedia.org/wiki/Taint_checking) and [tainted-ruby-security](http://www.chrisrolle.com/en/blog/tainted-ruby-security)

**Comment by ohler55** [comment]
I can that argument made for some Oj modes but not for `:compat` or `:rails` as that would break compatibility with the way the JSON gem and Rails handle parsing.

**Comment by ohler55** [comment]
If the returned object should be tainted then all elements of the returned object should also be tainted. Is that the desired behavior?

**Comment by ohler55** [comment]
Is this a dead issue?

**Comment by ohler55** [comment]
Closing since there have been no responses.
