### ISSUE TITLE
EncodingError: invalid encoding symbol

### ISSUE THREAD

**Issue by rkotov93** [ohler55/oj#468]
Hello,

I've met a pretty weird bug using `oj` in rails project with `Oj.optimize_rails` initializer added. So, I have a json with utf-8 encoded field name. Weirdness is that sometimes `Oj` parses it, sometimes 
raises `EncodingError: invalid encoding symbol`, but the parsed value is different every time.

```ruby
json = "{\"s\\u0000t\\u0000a\\u0000t\\u0000e\":\"\"}"

JSON.parse(json, symbolize_names: true)
#=> {:"s\x00\x00\x00\x00\x00\x00@?"=>""}

JSON.parse(json, symbolize_names: true)
#=> EncodingError: invalid encoding symbol
#=> from (pry):17:in `parse'

JSON.parse(json, symbolize_names: true)
#=> EncodingError: invalid encoding symbol
#=> from (pry):18:in `parse'

JSON.parse(json, symbolize_names: true)
#=> EncodingError: invalid encoding symbol
#=> from (pry):19:in `parse'

JSON.parse(json, symbolize_names: true)
#=> {:"s\x00\x00\x00\x00\x00\x00@Z"=>""}
```

**Comment by ohler55** [comment]
I would expect `{:"s\x00t\x00a\x00\t\x00e"=>""}`. Do you agree with that?

I was able to confirm that the results are not consistent and not what was expected.

**Comment by rkotov93** [comment]
Yeah, if `\` before `t` is just a typo 😊 
Default JSON gem returns `{:"s\x00t\x00a\x00t\x00e"=>""}`

**Comment by ohler55** [comment]
I just created a branch called 'zero' that has a fix in it. Please give it a try.

**Comment by rkotov93** [comment]
Yay, works fine :+1:

**Comment by ohler55** [comment]
ok, release completed.

**Comment by rkotov93** [comment]
Great! Checked it in a project as well and works fine! Thank you!
