### ISSUE TITLE
Oj.load fails to parse IPv6 addresses correctly

### ISSUE THREAD

**Issue by hlakshmi** [ohler55/oj#472]
Encountered the following:

```
>> data_raw = "{\"hostname\":\"example.com\",\"ip_list\":[\"::ffff:10.106.213.228\"]}"
=> "{\"hostname\":\"example.com\",\"ip_list\":[\"::ffff:10.106.213.228\"]}"
>> Oj.load(data_raw)
=> {"hostname"=>"example.com", "ip_list"=>[:":ffff:10.106.213.228"]}
```
Following is the output with std JSON parser which works as expected:

```
>> require 'json'
=> true
>> JSON.load(data_raw)
=> {"hostname"=>"example.com", "ip_list"=>["::ffff:10.106.213.228"]}
```

**Comment by ohler55** [comment]
Oj has several different modes. Set the mode to something other than `:object` mode and it should give you what you want. If trying to mimic the JSON gem then use the `:compat` mode.

**Comment by ohler55** [comment]
No impact at all. You can just set the default options once instead. Each mode has a different output and handles input differently. In some cases the difference is small. Object mode is meant for encoding and decoding Ruby objects. It was the first use of Oj many years ago and is faster for serializing objects but not compatible with the JSON gem.

**Comment by ohler55** [comment]
Can this be closed?

**Comment by hlakshmi** [comment]
@ohler55 
Sure.
