### ISSUE TITLE
Can't understand how to do what I'm after

### ISSUE THREAD

**Issue by riddley** [ohler55/oj#480]
I was using version 2.18.5 to do this and with 3.6.2 it doesn't work anymore. I've read and re-read the docs and even found issue 322 which sorta does what I want, but it either doesn't work anymore or wasn't what I wanted after all.

In ruby I have a hash where the values are arrays of custom objects that need to be converted to plain(meaning I don't ever want to parse them back into Ruby objects) JSON hashes. Each of these object types has a #to_hash instance method. For potential clarity:

```ruby

class MyCustomObject
    def to_hash
        { whatever: 'thing', otherthing: 'yes' }
    end
end

mydata = { "key1" => [MyCustomObject, MyCustomObject, ...], "key2" => [MyOtherCustomOb, MyOtherCustomOb,...] }

json = Oj.dump( mydata, { use_to_hash: true })
```

What I get is arrays of the default #inspect for the objects. I've tried setting modes, I tried adding use_to_json: true as issue 322 suggests, didn't work. I tried various other modes. Is there a way to do what I want with this version?  Is the problem that I'm using Symbols for keys?

**Comment by ohler55** [comment]
Oj has multiple modes as described in the [modes description](http://ohler.com/oj/doc/file.Modes.html). The only modes that support the `to_hash` method are the `:rails` and `:custom` modes. If you were using `:compat` mode then that mode is not supported as the `:compat` mode is meant to mimic the JSON gem which does not support the `to_hash` method.

**Comment by riddley** [comment]
Thanks. Is there a way to do what I'm after? I read the modes over and over and still don't see how to do what I want.

**Comment by ohler55** [comment]
This worked for me.

```ruby
require 'oj'

class MyCustomObject
    def to_hash
        { whatever: 'thing', otherthing: 'yes' }
    end
end

mydata = { "key1" => [MyCustomObject.new, MyCustomObject.new], "key2" => [MyCustomObject.new, MyCustomObject.new]}

json = Oj.dump(mydata, use_to_hash: true, mode: :custom)

puts json
```

It returned

```ruby
{"key1":[{"whatever":"thing","otherthing":"yes"},{"whatever":"thing","otherthing":"yes"}],"key2":[{"whatever":"thing","otherthing":"yes"},{"whatever":"thing","otherthing":"yes"}]}
```

**Comment by riddley** [comment]
Thanks. That example works for me too. Do you have any suggestions about how to troubleshoot this? If I do:

`Oj.dump( mydata['key1'].first, use_to_hash: true, mode: :custom)
`
It still gives the #inspect output, but if I do

`Oj.dump( mydata['key1'].first.to_hash, use_to_hash: true, mode: :custom)
`
It works fine.

**Comment by riddley** [comment]
I've been saying it's serializing them to the default #inspect output, but I'm wrong. It's using #to_s.

**Comment by riddley** [comment]
The problem was that I had a call to Oj.mimic_json elsewhere in the code. Sorry for the noise.

**Comment by ohler55** [comment]
You can override the mimic setting by adding `use_to_json: false`.

**Comment by ohler55** [comment]
The mimic behaviour gets a bit tricky.
