### ISSUE TITLE
Unable to install oj-3.6.2 on Windows 10 ruby 2.2.10

### ISSUE THREAD

**Issue by mailtosmyk** [ohler55/oj#481]
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
C:/tools/Bitnami/rubystack-2.2.10-2/ruby/lib/ruby/gems/2.2.0/gems/oj-3.6.2/ext/oj
C:/tools/Bitnami/rubystack-2.2.10-2/ruby/bin/ruby.exe -r
./siteconf20180621-9200-kjngeb.rb extconf.rb
>>>>> Creating Makefile for ruby version 2.2.6 on i386-mingw32 <<<<<
creating Makefile

current directory:
C:/tools/Bitnami/rubystack-2.2.10-2/ruby/lib/ruby/gems/2.2.0/gems/oj-3.6.2/ext/oj
make "DESTDIR=" clean

current directory:
C:/tools/Bitnami/rubystack-2.2.10-2/ruby/lib/ruby/gems/2.2.0/gems/oj-3.6.2/ext/oj
make "DESTDIR="
generating oj-i386-mingw32.def
compiling cache8.c
In file included from
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/defines.h:163:0,
from
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/ruby.h:36,
from
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby.h:33,
                 from cache8.c:8:
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/win32.h:319:44:
warning: 'struct timespec' declared inside parameter list
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/win32.h:319:44:
warning: its scope is only this definition or declaration, which is probably not
what you want
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/win32.h:320:43:
warning: 'struct timespec' declared inside parameter list
compiling circarray.c
In file included from
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/defines.h:163:0,
from
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/ruby.h:36,
from
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby.h:33,
                 from circarray.h:9,
                 from circarray.c:6:
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/win32.h:319:44:
warning: 'struct timespec' declared inside parameter list
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/win32.h:319:44:
warning: its scope is only this definition or declaration, which is probably not
what you want
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/win32.h:320:43:
warning: 'struct timespec' declared inside parameter list
compiling code.c
In file included from
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/defines.h:163:0,
from
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/ruby.h:36,
from
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby.h:33,
                 from code.h:9,
                 from code.c:6:
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/win32.h:319:44:
warning: 'struct timespec' declared inside parameter list
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/win32.h:319:44:
warning: its scope is only this definition or declaration, which is probably not
what you want
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/win32.h:320:43:
warning: 'struct timespec' declared inside parameter list
compiling compat.c
In file included from
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/defines.h:163:0,
from
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/ruby.h:36,
from
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby.h:33,
                 from oj.h:18,
                 from compat.c:8:
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/win32.h:319:44:
warning: 'struct timespec' declared inside parameter list
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/win32.h:319:44:
warning: its scope is only this definition or declaration, which is probably not
what you want
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/win32.h:320:43:
warning: 'struct timespec' declared inside parameter list
compiling custom.c
In file included from
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/defines.h:163:0,
from
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/ruby.h:36,
from
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby.h:33,
                 from code.h:9,
                 from custom.c:8:
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/win32.h:319:44:
warning: 'struct timespec' declared inside parameter list
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/win32.h:319:44:
warning: its scope is only this definition or declaration, which is probably not
what you want
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/win32.h:320:43:
warning: 'struct timespec' declared inside parameter list
compiling dump.c
In file included from
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/defines.h:163:0,
from
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/ruby.h:36,
from
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby.h:33,
                 from oj.h:18,
                 from dump.c:18:
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/win32.h:319:44:
warning: 'struct timespec' declared inside parameter list
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/win32.h:319:44:
warning: its scope is only this definition or declaration, which is probably not
what you want
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/win32.h:320:43:
warning: 'struct timespec' declared inside parameter list
compiling dump_compat.c
In file included from
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/defines.h:163:0,
from
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/ruby.h:36,
from
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby.h:33,
                 from code.h:9,
                 from dump_compat.c:6:
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/win32.h:319:44:
warning: 'struct timespec' declared inside parameter list
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/win32.h:319:44:
warning: its scope is only this definition or declaration, which is probably not
what you want
c:/tools/Bitnami/rubystack-2.2.10-2/ruby/include/ruby-2.2.0/ruby/win32.h:320:43:
warning: 'struct timespec' declared inside parameter list
dump_compat.c: In function 'time_alt':
dump_compat.c:474:12: error: variable 'ts' has initializer but incomplete type
dump_compat.c:474:12: error: invalid use of undefined type 'struct timespec'
dump_compat.c:474:21: error: storage size of 'ts' isn't known
dump_compat.c:474:21: warning: unused variable 'ts'
make: *** [dump_compat.o] Error 1

make failed, exit code 2

Gem files will remain installed in
C:/tools/Bitnami/rubystack-2.2.10-2/ruby/lib/ruby/gems/2.2.0/gems/oj-3.6.2 for
inspection.
Results logged to
C:/tools/Bitnami/rubystack-2.2.10-2/ruby/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/oj-3.6.2/gem_make.out

An error occurred while installing oj (3.6.2), and Bundler cannot continue.
Make sure that `gem install oj -v '3.6.2'` succeeds before bundling.

**Comment by ohler55** [comment]
Found it, fixed it. Will release soon.

**Comment by ohler55** [comment]
Released 3.6.3.

**Comment by ohler55** [comment]
No response. Assuming it was fixed.
