### ISSUE TITLE
Inconsistent JSON.generate behaviour

### ISSUE THREAD

**Issue by faucct** [ohler55/oj#483]
```ruby
require 'active_support/json/encoding.rb'
require 'json'

class Foo
  def to_json(*)
    '{"foo":"bar"}'
  end
end

puts JSON.generate([Foo.new])
# => [{"foo":"bar"}]
puts JSON.generate(Foo.new)
# => {"foo":"bar"}

require 'oj'
Oj.optimize_rails

puts JSON.generate([Foo.new])
# => [{"foo":"bar"}]
puts JSON.generate(Foo.new)
# => "#<Foo:0x007fecc810ad30>"
```

**Comment by ohler55** [comment]
I'll look into it. You are treading in a gray area though. Using rails but then not using the rails encoding but the JSON gem encoding.

**Comment by faucct** [comment]
Sadly I need to use JSON gem in Rails to make it possible interpolating preserialized JSON strings in jsonified structures, taken from serializers fragment cache:

```ruby
class SerializedJSON
  def initialize(json_string)
    @json_string = json_string
  end
end

JSON.generate([SerializedJSON.new('{"foo": "bar"}')])
```

Do you have any other solution for doing this in Rails?

**Comment by ohler55** [comment]
That is a tough one. Rails deprecates the use of `to_json` in favor of `as_json` but that doesn't work if you already have the JSON string. Anyway, I'll take a look tonight and see what can be done. One way or another we'll get it to work.

**Comment by ohler55** [comment]
Try the master branch. It turned out the generate method was not setting the `:to_json` option as it was supposed to.

**Comment by faucct** [comment]
The example I have provided works now, but now I am not sure if `JSON.generate` is the thing I need: I need objects to be serialized the way `Rails` does it but with an exception for preserialized JSON strings. It looks like I have to use `#to_json`, but I don't see a way I could interpolate preserialized JSON there. Do you have any ideas how to do it?

BTW, found some more differences `oj` brings in:

```ruby
require 'active_support'
require 'active_support/core_ext'
require 'active_support/json/encoding.rb'
require 'json'

class Foo
  def to_json(**)
    '{"foo":"bar"}'
  end
end

hash_with_time = { foo: Time.now.utc }

puts hash_with_time.to_json
# => {"foo":"2018-06-28T09:07:40.464Z"}
puts JSON.generate(hash_with_time)
# => {"foo":"2018-06-28 09:07:40 UTC"}

puts JSON.generate({ foo: Foo.new }.with_indifferent_access)
# => {"foo":{"foo":"bar"}}
puts({ foo: Foo.new }.to_json)
# => {"foo":{}}

require 'oj'
Oj.optimize_rails

puts hash_with_time.to_json
# => {"foo":"2018-06-28T09:07:40.464Z"}
puts JSON.generate(hash_with_time)
# => {"foo":"2018-06-28T09:07:40.464Z"}

puts JSON.generate({ foo: Foo.new }.with_indifferent_access)
# => {"foo":{}}
puts({ foo: Foo.new }.to_json)
# => {"foo":{}}
```

**Comment by ohler55** [comment]
More checking I suppose.

**Comment by ohler55** [comment]
I'm not sure I can get this resolved without special casing each type. What I see is when a Hash contains a Time then the `to_json` method is called on it. If the Hash contains something that is not a time then `to_s` is called. I'm still trying to get the patterns and exceptions identified but so far I have not seen any consistency with the JSON gem.

**Comment by ElMassimo** [comment]
@faucct FYI, the `raw_json` option added in #542 might be what you need to implement `SerializedJSON`.

A sample implementation, only `raw_json` needs to be implemented, but providing the code as-is:

```ruby
# Public: Allows to prevent double encoding an existing JSON string.
#
# NOTE: Oj's raw_json option means there's no performance overhead, as it would
# occur with the previous alternative of parsing the JSON string.
class JsonValue
  # Helper: Expects an Array of JSON-encoded strings and wraps them in a JSON array.
  def self.array(json_rows)
    new("[#{ json_rows.join(',') }]")
  end

  # Helper: Expects a JSON-encoded string and wraps them in a JSON object.
  def self.object(json_values)
    new("{#{ json_values }}")
  end

  def initialize(json)
    @json = json
  end

  # Internal: Used by Oj::Rails::Encoder because we use the `raw_json` option.
  def raw_json(*)
    @json
  end

  # Internal: Used by Oj::Rails::Encoder when found inside a Hash or Array.
  def as_json(_options = nil)
    self
  end
end
```

**Comment by ohler55** [comment]
@faucct , did @ElMassimo's example take care of the issue?

**Comment by faucct** [comment]
Hello, I have already gave up on that idea, but I believe it would work.
