### ISSUE TITLE
OJ for MRuby

### ISSUE THREAD

**Issue by proyb6** [ohler55/oj#484]
Do you planning to support OJ on MRuby? I have not found someone create a binding and I think it can be faster than MRuby-JSON.

**Comment by ohler55** [comment]
I'll look into it. It does make sense to support mruby if it is reasonably straight forward to do so.

**Comment by ohler55** [comment]
Anyone interested in helping with getting Oj on mruby?

**Comment by proyb6** [comment]
If someone would build it, I suggest the APi could be compatible with MRuby-JSON so we can do a drop-in replacement easily.

**Comment by ohler55** [comment]
It would really have to be a different project to support MRuby. The C APIs are completely different.
