### ISSUE TITLE
Oj::Doc fetch values change when mixed with Oj.load

### ISSUE THREAD

**Issue by mrdanadams** [ohler55/oj#486]
I'm using `Oj::Doc` to iterate through a document. If I iterate through the same items again some of the values will intermittently be changed to be a totally unrelated object (like a pointer got pointed at the wrong memory address or something). It appears to be related to using `Oj.load` while I have a `Oj::Doc` open. I'm working with this as read-only and am not changing anything on the original doc.

I'm able to reproduce it (it fails most of the time and not always in the same way):

```ruby
# couldn't reproduce this without this many items and having both key and count
json = { aggregations: { hashtags: { buckets: Array.new(100) { { key: 'foo', count: 100 } } } } }.to_json
# lots of iterations helps reproduce it
100.times do
	Oj::Doc.open(json) do |doc|
		# this always passes
		doc.each_child('/aggregations/hashtags/buckets') do |bucket|
			expect(bucket.fetch('key')).to eq 'foo'
			expect(bucket.fetch('count')).to eq 100
		end

		# load any other json using Oj.load
		# this will pass
		other = Oj.load(json)
		other.dig('aggregations', 'hashtags', 'buckets').each do |bucket|
			expect(bucket.dig('key')).to eq 'foo'
			expect(bucket.dig('count')).to eq 100
		end

		doc.each_child('/aggregations/hashtags/buckets') do |bucket|
			# This is where it fails!!!! It will be some other object (even an rspec matcher in some cases)
			expect(bucket.fetch('key')).to eq 'foo'
			expect(bucket.fetch('count')).to eq 100
		end

		# this always passes if it gets this far
		other.dig('aggregations', 'hashtags', 'buckets').each do |bucket|
			expect(bucket.dig('key')).to eq 'foo'
			expect(bucket.dig('count')).to eq 100
		end
	end
end
```

**Comment by ohler55** [comment]
Thanks for the test case. I'm starting work on it now.

**Comment by ohler55** [comment]
I re-wrote the test to not use rails or a test suite and it worked fine until a GC was forced. It looks like some objects are being collected when they are still in use. I should be able to get that fixed.

**Comment by ohler55** [comment]
Please try the `win-time` branch. I'll release once I get the Windows time oddness worked out.

**Comment by ohler55** [comment]
Did it work for you?

**Comment by ohler55** [comment]
Is this still an issue or can it be closed?

**Comment by ohler55** [comment]
No response, closing.
