### ISSUE TITLE
Unable to load json object to custom object_class or hash_class

### ISSUE THREAD

**Issue by GeorgeKaraszi** [ohler55/oj#487]
I've been decoding a bunch of API requests lately, but something that has always confused me was the usage of `object_class` and `hash_class` options for the `.load` method.

So far I have been unsuccessful in being able to decode responses with either of these two options.

Example:
`Oj.load(raw_json_string, object_class: OpenStruct)`

 Returns standard Hash rather than a OpenStruct instance.

Is there something I'm missing or misunderstanding about this or is this a potential bug?

Ruby: 2.5.1
Oj: 3.6.4

**Comment by ohler55** [comment]
Check out the [Modes](http://ohler.com/oj/doc/file.Modes.html) page. The `:object_class` option is only available in `:compat` or `:custom` modes.

This worked for me.
```ruby
irb(main):001:0> Oj.load('{"a":23}', mode: :compat, object_class: OpenStruct)
=> #<OpenStruct a=23>
```

**Comment by GeorgeKaraszi** [comment]
Interesting.. I guess this was a case of me not understanding the `mode` option. Just tested it and verified it works.

Thanks @ohler55
