### ISSUE TITLE
Oj.optimize_rails makes dump escape `<` and `>`

### ISSUE THREAD

**Issue by ixti** [ohler55/oj#493]
Subj.

```
Loading development environment (Rails 4.2.10)
irb(main):001:0> Oj.dump :x => "<y>"
=> "{\"x\":\"<y>\"}"
irb(main):002:0> Oj.optimize_rails
=> nil
irb(main):003:0> Oj.dump :x => "<y>"
=> "{\"x\":\"\\u003cy\\u003e\"}"
```

Same in rails 5.x as well. Is that expected?

**Comment by ohler55** [comment]
What mode did you have Oj in on the first call? Calling `Oj.optimize_rails` puts Oj in rails mode with attempts to act the same as rails when calling the rails functions. It also sets the default for Oj to match rails. The specification for JSON does not call for `<` and `>` to be unicode but rails encodes them anyway so Oj attempts to do the same when in rails mode.

**Comment by ohler55** [comment]
Is there any reason to keep this open?

**Comment by ixti** [comment]
I'm really sorry for not getting back. I planned on getting back with details explanations in a moment, but then went to vacation...

So, I got your point. Although:

> Calling Oj.optimize_rails puts Oj in rails mode

Kinda conflicts with:

> Either of those steps will setup Oj to mimic Rails but it will not change the default mode type as the mode type is only used when calling the Oj encoding directly. If Rails mode is also desired then use the Oj.default_options to change the default mode.
> -- https://github.com/ohler55/oj/blob/master/pages/Rails.md

Closing this issue in any case, because my issue seems to be unrelated to Oj itself, but rather under/mis-configuration or some gem conflicts.

Thanks for your time and for amazing gem! :D

**Comment by ohler55** [comment]
Thanks for the explanation. Trying to keep up with rails and the JSON gems has been the cause of a majority of Oj issues since both have different ideas of what the correct encoding should be.
