### ISSUE TITLE
Update to 2.18.5 to 3.6.7 issue

### ISSUE THREAD

**Issue by JulienItard** [ohler55/oj#498]
Hello,

I just updated my old gem from 2.18.5 to 3.6.7.

It returns a `ActiveModel::ArraySerializer` instead of array directly. I only use `Oj.safe_load`

Am i missing something ? Didnt find something related in Changelog.

thanks !

**Comment by ohler55** [comment]
`Oj.safe_load` should not have changed. Lets see if we can figure out what is going on then either a work around will present itself of I'll make sure Oj gets fixed.

Do you have a simple test example I can run? Can you describe you environment? I'm guessing you are running in Rails.

**Comment by ohler55** [comment]
Are you still interested in this? I need more information before I can address the issue.

**Comment by ohler55** [comment]
No response. Closing.
