### ISSUE TITLE
JSON is too deeply nested (64 bits)

### ISSUE THREAD

**Issue by fcsonline** [ohler55/oj#50]
I have an issue loading JSON object with Oj in a set of machines. Some examples:

```
1.9.3p0 :016 > res=Oj.dump({:a=>'b'})
 => "{\":a\":\"b\"}"
1.9.3p0 :015 > Oj.load(res)
SystemStackError: JSON is too deeply nested
1.9.3p0 :015 > Oj.load('{}')
SystemStackError: JSON is too deeply nested
```

I'm have the same Ruby version 1.9.3p0 in both machines. The working machines are 32 bits (Ubuntu 10.04) and the failing machines are 64 bits (12.10 and 12.04).

Some suggestion?

**Comment by boof** [comment]
We'll I noticed this behaviour when my Gemfile uses oj and oj_mimic_json but also requires another lib that requires these libraries.

**Comment by ohler55** [comment]
If you can describe the problem and how to get it to show up, please open a new issue. This one is 2 years old and really unrelated to the current code base. If it is a problem I would like to get it fixed.
