### ISSUE TITLE
Crash in Oj 3.6.6 in mark_doc

### ISSUE THREAD

**Issue by jsrtr** [ohler55/oj#500]
I'm seeing crashes in mark_doc here:

https://sourcegraph.com/github.com/ohler55/oj@v3.6.6/-/blob/ext/oj/fast.c#L810

I don't have symbols in my environment, but the disassembling the mark_doc function and looking at the address of the faulting instruction shows the crash is after the call to rb_gc_mark.  I'm pretty sure that ->data isn't being initialized correctly somewhere.

**Comment by ohler55** [comment]
I'll look into it. Can you provide any sample code that caused the crash?

**Comment by jsrtr** [comment]
It's basically

``` ruby
Oj::Doc.open("[#{list of arrays}]") { |doc| 
  doc.each_child {
    pull out some array elements
    add to another data structure 
  } 
}
```

That gets called several thousand times in an outer loop, and each "doc" element is a few kilobytes at most, all strings and integers.

Given the same data and parsing logic, it won't crash in a synthetic minimal test case by itself.  It only seems to crash when running as part of a larger rails application and the "add to another data structure" step is a more heavyweight call.

**Comment by ohler55** [comment]
Ok, let me start by looking carefully at the code. I will need some way of testing though. Ideally I would like to be able to run the tests myself. Any help getting that set up even if it involves firing up rails would be helpful.

**Comment by ohler55** [comment]
No response. Closing.
