### ISSUE TITLE
SystemStackError (stack level too deep)

### ISSUE THREAD

**Issue by mattgilbertnet** [ohler55/oj#504]
I know similar issues have come up and been closed in the past, but I haven't found a fix among them for my case.

I have a tableless model called Attashment that is used to upload a file with carrierwave. (The "typo" in "Attashment" is to avoid potential naming conflict with "attachments" in the POST params.) In my uploader, I'm getting a "SystemStackError (stack level too deep)" at Oj.dump():
```
class Admin::UploadattashmentController < Admin::ApplicationController
  ...

  def attashment    
    @attashment = Attashment.new(body: params[:attachments].first)
    render json: Oj.dump([@attashment])
  end

...

end
```

Here's the model:
```
class Attashment
  extend CarrierWave::Mount
  include ActiveModel::Model
  mount_uploader :body, AttashmentUploader
end
```

I'm not sure how to replicate the problem since it involves uploading a file, but an example of the value of `params` is:
```
  Parameters: {"attachments"=>[#<ActionDispatch::Http::UploadedFile:0x007fbb88b671a0 @tempfile=#<Tempfile:/var/folders/m1/msw6k6ws5czb2m5nf2fpsr8h0000gn/T/RackMultipart20180923-16062-1d0mqs1.png>, @original_filename="test.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"attachments[]\"; filename=\"test.png\"\r\nContent-Type: image/png\r\n">]}
```

A similar model (that isn't tableless) doesn't run into this error, so I guess that means ActiveModel is calling itself somehow. Is there a way around this, or a way to get more info about the problem?

oj 3.6.10
Rails 5.1.3
ruby 2.3.1

**Comment by ohler55** [comment]
A stack exception is usually a circular reference. Have you tried the `:circular` option? Set that to `true` and see if that fixes the issue.

**Comment by mattgilbertnet** [comment]
I tried `:circular`, and there was no change. I eventually made Attashment a normal model rather than a tableless model. This avoids ActiveModel, and apparently, whatever loop it was causing. Carrierwave sorta requires a table anyway, so I guess that's fine.

**Comment by ohler55** [comment]
Glad it worked out. I am curious about what the issue was but if you are moving ahead there is no need to go back.
