### ISSUE TITLE
Is there a way to recover the old behaviour of JSON.parse allowing nil and empty strings?

### ISSUE THREAD

**Issue by barrucadu** [ohler55/oj#505]
Hello,

I'm trying to upgrade from 2.18.3 to 3.6.10, and have hit the change of behaviour described in #502.  Is there a way to recover the old behaviour?

This is how I'm currently trying to set up oj, in a rails initialiser in my app:

```ruby
require 'oj'

Oj.default_options = {
  nilnil: true,
  allow_blank: true,
}

Oj.optimize_rails
```

But `JSON.parse(nil)` throws an exception, and sending an empty string to a controller with the content type `application/json` throws an `ActionDispatch::Http::Parameters::ParseError` as Rails internally tries to decode it.

**Comment by ohler55** [comment]
By calling `Oj.optimize_rails` you are telling Oj to behave like rails and the JSON gem. The JSON gem raises and exception so Oj does as well as it mimics the gem. The earlier version of Oj was more tolerant than the JSON gem which caused people to complain that it was not mimicking correctly. 

The solution is to modify the place where the parse is attempted. Basically use a solution that works for your app with and without Oj. I'd be glad to help if I knew more about you app or where the `#parse` is being called.

**Comment by barrucadu** [comment]
There are a few instances of `JSON.parse` which I can change easily enough, but there's one case which is a bit trickier.  [We have a test that the app responds with a 400 when invalid JSON is sent](https://github.com/alphagov/publishing-api/blob/dc5310c199c81ac224fe82c9aae6cda10d8dbc13/spec/controllers/v2/content_items_controller_spec.rb#L451-L461): 
```ruby
    context "with invalid request body" do
      before do
        request.env["CONTENT_TYPE"] = "application/json"
        request.env["RAW_POST_DATA"] = ""
        put :put_content, params: { content_id: content_id }
      end

      it "responds with 400" do
        expect(response.status).to eq(400)
      end
    end
```

With the newer version of oj, the request doesn't seem to make it to our controller at all (which is what generates the 400), it looks like the Rails parameter decoding middleware is throwing an exception:
```
  12) V2::ContentItemsController put_content with invalid request body responds with 400
      Failure/Error: put :put_content, params: { content_id: content_id }
      
      ActionDispatch::Http::Parameters::ParseError:
        An empty string is not a valid JSON string.
      # ./spec/controllers/v2/content_items_controller_spec.rb:455:in `block (4 levels) in <top (required)>'
      # ./spec/rails_helper.rb:84:in `block (3 levels) in <top (required)>'
      # ./spec/rails_helper.rb:84:in `block (2 levels) in <top (required)>'
      # ------------------
      # --- Caused by: ---
      # JSON::ParserError:
      #   An empty string is not a valid JSON string.
      #   ./spec/controllers/v2/content_items_controller_spec.rb:455:in `block (4 levels) in <top (required)>'
```

I'm actually not too familiar with the current code, but I *think* the current behaviour is that this invalid JSON is parsed to `nil` by the oj-instrumented Rail, which is then handled elsewhere in the app (somewhere).

It's not the end of the world if we just have to be happy with this exception (and fix a few calls to `JSON.parse` elsewhere), but it would be nice to get the old behaviour back.

**Comment by ohler55** [comment]
The problem is not that it is too much work but that it would end up with Oj not being the same as not using Oj which would cause problems for other users. 

So what you want is to change the behaviour of rails since I presume you see the same error if you run without Oj. I looked for the `content_items_controller_spec.rb` file but did not find it in the rails 5.2.1 release. What version of rails are you using or where would I find the `content_items_controller_spec.rb` file?

**Comment by barrucadu** [comment]
It's a test from our app, linked from my comment

**Comment by ohler55** [comment]
Right, of course. Can you point me at the code that is being tested or is the the tough part you haven't figured out yet?

**Comment by barrucadu** [comment]
After a bit of discussion on our end, we've decided to just remove the test.

Testing that sending invalid JSON returns an error isn't a useful test with this updated version of oj, as really all it's testing is that Rails is working properly - and we trust Rails.

Thanks for your time

**Comment by ohler55** [comment]
Sounds like the best idea. Happy coding.
