### ISSUE TITLE
Oj::ParseError unexpected character

### ISSUE THREAD

**Issue by tmmgarcia** [ohler55/oj#506]
Hi, I'm trying to parse the following JSON using the OJ Gem. However, I can't see what is going wrong with my string.
```
params = "[{ \"day\" => \"2018-10-04\" }, {\"application\"=>\"West (test)\"}]"
Oj.load(params)
#Traceback (most recent call last):
#        3: from /home/tiago/.rvm/rubies/ruby-2.5.1/bin/irb:11:in `<main>'
#        2: from (irb):200
#        1: from (irb):200:in `load'
# Oj::ParseError (unexpected character ([0].day) at line 1, column 10 [parse.c:692])
```
I had look at the [Docs](https://www.rubydoc.info/github/ohler55/oj/Oj#default_options-class_method) and used different parameters to fix this issue but I had no success. 

Another thing, if I use `eval` I get the result I'm looking for.
```
eval(params)
=> [{"day"=>"2018-10-04"}, {"application"=>"West (test)"}]
```

I believe the expected result to `Oj.parse` should be the same as `eval` method.

I've done this test using ruby `2.5.1` and Oj `'~> 3.6', '>= 3.6.10'`.

I'd appreciate any help here. Thanks in advance.

**Comment by ohler55** [comment]
Close but not quite. Oj parses JSON the string `[{ "day" => "2018-10-04" }, {"application"=>"West (test)"}]` is not JSON. It is kind of a mix of Ruby and JSON. JSON would look like `[{ "day": "2018-10-04" }, {"application": "West (test)"}]`.

**Comment by tmmgarcia** [comment]
Yeah it makes totally sense. Shame on me. What I can do here is convert this weird format to "true json". 
Thanks for that.
