### ISSUE TITLE
Question: proper way to use with Sinatra

### ISSUE THREAD

**Issue by brauliobo** [ohler55/oj#507]
Hi,
when rendering with `json` engine (from https://github.com/sinatra/sinatra/blob/master/sinatra-contrib/lib/sinatra/json.rb) like in
```ruby
get do
  json message: 'blah'
end
```
What is the proper way to switch to Oj?

**Comment by brauliobo** [comment]
it seems it is enough to set in the `Base` controller:
```ruby
      set :json_encoder do                                                                                                                                                                   
        ::Oj                                                                                                                                                                                 
      end                                                                                                                                                                                    
```
Although I got only a 7% performance increase in a JSON intensive endpoint.

**Comment by ohler55** [comment]
I suspect there is enough other code being used that JSON encoding is only a small part of the overhead. I haven't looked at Sinatra to see what they are doing or how Oj is being used.
