### ISSUE TITLE
How can one interrupt JSON stream parsing?

### ISSUE THREAD

**Issue by laserlemon** [ohler55/oj#510]
First, I just want to say that using `Oj::ScHandler` is wonderful! It allows me to do some very detailed parsing of large streaming JSON inputs. But in many use cases, the values that are needed can be found well before we reach the end of the JSON stream.

&nbsp;&nbsp;&nbsp;&nbsp;💭 
🤔 How can I interrupt JSON stream parsing before reaching the end of the stream?

Any way I've tried so far raises a parser error, presumably because the parser has started/opened a number of objects and arrays without having closed them yet. For these use cases, that's fine! I don't actually care that the entire document is valid JSON or what any future values are. I just want to take the values that the parser has already found and built for me and go home. 😄

Can you give me any advice on how I might accomplish that? Unfortunately, while my Ruby is 💪, I'm not so good at reading the C source so I'm having some trouble deciding how to start.

Thank you for the wonderful gem and keep up the great work!

---

For example:

```ruby
class MyParser
  def initialize
    @current_depth = 0
  end

  def parse(file)
    Oj.sc_parse(self, file)
  end

  def hash_start
    @current_depth += 1
    {}
  end

  # Other Oj::ScHandler methods go below.
  # The parser's purpose is to find a specific value nested deep within the streaming JSON
  # and to stop parsing immediately afterward.
end

parser = MyParser.new
parser.parse(some_big_open_file)
parser.found_specific_value # => 42
```

**Comment by ohler55** [comment]
I’m away from the computer right now but will look at it. If there is not a way other than raising your own exception I will add a way.

**Comment by ohler55** [comment]
It looks like there is no nice way other than raising an exception to abort the parsing. So something like this will abort the parsing. If you use your own Exception class you can rescue on your own class to differentiate between a parse error and your detection of the value.

```ruby
    def add_value(v)
      raise Exception.new('Found it!`) if v == 42
    end
```

**Comment by laserlemon** [comment]
I thought `add_value` was only called at the end of a JSON document! I'll give that a shot and report back. Thank you!

**Comment by laserlemon** [comment]
Hmm, yeah it seems to only be called once, when the entire document has been read and parsed. I may just try the same approach within different callback methods. Thank you for your attention!

**Comment by ohler55** [comment]
Were you able to get it working?

**Comment by laserlemon** [comment]
Yes, with something like:

```ruby
class MyParser < Oj::ScHandler
  EarlyTermination = Class.new(StandardError)

  def parse(io)
    Oj.sc_parse(self, io)
  rescue EarlyTermination
    @special_value
  end

  # Many handler methods omitted here!

  def hash_set(hash, key, value)
    check_for_doneness!(value)
    hash[key] = value
  end

  def array_append(array, value)
    check_for_doneness!(value)
    array << value
  end

  private

  def check_for_doneness!(value)
    if special_conditions_met?
      @special_value = value
      raise EarlyTermination
    end
  end
end
```
