### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [ohler55/oj#514]
I would like to point out that identifiers like “[`__OJ_VAL_STACK_H__`](https://github.com/ohler55/oj/blob/91f9fcf005a36c9d788d4b0d7bb8f517031c6553/ext/oj/val_stack.h#L31 "Update candidate")” and “[`_ParseInfo`](https://github.com/ohler55/oj/blob/5c40e67aee3f2566c16486fa9052e2042e31e60e/ext/oj/parse.h#L38 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by ohler55** [comment]
Addressed in release Oj 3.7.6.
