### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [ohler55/oj#515]
Would you like to add more error handling for return values from functions like the following?
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex.") ⇒ [Init_oj](https://github.com/ohler55/oj/blob/2a36feff7e9c1c0a44745306c08b08416d0443f2/ext/oj/oj.c#L1701)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [oj_reg_odd](https://github.com/ohler55/oj/blob/503e470834a7883a662c7052447c30a06acded9d/ext/oj/odd.c#L186)

**Comment by ohler55** [comment]
Addressed in release Oj 3.7.6.

**Comment by elfring** [comment]
Thanks for your source code adjustments.

How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for [this software](https://github.com/ohler55/oj/blob/2a36feff7e9c1c0a44745306c08b08416d0443f2/ext/oj/resolve.c#L70 "Update candidate: oj_name2class()")?

**Comment by ohler55** [comment]
I've been looking at Cppcheck but so far have not spent the time to configure it and make it part of my development cycle.
