### ISSUE TITLE
Error when deserializing lazily loaded class

### ISSUE THREAD

**Issue by skliew** [ohler55/oj#518]
Oj version used: 3.7.4.

Using a simplified example as follows:
```
require 'oj'
class MyKlass
end

class LazyKlass
  def self.const_missing constant
    const_set(constant, MyKlass)
  end
end

string = '{"^o":"LazyKlass::AAA"}'
result = Oj.load(string)
puts result
```

Running the above script results in an error:
` class LazyKlass::AAA"} is not defined (^o) at line 1, column 21 [resolve.c:62] (ArgumentError)`

This was found when the serializing and deserializing are done in different Ruby instances. One solution is to eagerly load the lazily loaded classes beforehand. Just thinking if this could be/would be better solved at the library level?

**Comment by ohler55** [comment]
Looks like it is working as expected. You are using `:object` mode. It you don't want that mode change the defaults or add a different mode option when calling `#load`. http://ohler.com/oj/doc/file.Modes.html describes the modes.

**Comment by skliew** [comment]
In my case, the serialization is also done using the `:object` mode. The result of it is the value of the `string` variable in the above example.  The result is then stored and consumed in another Ruby instance which does not have the lazily loaded class loaded yet.

I guess I would have to eagerly load the classes before deserializing my json string then. Cheers. Thanks for the great library :)

**Comment by ohler55** [comment]
There is an option to create a dummy class that has the data fields but no extra methods if that helps.
