### ISSUE TITLE
StreamWriter push encoding fails

### ISSUE THREAD

**Issue by ohler55** [ohler55/oj#524]
Oddly enough, when pushing ASCII characters with UTF-8 encoding or even ASCII-8BIT does not change the output encoding. Pushing any non-ASCII no matter what the encoding changes the output encoding to ASCII-8BIT. Related to PR #523 

Thanks  @PikachuEXE for finding this.

**Comment by ohler55** [comment]
Branch `encoding` has a fix.

**Comment by PikachuEXE** [comment]
I have tested the branch with test script and actual implementation (that triggers the bug)
And the branch seems working

**Comment by PikachuEXE** [comment]
Anything left to be done on `encoding` branch?

**Comment by PikachuEXE** [comment]
Oh I see [new version released](https://github.com/ohler55/oj/commit/e92ab2b2feb864229aec265daee1307d446be8c2)
Let me close this

**Comment by ohler55** [comment]
:-) I wanted to track the fix with an issue. I'll close it now. Thanks for finding the issue.
