### ISSUE TITLE
create_opt can only return NULL

### ISSUE THREAD

**Issue by enebo** [ohler55/oj#527]
It appears create_opt unconditionally returns NULL:

https://github.com/ohler55/oj/blob/1020f3d54a42e5355b795647fcf8654306c42a9f/ext/oj/rails.c#L636

but optimimize checks result to set on to true/false (although it will still set it to true in create_opt):

https://github.com/ohler55/oj/blob/master/ext/oj/rails.c#L754

I believe with optimize this happens to work but for deoptimize it will turn on the passed type to optimizing.  I am just starting to port this code now to Java (and it is still not baked in my brain yet) so I half wonder if perhaps passing 'on' to create_opt and making it a void would be a reasonable change?

**Comment by ohler55** [comment]
Good catch.  I'll fix that immediately.

**Comment by ohler55** [comment]
Fixed in January.
