### ISSUE TITLE
to_json Subtracting Day From Time

### ISSUE THREAD

**Issue by cmr119** [ohler55/oj#529]
We noticed this issue when trying to index an object in Elasticsearch.  A date/time field on the object had a value of `2003-03-01T15:14:54Z`, but Elasticsearch raise an invalid date error trying to index `2003-02-29T15:14:54Z`.  We send json to Elasticsearch, which is how we tracked this issue down.
```
(2000..2019).map { |year| Time.parse("#{year}-03-01T15:14:54Z").to_json }
=> ["\"2000-03-01T15:14:54.000Z\"",
 "\"2001-02-29T15:14:54.000Z\"",
 "\"2002-02-29T15:14:54.000Z\"",
 "\"2003-02-29T15:14:54.000Z\"",
 "\"2004-03-01T15:14:54.000Z\"",
 "\"2005-03-01T15:14:54.000Z\"",
 "\"2006-03-01T15:14:54.000Z\"",
 "\"2007-03-01T15:14:54.000Z\"",
 "\"2008-03-01T15:14:54.000Z\"",
 "\"2009-03-01T15:14:54.000Z\"",
 "\"2010-03-01T15:14:54.000Z\"",
 "\"2011-03-01T15:14:54.000Z\"",
 "\"2012-03-01T15:14:54.000Z\"",
 "\"2013-03-01T15:14:54.000Z\"",
 "\"2014-03-01T15:14:54.000Z\"",
 "\"2015-03-01T15:14:54.000Z\"",
 "\"2016-03-01T15:14:54.000Z\"",
 "\"2017-03-01T15:14:54.000Z\"",
 "\"2018-03-01T15:14:54.000Z\"",
 "\"2019-03-01T15:14:54.000Z\""]
```
For years 2001-2003 when calling `to_json` on any date after February 28th a day is subtracted from the output.

We are using version `3.7.9` and calling `Oj.optimize_rails` in an initializer.

**Comment by ohler55** [comment]
I'll look in to it. There was a recent change to the date conversions to handle dates before 1970 so that where I am guessing the bug would be.

**Comment by ohler55** [comment]
I just pushed a fix to master. I will release tomorrow assuming there are no objections. Saving the release for 𝜋 day.

**Comment by cmr119** [comment]
Thanks for the quick fix!

**Comment by ohler55** [comment]
Released.

**Comment by ohler55** [comment]
Ok to close?

**Comment by cmr119** [comment]
Yes sir.  Thanks again!
