### ISSUE TITLE
symbolize_names option not working with specific setup

### ISSUE THREAD

**Issue by augustocravosilva** [ohler55/oj#530]
Hey,

I have this config
```ruby
Oj::Rails.set_encoder()
Oj::Rails.set_decoder()
Oj::Rails.optimize()
```

And realized this is broken:
```ruby
>>  JSON.parse('{"a":1}', symbolize_names: true)
=> {"a"=>1}
``` 

If I add `Oj::Rails.mimic_JSON()`, `symbolize_names` does work. In the docs it says that `set_decoder` should also monkey-patch `JSON.parse` but something seems to be missing.

Looks like a bug, maybe related to https://github.com/ohler55/oj/issues/400

I am using the latest gem version, rails `5.1.6`, ruby `2.5.3`

Thanks

**Comment by ohler55** [comment]
I'll take a look in the next day or two.

**Comment by ohler55** [comment]
Released this morning.

**Comment by ohler55** [comment]
Good to close?

**Comment by augustocravosilva** [comment]
👍 thanks a lot!
