### ISSUE TITLE
Test with Rails 4.2, 5.2, 6.0 (RC)?

### ISSUE THREAD

**Issue by aried3r** [ohler55/oj#535]
Hey, I just saw that oj is being tested with Rails 4.1.x which is EOL and Rails 5.0.2 specifically. Soon, there will also be Rails 6 released, a RC1 is already released and a `6-0-0-stable` branch cut. I think Rails 4.2 will be EOL once Rails 6 is released, but of course that doesn't mean oj shouldn't support it, unless it requires a lot of additional work.

How does oj's testing strategy work? Personally I'd love to see the currently supported Rails versions being tested, but that might increase test run time a lot, so maybe testing 4.2.x, 5.2.x and 6.0.x should be ok?

And as for Ruby versions, I see [only 2.3 and above](https://github.com/ohler55/oj/blob/06a626f4857cb02548773f88ca850776b2e88b03/.travis.yml#L12-L16) (making [this](https://github.com/ohler55/oj/blob/06a626f4857cb02548773f88ca850776b2e88b03/.travis.yml#L27-L28) obsolete I think) being tested while the `.gemspec` file says [`>= 2`](https://github.com/ohler55/oj/blob/06a626f4857cb02548773f88ca850776b2e88b03/oj.gemspec#L23).

https://weblog.rubyonrails.org/2019/4/27/this-week-in-rails-rails-6-0-0-rc1-is-here-say-hi-at-railsconf/
https://guides.rubyonrails.org/maintenance_policy.html

**Comment by ohler55** [comment]
Thanks, I'll do some CI cleanup this weekend.

**Comment by ohler55** [comment]
I've made the updates to the .travis file as you suggested.

As for testing, Oj has its own tests but also uses the tests from the JSON gem and Rails. When rails is officially released I'll take the same approach with rails 6 and copy the tests and make sure Oj supports them. I anticipate a significant change in Oj if it needs to support both rails 5 and rails 6 as usually rails make breaking changes to the use of JSON. Will have to wait and see.

**Comment by aried3r** [comment]
I see, thank you! Do you plan to keep supporting Rails 4? In which case I'd suggest copying the JSON tests from the latest 4.2 and 5.2 release, what do you think?

**Comment by ohler55** [comment]
I'll most likely drop support for rails 4 when 6 becomes official. That doesn't mean Oj will no longer work with rails 4 but it will no longer be tested against 4.

I should update the tests for rails 5.2 but have not gotten to it yet.

**Comment by aried3r** [comment]
I believe this can be closed once #562 is merged, unless you want to update the test cases for the EOL Rails versions as well.

**Comment by ohler55** [comment]
Agree, it can be closed.
