### ISSUE TITLE
Float deserialization giving a floating point issue

### ISSUE THREAD

**Issue by BuonOmo** [ohler55/oj#538]
Hi,

I see this issue has come many times, but it looks like floating point float deserialization stroke again.

I still get a similar issue as #181 in `3.7.12`, macos `10.14.3` and also heroku machines (`4.4.0-1042-aws #45-Ubuntu`) (Ruby `2.5.3`, although I guess it doesn't matter):

```rb
> Oj.strict_load("48.949268")
 => 48.949268000000004 
```

If need be, I can give you any more information that bash has. I'd be ready to help, but C in not where I am the best.

**Comment by ohler55** [comment]
That should be enough. I'll see what I can do to for this recurring problem.

**Comment by ohler55** [comment]
The issue is converting a long double to a double. For 48.949268 a double is only accurate to 16 places. The `rb_float_new()` function creates a Ruby decimal that thinks it is good to 17 places. I haven't given up yet. I'm trying to find a way to force the accuracy on the Ruby decimal after it is created.

**Comment by BuonOmo** [comment]
Have you got any news on this one? I'm trying to investigate as well. It seems like `rb_float_new()` either defines a float on the stack or on the heap depending on the float size and `USE_FLONUM` macro.

```c
#if SIZEOF_VALUE >= SIZEOF_DOUBLE
#define USE_FLONUM 1
#else
#define USE_FLONUM 0
#endif
```

This explains that we may have no issues on x32 computers since double is preserved. You may already know of that, I'm progressing by little steps unfortunately. Could you help me by telling whether I'm in a great direction? I also guessed that the interesting part in Oj's source code is `leaf_float_value()`.

**Comment by ohler55** [comment]
I suspect you will find that the approach is very slow. You might try the approach with numbers that are both much larger and much smaller and see if the approach still holds. Maybe 0.000000000012345678  1.2345e16 for example

**Comment by BuonOmo** [comment]
@ohler55 I think I just found something very interesting: using only `double` rather than long double seems to work. Moreover, it looks like this is a common practice. I'm currently opening a PR for you to see what it implies :)

**Comment by ohler55** [comment]
I started using long double when parsing as it does not round off early. What might work is casting to a double first like you did in the sprint example.

**Comment by BuonOmo** [comment]
Exactly, take a look at my PR. I'm just waiting for tests to pass on the CI 😄
