### ISSUE TITLE
`.to_json` ignores `.as_json` but `render json:` doesn't

### ISSUE THREAD

**Issue by omnibs** [ohler55/oj#540]
I'm struggling to understand this behavior, not sure if I'm approaching things with the wrong expectation here or if I'm misunderstanding the modes and settings, but I can't find a way to make `.to_json` and `render json:` to have consistent behavior when overriding `as_json`.

In my `application.rb`:

```ruby
require 'oj'

Oj::Rails.set_encoder()
Oj::Rails.set_decoder()
Oj::Rails.optimize()
Oj::Rails.mimic_JSON()
```

A `Module` with overridden `as_json`:

```ruby
module Something
  def self.as_json(_opts = nil)
    { tag: :Submitted }
  end
end
```

* When I `render json: Something` I get `{"tag":"Submitted"}`
* When I `Something.to_json` I get `"Something"`

An example app demonstrating the behavior: https://repl.it/repls/ComfortableWhoppingWorkspaces

**Comment by ohler55** [comment]
I feel your pain. I have struggled for a long time to mimic the rails and JSON behavior when they are combined. It is very finicky.

I suspect you will see similar behavior with rails and the JSON gem. I believe `render` will use rails while `.to_json` uses the JSON gem. Oj does it's best to mimic that behavior. Having said that, it seems odd that the class name is returned. What does the `to_json` method look like?

Something you could try would be to put the `Oj::Rails.mimic_JSON()` before the OJ rails calls.

**Comment by omnibs** [comment]
Thanks for the quick response! It helps to know I'm not misunderstanding the docs and this is actually hard! =]

I'll do some more testing soon and report back!

> What does the `to_json` method look like?

I'm not sure what you mean by what does it look like. Like, what code paths it actually executes? I'm not sure how to check that besides `pry` and stepping into things, so if you have any tips on how to check this I'd be super thankful!

**Comment by ohler55** [comment]
There are some trace options that can be used. Oj has a trace option as well.

I think you will find that the JSON gem sets up the `to_json` methods directly and does not call `as_json`. With rails in the mix then `as_json` is called when encoding as JSON. Generally avoid direct calls to `to_json` to avoid issues. If using rails call the rails encoder and decoders.

**Comment by ohler55** [comment]
Any thing else I can help you with?

**Comment by omnibs** [comment]
Sorry for the lack of comm, I haven't poked at this again and don't know when I'll have time. Closing the issue. Will reopen if I have any trouble.

Thanks for the help!

**Comment by KJTsanaktsidis** [comment]
I just ran into this, I'm fairly certain it's because `render :json` passes options to `to_json` - a hash with keys `:prefixes`, `:template`, and `:layout`. Oj sees these options in `Oj::Rails::Encoder.new`, saves them, and then when running `Oj::Rails::Encoder#encode`, sees that options were passed and thus realises that it must call `#as_json` because options were present: https://github.com/ohler55/oj/blob/0032fbb15f5ec73bde62bf966cfd0130943ecd6d/ext/oj/rails.c#L1343

I might try and solve this in our app by overwriting what `render json:` does to not pass any options. Perhaps this is also something that `optimize_rails` could do?

**Comment by KJTsanaktsidis** [comment]
I opened a new issue to discuss this specific problem with render json I discovered: https://github.com/ohler55/oj/issues/913
