### ISSUE TITLE
String including a backslash throws Oj::ParseError (invalid escaped character)

### ISSUE THREAD

**Issue by ezekg** [ohler55/oj#541]
Using Rails compat, I'd expect Oj to match JSON's behavior for strings containing backslashes. I'd rather not throw for such a small thing. Is there an option for this that I may be missing?

## My Rails initializer

```ruby
require 'oj'

Oj::Rails.tap do |oj|
  oj.set_encoder
  oj.set_decoder
  oj.optimize
  oj.mimic_JSON
end
```

## Using Oj

```
> Oj.load('{"test":"random_\$escaped/symbols\;here"}')
Traceback (most recent call last):
        3: from (irb):15
        2: from (irb):15:in `rescue in irb_binding'
        1: from (irb):15:in `load'
Oj::ParseError (invalid escaped character (test) at line 1, column 17 [parse.c:269])
```

## Using JSON

```
> JSON.parse('{"test":"random_\$escaped/symbols\;here"}')
 => {"test"=>"random_$escaped/symbols;here"}
```

**Comment by ohler55** [comment]
To be fair, a string element in JSON has rules around the use of backslashs. A `\n` is fine. A `\$` is not. If you want to encode a string that includes a backslash then Oj should be fine. The string you are encountering is not valid JSON and should cause an error in any JSON parser.

**Comment by ezekg** [comment]
Okay, fair enough. I have some light fuzzing in my integration tests and this came up while testing the move to Oj. I suppose expecting a JSON parse error there is reasonable, since it shouldn't have worked in the first place.

**Comment by ohler55** [comment]
Is this something you see in production or just in your unit tests?

**Comment by ezekg** [comment]
This particular case is only for integration tests, but users are users (lol) and they send me the weirdest data. I try to return useful error messages when possible. I just wasn't sure if it was a bug or not. It's fine either way, as I can adjust my tests to expect Oj behavior.

**Comment by ohler55** [comment]
Okay to close?
