### ISSUE TITLE
When using Oj.optimize_rails it ignores Oj.default_options

### ISSUE THREAD

**Issue by romankovt** [ohler55/oj#543]
Hello,
First of all, thank you for the amazing work you've done with optimizing json serialization.
When we enabled Oj.optimize_rails in our rails project we got some of our specs failed due to changes of float precision (gem default is 16).

We tried to workaround this issue with setting the default float precision to nil or a higher value 

```ruby
Oj.default_options = { float_precision: nil } 
Oj.optimize_rails
```
But when we use ::optimize_rails it looks like it ignores the default value and precision is always 16 digits anyway.

We are using rails 5.2.3, ruby 2.5.1 and oj 3.7.12

**Comment by ohler55** [comment]
Oj does not support `:float_precision` in rails mode. Take a look at http://www.ohler.com/oj/doc/file.Modes.html. Since Oj is attempting to mimic rails and rails does not have that option it is not available.

**Comment by romankovt** [comment]
@ohler55, sorry, my bad, you've clearly stated in the docs that significant digits in Ruby\Rails and Oj differs

> Optimized Floats set the significant digits to 16. This is different than Ruby which is used by the json gem and by Rails. Ruby varies the significant digits which can be either 16 or 17 depending on the value.

So after using Oj in Rails I've got something like which led to some specs failed:
```ruby
# with default Rails
1.123456789123456789.to_json
=> "1.1234567891234568"
# with Oj
1.123456789123456789.to_json
=> "1.123456789123457"
```
I believe it's intended behaviour, so I'm gonna close the issue.
