### ISSUE TITLE
Expected JSON::ParserError, received Oj::ParseError

### ISSUE THREAD

**Issue by TGRGIT** [ohler55/oj#555]
https://github.com/TGRGIT/oj/tree/parse_error has test case added to demonstrate in https://github.com/TGRGIT/oj/blob/6464d21c1c4c76fa78527273ea218d19643b20c8/test/json_gem/json_common_interface_test.rb#L122

```
def test_attribute_error_behaviour
    assert_raise(JSON::ParserError) { JSON.load('name=', nil, :allow_blank => true) }
end
```

Alternative simple script to reproduce:

```
require 'oj'
Oj.mimic_JSON()

begin
::JSON.load('name=&email=&subject=&comment=&submit=Send+Message')
rescue ::JSON::ParserError
end
```

Using ruby 2.6.3, the above raises Oj::ParseError, when JSON::ParserError was expected. 

ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]

(Also tested as occurring on linux - ruby 2.6.2)

*** LOCAL GEMS ***

bigdecimal (default: 1.4.1)
bundler (default: 1.17.2)
cmath (default: 1.0.0)
csv (default: 3.0.9)
date (default: 2.0.0)
dbm (default: 1.0.0)
debase (0.2.4, 0.2.3.beta5)
debase-ruby_core_source (0.10.5)
did_you_mean (1.3.0)
e2mmap (default: 0.1.0)
etc (default: 1.0.1)
fcntl (default: 1.0.0)
fiddle (default: 1.0.0)
fileutils (default: 1.1.0)
forwardable (default: 1.2.0)
gdbm (default: 2.0.0)
gem-wrappers (1.4.0)
io-console (default: 0.4.7)
ipaddr (default: 1.2.2)
irb (default: 1.0.0)
json (default: 2.1.0)
logger (default: 1.3.0)
matrix (default: 0.1.0)
minitest (5.12.0, 5.11.3)
mutex_m (default: 0.1.0)
net-telnet (0.2.0)
openssl (default: 2.1.2)
ostruct (default: 0.1.0)
power_assert (1.1.5, 1.1.3)
prime (default: 0.1.0)
psych (default: 3.1.0)
rake (12.3.3, 12.3.2)
rake-compiler (1.0.8)
rdoc (default: 6.1.0)
rexml (default: 3.1.9)
rss (default: 0.2.7)
ruby-debug-ide (0.7.0.beta7)
rvm (1.11.3.9)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
shell (default: 0.7)
stringio (default: 0.0.2)
strscan (default: 1.0.0)
sync (default: 0.5.0)
test-unit (3.3.3, 3.2.9)
thwait (default: 0.1.0)
tracer (default: 0.1.0)
webrick (default: 1.4.2)
wwtd (0.9.1)
xmlrpc (0.3.0)
zlib (default: 1.0.0)

**Comment by ohler55** [comment]
I'll take a look.

**Comment by ohler55** [comment]
Please try out the mimic-parse-error branch.

**Comment by TGRGIT** [comment]
As a test I ran https://gist.github.com/TGRGIT/55b2ab22bd90c1a3392c76653bf4263f

Expected outcome: I would have expected a JSON::ParserError error to have been caught by the rescue block.

Actual outcome: Unexpected Oj::ParseError error raised

```
➜  oj git:(mimic-parse-error) ✗ ruby -v

ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]

➜  oj git:(mimic-parse-error) ✗ ruby test.rb

Traceback (most recent call last):

1: from test.rb:5:in <main>

test.rb:5:in load': not a number or other value () at line 1, column 1 [parse.c:414] in 'name=&email=&subject=&comment=&submit=Send+Message (Oj::ParseError) ```

**Comment by ohler55** [comment]
The exact same test worked for me but I did one thing differently. I specified the path to the local Oj instead of the gem. So, if you have the repo at `~/git/oj` you would run the test like this.

```
ruby -I ~/git/oj/ext -I ~/git/oj/lib test.rb
```

**Comment by TGRGIT** [comment]
Aha! you are indeed correct, that works. Thank you!

**Comment by ohler55** [comment]
Released.
