### ISSUE TITLE
About escaping specific characters

### ISSUE THREAD

**Issue by pocari** [ohler55/oj#557]
The difference between jsonization of specific characters and to_json occurs.
Is this the intended result?

```
[1] pry(main)> Oj.default_options = { mode: :compat }
=> {:mode=>:compat}
[2] pry(main)> "<&>".to_json
=> "\"\\u003c\\u0026\\u003e\""
[3] pry(main)> Oj.dump("<&>")
=> "\"<&>\""
```

I thought compatibility was important, so I added the following processing.

```
module ExtendOj
  def dump(obj)
    result = super(obj)
    result.gsub!("&", '\\u0026')
    result.gsub!("<", '\\u003c')
    result.gsub!(">", '\\u003e')
    result
  end
end
Oj.singleton_class.prepend(ExtendOj)
```

**Comment by ohler55** [comment]
What mode are you using? Oj has many options. Some options control the way certain characters are encoded.

**Comment by pocari** [comment]
@ohler55 I use `Oj.default_options = { mode: :compat }` only.

**Comment by pocari** [comment]
@ohler55 Oh,  `Oj.default_options = { mode: :compat, escape_mode: :xss_safe }` !!

**Comment by pocari** [comment]
Thanks!!

**Comment by ohler55** [comment]
Try setting the `:escape_mode` to `:xss_safe`.

**Comment by ohler55** [comment]
Oops you already discovered that. :-)

**Comment by pocari** [comment]
I was able to find it thanks to your hints! Thank you!

**Comment by pocari** [comment]
@ohler55 
Ah, in case of "escape_mode:: xss_safe", there was no problem for "<", "&", ">".

However, regarding "/", to_json is not escaped, but Oj.dump has escaped it.

```
[1] pry(main)> Oj.default_options = { mode: :compat, escape_mode: :xss_safe }
=> {:mode=>:compat, :escape_mode=>:xss_safe}
[2] pry(main)> "/<&>".to_json
=> "\"/\\u003c\\u0026\\u003e\""
[3] pry(main)> Oj.dump("/<&>")
=> "\"\\/\\u003c\\u0026\\u003e\""
```

I wanted the default to_json behavior of ruby(rails?).

**Comment by ohler55** [comment]
If you use the `:rails` mode the characters will be escaped. Not the `/` though. That is the rails behaviour. Rails and the JSON gem have different behaviours and that changes in rails versus outside rails.

**Comment by pocari** [comment]
@ohler55 Thanks. `:rails` mode worked correctly in my case!
