### ISSUE TITLE
RubyDoc not working

### ISSUE THREAD

**Issue by aried3r** [ohler55/oj#559]
On if you click on a link like "Rails" https://rubydoc.info/gems/oj, you are taken to https://rubydoc.info/gems/oj/file/Rails.md which is a 404. This works on ohler.com http://www.ohler.com/oj/doc/file.Rails.html.

Is there a way to have both working?

**Comment by ohler55** [comment]
I haven't been able to get the rubydoc version to work. Not sure why the files are not copied or copied to some other place.

**Comment by ohler55** [comment]
Not much I can do about rubydocs. Please use http://ohler.com/oj/index.html.

I'm closing this issue as it is not something I can do here to fix the issue.
