### ISSUE TITLE
Inconsistent behaviour of `second_precision` during dump

### ISSUE THREAD

**Issue by smanolloff** [ohler55/oj#567]
Hey there,

turns out that, at some point (I would assume after v3) seconds precision is omitted when the fractional part is 0:

```ruby
RUBY_VERSION
# => "2.5.5"

Oj::VERSION
# => "3.9.0"

Oj.default_options
# => {:indent=>2,
#  :second_precision=>3,
#  :circular=>false,
#  :class_cache=>true,
#  :auto_define=>false,
#  :symbol_keys=>true,
#  :bigdecimal_as_decimal=>true,
#  :create_additions=>false,
#  :use_to_json=>false,
#  :use_to_hash=>false,
#  :use_as_json=>false,
#  :use_raw_json=>false,
#  :nilnil=>false,
#  :empty_string=>true,
#  :allow_gc=>true,
#  :quirks_mode=>true,
#  :allow_invalid_unicode=>false,
#  :allow_nan=>false,
#  :trace=>false,
#  :safe=>false,
#  :float_precision=>16,
#  :mode=>:custom,
#  :integer_range=>nil,
#  :escape_mode=>:json,
#  :time_format=>:xmlschema,
#  :bigdecimal_load=>:bigdecimal,
#  :create_id=>nil,
#  :space=>nil,
#  :space_before=>nil,
#  :object_nl=>nil,
#  :array_nl=>nil,
#  :nan=>:auto,
#  :omit_nil=>false,
#  :hash_class=>nil,
#  :array_class=>nil,
#  :ignore=>nil}

Oj.dump(Time.utc(2000, 1, 1, 0, 0, 0.1))
# => "\"2000-01-01T00:00:00.100Z\""

Oj.dump(Time.utc(2000, 1, 1, 0, 0, 0.0))
# => "\"2000-01-01T00:00:00Z\""    # <--- seconds precision missing
```

My workaround for now is to add 1ms in these cases to ensure the fractional digits are there.

Can you make it consistent (ie. the last example should produce `2000-01-01T00:00:00.000Z`), like it used to be in v2? I'd be glad to provide more information if needed.

Cheers!

**Comment by ohler55** [comment]
When you say v1, v2, and v3, what are you referring to? Major Oj versions or something else?

I'm not sure when the change was made but I'll look into it and consider possibilities.

**Comment by smanolloff** [comment]
I mean major versions, since we upgraded from 2.17.4 to 3.9.0 recently when this came up.
Here is the behaviour with the old version:
```ruby
Oj.dump(Time.utc(2000, 1, 1, 1, 0, 0, 0), mode: :compat)
# => "\"2000-01-01T01:00:00.000Z\""

RUBY_VERSION
# => "2.4.6"

Oj::VERSION
# => "2.17.4"

Oj.dump(Time.utc(2000, 1, 1, 1, 0, 0, 0), mode: :compat)
=> "\"2000-01-01T01:00:00.000Z\""     # <- seconds precision is present
```
(we had to migrate from `:compat` to `:custom` due to differences in the time and decimal serialization between 2.17.4 and 3.9.0 in `:compat` mode)

**Comment by ohler55** [comment]
As of Oj 3.x the JSON gem tests are used to test the `:combat` mode behaviour. I can take a look at what the JSON gem does but that could be the reason for the change.

**Comment by ohler55** [comment]
Odd, the JSON gem outputs `"\"2000-01-01 00:00:00 UTC\""` for me and Oj does the same.  I can get the results you describe in custom mode but not :compat mode.

**Comment by smanolloff** [comment]
Keep in mind that for compat mode I am using ruby 2.4.6 and oj 2.17.4 (as I can't compile it with ruby 2.5)

**Comment by ohler55** [comment]
ok, I try with and older Ruby version but stay with the latest Oj.

**Comment by ohler55** [comment]
Ruby 2.4.6 with Oj 3.9.2 outputs

```ruby
irb(main):001:0> Oj.dump(Time.utc(2000, 1, 1, 1, 0, 0, 0), mode: :compat)
=> "\"2000-01-01 01:00:00 UTC\""
```
 If you want XSD time format you will need the custom mode. I did see that when there are no fractional seconds no fractional parts are shown even when `:second_precision` is set. That is a bug I can fix. As for output a format that is not compliant with the JSON gem in `:compat' mode, that kind of breaks the mimicking of the gem so I don't want to break compatibility. Would fixing the bug in custom mode take care of your issue?

**Comment by smanolloff** [comment]
Yes, fixing the bug in `:custom` mode is exactly what I need!

(we have already migrated from `:compat` to `:custom` mode since we upgraded, I just gave the `:compat` output with the old version for reference, sorry if that was confusing)

**Comment by ohler55** [comment]
Release 3.10.0 includes a fix for this issue.

**Comment by ohler55** [comment]
Can this be closed?

**Comment by smanolloff** [comment]
Yes, we are already using oj 3.10.0 on production and this issue seems solved.
Thank you very much 🍺
