### ISSUE TITLE
Strange behavior with optimize_rails and BigDecimal

### ISSUE THREAD

**Issue by kapcod** [ohler55/oj#568]
We're still at Rails 4.2 so maybe all of this is outdated, but still.
It's documented that :bigdecimal_as_decimal isn't available for mode: :rails. However, if I run it like this:
```ruby
Oj.optimize_rails
Oj.default_options = { mode: :rails, bigdecimal_as_decimal: true }
```
It does the job - Oj dumps BigDecimal as number.
If I later add `bigdecimal_as_decimal: true` explicitely in the `dump` it works for single number dump, but not for Hash.
```ruby
Oj.dump(BigDecimal('1.2')) # => "1.2"
Oj.dump({a: BigDecimal('1.2')}) # => "{\"a\":1.2}"
Oj.dump(BigDecimal('1.2'), bigdecimal_as_decimal: true) # => "1.2"
Oj.dump({a: BigDecimal('1.2')}, bigdecimal_as_decimal: true) # => "{\"a\":\"1.2\"}" - unexpected
```

Also when I remove running `Oj.optimize_rails`, Oj ignores `bigdecimal_as_decimal` and dumps BigDecimal as string.

Currently, it works OK for me, just wanted to check what's the expected behavior and if it should be aware when upgrading Rails or Oj.

Tested with latest Oj.

Thanks

**Comment by ohler55** [comment]
Actually, the Oj documentation on the pages/mode.md file indicates the :bigdecimal_as_decimal option is available but there is a footnote, number 3.

I suspect what you are seeing is the mode you are in is compat mode (JSON gem mimicking). That always outputs a string. Check the mode and see if that is the case. Each mode is different as there is no standard and each encoder has different ideas about what is correct. Oj gives options to match either approach or at least that is the intent.

**Comment by crazyshot** [comment]
No, I was talking about inconsistency that when you put the option in
"default_options" it works, but when put directly into 'dump' it reverts
the behavior to string.

**Comment by ohler55** [comment]
I see, I'll look into it.

**Comment by ohler55** [comment]
Release 3.10.0 includes a fix for this issue.

**Comment by ohler55** [comment]
Can this be closed?

**Comment by crazyshot** [comment]
Sorry for delayed check. I can see it still happens:
[6] pry(main)> Oj.default_options = { mode: :rails, bigdecimal_as_decimal: true }
=> {:mode=>:rails, :bigdecimal_as_decimal=>true}
[7] pry(main)> Oj.dump({a: BigDecimal.new('123')})
=> "{\"a\":123.0}" ### NUMBER
[8] pry(main)> Oj.dump({a: BigDecimal.new('123')}, bigdecimal_as_decimal: true)
=> "{\"a\":\"123.0\"}" ### STRING

**Comment by crazyshot** [comment]
Also, when you say fixed, what exactly functionality is your goal, to allow overriding 'bigdecimal_as_decimal' or not? I'd prefer to be allowed overriding it while not forcing me to change mode.

**Comment by ohler55** [comment]
I thought the inconsistency was fixed. Apparently not. I've reopened the issue.

**Comment by ohler55** [comment]
I pushed another attempt to the develop branch with a unit test in `test_rails.rb`.

**Comment by ohler55** [comment]
Please let me know if this branch fixes the issue.
