### ISSUE TITLE
Encoding Time.now.to_i on 32 bit machines?

### ISSUE THREAD

**Issue by jdelStrother** [ohler55/oj#572]
I've got a 32 bit SmartOS machine which ran into problems when upgrading from 3.9.2 to 3.10.0.  It used to be able to encode `Time.now.to_i` as an integer, but it now encodes it as a string:

```ruby
require 'bundler/inline'
gemfile do
  source 'https://rubygems.org'
  # gem 'oj', '3.9.2'
  gem 'oj', '3.10.0'
end
puts Oj::Rails::Encoder.new.encode(t: Time.now.to_i) # => {"t":"1575892189"}
```

The cutoff point seems to be 1073741824 (2**30).  Was this an intentional change?

**Comment by ohler55** [comment]
It was not intentional but I can guess as to what is going on. Without having checked `Time.now.to_i` returns a big number which is then is encoded as a string since it is no longer a simple number. It might be Oj or it might be Rails making that call.

**Comment by jdelStrother** [comment]
Looks like this was fixed in 3.10.1 - maybe due to https://github.com/ohler55/oj/commit/6d265845ba698c5e2035d0f8300ebf6afbd218f7 ?

**Comment by ohler55** [comment]
Great! Can we close the issue then?

**Comment by jdelStrother** [comment]
Yep, think so
