### ISSUE TITLE
`Oj.dump(Time.utc)` is not the same as`JSON.dump(Time.utc)` 

### ISSUE THREAD

**Issue by atavistock** [ohler55/oj#573]
When `ActiveSupport::JSON::Encoding.use_standard_json_time_format = false` the output of ActiveSupport JSON is not the same as Oj 

With default ActiveSupport JSON
```
irb(main):001:0> JSON.dump([Time.now.utc])
=> "[\"2019-12-28 00:20:56 UTC\"]"
```

With oj and configured with `Oj.optimize_rails` and multi_json
```
irb(main):001:0> JSON.dump([Time.now.utc])
=> "[\"2019/12/28 00:22:16 +0000\"]"
```

Notable differences are slashes instead of dashes and "+0000" instead of "UTC"

Same behavior on both Ruby 2.3.3/Rails 5.1.7 and Ruby 2.5.6/Rails 6.0.2

**Comment by ohler55** [comment]
I am surprised since there are unit tests (the JSON gem tests) that pass. I'll look into it though. I suspect this is one of the areas where ActiveSupport and the JSON gem are fighting over which format and option to use.

**Comment by atavistock** [comment]
I tried to wrap it up in a smaller contiguous block and noticed another little issue where the state of `use_standard_json_time_format` is reset.  

Plain irb on ruby 2.5.6
```
irb(main):001:0> require 'active_support/json'
=> true
irb(main):002:0> ActiveSupport::JSON::Encoding.use_standard_json_time_format = false
=> false
irb(main):003:0> JSON.dump([Time.now.utc])
=> "[\"2019-12-28 01:14:44 UTC\"]"
irb(main):004:0> require 'oj'
=> true
irb(main):005:0> Oj.optimize_rails
=> nil
irb(main):006:0> JSON.dump([Time.now.utc])
=> "[\"2019-12-28T01:15:39.528Z\"]"
irb(main):007:0> ActiveSupport::JSON::Encoding.use_standard_json_time_format = false
=> false
irb(main):008:0> JSON.dump([Time.now.utc])
=> "[\"2019/12/28 01:15:55 +0000\"]"
```

**Comment by atavistock** [comment]
Also my quick look through the tests on the JSON gem.  It looks like they ensure that datetime can be serialized and then reconstructed into the same datetime, but no specific test on the format.  In my case I'm converting a project using the JSON gem which has brittle mobile clients that are expecting the same format.

**Comment by ohler55** [comment]
All that information is useful. Thanks. I'll see if I can get it resolved this coming week.

**Comment by atavistock** [comment]
More research if its helpful.  It just seems like the `.utc` method is an aberrant case.

`ActiveSupport/TimeWithZone` seems to have a final else specifically for this format:

```
  def to_s(format = :default)
      if format == :db 
        utc.to_s(format)
      elsif formatter = ::Time::DATE_FORMATS[format]
        formatter.respond_to?(:call) ? formatter.call(self).to_s : strftime(formatter)
      else
        "#{time.strftime("%Y-%m-%d %H:%M:%S")} #{formatted_offset(false, 'UTC')}" # mimicking Ruby Time#to_s format
      end 
    end 
```

I _think_ the OJ code where this would happen (excuse my rusty C if I'm wrong), this line is whats being rendered,  https://github.com/ohler55/oj/blob/develop/ext/oj/rails.c#L264 .  I suspect since does something strange here ruby, the only thing to do would be conditional.

**Comment by ohler55** [comment]
Thanks. Looks like there needs to be s special case for that in Oj as well.

**Comment by ohler55** [comment]
Looks like just including 
```
require "active_support/json"
```
is enough to change the output from Oj.

Still digging. Just giving an update.

**Comment by ohler55** [comment]
Try the rails-time branch.

Setting `ActiveSupport::JSON::Encoding.use_standard_json_time_format` before calling `Oj.optimize_rails` did not persist.

**Comment by atavistock** [comment]
Looks like theres a debug statement `*** rails time nano {}` that I'm getting in a loop

**Comment by ohler55** [comment]
I removed the statement. I suspect the loop just happens to include that line. What code are you using that is triggering the loop? My changes were rather small and should not have caused a loop so maybe a different issue.

**Comment by atavistock** [comment]
Hmm, still having the date format issue with that branch.

```
       -"updated_at" => "2020-01-02 19:26:05 UTC",
       +"updated_at" => "2020/01/02 19:26:05 +0000",
```

**Comment by atavistock** [comment]
Seems to be that format directly out of ActiveRecord when `ActiveSupport::JSON::Encoding.use_standard_json_time_format = false`

```
irb(main):001:0> u = User.first
...
irb(main):002:0> u.updated_at.to_s
=> "2019-08-02 00:23:43 UTC"
```

**Comment by ohler55** [comment]
okay, back to the drawing board.

**Comment by ohler55** [comment]
I pushed a version I think works better. `Oj.dump(t, mode: :rails)` doesn't match yet but the JSON gem mimicking seems to be okay.

**Comment by ohler55** [comment]
Looks like it's going to be tough to get right. The interplay between the JSON gem and Rails encoder will have to be considered. The changes made break the Rails tests so more condition checking will be needed.

**Comment by ohler55** [comment]
I found the culprit. It is a hack in active support that checks the options argument type (`::JSON::State`) and changes behaviour.

```ruby
module ActiveSupport
  module ToJsonWithActiveSupportEncoder # :nodoc:
    def to_json(options = nil)
      if options.is_a?(::JSON::State)
        # Called from JSON.{generate,dump}, forward it to JSON gem's to_json
        super(options)
      else
        # to_json is being invoked directly, use ActiveSupport's encoder
        ActiveSupport::JSON.encode(self, options)
      end
    end
  end
end
```

**Comment by ohler55** [comment]
Got it! The fix is a hack around the Active Support hack. :-)

**Comment by atavistock** [comment]
I just gave it a try and its so very, very close...

JSON.dump now works as expected.
```
> JSON.dump([Time.now.utc])
=> "[\"2020-01-06 18:55:27 UTC\"]"
```

But its still doing the other format for `as_json` and `to_json`
```
> DateTime.now.utc.as_json
=> "2020/01/06 18:54:41 +0000"
```

**Comment by ohler55** [comment]
I think you will find that is expected. If you take Oj out of the mix but require active support you get the rails version.

```ruby
require 'json'

t = [Time.now.utc]

puts "t.to_json - #{t.to_json}"

puts "--- active support"

require 'active_support'
require "active_support/json"

ActiveSupport::JSON::Encoding.use_standard_json_time_format = false

puts "t.as_json - #{t.as_json}"
puts "t.to_json - #{t.to_json}"
```

results in

```
t.to_json - ["2020-01-06 22:34:16 UTC"]
--- active support
t.as_json - ["2020/01/06 22:34:16 +0000"]
t.to_json - ["2020/01/06 22:34:16 +0000"]
```

**Comment by atavistock** [comment]
Indeed.  How interesting!  The permutations you must have had to deal with.  

Okay, I've gotta figure out why my clients specs think a ActiveRecord object `created_at` should be in `2020-01-06 22:34:16 UTC` format.

**Comment by ohler55** [comment]
More than you can imagine. Well, maybe you have a good imagination. 😄

**Comment by atavistock** [comment]
Looks good.

**Comment by sepehrhm** [comment]
What was the fix around this? Not using Oj?
