### ISSUE TITLE
Strange Behavior when using Oj.dump with Concurrent::Hash 

### ISSUE THREAD

**Issue by bbarberBPL** [ohler55/oj#574]
For the following environment
oj 3.9.2
ruby 2.6.5
rails v 5.2.4.1
I noticed  strange behavior when using this with the `Concurrent::Hash` class from `concurrent-ruby`

Given the following snippet I tried in the console

```
h = Concurrent::Hash[:key, 'val']
Oj.dump(h)
```  
The given output is 
```
"{\"^o\":\"Concurrent::Hash\",\"self\":{\":key\":\"val\"}}"
```
instead of
```
"{\":key\":\"val\"}"
```

**Comment by bbarberBPL** [comment]
Also updated to 3.10.0
And tested with ruby 2.5.7 with the same effects

**Comment by ohler55** [comment]
Oj has several different modes. The default is `:object` mode which generated the output you saw. Try setting the mode to `:strict` or pretty much any other mode the `:object`.

**Comment by bbarberBPL** [comment]
Ah I see thank you for the help.

**Comment by bbarberBPL** [comment]
After setting the default options in an initializer to

`Oj.default_options = { mode: :rails,..}` 

It now works as intended. As this was more of a configuration error on my end rather than a bug with Oj itself. I'll close this out.
