### ISSUE TITLE
Oj.dump vs Oj.generate

### ISSUE THREAD

**Issue by DenniJensen** [ohler55/oj#575]
Hey,

I was confused how I should use `Oj`. The README is pointing out to use the `dump` method. 
But using `Oj.dump` is not what I was looking for.

```ruby
my_hash = { a: 2, b: 'super cool' }
# => {:a=>2, :b=>"super cool"}

Oj.dump(my_hash)
# => "{\":a\":2,\":b\":\"super cool\"}"

Oj.generate(my_hash)
# => "{\"a\":2,\"b\":\"super cool\"}"
```

I never used `JSON.generate` before I wrote this issue. My usage in the past was `{}.to_json`. 
When I would use `Oj.dump`?

**Comment by ohler55** [comment]
Sorry for the slow reply.

When you call `{}.to_json` you are dropping into Ruby code immediately. When you use the methods like `Oj.dump` the Oj gem takes over and runs C code to walk the object and build the JSON output. Oj has different modes so it may call back into Ruby if an object implements the `#as_json` or `#to_json` methods. If you use the `:strict` or `:custom` modes you will get the best performance. 

Oj is all about getting the best performance possible.

**Comment by DenniJensen** [comment]
Hey,

thank you for the clarification.
