### ISSUE TITLE
Memory Spike with Saj Parser!

### ISSUE THREAD

**Issue by hassanrehman** [ohler55/oj#576]
I understand Sax to be stream parser, using chunks in memory instead of the entire file. However, a simple test is leading to a spike in memory .. which is roughly the same size as the size of the file. I'm attaching three screenshots from the video i made to demo this (github doesn't allow videos).
![SS1](https://user-images.githubusercontent.com/367647/72422871-1ae5e300-377b-11ea-8b4d-ce51d671f866.png)
![SS2](https://user-images.githubusercontent.com/367647/72422873-1b7e7980-377b-11ea-9fca-6801b64641c2.png)
![SS3](https://user-images.githubusercontent.com/367647/72422874-1b7e7980-377b-11ea-8b52-02a6df4d32ed.png)

Am i doing anything wrong here..?

**Comment by ohler55** [comment]
Note that the SAJ parser was deprecated many versions back in favour of the SCP parser. What you are seeing is expected. If you want a stream parser use `Oj.sc_parse` instead. It uses a similar approach.

**Comment by hassanrehman** [comment]
You're absolutely right. Used SCP Parser from the latest version and it worked fine. Kindly add deprecation notice to the [documentation here](https://www.rubydoc.info/github/ohler55/oj/Oj/Saj).

**Comment by ohler55** [comment]
There is a `@deprecated` on line 660 of saj.c. I'm not sure why yardocs doesn't pick it up.
