### ISSUE TITLE
Load issues with object mode

### ISSUE THREAD

**Issue by Asafb26** [ohler55/oj#577]
Hello,
I found a really weird issue that we encountered in our production env.
let's define this method for example:
```ruby
def example(value)
  dump = Oj.dump(value, mode: :object, circular: true)
  Oj.load(dump, mode: :object, circular: true)
end
```

now on most of the values the return value is the same as the input (as expected)
```ruby
example('test')
 => "test"
```
```ruby
example('sr1')
 => "sr1"
```
```ruby
> example(['sr0'])
 => ["sr0"]
```

but see what happen when the input is `['sr1']`:
```ruby
2.6.3 :076 > example(['sr1'])
 => [[...]]
2.6.3 :077 > result = example(['sr1'])
 => [[...]]
2.6.3 :078 > result.first
 => [[...]]
2.6.3 :079 > result.first.first.first.first
 => [[...]]
2.6.3 :080 > result.class
 => Array
```
this issue appeard in every level:
```ruby
example({value: ['sr1']})
 => {:value=>[{...}]}
```

another weird behavior happen with `["sr#{number}"]`:
```ruby
example(['sr2'])
 => [nil]
example(['sr123123'])
 => [nil]
```

**Comment by ohler55** [comment]
Thats certainly not expected. Let me look into what's going on with the circular reference handling.

**Comment by ohler55** [comment]
Okay, fixed (I hope) in the develop branch again.

**Comment by Asafb26** [comment]
Thanks!
Have an ETA for the next release?

**Comment by ohler55** [comment]
As soon as you verify this feature is working as expected I will roll out a release.

**Comment by Asafb26** [comment]
I see that the develop branch updated 15 days ago, need to push?

**Comment by ohler55** [comment]
My mistake, wrong project. That was fo Ox. I haven't looked at the circular reference yet. Please ignore the comment that it was fixed. No release is pending but when I do fix this issue there will be a release.

**Comment by ohler55** [comment]
Ok, really fixed this time. Oj gem. 😄

**Comment by Asafb26** [comment]
It works perfectly, thanks!

**Comment by ohler55** [comment]
Released
