### ISSUE TITLE
JSON.dump change the time format

### ISSUE THREAD

**Issue by rizalmuthi** [ohler55/oj#579]
Thanks for this amazing gem.
When I try to upgrade the gem from 3.10.0 to 3.10.2. 
I got a bunch of errors in my specs.
Open debugging I found out the `JSON.dump` change the time format

This is the comparison I have from my codebase
```Ruby

3.10.0

[1] pry(..)> now
=> 2020-01-31 11:47:42 +1100
[2] pry(..)> JSON.dump('metadata' => meta, 'data' => data)
=> "{\"metadata\":{\"executor\":\"exec\",\"correlationId\":\"corr\",\"eventTimestamp\":\"2020-01-31T11:47:42.306+11:00\"},\"data\":{\"name\":\"BarFoo\"}}

3.10.2

[1] pry(..)> now
=> 2020-01-31 11:46:32 +1100
[2] pry(..)> JSON.dump('metadata' => meta, 'data' => data)
=> "{\"metadata\":{\"executor\":\"exec\",\"correlationId\":\"corr\",\"eventTimestamp\":\"2020-01-31T11:46:32.006+11:00\"},\"data\":{\"name\":\"BarFoo\"}}"
```
The different
```
3.10.0 => "eventTimestamp\":\"2020-01-31T11:47:42.306+11:00\"
3.10.2 => "eventTimestamp\":\"2020-01-31 11:42:42 +1100\"
```

Is this expected?
Looks like this being introduced on version 3.10.1

**Comment by ohler55** [comment]
It was a bug in the older versions. `ActiveSupport::JSON::Encoding.use_standard_json_time_format` was not being honored depending on if it was modified before or after setting up Oj. It is alway used now. I am assuming you are using Rails or ActiveSupport or you should not have noticed a change. You are right, the change was in 3.10.1 as indicated by the CHANGELOG.md. If you want the Ruby version instead of the RFC3339 version just change the ActiveSupport setting.

**Comment by rizalmuthi** [comment]
Hi @ohler55 
Thanks for the quick response. Yes, indeed I am using ActiveSupport, not Rails tho.
Right, thanks for the explanation. Let me check the ActiveSupport settings.
Thank you

**Comment by rizalmuthi** [comment]
Hi @ohler55 
is that correct, I just need to set the `ActiveSupport::JSON::Encoding.use_standard_json_time_format = false` to use the Ruby version?

**Comment by rizalmuthi** [comment]
Is this expected?

```Ruby
version 3.10.0

[4] pry(#<Pry::CLI>)> ActiveSupport.use_standard_json_time_format = true
=> true
[5] pry(#<Pry::CLI>)>
[6] pry(#<Pry::CLI>)> t = Time.now
=> 2020-01-31 14:58:07 +1100
[7] pry(#<Pry::CLI>)> t.to_json
=> "\"2020-01-31T14:58:07.284+11:00\""
[8] pry(#<Pry::CLI>)> JSON.dump('time' => t)
=> "{\"time\":\"2020-01-31T14:58:07.284+11:00\"}"
[9] pry(#<Pry::CLI>)> ActiveSupport.use_standard_json_time_format = false
=> false
[10] pry(#<Pry::CLI>)> t = Time.now
=> 2020-01-31 14:58:27 +1100
[11] pry(#<Pry::CLI>)> t.to_json
=> "\"2020/01/31 14:58:27 +1100\""
[12] pry(#<Pry::CLI>)> JSON.dump('time' => t)
=> "{\"time\":\"2020/01/31 14:58:27 +1100\"}"
```

vs 

```Ruby
version 3.10.2

[1] pry(#<Pry::CLI>)> ActiveSupport.use_standard_json_time_format = true
=> true
[2] pry(#<Pry::CLI>)> t = Time.now
=> 2020-01-31 14:59:39 +1100
[3] pry(#<Pry::CLI>)> t.to_json
=> "\"2020-01-31T14:59:39.657+11:00\""
[4] pry(#<Pry::CLI>)> JSON.dump('time' => t)
=> "{\"time\":\"2020-01-31 14:59:39 +1100\"}"
[5] pry(#<Pry::CLI>)> ActiveSupport.use_standard_json_time_format = false
=> false
[6] pry(#<Pry::CLI>)> t = Time.now
=> 2020-01-31 15:00:04 +1100
[7] pry(#<Pry::CLI>)> t.to_json
=> "\"2020/01/31 15:00:04 +1100\""
[8] pry(#<Pry::CLI>)> JSON.dump('time' => t)
=> "{\"time\":\"2020-01-31 15:00:04 +1100\"}"
[9] pry(#<Pry::CLI>)>
```

Look at when the `ActiveSupport::JSON::Encoding.use_standard_json_time_format = true`
```
[8] pry(#<Pry::CLI>)> JSON.dump('time' => t)
=> "{\"time\":\"2020-01-31T14:58:07.284+11:00\"}"

Vs

[4] pry(#<Pry::CLI>)> JSON.dump('time' => t)
=> "{\"time\":\"2020-01-31 14:59:39 +1100\"}"
```

**Comment by ohler55** [comment]
Honestly the combinations of the JSON gem and ActiveSupport have a lot of edge cases. I will have to compare the results with and without Oj. I try to do that this weekend. Can you tell me what Oj setup calls were made? mimic_JSON and or Rails.optimize.

**Comment by rizalmuthi** [comment]
Our code directly just call ` JSON.dump` method.

**Comment by ohler55** [comment]
Okay, so you do not load Rails or the JSON gem but you do call Oj.mimic_JSON, right?

**Comment by ohler55** [comment]
By the way, I will make sure we get this working the way you need. I just need to know enough about your environment to be able to recreate what you are seeing.

**Comment by rizalmuthi** [comment]
I apologize if I gave wrong information.
Let me dig again into my codebase

This is what we have in our Gemfile

```
...
gem 'multi_json'
gem 'oj'
gem 'oj_mimic_json'

gem 'activesupport', '5.2.3'
gem 'activerecord', '5.2.3'
gem 'rails-html-sanitizer', '1.0.3'

...
gem 'sinatra', require: false
```


And on the `environment.rb`
we load the gems
```
...
require 'oj'
require 'oj_mimic_json'
....
```

is this enough? let me know anything i can provide

**Comment by rizalmuthi** [comment]
Owh also, we have this

`config/ensure_correct_parser_for_json_encoding.rb`
```
# refer: https://precompile.com/2015/07/25/rails-activesupport-json.html
# (andyn, 5/12/2016)
module ActiveSupport::JSON::Encoding
  class Oj < JSONGemEncoder
    def encode(value)
      ::Oj.dump(value.as_json)
    end
  end
end
```

**Comment by ohler55** [comment]
Great, thanks. I'll see what I can do with that.

**Comment by ohler55** [comment]
It was a busy week. Sorry it took some time to get to this. I tried various combinations trying to figure out why it was working for me and not for you but I was testing with a simple test app and not a full rails stack. Then I realized you patch for the correct parser was not being called in my tests. 

When the oj_mimic_json gem is loaded it calls Oj.mimic_JSON which changes the Oj defaults. So when calling Oj.dump() the defaults for mimicking the JSON gem are used including the mode and time format. Those options need to be turned off.

There a couple of ways to set the options correctly. If you have If you want to use the `ActiveSupport::JSON::Encoding.use_standard_json_time_format = true` option you can call dump like this:

```ruby
Oj.dump(value, time_format: :xmlschema, use_to_json: false)}"
```

or you can use this

```ruby
Oj.dump(value, time_format: :xmlschema, mode: :custom, use_to_json: false)
```

Or if you feel the need to call `#as_json` directly you can do that.

```ruby
Oj.dump(value.as_json, time_format: :xmlschema, mode: :custom, use_to_json: false)
```

Please let me know it that works in you you environment. You might find calling Oj.optimize_rails give a small performance boost as well if you are not already doing that. If that is the case then it is better not to call `#as_json` directly.

**Comment by ohler55** [comment]
Did the suggestions solve the issue?

**Comment by rizalmuthi** [comment]
Hi @ohler55 
Thanks for the response. 
I havent had a time to work on this in my part.
Ill probably look into this in the next couple of days.
I will definitely let you know the result

Thank you very much
