### ISSUE TITLE
Unexpected Unicode escaping behavior differences in rails mode with escape_html_entities_in_json

### ISSUE THREAD

**Issue by urkle** [ohler55/oj#581]
With 3.6.3  when encoding a string with unicode characeter (e.g. an em-dash u2014) it would be to_json'd as the UTF8 sequence.  However with >= 3.9.0 this behavior changed and I get \u2014 in my output to_json string.

This happens when I set the default_options to {mode: :rails}

If I fully disable Oj then to_json does not perform this escaping (stock Rails)

We are running Rails 5.2.x, originally we were running Oj 3.6.3 and upgrade to 3.10.0 2 months ago and we noticed this behavior (only today:() and are downgrading to prevent this behavior.

Our OJ initialization is
```ruby
require 'oj'

Oj.optimize_rails
Oj.default_options = {mode: :rails}
```

Why we care about this?

Well, this is for our API and the clients we having using our API, unfortunately have a "Bad" JSON parser that incorrectly decodes \u sequences (it treats any value > 127 as 127, thus horribly breaking the data!).

I tried fiddling with the config options but could not find any that would turn off this behavior

**Comment by ohler55** [comment]
I suspect the change was related to trying to match rails and JSON gem behavior. When in rails mode only a few options are honored as they would break the rails and JSON gem behavior. I'll look at this to see what is happening. Can you tell me what else you have in your setup? Are you running under rails?

**Comment by urkle** [comment]
I have narrowed it down further.

So with the update to >= 3.9.x the code now properly respects the set configuration for escape_html_entities_in_json

Which we wanted off (so it wouldn't escape & as -> \u0026 ). 
However,  when I turn that off it escapes characters like emdash.. If I turn it back on, then it won't escape emdash, but will escape &:).

```irb
ActiveSupport::JSON::Encoding.escape_html_entities_in_json = false

Oj.dump("\u2014 & \n \u{1F618}")
 => "\"\\u2014 & \\n 😘\""

ActiveSupport::JSON::Encoding.escape_html_entities_in_json = true

Oj.dump("\u2014 & \n \u{1F618}")
 => "\"— \\u0026 \\n 😘\""
```

**Comment by ohler55** [comment]
Thanks, that should help.

**Comment by ohler55** [comment]
I pushed a `rails-escape` branch that has a fix. Lets see if the rails tests fail on travis.

**Comment by ohler55** [comment]
I plan on merging this change and doing a release tomorrow. If it is not working as expected please let me know.

**Comment by ohler55** [comment]
Release 3.10.3 fixes this issue.

**Comment by ohler55** [comment]
No response from originator, closing.
