### ISSUE TITLE
Instance variables deserialization issue on Hash subclasses

### ISSUE THREAD

**Issue by Annih** [ohler55/oj#586]
Hello,

In the case you want to serialize objects that are inheriting `::Hash`, your instance variables might not be loaded properly.
I'm new to `Oj`, so I may have missed a configuration option. Just let me know

**Issue:**
Instance variables are loaded as values of the hash.

**Expected behavior:**
Instance variables are loaded as they were defined.

**Reproduction:**
```ruby
require 'oj'
class H < ::Hash
  def initialize
     @b = true
     @i = 1
     @s = 's'
  end
end
before = ::H.new
after = ::Oj.load(::Oj.dump(before))

issues = before.instance_variables.select do |var|
  before.instance_variable_get(var) != after.instance_variable_get(var)
end
raise "Following instance variables are not properly loaded: #{issues}" unless issues.empty?
```

**Comment by Annih** [comment]
Quick workaround if you just want the same behavior as an `::Hash` but do not care about the inheritance, you can use `::SimpleDelegator`

```ruby
require 'delegate'
class H < ::SimpleDelegator
  def initialize
    super({})
    @x = 1
  end
end
```

**Comment by ohler55** [comment]
Oj handles Hash and Array as special cases. To get the attributes of a class that inherits from Hash you will need to implement a as_json() method.

**Comment by Annih** [comment]
Ahh OK, I think I saw something like that but I didn't realize that was the way to go.

1. Does that mean we have to do the whole JSON serialization ourselves? (No Oj benefits on them)
2.Do you know why it works for the boolean variable?

**Comment by ohler55** [comment]
No not at all. as_json should return a serializable object such as Hash, Array, String, etc so since you already have a hash if you just make sure the instance variables are also in the Hash you should be okay.

Another approach I take instead of subclassing it to have a has member and then delegate Hash method to it. I'm guessing that is what the SimpleDelegator does but I haven't looked at that class.

**Comment by ohler55** [comment]
Can this be closed?
