### ISSUE TITLE
Incorrect precision on json parse

### ISSUE THREAD

**Issue by BS062721** [ohler55/oj#587]
We are trying to parse JSON using `Oj.load`, our values comes as numbers rather than strings and we are loosing precision on it (specially trailing zeros precision)

Example:

```
Oj.load({"value":1.00}) => 'value' => 1.0
Oj.load({"value":1.420}) => 'value' => 1.42

```

Is there any configuration we can use to keep precision as is?

**Comment by ohler55** [comment]
Precision is not the number of trailing zeros. What you are seeing is the way Ruby displays floats. It has nothing to do with Oj. You can of course use different string formatters to print out floats in a number of different ways. For example this:

```ruby
x = 1.420
puts "%0.3f" % [x]
```

**Comment by kimyu92** [comment]
agree with @ohler55, you can see in ruby irb, that's how it behaves as well
```ruby
irb(main):001:0> x = 1.420
=> 1.42
irb(main):002:0> x = 1.42
=> 1.42
irb(main):003:0> x = 1.0
=> 1.0
irb(main):004:0> 1.0000
=> 1.0
irb(main):005:0>
```

**Comment by ohler55** [comment]
No réponse for 2 weeks. Closing.
