### ISSUE TITLE
Feature request: validate json

### ISSUE THREAD

**Issue by crazyshot** [ohler55/oj#588]
For my current statistics server, I'm receiving event with JSON data, I don't need to parse it, only validate that it's a proper JSON and write it to file.
Currently, I don't see a way to validate JSON without using memory for all the Ruby objects.

`Oj.valid?(text)` would be very useful. If there's already some internal way to do it, I'll be glad to use it and create this syntax sugar.

**Comment by ohler55** [comment]
The best approach I've found is using Oj.sc_parse with a handler that has no callback methods. Simply using the Object class should be fine so:

```ruby
  Oj.sc_parse(Object, my_input)
```

**Comment by ohler55** [comment]
Can this be closed?

**Comment by crazyshot** [comment]
Yes
