### ISSUE TITLE
dump_object.c:621:3: error: void function 'dump_obj_attrs' should not return a value [-Wreturn-type]

### ISSUE THREAD

**Issue by eregon** [ohler55/oj#590]
This happens on TruffleRuby when `HAVE_RB_IVAR_FOREACH`/`rb_ivar_foreach` is not defined.

In such a case this line tries to `return` a value in a `void` function:
https://github.com/ohler55/oj/blob/d223a50ea9cd19261b7b04caeab8e81c610fe662/ext/oj/dump_object.c#L621

```
compiling dump_object.c
dump_object.c:621:3: error: void function 'dump_obj_attrs' should not return a value [-Wreturn-type]
                return ST_CONTINUE;
                ^      ~~~~~~~~~~~
1 error generated.
```

We'll implement `rb_ivar_foreach` in TruffleRuby to fix this, but it seems worth updating this code.

**Comment by ohler55** [comment]
Thanks for the catch. I'll get a fix out soon.

**Comment by ohler55** [comment]
Updated in the develop branch. Will release once CI completes.

**Comment by ohler55** [comment]
Released

**Comment by eregon** [comment]
Thanks!
