### ISSUE TITLE
Any Ideas to avoid affecting render json ?

### ISSUE THREAD

**Issue by SugiKent** [ohler55/oj#591]
## Environment
```
ruby: 2.4.6
oj (3.10.5)
rails (4.2.11.1)
multi_json (1.13.1)
```

How can I avoid to affecting `render json: any_hash` by oj options?

I have used oj (2.x) as one of dependencies gem of jbuilder ( and MultiJson ), then oj didn't affect render json.
After upgradeing oj 2.x to 3.x, oj encode BigDecimal to String as a default. So I added config/initializer/oj.rb like this.
```
Oj::Rails.set_encoder
Oj::Rails.optimize
Oj.default_options = { bigdecimal_as_decimal: true }
```

This setting enables oj to encode BigDecimal to Decimal :)
However, this initializer affects `render json`. So far an API response expects that BigDecimal encoded to String, but now, the response is Decimal because of config/initializer/oj.rb.

If you have any ideas please comment.
thanks

## Tried

I tried initialize only MultiJson.dump_options, but It does not working.

```
# Oj::Rails.set_encoder
# Oj::Rails.optimize
# Oj.default_options = { bigdecimal_as_decimal: true }

MultiJson.use(:oj)
MultiJson.dump_options = MultiJson.dump_options.merge({bigdecimal_as_decimal: true})
```

**Comment by ohler55** [comment]
From the sounds of it, Oj use used for both so setting a global default will effect both. You can override the global option with function call optional parameters. That means you need to find the place the call is being made and make some code changes. Is that possible?

**Comment by ohler55** [comment]
Can this be closed?
