### ISSUE TITLE
Oj not decoding ruby objects in :compat mode

### ISSUE THREAD

**Issue by alex-klepa** [ohler55/oj#592]
Am I missing something?
Encoder works fine, but decoder isn't

```ruby
require 'json'
require 'oj'
Oj.default_options = { mode: :compat }
Oj.add_to_json(Range)
Oj.mimic_JSON

json = (1..6).to_json
# "{\"json_class\":\"Range\",\"a\":[1,7,false]}"

JSON.load json
#{
#    "json_class" => "Range",
#    "a"          => [
#        [0] 1,
#        [1] 7,
#        [2] false
#    ]
# }

```

**Comment by ohler55** [comment]
You need to set some additional options just like with the JSON gem. The `create_additions` needs to be set to true. You can also changes the `create_id` from "json_class" to another value if you like.

**Comment by alex-klepa** [comment]
When I pass *create_additions* directly to JSON.load it works, but If default_options are ignored.
```ruby
JSON.load(json, create_additions: true) # Works
```

```ruby
# ...
Oj.default_options = { mode: :compat,  create_additions: true}
# ...
JSON.load(json) # Boom!
#{
#    "json_class" => "Range",
#    "a"          => [
#        [0] 1,
#        [1] 7,
#        [2] false
#    ]
# }
```

Thank  you!

**Comment by ohler55** [comment]
Ran a test locally and it worked the same in both cases but I did one thing different. The default for the JSON gem is to set the `create_additions` to false so when the call to `Oj.mimic_JSON` is made the value is set to false. You can set it back to true by setting the default options after the call to `Oj.mimic_JSON`.

**Comment by alex-klepa** [comment]
Oh I see, now it works. Thank you!
