### ISSUE TITLE
Missing argument 'options'  in RubyMine IDE

### ISSUE THREAD

**Issue by OlegsBoldirevs** [ohler55/oj#593]
How can i avoid passing `mode: :compat` argument for `Oj.load` and `Oj.dump` ?

This is what i got right now: `Oj.load(json, mode: :compat)`
This is what i'm looking to achieve:  `Oj.load(json)`
But my RubyMine IDE is throwing error `"Missing argument 'options'"`

I've tried creating initializer with `Oj.default_options = {:mode => :compat }` but still get error from IDE.
<img width="523" alt="Screenshot 2020-04-20 at 14 51 44" src="https://user-images.githubusercontent.com/24756168/79749227-81991080-8317-11ea-836b-e43777796699.png">

**Comment by ohler55** [comment]
Sounds like a bug in RubyMine. The second argument is optional.

**Comment by OlegsBoldirevs** [comment]
Well i figured it out. In Oj version 3.10.5 the second argument is required although in version 3.10.6 second argument is optional. I updated version of Oj and the problem is not relevant anymore.

**Comment by ohler55** [comment]
That is odd. That code hasn't changed in a very long time.

**Comment by OlegsBoldirevs** [comment]
Hm. This is what my IDE looks for.
`3.10.6`
<img width="624" alt="Screenshot 2020-04-20 at 15 24 40" src="https://user-images.githubusercontent.com/24756168/79751342-1bae8800-831b-11ea-9baa-b85cdeee31d5.png">
`3.10.5`
<img width="477" alt="Screenshot 2020-04-20 at 15 24 29" src="https://user-images.githubusercontent.com/24756168/79751345-1d784b80-831b-11ea-9dc1-ec261c75f6de.png">

**Comment by OlegsBoldirevs** [comment]
Well i don't see any changelog changes from 3.10.5 to 3.10.6 that might affect this. Probably RubyMine bug.

**Comment by ohler55** [comment]
I don't know where that file, oj.rb is from. It is not part of the Oj gem. Maybe RubyMine generates it from the documentation in the C source file or from the generated docs.
