### ISSUE TITLE
Unclear use of push_object in test case?

### ISSUE THREAD

**Issue by machty** [ohler55/oj#594]
I was looking at the `test_writer.rb` spec to get a sense for how to use the writer class, and I came across this [odd-looking line](https://github.com/ohler55/oj/blob/develop/test/test_writer.rb#L77) ([introduced here](https://github.com/ohler55/oj/commit/d35214fc5f1c703b6af68af46b755d2a320853ab#diff-23121d1d9af8f49c8877615e48809242R71)):

It seems the `'x'` key passed to `push_object` is totally forgotten and doesn't show up in the output. Is this functionality intentional?

**Comment by ohler55** [comment]
It is intentional. If a key has been pushed before it then the argument is ignored. That is a check to verify that behaviour works as expected.
