### ISSUE TITLE
oj gem installation fails

### ISSUE THREAD

**Issue by Roman-Sht** [ohler55/oj#596]
I am trying to install the gem using this command:
`gem install oj -v 3.10.6`

This is the response I get:
`Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing oj:
        ERROR: Failed to build gem native extension.

    current directory: C:/SystemTest/Ruby/lib/ruby/gems/2.6.0/gems/oj-3.10.6/ext/oj
C:/SystemTest/Ruby/bin/ruby.exe -I C:/SystemTest/Ruby/lib/ruby/site_ruby/2.6.0 -r ./siteconf20200429-4256-1cj2ebt.rb extconf.rb
>>>>> Creating Makefile for ruby version 2.6.3 on x64-mingw32 <<<<<
checking for rb_time_timespec()... yes
checking for rb_ivar_count()... yes
checking for rb_ivar_foreach()... yes
checking for stpcpy()... no
checking for rb_data_object_wrap()... yes
checking for pthread_mutex_init()... yes
creating Makefile
rm: cannot remove 'mkmf.log': Device or resource busy
make: [Makefile:174: clean] Error 1 (ignored)

current directory: C:/SystemTest/Ruby/lib/ruby/gems/2.6.0/gems/oj-3.10.6/ext/oj
make "DESTDIR=" clean

current directory: C:/SystemTest/Ruby/lib/ruby/gems/2.6.0/gems/oj-3.10.6/ext/oj
make "DESTDIR="
generating oj-x64-mingw32.def
compiling cache8.c
compiling circarray.c
compiling code.c
compiling compat.c
compiling custom.c
compiling dump.c
compiling dump_compat.c
compiling dump_leaf.c
compiling dump_object.c
compiling dump_strict.c
compiling err.c
compiling fast.c
compiling hash.c
compiling hash_test.c
compiling mimic_json.c
compiling object.c
compiling odd.c
compiling oj.c
compiling parse.c
compiling rails.c
compiling reader.c
compiling resolve.c
compiling rxclass.c
compiling saj.c
saj.c: In function 'oj_saj_parse':
saj.c:624:20: warning: array subscript -65536 is outside array bounds of 'volatile VALUE[1]' {aka 'volatile long long unsigned int[1]'} [-Warray-bounds]
  624 |     pi.stack_min = (void*)((char*)&obj - (512 * 1024)); /* assume a 1M stack and give half to ruby */
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
saj.c:607:20: note: while referencing 'obj'
  607 |     volatile VALUE obj = Qnil;
      |                    ^~~
compiling scp.c
compiling sparse.c
compiling stream_writer.c
compiling strict.c
compiling string_writer.c
compiling trace.c
compiling util.c
compiling val_stack.c
compiling wab.c
linking shared-object oj/oj.so
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: custom.o:custom.c:(.text+0x3776): undefined reference to `__memcpy_chk'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: dump.o:dump.c:(.text+0x1f91): undefined reference to `__chk_fail'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: dump.o:dump.c:(.text+0x32e8): undefined reference to `__strncpy_chk'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: dump_compat.o:dump_compat.c:(.text+0x187f): undefined reference to `__strcpy_chk'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: dump_object.o:dump_object.c:(.text+0x82e): undefined reference to `__memcpy_chk'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: dump_strict.o:dump_strict.c:(.text+0x5e0): undefined reference to `__strncpy_chk'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: fast.o:fast.c:(.text+0xa4f): undefined reference to `__memcpy_chk'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: fast.o:fast.c:(.text+0x18e3): undefined reference to `__memcpy_chk'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: fast.o:fast.c:(.text+0x1a49): undefined reference to `__memcpy_chk'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: mimic_json.o:mimic_json.c:(.text+0x10b1): undefined reference to `__strcpy_chk'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: mimic_json.o:mimic_json.c:(.text+0x1127): undefined reference to `__strcpy_chk'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: mimic_json.o:mimic_json.c:(.text+0x119a): undefined reference to `__strcpy_chk'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: mimic_json.o:mimic_json.c:(.text+0x1210): undefined reference to `__strcpy_chk'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: mimic_json.o:mimic_json.c:(.text+0x1286): undefined reference to `__strcpy_chk'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: object.o:object.c:(.text+0x12c6): undefined reference to `__strncpy_chk'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: object.o:object.c:(.text+0x1381): undefined reference to `__strncpy_chk'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: object.o:object.c:(.text+0x1540): undefined reference to `__memcpy_chk'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: object.o:object.c:(.text+0x1a2d): undefined reference to `__memcpy_chk'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: object.o:object.c:(.text+0x2075): undefined reference to `__memcpy_chk'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: oj.o:oj.c:(.text+0x2326): undefined reference to `__strcpy_chk'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: oj.o:oj.c:(.text+0x2387): undefined reference to `__strcpy_chk'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: oj.o:oj.c:(.text+0x23e5): undefined reference to `__strcpy_chk'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: oj.o:oj.c:(.text+0x2443): undefined reference to `__strcpy_chk'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: oj.o:oj.c:(.text+0x24a1): undefined reference to `__strcpy_chk'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: parse.o:parse.c:(.text+0x31c): undefined reference to `__memcpy_chk'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: rails.o:rails.c:(.text+0xc05): undefined reference to `__chk_fail'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: rails.o:rails.c:(.text+0x1482): undefined reference to `__memset_chk'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: rails.o:rails.c:(.text+0x1977): undefined reference to `__strcpy_chk'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: saj.o:saj.c:(.text+0x1c8): undefined reference to `__chk_fail'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: saj.o:saj.c:(.text+0x5d8): undefined reference to `__chk_fail'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: saj.o:saj.c:(.text+0x12c2): undefined reference to `__chk_fail'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: saj.o:saj.c:(.text+0x201e): undefined reference to `__chk_fail'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: saj.o:saj.c:(.text+0x26f9): undefined reference to `__chk_fail'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: trace.o:trace.c:(.text+0x125): undefined reference to `__memset_chk'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: trace.o:trace.c:(.text+0x139): undefined reference to `__chk_fail'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: trace.o:trace.c:(.text+0x215): undefined reference to `__memset_chk'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: trace.o:trace.c:(.text+0x229): undefined reference to `__chk_fail'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: trace.o:trace.c:(.text+0x2ed): undefined reference to `__memset_chk'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: trace.o:trace.c:(.text+0x301): undefined reference to `__chk_fail'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: trace.o:trace.c:(.text+0x3f4): undefined reference to `__memset_chk'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: trace.o:trace.c:(.text+0x409): undefined reference to `__chk_fail'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: trace.o:trace.c:(.text+0x4cc): undefined reference to `__memset_chk'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: trace.o:trace.c:(.text+0x4e1): undefined reference to `__chk_fail'
C:/SystemTest/Ruby/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: wab.o:wab.c:(.text+0x831): undefined reference to `__chk_fail'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:261: oj.so] Error 1

make failed, exit code 2

Gem files will remain installed in C:/SystemTest/Ruby/lib/ruby/gems/2.6.0/gems/oj-3.10.6 for inspection.
Results logged to C:/SystemTest/Ruby/lib/ruby/gems/2.6.0/extensions/x64-mingw32/2.6.0/oj-3.10.6/gem_make.out`

I am working on a windows 10 machine.
My ruby version is: ruby 2.6.3p62 (2019-04-16 revision 67580) [x64-mingw32]
and I installed ruby with the devkit.
ruby gems version 3.0.3
I also tried a few older versions of oj and still was not successful.

**Comment by ohler55** [comment]
Since the make failed trying to remove the log file I would guess your environment is not set up correctly. I don't know much about Windows but maybe someone else can help with that. Anyone listening?
