### ISSUE TITLE
undefined method `json_encoder='

### ISSUE THREAD

**Issue by mikos** [ohler55/oj#597]
I'm trying to use Oj 3.7.12 on a Rails 3.2.17 application running on Ruby 2.1.7p400. When I try to run `Oj.optimize_rails` from either an initializer or the Rails console I get the following:

```
NoMethodError: undefined method `json_encoder=' for ActiveSupport:Module
```

I've tried the suggestions in https://github.com/ohler55/oj/issues/406 to no avail.

**Comment by ohler55** [comment]
I'm not sure what to say. That version of Oj is only a year old but the rails version is 8 years old and the Ruby version is 7 years old. Both have been out of support for a very long time. Oj added Rails support for Rails 5. I don't doubt that Rails did not have an option for a json encoder at that time. There really isn't any way I can support those earlier versions of Ruby and Rails.

**Comment by mikos** [comment]
No problem, thanks. I thought this might be the case!
