### ISSUE TITLE
Inconsistent behavior for illegal/malformed utf-8

### ISSUE THREAD

**Issue by madejejej** [ohler55/oj#600]
There is an inconsistency when we call `Oj.optimize_rails` and use `JSON.generate` when there are invalid utf-8 characters in a string:

```
irb(main):001:0> str = "\xAE"
=> "\xAE"
irb(main):002:0> JSON.generate(str)
Traceback (most recent call last):
        1: from (irb):2
JSON::GeneratorError (source sequence is illegal/malformed utf-8)
irb(main):003:0> Oj.optimize_rails
=> nil
irb(main):004:0> JSON.generate(str)
=> "\"\xAE\""
```

I'd expect the same `JSON::GeneratorError` to be raised after the Oj patch is applied.

Oj version: 3.9.1
Ruby 2.6.5p114

**Comment by ohler55** [comment]
I'll look into it. You are correct, that is not the expected behaviour.

**Comment by ohler55** [comment]
I just pushed a branch named "json-escape-mode". You should note that Oj.optimize_rails optimizes rails and not the JSON gem although there is considerable overlap. If you are going to call JSON.generate() and wish to use the Oj replacement then you should also call Oj.mimic_JSON before attempting to use the JSON module calls. I suspect you are running in a rails environment though so may that has already been done.

**Comment by madejejej** [comment]
> If you are going to call JSON.generate() and wish to use the Oj replacement then you should also call Oj.mimic_JSON before attempting to use the JSON module calls. I suspect you are running in a rails environment though so may that has already been done.

Yes, I'm running in a Rails environment. I ran into this issue because Sidekiq uses 
`JSON.generate` when queuing jobs. 

So in order to get Oj performance benefits in Sidekiq, should we really initialize it like this?

```ruby
# config/initializers/oj.rb
Oj.mimic_JSON
Oj.optimize_rails
```

It seems that `Oj.optimize_rails` calls `Oj::Rails.mimic_JSON()`, but I'm not sure about the differences between `Oj::Rails.mimic_JSON()` vs `Oj.mimic_JSON()`.

**Comment by ohler55** [comment]
There are a lot of unexpected interactions between Rails and the JSON gem. It has gotten much better than a few years ago but both use a monkey patch approach to base/core classes to implement their behaviour so it is expected that there will be some issues. The Oj.mimic_JSON replaces the JSON gem while Oj.optimize_rails replaces the Rails encoding as well as providing JSON gem alterations. Calling both as you've shown is usually the best approach.

**Comment by pftg** [comment]
there is another issue:

```ruby
# setup in intializer
Oj.mimic_JSON
Oj.optimize_rails

# in the code
# json serialized attribute mysql2 adapter, encoding: utf8 / utf8mb4

sample_record.sample_json_field_before_type_cast.encoding #=> `ASCII-8BIT`
```

but without oj enabled:

```ruby
sample_record.sample_json_field_before_type_cast.encoding #=> `UTF-8`
```

What env does oj read which makes him to switch to ascii?

**Comment by ohler55** [comment]
Oj always uses UTF-8 encoding. JSON text is defined as a sequence of Unicode code points. ASCII is not a valid encoding since it does not support Unicode. UTF-8 does support Unicode and is the suggested encoding for JSON. Are you seeing the JSON gem emitting ASCII-8BIT strings? That seems broken but if that is what the JSON gem is emitting Oj in compat and rails mode will need to be updated.

**Comment by pftg** [comment]
@ohler55 I'm still investigating, maybe some other gems which loading oj by default setup it wrong.

So what I see that before type cast strings has encoding ascii with:

```ruby
Oj.mimic_JSON
Oj.optimize_rails
```

as you mentioned in other comments, there are a lot of monkey patches, and that maybe other gems in app are trying to change behaviour

**Comment by pftg** [comment]
For now, could confirm this start happen after the new rails security fix `6.1.2.1`

**Comment by ohler55** [comment]
Is that when rails started emitting ASCII-8BIT?

**Comment by pftg** [comment]
@ohler55 thanks for your help, I'm still investigating: related gems mysql2, and somehow disabling the oj could prevent MySQL2 encoding mess on production env.

**Comment by ohler55** [comment]
Feel free to keep this issue open for your issues. I'll do what I can when questions arise.

**Comment by ohler55** [comment]
An reason to keep this open?

**Comment by madejejej** [comment]
Not on my side. I'm going to close this one. Huge thank you for your help and for building & maintaining this great gem @ohler55! 🙏

**Comment by pftg** [comment]
The bug was related to the rails + MySQL2 integration. There was a not safe charset change.
