### ISSUE TITLE
Incorrect error message for "unexpected character"

### ISSUE THREAD

**Issue by ndbroadbent** [ohler55/oj#601]
Hello! I am using Oj version `3.9.2`, ruby `2.6.5p114`.

I believe Oj is producing an incorrect/misleading error message for the following case:

```ruby
Oj.load('{ "foo": 123, bar: 234 }')
# Oj::ParseError: unexpected character (foo) at line 1, column 15 [parse.c:705]
```

Is this the expected behavior? I would expect this error message to read:

```
Oj::ParseError: unexpected character (bar) at line 1, column 15 [parse.c:705]
```

Thanks for all your work on Oj!

**Comment by ohler55** [comment]
The parse can't really identify the 'bar' element as that has not been ready yet but I do agree that the messages could be more clear. How about something like "unexpected character near (foo)..." or "unexpected character after (foo)..."?

**Comment by ndbroadbent** [comment]
Hi @ohler55, thanks for your reply! I just realized that the `(foo)` is actually referring to the current "cursor" in the parser, and it's not talking about the content that actually caused the parsing error. (I noticed that it can also be separated by periods when parsing nested JSON structures, so that makes sense.)

I am building an API service, so when someone sends invalid JSON I am sending them the Oj errors in the API response. (With a little bit of regex to remove the `[parse.c:705]` string, etc.) It's really helpful that the Oj errors include the line and column numbers!

I think either "near" or "after" might make the error message more clearer, otherwise my first impression is that something is wrong with the `"foo"` key.

Another idea would be something like this:

```
Oj::ParseError: (in foo) unexpected character at line 1, column 15 [parse.c:705]
```

**Comment by ndbroadbent** [comment]
Oh, I was also thinking that the parser is able to detect the comma character after `"foo": 123`, so should it pop the `(foo)` state once it knows that the the complete `"foo": 123,` section is valid JSON? I'm not at all familiar with the internals of how Oj works, but I'm guessing that it stores `"foo"` to handle this case: `{ "foo": { ...`. But once Oj sees the `,` after `123`, I think it would be safe to "pop" `foo` from the stack and get back to the "root" JSON object, (`()`), and then maybe hide any `()` by default? 

Some examples of what I'm thinking: 

```
Oj.load('{ "foo": 123, bar: 234 }')
```

=> `Oj::ParseError: unexpected character at line 1, column * [parse.c:705]`

```
Oj.load('{ "foo": bar }')
```

=> `Oj::ParseError: unexpected character (foo) at line 1, column * [parse.c:705]`


```
Oj.load('{ "foo": { "bar": baz } }')
```

=> `Oj::ParseError: unexpected character (foo.bar) at line 1, column * [parse.c:705]`


Sorry I don't know if I explained my thoughts clearly enough, or if that makes sense! And no problem at all if this would take too much effort to change. 

Thanks for your time!

**Comment by ohler55** [comment]
Unfortunately it isn't exactly like that. There is a stack but once a key and value are both encountered the value is popped and added to the parent. All that is left is the previous key which is immediately cleared and over-written as soon as the next " character is hit. The path down to the current position is not maintained so it is not available to a full path error message. Oj was designed for speed first and error reporting sometime after that.

I think the reasonable possibilities with the current code would be either no indication of the key or an indication that the error was after the key such as foo. So, what of those two choices makes the most sense to you?

You expressed yourself just fine.

**Comment by ndbroadbent** [comment]
Ah right, that makes sense! I definitely appreciate the performance, and the error messages are miles better than the default JSON library, so I'm definitely very happy either way! I think an indication that the error was after the key would be great if possible. Anyway, I don't want to take up any more of your time! I just thought I'd leave some feedback in case that might be helpful. But I'll close this issue for now because it's nothing urgent. Thanks again for building such a great library!

**Comment by ohler55** [comment]
I'll add in an indication that it is after. Thanks for the feedback.
