### ISSUE TITLE
JSON::GeneratorError:  Invalid Unicode [ff d8 ff e0 00] at 0 in '????'

### ISSUE THREAD

**Issue by KhadeevKamil** [ohler55/oj#604]
I tried to use oj gem and have this problem:

When tests run have this mistake

`JSON::GeneratorError:
       Invalid Unicode [ff d8 ff e0 00] at 0 in '????'`

on string

`payload[:params]       = params.except(:controller, :action, :email, :password, :session, :user, :base).to_json`

with body
`{"attachment"=>
  #<Rack::Test::UploadedFile:0x00007fd9e841dbf0
   @content_type="image/jpeg",
   @original_filename="asset.jpg",
   @tempfile=
    #<File:/var/folders/11/m01tf5c95yx8_0ksd2c02jtc0000gq/T/asset.jpg20200630-96927-jiu3rz>>,
 "site"=>"site",
 "format"=>"json"}`

how resolve it?

**Comment by ohler55** [comment]
Without knowing what the `params.except` returns I can't really determine what would cause the error.

I'm not sure what the body is but it seems to include files of some type and not strings or data that can be converted to JSON.

I suggest looking at the result of `params.except` first and determine what it returns. It it is a Hash or Array then look at each member. Can each member be converted to JSON.

I assume you are actually using Oj and maybe Oj.mimic_JSON, right?

**Comment by KhadeevKamil** [comment]
Problem was in attachment file. OJ can't serialize binary file.
