### ISSUE TITLE
Option `second_precision` seems to be ignored

### ISSUE THREAD

**Issue by lvonk** [ohler55/oj#605]
Hi,

From the documentation at https://github.com/ohler55/oj/blob/develop/pages/Options.md#second_precision-fixnum I thought that setting `second_precision` will allow me to add precision to seconds when dumping `DateTime`s.

However it seems that I only can get millis no matter what I set for `second_precision` 

```ruby
pry(main)> Oj.dump(DateTime.now, second_precision: 0)
=> "\"2020-07-06T14:24:35.675+02:00\""
pry(main)> Oj.dump(DateTime.now, second_precision: 6)
=> "\"2020-07-06T14:30:04.072+02:00\""
```

Am I misunderstanding this option, if so how to tweak the precision DateTime that is dumped?

**Comment by ohler55** [comment]
Make sure you are using a mode that supports that option. https://github.com/ohler55/oj/blob/develop/pages/Modes.md
As an example neither Rails nor the JSON gem mode (:compat) mode support that option as that would make the output different than those gems.

**Comment by lvonk** [comment]
Thanks for the quick reply, I just came to that conclusion myself... 🤦
