### ISSUE TITLE
Inconsistency with JSON.pretty_generate

### ISSUE THREAD

**Issue by robotmay** [ohler55/oj#608]
I've just bumped into an inconsistency with how the `json` gem generates empty arrays/objects in the resulting JSON:

#### json
```
JSON.pretty_generate({ test: [] })
=> "{\n \"test\": [\n\n  ]\n}"
```

#### oj mimicking JSON
```
JSON.pretty_generate({ test: [] })
=> "{\n \"test\": []\n}"
```

I think there's a gap in the compatibility tests to cover this, but as there's not a configuration option for splitting empty arrays/objects over multiple lines, I'm not sure how to implement this fix (or I'd have submitted a patch) :smile:

**Comment by robotmay** [comment]
Just to add to this, the `json` gem isn't even internally consistent:

#### Arrays
```
[

]
```

#### Objects
```
{
}
```

**Comment by ohler55** [comment]
That really is a mess. I suspect it might vary with versions as well. I'll take a look but it will not be a high priority item.

**Comment by robotmay** [comment]
Thanks @ohler55! Yeah I think I need a drink after discovering that :sweat_smile:

I've been writing our own JSON wrapper to help with old legacy expectations like specs needing that horrible formatting, so for now I can force `.pretty_generate` calls through the `json` gem for consistency, so there's no rush from my side :smile:

**Comment by ohler55** [comment]
ok, thanks
