### ISSUE TITLE
3.10.1 seems to have broken how Sets are serialized when using oj_mimic_json

### ISSUE THREAD

**Issue by magni-** [ohler55/oj#609]
• | just `oj`, `JSON.dump(Set.new)` | just `oj`, `Oj.dump(Set.new)` | `oj` + `oj_mimic_json`, `JSON.dump(Set.new)` | `oj` + `oj_mimic_json`, `Oj.dump(Set.new)`
--- | --- | --- | --- | ---
`3.10.1` (and after) | `"#<Set: {}>"` | `{"^o":"Set","hash":{}}` | `"#<Set: {}>"` | `"[]"`
`3.10.0` (and prior) | `"#<Set: {}>"` | `{"^o":"Set","hash":{}}` | `"[]"` | `"[]"`

One of our dependencies calls `JSON.dump`, which when coupled with prior versions of `oj`, would properly cast a Set to an Array. Once we tried upgrading `oj` past `3.10.0`, we ran in the issue outlined above, where the Set is instead serialized as its `#to_s` string.

From looking at the [`CHANGELOG`](https://github.com/ohler55/oj/blob/master/CHANGELOG.md#3101---2020-01-14), I'm not quite sure what the issue is.

**Comment by ohler55** [comment]
I may be looking at the results incorrectly but are you showing that Oj when mimicking the JSON gem is now showing the same behaviour as the JSON gem when before it did not? If so that is the intent of mimicking the JSON gem. Is there a way to modify the calls being made if you don't want the JSON gem behaviour?

**Comment by magni-** [comment]
> are you showing that Oj when mimicking the JSON gem is now showing the same behaviour as the JSON gem when before it did not?

It's the opposite. Until `3.10.0`, both `Oj.dump` and `JSON.dump` returned `"[]"` for an empty set. As of `3.10.1`, `Oj.dump` still returns `"[]"`, but `JSON.dump` now returns `"#<Set: {}>"`.

**Comment by ohler55** [comment]
I must have mis read the table. The first column is using just the actual JSON gem, right? The third column is Oj mimicking the JSON gem. Shouldn't column 1 and 3 match?

**Comment by magni-** [comment]
My bad for the poor formatting, I started writing up this issue before realizing the `oj_mimic_json` gem was involved. Those first two columns are irrelevant (unless I'm misunderstanding the `oj_mimic_json` gem's purpose).

My understanding was that `mimic_JSON` mode meant that `JSON.dump` (3rd column) and `Oj.dump` (4th column) return the same string, as was the case up to `v3.10.0`. Updating `oj` has somehow changed what `JSON.dump` returns (but not what `Oj.dump` returns).

**Comment by ohler55** [comment]
Probably best to add a column that shows what the actual JSON gem returns too. That is the target when Oj is mimicking the JSON gem. Calling `Oj.dump` with `mode: :compat` should also match but not for some edge cases.

**Comment by magni-** [comment]
`JSON.dump(Set.new)` in plain Ruby returns `"#<Set: {}>"`, so I guess we were relying on unintentional behavior by Oj that was fixed 👍 

> 3.10.1 ~seems to have broken~ _fixed_ how Sets are serialized when using `oj_mimic_json`

Thanks for the quick replies throughout this thread 🙏

**Comment by ohler55** [comment]
Sorry it wasn't what you wanted to hear.
