### ISSUE TITLE
Oj dump incorrect value with symbols

### ISSUE THREAD

**Issue by leoluchini** [ohler55/oj#611]
I've just updated my ruby version to 2.6.6 and my Oj gem to `3.10.8` and I realized when I tried to parse a hash with symbols I got this result:

```
irb(main):001:0> require "oj"
=> true
irb(main):002:0> Oj.dump(count: 1)
=> "{\":count\":1}"
```

**Comment by ohler55** [comment]
You are using `:object` mode which is the default. Each mode is a bit different. If you want a key that does not have the leading `:` try one of the others like `:custom`.

**Comment by leoluchini** [comment]
@ohler55 thanks for your response!

**Comment by vhermecz** [comment]
Wow. This just bit me. I'd expect the default output to be valid json.
(Though to be fair, that is not an Oj problem, other JSON library in ruby already did this to me (see: https://stackoverflow.com/a/13734170))

**Comment by ohler55** [comment]
The output is valid JSON and it is not a problem. As the comments above indicate there are multiple modes in Oj. Pick the one that has the behaviour you want. As for the stackoverflow article, the end result of the comments is that it is not problem with the parsers. You have to tell the parser what you want it to product.
