### ISSUE TITLE
Adding Oj to gemfile in rails auto changes JBuilders results

### ISSUE THREAD

**Issue by MosheZemah** [ohler55/oj#615]
I've noticed that only by adding the Oj gem to the gemfile, time value is changed in JBuilder
i.e.
json.test_time(Time.parse('2020-08-08'))

results in "2020-08-08T00:00:00.000+00:00"
while before adding to Gemfile it was "2020-08-08T00:00:00+00:00" (no ".000")

Is it possible to use the Gem without affecting anything related to json in rails? 
I want to be able to use the Oj explicitly in the places I want using Oj.dump.
Thanks

**Comment by MosheZemah** [comment]
A quicker way to reproduce:
a = { time: Time.parse("2020-08-08") }

Before adding OJ to Gemfile:
MultiJson.dump(a)
=> "{\"time\":\"2020-08-08T00:00:00+00:00\"}"

After adding OJ to Gemfile:
MultiJson.dump(a)
=> "{\"time\":\"2020-08-08T00:00:00.000+00:00\"}"

Notice the ".000" added at the end

**Comment by ohler55** [comment]
Depending on what was called in rails Oj maybe be replacing the JSON gem. If `Oj.mimic_JSON` was called that replace the JSON gem. If you want explicit control of when Oj is used do not call that method and instead just call Oj directly with what ever options you prefer for formatting. There are a lot of options.

**Comment by MosheZemah** [comment]
Hi, thanks for the response. We found the issue.
Apparently MultiJson auto select Oj if present, which changed the serialize result we've got
What we did is make MultiJson explicitly use the previous Gem:

MultiJson.use(:json_gem) # make sure MultiJson still uses the json_gem instead of Oj (Oj changes the time format for iOS mobile notifications)

**Comment by ohler55** [comment]
Glad you found the issue. I am a bit surprised iOS doesn't know how to read the RFC3339 formatted time though.
