### ISSUE TITLE
Bigdecimal version

### ISSUE THREAD

**Issue by gottfrois** [ohler55/oj#616]
Hello,

Specifying the bigdecimal version dependency as `~> 2.0` makes the gem incompatible with rails 4 since it cannot use BigDecimal 2.x version.

Unless you really depend on something in version >= 2.0, I would suggest allowing version 1.x and 2.x with something like:

```
spec.add_dependency 'bigdecimal', ['>= 1.0', '< 3']
```

**Comment by ohler55** [comment]
ok, will change

**Comment by scott-knight** [comment]
Changing this to use `~> 1` made this update incompatible with my Rails 6.0 with Ruby 2.7.1 API which uses bigdecimal 2 by default. I have to force the project to use `bigdecimal 1.4.4` or revert to using `oj 3.10.9`. I would think it preferable that an older version of the OJ gem support older (5+ year old unsupported versions) of Rails.

**Comment by ohler55** [comment]
Sigh, can't win. Another release coming up.

**Comment by ohler55** [comment]
released

**Comment by scott-knight** [comment]
In my `Gemfile` I have `gem 'bigdecimal', '~> 2.0', '>= 2.0.0'`, then added `gem 'oj', '~> 3.10', '>= 3.10.11'` and tried running `bundle update` it's still forcing `bigdecimal 1.4.4`

```
Bundler could not find compatible versions for gem "bigdecimal":
  In Gemfile:
    bigdecimal (~> 2.0, >= 2.0.0)

    oj (~> 3.10, >= 3.10.11) was resolved to 3.10.11, which depends on
      bigdecimal (~> 1.0, < 3)
```

**Comment by ohler55** [comment]
So what actually works, just the `~> 2.0`?

**Comment by scott-knight** [comment]
Correct. They way `oj 3.10.9` is set up, that's what works.

**Comment by orien** [comment]
The `~> 1.0` prevents using version 2. I humbly suggest `>= 1.0` instead.

**Comment by ohler55** [comment]
released

**Comment by scott-knight** [comment]
Installed, ran the test suite, works great! Thank you.

**Comment by ohler55** [comment]
Please comment on #617

**Comment by ohler55** [comment]
Can this b closed?

**Comment by and0x000** [comment]
as https://github.com/ohler55/oj/issues/617 has been closed, I think this can be considered resolved as well.
