### ISSUE TITLE
Includes bigdecimal as a runtime dependency

### ISSUE THREAD

**Issue by orien** [ohler55/oj#617]
The `bigdecimal` gem is part of the standard Ruby API. It's included in the official Ruby distribution and its interface included in the API documentation. It's fair to assume that it's present and available.

Note however that different versions of Ruby include different versions of bigdecimal.

- Ruby 2.7.1 comes with bigdecimal 2.0.0
- Ruby 2.6.6 comes with bigdecimal 1.4.1
- Ruby 2.5.8 comes with bigdecimal 1.3.4

Specifying `bigdecimal` as a runtime dependency pushes undue complexity on downstream projects: they are now responsible for managing the version of `bigdecimal`. This is especially difficult as there are breaking changes introduced in version 2.0.0. It's hard to contemplate the problems that may be introduced when using a different version of bigdecimal than the one that comes packaged with Ruby.

I don't believe it's idiomatic to specify a dependency on a gem included in the standard Ruby API. Rails doesn't specify such a dependency even though it makes use of bigdecimal.

In some environments, as described in #613, the official Ruby distribution is divided among multiple OS packages. In these cases, it's expected to install all the packages the application needs. For example, to use bigdecimal on Alpine Linux you would install the [`ruby-bigdecimal`](https://pkgs.alpinelinux.org/package/v3.12/main/x86_64/ruby-bigdecimal) package.

I propose removing the runtime dependency on `bigdecimal`.

**Comment by ohler55** [comment]
Glad to have further discussion.

**Comment by scott-knight** [comment]
Was there a particular reason is was added in 3.10.9?

**Comment by ohler55** [comment]
There was. #613 pointed out that the ruby 2.7.1 in one of the alpine images expected bigdecimal to be included in the dependencies.

**Comment by scott-knight** [comment]
Gotcha. That makes sense. I believe your latest release addresses the issue; it did for my situation. You might need to test the other situations outlined above to make sure those work as well.

**Comment by louim** [comment]
I'm with @orien on this one, i'd rather not have a gem version of the stdlib defined as a dependency. My understanding of the code is that the Bigdecimal require is a quirk for Rubinius? https://github.com/ohler55/oj/blob/f300fa5c8cb33616c8282a9fcb8d947fde947e00/lib/oj.rb#L5-L11
@ohler55 you said here [that Rubinius is not supported anymore](https://github.com/ohler55/oj/issues/454#issuecomment-399277346), would it make sense to remove the hard dependency since I assume it's not needed?

**Comment by ohler55** [comment]
I'll give that a try and push to the develop branch. If interested parties can try it that would be helpful.

**Comment by ohler55** [comment]
Removed and pushed.

**Comment by scott-knight** [comment]
I just update my `Gemfile` with `gem 'oj', git: 'https://github.com/ohler55/oj.git', branch: 'develop'` then ran `bundle update`. It removed references in the `gemfile.lock` :

DELETED
```rb
bigdecimal (2.0.0)

oj (3.10.12)
      bigdecimal (>= 1.0, < 3)
```

Ran rspec tests, everything passed without a hitch for me. Rails 6.0.3.2 with Ruby 2.7.1 using RBENV.

**Comment by and0x000** [comment]
Being the one who started the discussion, I realized, that this might be rather a problem of mine, using the incorrect alpine package.

In alpine, there is `ruby` which is the bare minimum, not including the standard libraries. Then again, there is `ruby-full`, which is a meta package, that includes `ruby` plus the packages covering the standard library. This was a bit counter-intuitive for me, as I would have expected a package `ruby` to cover the full standard library.

Related discussion see https://github.com/simplecov-ruby/simplecov/issues/917

**Comment by ohler55** [comment]
Glad you figured out that issue. I think that resolves the issue for all. I'll release again back to the old way but with the rubinius depends removed.

**Comment by ohler55** [comment]
Released

**Comment by ohler55** [comment]
Can this be closed?

**Comment by scott-knight** [comment]
> Can this be closed?

I believe so. I haven't had any issues since the last release.

**Comment by orien** [comment]
Thanks all. I appreciate the discussion.
