### ISSUE TITLE
float rounding error in tests with 3.10.13 on some architectures

### ISSUE THREAD

**Issue by boutil** [ohler55/oj#620]
Hi,

We uploaded in Debian the new version 3.10.13. The test suite happens to fail on some architectures: armel, armhf, mipsel, hppa
with the same (unique) test failure on these cases:

```
  1) Failure:
CustomJuice#test_float_parse_fast [/<<PKGBUILDDIR>>/test/test_custom.rb:129]:
Expected: "12.12345678901235"
  Actual: "12.12345678901234"
```

You can find the build logs from the following page summarizing the status of the build process of the Debian package for 3.10.13.
https://buildd.debian.org/status/package.php?p=ruby%2doj

Let me know if you want me to test some code on the corresponding architectures.

**Comment by ohler55** [comment]
Looks like were rounding error on the 16 decimal place. I can fix those with some tolerance built into the test. Not sure what to do about ia64 with Ruby 2.5 missing a kernel file though.

**Comment by boutil** [comment]
yes, the ia64 has to be dealt with on Debian's side, since it seems to be a problem with the ruby interpreter on that architecture.

**Comment by ohler55** [comment]
If you are able can you check the develop branch? I just pushed a more tolerant float test.

**Comment by boutil** [comment]
A version 3.10.13-2 has been uploaded in Debian with your changes for more tolerant float tests. All the failures are gone. Thanks a lot.

**Comment by ohler55** [comment]
Released

**Comment by ohler55** [comment]
Can this be closed?

**Comment by boutil** [comment]
Yes, thank you. I am closing it.
