### ISSUE TITLE
parsing multiple colons

### ISSUE THREAD

**Issue by and0x000** [ohler55/oj#622]
When parsing multiple colons in json data, oj converts them into symbols.

Example:
```ruby
[1] pry(main)> require 'oj'
=> true
[2] pry(main)> Oj.load '{"string":"::1"}'
=> {"string"=>:":1"}
```
Please note, that one colon is before the value's quotation marks of the key/value pair after parsing.

With the native JSON class, the value is preserved.

```ruby
[1] pry(main)> require 'json'
=> true
[2] pry(main)> JSON.load '{"string":"::1"}'
=> {"string"=>"::1"}
```

This breaks e.g. when the JSON contains e.g. the shorthand form of IPv6 addresses.

I know that there is the `symbolize_names` option, that converts keys to symbols but I think this should not be applied to values. 

Is this behavior intended? Is there some format option to switch it?

**Comment by ohler55** [comment]
That is the intended behaviour when using the `:object` mode. If you are seeing it in a different mode that would be a bug. `:object` mode is for marshalling and unmarshalling Ruby objects or values. It is not intended to be a mode where hand crafted strings are parsed unless you are familiar with the notations used in that mode.

**Comment by ohler55** [comment]
Did that all make sense to you? Can this be closed?

**Comment by and0x000** [comment]
I haven't had any time to further tinker with it yet, but in general: Yes it makes sense and I think this can be closed for now. Thank you for the explanation.
