### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by hrieke** [ohler55/oj#624]
Ok, first to admit here that I'm quibbling on two very permissive licenses, but I would like to understand a point:
((All || Some) of the) Files in the directory /ext/oj are under the BSD 3-clause license.
Remainder of the code is under the MIT License as found at the root of the project.

Correct or not?

Thanks!

**Comment by ohler55** [comment]
All should be MIT. I'll search for the incorrect ones and changes them. Thanks for pointing that out.

**Comment by hrieke** [comment]
You're welcome.
To everyone else, sorry for the headache!

**Comment by ohler55** [comment]
Released with license removed from the code. Now just the MIT license at the root.
