### ISSUE TITLE
Dumping invalid UTF8 strings sometimes raises errors with mode: rails

### ISSUE THREAD

**Issue by onlynone** [ohler55/oj#626]
Without changing any `default_options` (so `mode` is `:object`), the following two lines run just fine:

```
Oj.dump(message: "\xf3j")
Oj.dump(message: "\"\xf3j")
```

With `Oj.default_options = {mode: :rails}`, the first of the above lines runs fine, but the second fails with:

```
#<EncodingError: Invalid Unicode [6a] at 2 in '"?j'>
```

When executed inside irb, this seems to trigger an unrelated bug in IRB (described here: https://github.com/ruby/irb/issues/141), so you'll need to catch the error before inspecting it.

**Comment by ohler55** [comment]
I'll look into it. I suspect that the issue is that in rails more the string is expected to be unicode.

**Comment by ohler55** [comment]
I believe you will find that Rails raises an exception on the same string which would mean Oj is being consistent with the rails mode. If you see Oj is not exhibiting the same behaviour as Rails let me know the version of Rails you are using and I can take another look.

**Comment by onlynone** [comment]
Wouldn't be surprised if it's a rails thing. But can you tell me how you're checking the rails json encoding behavior? Because when I try:

```
ActiveSupport::JSON.encode(message: "\xf3j")
ActiveSupport::JSON.encode(message: "\"\xf3j")
```

They both fail with `JSON::GeneratorError (partial character in source, but hit end)`. But I'm only seeing the issue with `oj` on the second one.

**Comment by ohler55** [comment]
If they both fail for rails they should both fail for Oj. I look into it. What version of rails or active support are you using?

**Comment by ohler55** [comment]
The digital-class branch has a fix. Please give it a try.

**Comment by ohler55** [comment]
I plan on releasing this in the next day or two. If you can try it out first that would be great.

**Comment by onlynone** [comment]
I guess it's fixed, in that it seems to be consistent whether there's a `\"` or not. But it's a little awkward to test. This is what I get in IRB:

Capturing the error raised when dumping with the `\"`
```
irb(main):014:0> require 'oj'
=> true
irb(main):015:1* begin
irb(main):016:1*   d = Oj.dump({message: "\"\xf3j"}, mode: :rails)
irb(main):017:1* rescue => e
irb(main):018:1*   r = e
irb(main):019:0> end
Traceback (most recent call last):
        3: from /usr/local/opt/ruby@2.6/bin/irb:23:in `<main>'
        2: from /usr/local/opt/ruby@2.6/bin/irb:23:in `load'
        1: from /usr/local/lib/ruby/gems/2.6.0/gems/irb-1.2.7/exe/irb:11:in `<top (required)>'
Encoding::UndefinedConversionError ("\xF3" from ASCII-8BIT to UTF-8)
```

Okay, so I guess the error raised is `Encoding::UndefinedConversionError`. Let's look into it a bit more:

```
irb(main):020:0> r
Traceback (most recent call last):
        3: from /usr/local/opt/ruby@2.6/bin/irb:23:in `<main>'
        2: from /usr/local/opt/ruby@2.6/bin/irb:23:in `load'
        1: from /usr/local/lib/ruby/gems/2.6.0/gems/irb-1.2.7/exe/irb:11:in `<top (required)>'
Encoding::UndefinedConversionError ("\xF3" from ASCII-8BIT to UTF-8)
irb(main):021:0> r.class
=> EncodingError
irb(main):022:0> r.cause
=> nil
irb(main):023:0> r.inspect
=> "#<EncodingError: Invalid Unicode [6a] at 2 in '\"\xF3j\xEE\xFE\x7F'>"
irb(main):024:0> raise r
Traceback (most recent call last):
        5: from /usr/local/opt/ruby@2.6/bin/irb:23:in `<main>'
        4: from /usr/local/opt/ruby@2.6/bin/irb:23:in `load'
        3: from /usr/local/lib/ruby/gems/2.6.0/gems/irb-1.2.7/exe/irb:11:in `<top (required)>'
        2: from (irb):16
        1: from (irb):16:in `dump'
IRB Bug!
```

Okay, so I think the actual error raised was `EncodingError`, but because IRB is attempting to print out the error and the error `message` itself contains the problematic unicode sequence, it also runs into an error. Sometimes that manifests in `Encoding::UndefinedConversionError` being raised, and sometimes that manifests in `IRB Bug!` being printed. It's the same without the `\"` in the original string.

Would it be possible to hide/mask/escape the entirety of the original problematic sequence, so that it doesn't cause other issues upstream?

**Comment by ohler55** [comment]
Good catch. I'll remove the original string from the error message.

**Comment by ohler55** [comment]
Fixed and released.
