### ISSUE TITLE
Oj.load does not respect default_options for empty_string

### ISSUE THREAD

**Issue by ilyadh** [ohler55/oj#627]
Issue:
```
[1] pry(main)> Oj.default_options = { empty_string: true }
=> {:empty_string=>true}
[2] pry(main)> Oj.default_options[:empty_string]
=> true
[3] pry(main)> Oj.load("")
Oj::ParseError: unexpected character at line 1, column 1 [parse.c:617]
from (pry):3:in `load'
[4] pry(main)> Oj.load("", empty_string: true)
=> nil
```

Expected behavior (as in the last working version **3.3.6**):
```
[1] pry(main)> Oj.default_options = { empty_string: true }
=> {:empty_string=>true}
[2] pry(main)> Oj.load("")
=> nil
[3] pry(main)> Oj.default_options = { empty_string: false }
=> {:empty_string=>false}
[4] pry(main)> Oj.load("")
Oj::ParseError: unexpected character at line 1, column 1 [parse.c:617]
from (pry):3:in `load'
```

Issue reproduces starting from 3.3.7 and up to 3.10.16

**Comment by ilyadh** [comment]
I looked at the source code, and found out that `:rails` mode, that I was using, hard overrides some of the default options. And from [pages/Modes](https://github.com/ohler55/oj/blob/develop/pages/Modes.md) I see it's documented behaviour. 

It's still is kind of a bummer that this got broken in a patch/minor version update. It's easy enough to start to rely on buggy behaviour without noticing 😄. And then try to update and have a lot of code to fix accidentally 😅.

I'll close the issue for now, but maybe it's possible to provide an additional keyword argument, something like `force: true` to allow to override options from `mode` @ohler55?

**Comment by ohler55** [comment]
The approach I usually take is to use the custom mode. Then all options work. The rails and compat modes are really just trying to keep up with the idiosyncrasies of active support and the json gem. Staying compatible has cause more issues than anything else. I'm afraid that offering a way to break compatibility will only lead to more confusion.
