### ISSUE TITLE
Fiber transparency

### ISSUE THREAD

**Issue by flash-gordon** [ohler55/oj#633]
Hey 👋 Thank you for working on this gem, I've been using it for years.

Recently I've been asked about the compatibility of `Oj::Rails::Encoder` and [dry-effects](https://github.com/dry-rb/dry-effects). Under the hood, dry-effects uses fibers and this seems to break things in presence of the Rails encoder. Take a look at the repro:

```ruby
require 'oj'

class Foo
  def as_json
    { value: Fiber.yield }
  end
end

fiber = Fiber.new do
  Oj::Rails::Encoder.new({}).encode(Foo.new)
end

fiber.resume
result = fiber.resume(1)
```

It fails with:

```
oj_spec.rb:5:in `yield': fiber called across stack rewinding barrier (FiberError)
        from oj_spec.rb:5:in `as_json'
        from oj_spec.rb:10:in `encode'
        from oj_spec.rb:10:in `block in <main>'
```

Apparently, this is because of the barrier set at https://github.com/ohler55/oj/blob/b73e9fed77b34bbefc83807e4ea1e31f9ed92ecb/ext/oj/rails.c#L938

Not pretending to understand the details I'm wondering is this a bug or a limitation of the Rails encoder?

**Comment by ohler55** [comment]
To be clear, the code is for the Oj::Rails::Encoder which is different than the Rails::Encoder. The limitation is indeed in the code. The rb_protect call is to catch raised exceptions. It has to be there to avoid segfaults although rb_rescue2 could be used instead. I don't know if the same barrier would be set up with rb_rescue2 or not but I suspect it would.

Looking at the issue from a different perspective, if an exception is raised in as_json in a different fiber you would want that exception to be passed to the original call to encode but exceptions don't cross fibers.

So, solutions might be to make an alternative encode call that is not protected from raised exceptions but then Oj::Rails::Encoder would not be compatible with the Rails::Encoder. It might be a win but it would lock you into the Oj::Rails::Encoder.

**Comment by ohler55** [comment]
Comments?

**Comment by flash-gordon** [comment]
@ohler55 yeah, sorry for this silence and thank you for the clear explanation. I think it'd be nice to have an option for this, saying it's guaranteed there'll be no exceptions in the fiber. From the library's perspective, I can catch them all and re-throw in the encoder's fiber. Maybe this option can be provided by default in a subclass of `Oj::Rails::Encoder`, then compatibility-wise it'll be no different from `Rails::Encoder`, am I getting this correctly?

**Comment by ohler55** [comment]
Something like that although it would be a `Oj::Rails::EncoderX` that would be set up to not be protected so any exception would crash the system. You would have to be sure there would be no errors. Kind of risky.

**Comment by ohler55** [comment]
Can this be closed?

**Comment by flash-gordon** [comment]
@ohler55 I'll close since it's answered, thanks. I think I can experiment with the `rb_rescue2` option and a custom encoder. I'm not entirely sure it's safe or "wise" having it as a configuration option in `Oj::Rails::Encoder` so I don't even propose that :)
