### ISSUE TITLE
Minor: test_time is duplicated in test_compat.rb

### ISSUE THREAD

**Issue by mqchau** [ohler55/oj#635]
https://github.com/ohler55/oj/blob/362ce48caefceac5eb60afec8d6ea5a7443d8458/test/test_compat.rb#L181
https://github.com/ohler55/oj/blob/18a28049a8cc6aecc0802e6035bc445e78240d3e/test/test_compat.rb#L287

Should I make a PR to fix it?

**Comment by ohler55** [comment]
That would be great. Would like to see your name on the list of contributors.
