### ISSUE TITLE
GC.compact moves references held by Oj, leading to TypeErrors

### ISSUE THREAD

**Issue by pushrax** [ohler55/oj#637]
After loading Oj and running GC.compact, errors like this can occur ``... in `safe_load': wrong argument type Time (expected Class) (TypeError)``

@casperisfine worded this well:
> Since Ruby 2.7, C global variables holding references to Ruby objects must be declared to the GC even if they are also held from the Ruby side, otherwise a call to GC.compact might move them to another location.

Examples of fixes to other C extensions:

https://github.com/brianmario/mysql2/pull/1115
https://github.com/Shopify/semian/pull/275

cc @XrXr @casperisfine this is blocking use of GC.compact in SFR, if you feel like tackling it. Or @ohler55 of course 😄

**Comment by ohler55** [comment]
It will take some research to figure out the new way of marking variables. If you have any references that would help.

**Comment by pushrax** [comment]
Thanks @XrXr!!

**Comment by ohler55** [comment]
It will get released today. Just waiting on travis and considering moving to AppVeyor if CI is going to take so long.

**Comment by casperisfine** [comment]
Everybody is moving to GitHub actions these days.

**Comment by ohler55** [comment]
I'll take a look at actions then. Thanks for the suggestion.

**Comment by BuonOmo** [comment]
@ohler55 just bumping in there, I've recently moved a few projects to github actions, I could help with that easily (you'd still need to change a few settings of course)

**Comment by ohler55** [comment]
That would be great. I'm ready whenever you are.
