### ISSUE TITLE
Compat mode behavior change

### ISSUE THREAD

**Issue by kmasuda-aiming** [ohler55/oj#640]
### Steps to reproduce

```
$ irb
> require 'oj'
> Oj.default_options = { mode: :compat }
> Oj.load('3.14159265358979323846')
> Oj.load('3.141592653589793')
```

### Expected behavior

oj 3.10.18 behavior
```
> Oj.load('3.14159265358979323846')
=> 0.314159265358979323846e1
> Oj.load('3.141592653589793')
=> 3.141592653589793
```

### Actual behavior

after oj 3.11.0
```
> Oj.load('3.14159265358979323846')
=> 3.141592653589793
> Oj.load('3.141592653589793')
=> 3.141592653589793
```

https://github.com/ohler55/oj/blob/2e83d4dd46f0cf40ce1209b62629f87c9389673d/ext/oj/oj.c#L596-L600
`compat_bigdec` is expect boolean, but assign BigLoad. Is it correct?

**Comment by ohler55** [comment]
I do believe you have found a bug. I'll get that fixed tomorrow. Good catch. Basically any value would be treated as true.

**Comment by ohler55** [comment]
Please try the bug/decimal-class branch.

**Comment by kmasuda050** [comment]
Thanks.

bug/decimal-class branch behavior is below.
```
> Oj.load('3.14159265358979323846')
=> 3.141592653589793
> Oj.load('3.141592653589793')
=> 3.141592653589793
```
Did AutoDec become unusable compat mode?

**Comment by kmasuda-aiming** [comment]
Thanks.

bug/decimal-class branch behavior is below.
```
> Oj.load('3.14159265358979323846')
=> 3.141592653589793
> Oj.load('3.141592653589793')
=> 3.141592653589793
```
Did AutoDec become unusable compat mode?

**Comment by ohler55** [comment]
Yes. compat mimics the JSON which does not have the `:bigdecimal_load` that Oj has. The JSON gem alternative is `:decimal_class` which can be either Float or BigDecimal. It is not a documented feature of the JSON gem but it does exist. To use the Oj `:bigdecimal_load` option the custom mode is best.

**Comment by kmasuda-aiming** [comment]
Thank you for your advice. I change to use custom mode.

bug/decimal-class branch commit looks good to me 👍

**Comment by ohler55** [comment]
Thank you. I will release today.

**Comment by ohler55** [comment]
Release. 39

**Comment by kmasuda-aiming** [comment]
Thanks for the quick release.
