### ISSUE TITLE
Oj.load(Oj.dump(object)) doesn't return the same object

### ISSUE THREAD

**Issue by senhalil** [ohler55/oj#643]
I have an [active_hash](https://github.com/zilkey/active_hash) model and after Oj.dump+load the object doesn't stay the same.

```
(byebug) vrp == Oj.load(Oj.dump(vrp))
false
(byebug) vrp == Oj.load(Oj.dump(vrp, mode: :object))
false
(byebug) vrp == Oj.load(Oj.dump(vrp, mode: :compat))
false
```

I tried and the same object can be Marshal'ed. 
```
(byebug) vrp == Marshal.load(Marshal.dump(vrp))
true
```

In fact the difference comes from the sub-objects. There is a sub-object which has a field that references to another sub-object (there is no circular relation afaik) but this is not the case after Oj.dump+load.

In the original object, `vrp[:services][0][:activity][:point]` points to `vrp[:points][0]` and there is only one `Models::Point` object
```
(byebug) vrp[:services][0][:activity][:point].object_id
47462055170100
(byebug) vrp[:points][0].object_id
47462055170100
(byebug) vrp[:services][0][:activity][:point]
#<Models::Point:0x000056553de0a068 @attributes={:id=>"p194", :location=>#<Models::Location:0x000056553de09ff0 @attributes={:lat=>45.766483, :lon=>4.883626, :id=>195}>, :associated_stops=>[], :matrix_index=>0}>
(byebug) vrp[:points][0]
#<Models::Point:0x000056553de0a068 @attributes={:id=>"p194", :location=>#<Models::Location:0x000056553de09ff0 @attributes={:lat=>45.766483, :lon=>4.883626, :id=>195}>, :associated_stops=>[], :matrix_index=>0}>
```

but this is not the case for `vrp_oj = Oj.load(Oj.dump(vrp))` and there are two different `Models::Point` objects:

```
(byebug) vrp_oj[:services][0][:activity][:point].object_id
47462053065160
(byebug) vrp_oj[:points][0].object_id
47462053135940
(byebug) vrp_oj[:services][0][:activity][:point]
#<Models::Point:0x000056553da06390 @attributes={:id=>"p194", :location=>#<Models::Location:0x000056553da062f0 @attributes={:lat=>45.766483, :lon=>4.883626, :id=>195}>, :associated_stops=>[], :matrix_index=>0}>
(byebug) vrp_oj[:points][0]
#<Models::Point:0x000056553da28c88 @attributes={:id=>"p194", :location=>#<Models::Location:0x000056553da28bc0 @attributes={:lat=>45.766483, :lon=>4.883626, :id=>195}>, :associated_stops=>[], :matrix_index=>0}>
```

Is this a bug or our use case doesn't quite fit the bill?

**Comment by ohler55** [comment]
If you want to preserve s shared reference then the circular option should be used.

**Comment by senhalil** [comment]
Yeap, that did the trick!

I read the description of all options before asking; however, since there were no loops in my object I didn't realize that it might be related. 

Maybe the description of this option can be improved as "Detect circular 'and/or shared' references while dumping." or better, a separate option `:shared` might be useful since looped references are a very specific. It can be an alias to `:circular` option at first and can be optimized later. 

In any case, I am marking this ticket as closed, thanks @ohler55 !

**Comment by ohler55** [comment]
The processing and encoded format would be the same for circular vs shared. I'll update the docs for the circular option. You are correct it could be more clear.
