### ISSUE TITLE
License ambiguity

### ISSUE THREAD

**Issue by ziggythehamster** [ohler55/oj#646]
In #624, you removed the license headers from the C sourcecode, but you left "All rights reserved." in the license header. It's clear from your actions in that issue as well as the root-level license file that you intend to license it MIT, but I think legal departments might interpret this as "the Ruby code is MIT, but the C code cannot be freely copied", at least given my experience lately of having to dig up license files for auditing reasons.

I would suggest adding something like "See LICENSE file for usage rights." or "Licensed MIT, see LICENSE for more information."

I hope this issue report doesn't annoy you too much, having recently fixed a related issue :).

**Comment by ohler55** [comment]
If I understand correctly the copyright in the header is fine but the rights should be changed to refer to the license file. Kind of makes sense.

**Comment by ohler55** [comment]
Push changes to the develop branch. After doing some reading and looking for consensus I left the rights statement but added the license reference. I think that works. "All rights reserved" indicates no rights are given up and the license tells how the source can be used.

**Comment by ziggythehamster** [comment]
I think what you've committed is perfect. My concern was that some lawyer-type would consider the C code to be proprietary and not subject to the MIT license like you obviously intended. I think it'd be less of a problem in Europe, where "all rights reserved" is interpreted less literally than in the US, where "all rights reserved" is the sort of thing I would be requested to put on proprietary code with no license.
