### ISSUE TITLE
NoMethodError when calling Oj.generate

### ISSUE THREAD

**Issue by mmainz** [ohler55/oj#655]
I think there is a bug in your last release. I can't call `Oj.generate` anymore without receiving an error. Even when just starting an IRB and only loading Oj, it immediately errors.

```ruby
irb(main):001:0> require 'oj'
=> true
irb(main):002:0> Oj.generate({})
Traceback (most recent call last):
        5: from /Users/mmainz/.asdf/installs/ruby/3.0.0/bin/irb:23:in `<main>'
        4: from /Users/mmainz/.asdf/installs/ruby/3.0.0/bin/irb:23:in `load'
        3: from /Users/mmainz/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/irb-1.3.0/exe/irb:11:in `<top (required)>'
        2: from (irb):2:in `<main>'
        1: from (irb):2:in `generate'
NoMethodError (undefined method `new' for false:FalseClass)
```

**Comment by ohler55** [comment]
You are correct. I'll add a test and fix.

**Comment by ohler55** [comment]
For a quick fix, call `Oj.mimic_JSON` first.

**Comment by mmainz** [comment]
> For a quick fix, call `Oj.mimic_JSON` first.

No worries, I just reverted by one patch version and everything works fine.

**Comment by ohler55** [comment]
Version v3.11.5 pushed with the fix.

**Comment by mmainz** [comment]
It's working now, thanks a lot!
