### ISSUE TITLE
:float_precision option retains too many digits if there is a nonzero digit at the end of the string

### ISSUE THREAD

**Issue by HotFusionMan** [ohler55/oj#660]
Test program:
```ruby
require 'oj'

Oj.default_options = { :mode => :strict, :float_precision => 6 }

hash = Oj.load( <<~EOJSON
{
  "b": 0.028000000000000004
}
EOJSON
)

puts Oj.dump(hash)
```
Running the above results in `{"b":0.28000000000000004e-1}` being printed out, despite the fact that the trailing digit 4 is far, far past the 6 digits of precision asked for.

**Comment by ohler55** [comment]
What you are seeing is the number in the hash is not a float but a bigdecimal. If you don't care about the extra precision  that is included in the EOJSON then force the loaded value to a float using `:bigdecimal_load` and set it to `:float`. Oj assume that if the JSON includes a decimal number with that many decimals it should keep all decimals and the only way to do that is with a BigDecimal. You can change that default with the `:bigdecimal_load` option.

**Comment by HotFusionMan** [comment]
Thanks for the quick response! I'm closing this issue.
