### ISSUE TITLE
Oj::Rails.mimic_JSON() raises Oj::ParseError 

### ISSUE THREAD

**Issue by hmcfletch** [ohler55/oj#663]
I might be misunderstanding the expected behavior, but I am seeing some differences between `Oj::Rails.mimic_JSON()` and `Oj.mimic_JSON()` that I did not expect.

I was looking at #555 and used the same test in a little script to replicate the issue I am seeing.

Works as expect, the parser error is handled correctly.
```ruby
require 'active_support'
require 'oj'

Oj.mimic_JSON()
begin
::JSON.load('name=&email=&subject=&comment=&submit=Send+Message')
rescue ::JSON::ParserError
  put 'parser error handled'
end
```

The following raises and `Oj::ParseError` which is not handled.
```ruby
require 'active_support'
require 'oj'

Oj::Rails.mimic_JSON()
begin
::JSON.load('name=&email=&subject=&comment=&submit=Send+Message')
rescue ::JSON::ParserError
  put 'parser error handled'
end
```

We were using `Oj.optimize_rails()`, but I was able to track the issue to this particular call.

**Versions**
`Ruby`: `ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]`
`ActiveSupport`: `6.1.3.2`
`Oj`: `3.11.6`

**Comment by ohler55** [comment]
Please try the rails-mimic-json branch. I believe that fixes the issue. If it does I will release a new version of Oj.

**Comment by hmcfletch** [comment]
It looks like it works! Just to be sure this is what I did to test my script:
```bash
> git checkou rails-mimic-json
> cd ext/oj
> ruby extconf.rb
> make
> cd ../..

```

`test.rb`
```ruby
require 'active_support'
require_relative 'lib/oj'
puts RUBY_VERSION
puts ActiveSupport.version
puts Oj::VERSION
# Oj.mimic_JSON()
Oj::Rails.mimic_JSON()

begin
::JSON.load('name=&email=&subject=&comment=&submit=Send+Message')
rescue ::JSON::ParserError
  puts 'parser error handled'
end
```

```bash
ruby -I ~/Projects/oj/ext -I ~/Projects/oj/lib test.rb
```

Both versions of `mimic_JSON()` print out `parser error handled`.

**Comment by hmcfletch** [comment]
Thanks for the super prompt response!
