### ISSUE TITLE
v3.11.7 causing strange issues with non-rails app

### ISSUE THREAD

**Issue by abury** [ohler55/oj#665]
Hi Team,

I'm investigating the details of this, but I was hoping to get a bit of insight if possible to help. After deploying this update to a non rails app, we found that a specific service started failing.

Totally aware that that's no where near enough information, I'm currently digging through multiple layers of obfuscation trying to get to the root cause, but I was hoping to gleen some understanding of this line

```ruby
oj_default_options.mode = RailsMode;
```
would this have any impact on non rails apps at all? I assume not given the location and the default options don't seem to have changed after the update, it's just one of the straws I'm clutching at at the moment.

Cheers

**Comment by tonobo** [comment]
Howdy, can confirm this in some kind. Our pipelines noticed issues with 3.11.7 as well, but I haven't investigated further yet.

**Comment by ohler55** [comment]
If you are attempting to set the default options for Oj try `Oj.default_options = {mode: :rails}`. The default is `:object` mode.

Of course that may have nothing to do with what ever wrappers or layers you have on top of Oj.

**Comment by abury** [comment]
Glad to hear it's not just us @tonobo, we're continuing to look into it this week, will report back here with any findings. Are you experiencing it on a non rails app as well?

@ohler55 the default mode shouldn't have changed in this release though right? I've checked the options for 3.11.6 and 3.11.7 and couldn't find any differences so feeling like this may be a dead end unfortunately.

Unfortunately the error we were receiving from our cloud provider makes absolutely no sense given the problem domain, suspect there may be an error in their reporting. We'll hopefully hear back from them today/tomorrow which should help us look into this more accurately.

**Comment by ohler55** [comment]
No change in the defaults. It has been `:object` mode since day one. If I knew more about the way Oj was being used I might be able to help more.

**Comment by abury** [comment]
I suspected that was the case, but thanks for clarifying.

**Comment by tonobo** [comment]
I've found the cause and it was totally unrelated to oj at all. Sorry for the inconvenience

**Comment by ohler55** [comment]
okay to close?
