### ISSUE TITLE
[v3.11.7] Oj.optimize_rails overwrites existing default_options configuration

### ISSUE THREAD

**Issue by codealchemy** [ohler55/oj#668]
Seen when upgrading from `v3.11.6`.

Given a Rails project with an initializer for setting up the Oj configuration, if `Oj.optimize_rails` (or `Oj::Rails.mimic_JSON`) is called _after_ setting `Oj.default_options = { mode: :object }`, the mode is overridden as `mode: :rails`.

Per the [Rails compatibility doc](https://github.com/ohler55/oj/blob/develop/pages/Rails.md#oj-rails-compatibility), this appears to be an unexpected change from prior behavior

>Either of those steps will setup Oj to mimic Rails but it will not change the default mode type as the mode type is only used when calling the Oj encoding directly. If Rails mode is also desired then use the Oj.default_options to change the default mode.

A simple workaround is to reorder the calls such as `Oj.default_options` sets the `mode` _after_ `Oj.optimize_rails` is called.

Reproduced on Rails `5.2` and `6.1` using an initializer 

```
➜  oj_override_default_options_example git:(master) ✗ cat config/initializers/json.rb
require 'oj'

Oj.default_options = { mode: :object }
Oj.optimize_rails # or Oj::Rails.mimic_JSON()
➜  oj_override_default_options_example git:(master) ✗ rails c
Loading development environment (Rails 6.1.4)
irb(main):001:0> Oj.default_options[:mode]
=> :rails
```

**Comment by ohler55** [comment]
I'll look into it. I think I know what happened.

**Comment by ohler55** [comment]
The default mode setting is commented out in the default-mode branch. I still have to verify nothing else breaks but please give it a try.

**Comment by codealchemy** [comment]
<details>

<summary>I gave the `default-mode` branch a run on the example I had set up - the issue looks to be resolved for the check I was using</summary>

```
➜  oj_override_default_options_example git:(master) ✗ cat Gemfile | grep oj
gem 'oj', git: 'https://github.com/ohler55/oj.git', branch: 'default-mode'
➜  oj_override_default_options_example git:(master) ✗ cat config/initializers/json.rb
require 'oj'

Oj.default_options = { mode: :object }
Oj.optimize_rails # or Oj::Rails.mimic_JSON()
➜  oj_override_default_options_example git:(master) ✗ rails c
Loading development environment (Rails 6.1.4)
irb(main):001:0> Oj.default_options[:mode]
=> :object
```

</details>

**Comment by ohler55** [comment]
Thanks for the quick check.

**Comment by ohler55** [comment]
v3.11.8 released

**Comment by ohler55** [comment]
And v3.12.0 released with a boost in speed!

**Comment by codealchemy** [comment]
Great - thank you for such a quick response! Closing now that this is resolved.
