### ISSUE TITLE
ArgumentError: :cache_str must be a Integer with Oj::CUSTOM_MIMIC_JSON_OPTIONS

### ISSUE THREAD

**Issue by troex** [ohler55/oj#677]
```
> Oj.default_options = Oj::CUSTOM_MIMIC_JSON_OPTIONS
ArgumentError: :cache_str must be a Integer.
from (pry):6:in `default_options='
> Oj::VERSION
=> "3.12.2"
```

Also I don't see any docs in Options or Modes files about `cache_keys` and `cache_str`

**Comment by ohler55** [comment]
There is some documentation here http://www.ohler.com/oj/doc/Oj.html but you are correct. I forgot to update the options and modes page. The `Oj:: CUSTOM_MIMIC_JSON_OPTIONS` is also broken so I will fix both issues tonight.

**Comment by ohler55** [comment]
Fixed in the release yesterday.

**Comment by ohler55** [comment]
Can this be closed?
