### ISSUE TITLE
Memory leak introduced in 3.12.0

### ISSUE THREAD

**Issue by normelton** [ohler55/oj#696]
We've been chasing a memory leak in Oj. It seems that our project runs fine with 3.11.8, but upgrading to 3.12.0 (or anything thereafter) results in a slow memory leak. After about 24 hours, all the memory is used up and our process crashes.

Most frustrating, I can't seem to reproduce this in a test case. Equally frustrating, other projects that use Oj in the same fashion don't have a problem. 

I know we have nothing really to go on, is there a recommended path for diagnosing a memory leak in production?

**Comment by normelton** [comment]
If it helps ...

`Oj.default_options = {:mode => :rails }`

**Comment by ohler55** [comment]
A caching option was introduced in 3.12. It gives a nice speedup when the input hash keys repeat but if the hash keys continue to change then memory will be used for each new key. The cache option can be turned off with the `:cache_keys` and `:cache_strings` option.

I am in the process of updating the caching to expire cached keys and strings if they are not used for a few GC cycles. That will most likely solve the issue you are seeing while still being able to bet the performance boost from caching.

Let me know it that takes care of the issue. If not I'll look more and if need be create a debug version for you.

**Comment by normelton** [comment]
Ahh thanks, I'm disabling the cache now and will let it run. Should know for sure by tomorrow morning.

Thanks for the quick response!

**Comment by normelton** [comment]
Okay, I've got:

`Oj.default_options = {:mode => :rails, :cache_keys => false, :cache_strings => false }`

But still see memory usage growing. With 3.11, system RAM usage hovers around 1GB, it's currently at 2GB and trending upward.

**Comment by ohler55** [comment]
`:cache_strings` should be a number. Set it to -1 for no caching.

Did the change help some?

**Comment by ohler55** [comment]
If you are interested I have a branch that includes the expiring cache mentioned earlier. If you have a place to try it that would be great.

**Comment by normelton** [comment]
Well ...

`Oj.default_options = {:mode => :rails, :cache_keys => false, :cache_strings => -1 }`

... and memory is still growing. This is on 3.12.0. I'll try the expire-cache branch and let you know what we find.

Thanks!

**Comment by ohler55** [comment]
Thank you. Is the memory growing less or the same? If the same we might be looking in the wrong place.

**Comment by normelton** [comment]
Good news, memory usage has remained stable over the weekend..

https://imgur.com/a/VgzpAKP

**Comment by ohler55** [comment]
Excellent. I'll merge into develop. Maybe do a release. I have to double check a few things first though.

**Comment by ohler55** [comment]
Released!

**Comment by ohler55** [comment]
Can this be closed?

**Comment by normelton** [comment]
Yep, thanks again for the help!
