### ISSUE TITLE
undefined method `reject' for #<JSON::Ext::Generator::State:0x000055e83837d400>

### ISSUE THREAD

**Issue by bheemreddy181** [ohler55/oj#697]
Has anyone seen issues like this before with version 3.13 ?

**Comment by bheemreddy181** [comment]
This still fails on this particular brach 
```
GIT
  remote: https://github.com/ohler55/oj.git
  revision: 5dca1cf36a5194cd9d7e78f3158fbb87b0e36718
  branch: expire-cache
  specs:
    oj (3.13.3a2)
```
but i think now the error is from a different gem I assume

**Comment by ohler55** [comment]
It is likely that the failure is not Oj but the JSON gem State object. The real culprit is that ever code is assuming the argument is a Hash and not a JSON::State.

**Comment by bheemreddy181** [comment]
https://github.com/trailblazer/roar/issues/104#issuecomment-908658897 error for reference

**Comment by ohler55** [comment]
Ok to close?

**Comment by bheemreddy181** [comment]
Can you release the above branch and close it ?

**Comment by ohler55** [comment]
The change was in the 3.13.3 release at the end of August. As noted though I suspect it is actually the JSON gem State that is raising the exception. Well really the calling code but if it is a Oj JSON::State it will act correctly.

**Comment by bheemreddy181** [comment]
Makes sense please go ahead then appreciate your insights on this thanks
