### ISSUE TITLE
add CHANGELOG.md to gemspec

### ISSUE THREAD

**Issue by nijikon** [ohler55/oj#698]
Can we please add `CHANGELOG.md` to the gemspec file [here](https://github.com/ohler55/oj/blob/develop/oj.gemspec#L25). That change will allow getting the information straight from the release while diffing. With a tool like Diffend, for example, https://my.diffend.io/gems/oj/3.13.2/3.13.3.

**Comment by ohler55** [comment]
Thanks for the suggestion. I added it in the develop branch so it will go into the next release.

**Comment by nijikon** [comment]
@ohler55 Thanks!
