### ISSUE TITLE
Time serialization output changed between 3.11.3 and 3.11.4

### ISSUE THREAD

**Issue by grk** [ohler55/oj#701]
Something in 3.11.4 changed so that the output of `JSON.dump(Time.current)` changed. 

Reproducible with the following ruby code:

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "activesupport", "6.1.4.1"
  gem "oj", ENV.fetch("OJ_VERSION")
end

require "active_support/all"
require "oj"

Time.zone = "UTC"

Oj.optimize_rails

puts Time.current.as_json
puts Time.current.to_json
puts JSON.generate(Time.current)
```

```
➜  oj_repro OJ_VERSION=3.11.3 ruby oj-repro.rb
2021-09-06T16:42:14.231Z
"2021-09-06T16:42:14.231Z"
"2021-09-06T16:42:14.231Z"
➜  oj_repro OJ_VERSION=3.11.4 ruby oj-repro.rb
2021-09-06T16:42:15.778Z
"2021-09-06T16:42:15.778Z"
"2021-09-06 16:42:15 UTC"
```

I compared this to how it works without oj, and the change from 3.11.4 works the same way, even though it's inconsistent internally:

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "activesupport", "6.1.4.1"
end

require "active_support/all"

Time.zone = "UTC"

puts Time.current.as_json
puts Time.current.to_json
puts JSON.generate(Time.current)
```

```
➜  oj_repro ruby no-oj.rb                     
2021-09-06T16:42:17.795Z
"2021-09-06T16:42:17.796Z"
"2021-09-06 16:42:17 UTC"
```

With that, I'm not sure if this should even be an issue or not.

**Comment by ohler55** [comment]
In rails or compat mode Oj is meant to act the same as the JSON gem. At you notes Oj is same as the JSON at least in those 3 examples. The JSON has many case that most people might find inconsistent. Oj has to follow along to be compatible even if they do seem like like bugs.

**Comment by grk** [comment]
Yeah, the output changed between 3.11.3 and 3.11.4 but in the newer version it's more consistent with how bare Rails works, so while surprising it is not a bug.

I think the underlying cause is that it used to try to call `as_json` on anything that was being serialized. Here's an example for nested objects:

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "activesupport", "6.1.4.1"
  gem "oj", ENV.fetch("OJ_VERSION")
end

require "active_support/all"
require "oj"

class A
  def initialize(foo, bar)
    @foo = foo
    @bar = bar
  end

  def as_json(*)
    {
      foo: @foo,
      bar: @bar
    }
  end
end

class Bar
  def initialize(baz)
    @baz = baz
  end

  def as_json(*)
    {
      baz: @baz
    }
  end
end

a = A.new("foo", Bar.new("baz"))

Oj.optimize_rails

puts a.as_json
puts a.to_json
puts JSON.generate(a.as_json)
```

```
➜  oj_repro OJ_VERSION=3.11.3 ruby object-serialization.rb
{:foo=>"foo", :bar=>#<Bar:0x00000001029b3810 @baz="baz">}
{"foo":"foo","bar":{"baz":"baz"}}
{"foo":"foo","bar":{"baz":"baz"}}
➜  oj_repro OJ_VERSION=3.11.4 ruby object-serialization.rb
{:foo=>"foo", :bar=>#<Bar:0x0000000145359418 @baz="baz">}
{"foo":"foo","bar":{"baz":"baz"}}
{"foo":"foo","bar":"#<Bar:0x0000000145359418>"}
```

**Comment by ohler55** [comment]
Are you saying that example differs when using the JSON gem vs Oj?

**Comment by ohler55** [comment]
I figured it was a bug since Oj is supposed to be like the JSON gem that's why it was a point release. There was an issue opened for it if I remember correctly. Of course it could also be that the JSON gem behaviour changed. That has happened before as well.
