### ISSUE TITLE
Segmentation fault using Oj::Parser

### ISSUE THREAD

**Issue by evanleck** [ohler55/oj#703]
I'm hitting a segmentation fault using the new `Oj::Parser.new(:usual)` on a trivial JSON string. I've created a reproduction repository at https://github.com/evanleck/oj-segfault-reproduction that includes the details of the fault as well the JSON and Ruby script to reproduce it. 

The strange thing is that the script appears to finish running and faults _after_ it completes. I produced the JSON by whittling down an existing package.json to the parts that produce the fault.

**Comment by ohler55** [comment]
Working on it soon.

**Comment by ohler55** [comment]
Please try the "off-by-one" branch.

**Comment by ohler55** [comment]
BTW, are you reusing the parser? That is the suggested use.

**Comment by ohler55** [comment]
Your suggestion for optional arguments has also been added so `Oj::Parser.new(:usual, cache_keys: true)` now works. Add as many pairs as desired.

**Comment by evanleck** [comment]
@ohler55 the off-by-one branch no longer segfaults in my reproduction repo, thanks for fixing that so quickly! Yeah, I'm basically creating one parser instance per thread and re-using it as long as the thread is alive (I'm using it in a Puma-backed web app, so whenever Puma cleans up the thread a new parser will get created).

Thanks for adding the configuration options to initialization, I'll give it a shot shortly!

**Comment by ohler55** [comment]
Released!

**Comment by evanleck** [comment]
Thanks!
