### ISSUE TITLE
JSON.load doesn't symbolize names

### ISSUE THREAD

**Issue by Yv-vY** [ohler55/oj#704]
When using Oj as a replacement for the standard library JSON module, with the use of `Oj.mimic_JSON` I've found that the `load` method fails to symbolize names. What is not consistent with the standard library.

```
 $ ./json_parse_vs_load.rb
JSON.load, no symbolize => OK
{"a"=>1, "b"=>2}
JSON.load, symbolize => KO: keys are not symbols
{"a"=>1, "b"=>2}
JSON.load, no symbolize => OK
{"a"=>1, "b"=>2}
JSON.load, do symbolize => OK
{:a=>1, :b=>2}
```

I'm using the latest version of Ruby (3.0.2) and the latest version of Oj (3.6.13).

Here's my test script:
```
#!/usr/bin/env ruby

# require 'json'
require 'oj'
Oj.mimic_JSON

source = %( {"a": 1, "b": 2} )
puts "JSON.load, no symbolize => OK"
pp JSON.load( source )
puts "JSON.load, do symbolize => KO: keys are not symbols"
pp JSON.load( source, nil, symbolize_names: true, create_additions: false )
puts "JSON.parse, no symbolize => OK"
pp JSON.parse( source )
puts "JSON.parse, do symbolize => OK"
pp JSON.parse( source, symbolize_names: true )

```

**Comment by ohler55** [comment]
I'll take a look.

**Comment by ohler55** [comment]
Oj is still using the old JSON behaviour from a long while ago. I'll get it updated to support all the options in load.

**Comment by Yv-vY** [comment]
Thanks, I guess this will be a welcome update as I stumbled on this shortcoming of Oj that made my Gtk application crash at startup. The basic workaround was obviously to get Oj loaded after Gtk3 gem.
This will make Oj use more transparent :)

**Comment by ohler55** [comment]
Thanks for the patients. I've been dealing with a segfault but should be able to get to this one pretty soon as the segfault has been fixed and will be merged into develop.

**Comment by Yv-vY** [comment]
No worries, I've worked my way around by patching the red-color gem (loaded by the Gtk one) to use JSON.parse instead of JSON.load.
I'm just wondering how many users this shortcoming is impacting (obviously not that many as I'm the first to report the issue).

So take your time and thanks for the great job you're doing with Oj! :)

**Comment by ohler55** [comment]
I know it took a while but the symbolize-names branch has a fix. Please let me know if it works for you and I'll make a release.

**Comment by ohler55** [comment]
Released
