### ISSUE TITLE
`:allow_invalid_unicode` option not parsed / applied?

### ISSUE THREAD

**Issue by booleanbetrayal** [ohler55/oj#711]
We initialize Oj as following in a Rails 6.1 environment:

```
Oj.default_options = { mode: :rails }
Oj.optimize_rails()
```

After upgrading to `3.13.6` -> `3.13.7` several specs related to invalid JSON parsing / handling in our test suite break.

Updating our Oj initialization as following does not seem to revert the behavior:

```
Oj.default_options = { mode: :rails, allow_invalid_unicode: false }
Oj.optimize_rails()
```

FWIW, I'm seeing the new flag default in `mimic_parse_core`, but am not seeing where the option override is actually parsed following the `oj_hash_has_key` / `rb_hash_lookup` scheme.

**Comment by ohler55** [comment]
The option does not apply to Rails as the JSON gem does not support rejecting invalid unicode unless there is an option I'm not aware of. If there is let me know and I'll hook it up.

**Comment by booleanbetrayal** [comment]
So, it turns out that we were overriding `ActiveSupport::JSON` with a very specific targeting of invalid unicode characters we had seen across the wire. These were previously raising `JSON::ParserError` and we were subbing out unicode replacement characters for the invalid blocks of unicode.

I think for our application, we can now just rely on `JSON::ParserError` not being thrown, and can revert our custom handling, as invalid unicode shouldn't affect any downstream processing. Will confirm with our team, but regardless, this is out of scope for Oj. 

Thanks and sorry for any confusion!

**Comment by ohler55** [comment]
Glad you got it resolved. I wonder if it makes sense to have an option for Oj that basically says "allow all options in all modes". You aren't the first to want to change the JSON gem behaviour without resorting to the Oj custom mode. If you think it is worth discussing feel free to create discussion topic. (Discussions at the top of this page)

**Comment by booleanbetrayal** [comment]
Thanks @ohler55 ! Will discuss and will go that route if we think it's something we'd find valuable.
