### ISSUE TITLE
Decimal parsing using Oj::Parser seems strange

### ISSUE THREAD

**Issue by evanleck** [ohler55/oj#712]
Running the following snippet of code:

```ruby
require 'oj'

parser = Oj::Parser.new(:usual, cache_keys: true, cache_strings: 30, decimal: :bigdecimal, symbol_keys: false)
raw = %({"amount":0.10})
parsed = parser.parse(raw)

pp parsed
puts parsed['amount'].class
```

Yields a strange result when printing, specifically the size of the amount field:

```
{"amount"=>0.46427e-309}
BigDecimal
```

The `BigDecimal` class is as expected, but the amount seems ludicrously small. I stumbled upon this because I was getting strange results when printing BigDecimals in my own application.

This is using Oj version 3.13.7.

**Comment by ohler55** [comment]
Well that will have to be fixed.

Any feedback on the new parser otherwise?

**Comment by evanleck** [comment]
@ohler55 nope, it's been chugging along and working great!

**Comment by ohler55** [comment]
Excellent. I got 0 for the value which isn't right either. Will get it fixed tonight though. That's the plan anyway. :-)

**Comment by ohler55** [comment]
Looks like a compiler issue with `snprintf()` and long doubles. `sprintf()` seems to work though so switching to that.

**Comment by ohler55** [comment]
Released the fix.

**Comment by evanleck** [comment]
Looks good, thanks for getting that fixed so quickly!
