### ISSUE TITLE
Best place to put rails initialization code?

### ISSUE THREAD

**Issue by jjb** [ohler55/oj#713]
The rails docs https://github.com/ohler55/oj/blob/develop/pages/Rails.md don't say where to put `Oj.optimize_rails`. I was surprised to not find this anywhere but maybe because the obvious answer is "in an initializer". But for something like Oj I wonder if as soon as possible in the boot process has some benefits. I've put it right after `Bundler.require(*Rails.groups)` in application.rb, seems to do the trick. Thanks for any tips, I'll make a PR for the docs.

----
update

also: it's not totally clear to me in what circumstances Oj will be used instead of JSON. 

> The ActiveSupport decoder is the JSON.parse() method. Calling the Oj::Rails.set_decoder() method replaces that method with the Oj equivalent.

This seems to indicate that JSON will be taken over everywhere. Is that the case? I'm trying to poke around in console to test this but can't really think of a way to do so.

**Comment by ohler55** [comment]
I'm not a Rails developer so I can't help answer that. Sorry.

**Comment by jjb** [comment]
Thanks! I made this PR https://github.com/ohler55/oj/pull/714

**Comment by ohler55** [comment]
PR was merged. Thanks.
