### ISSUE TITLE
When using ActiveSupport passing a hash to JSON.dump changed behavior in Oj > 3.10.0

### ISSUE THREAD

**Issue by HeyNonster** [ohler55/oj#726]
Passing a Time object in a hash to JSON.dump used to match how Oj.dump would parse the object in `Oj < 3.10.0` but no longer in `Oj 3.10.1+`

Script to reproduce:

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "activesupport", "5.2.6"
  gem "oj", ENV.fetch('OJ_VERSION')
end

require "json"
require "oj"
if ENV['ACTIVE_SUPPORT']
  require "active_support/json"
  require "active_support/json/encoding"
  Oj.default_options = { mode: :rails}
  Oj.optimize_rails
else
  Oj.mimic_JSON
end

puts "Oj: #{Gem.loaded_specs["oj"].version}"
puts "ActiveSupport: #{Gem.loaded_specs["activesupport"].version}" if ENV.keys.include?("ACTIVE_SUPPORT")
puts


puts "--- HASH ---"
puts "JSON.dump({created_at: Time.now.utc}) => #{JSON.dump({created_at: Time.now.utc})}"
puts "Oj.dump({created_at: Time.now.utc})   => #{Oj.dump({created_at: Time.now.utc})}"
puts
puts "--- NO HASH ---"
puts "JSON.dump(Time.now.utc) => #{JSON.dump(Time.now.utc)}"
puts "Oj.dump(Time.now.utc)   => #{Oj.dump(Time.now.utc)}"
```

**Oj 3.10.0 without ActiveSupport**
```
> OJ_VERSION=3.10.0 ruby oj_test.rb
Oj: 3.10.0

--- HASH ---
JSON.dump({created_at: Time.now.utc}) => {"created_at":"2021-12-13 12:21:58 UTC"}
Oj.dump({created_at: Time.now.utc})   => {"created_at":"2021-12-13 12:21:58 UTC"}

--- NO HASH ---
JSON.dump(Time.now.utc) => "2021-12-13 12:21:58 UTC"
Oj.dump(Time.now.utc)   => "2021-12-13 12:21:58 UTC"
```

**Oj 3.10.0 _with_ ActiveSupport**
```
> OJ_VERSION=3.10.0 ACTIVE_SUPPORT=t ruby oj_test.rb
Oj: 3.10.0
ActiveSupport: 5.2.6

--- HASH ---
JSON.dump({created_at: Time.now.utc}) => {"created_at":"2021-12-13T12:24:12.781Z"}
Oj.dump({created_at: Time.now.utc})   => {"created_at":"2021-12-13T12:24:12.781Z"}

--- NO HASH ---
JSON.dump(Time.now.utc) => "2021-12-13 12:24:12 UTC"
Oj.dump(Time.now.utc)   => "2021-12-13T12:24:12.781Z"
```

**Oj 3.10.1 without ActiveSupport**
```
> OJ_VERSION=3.10.1 ruby oj_test.rb                 
Oj: 3.10.1

--- HASH ---
JSON.dump({created_at: Time.now.utc}) => {"created_at":"2021-12-13 12:25:55 UTC"}
Oj.dump({created_at: Time.now.utc})   => {"created_at":"2021-12-13 12:25:55 UTC"}

--- NO HASH ---
JSON.dump(Time.now.utc) => "2021-12-13 12:25:55 UTC"
Oj.dump(Time.now.utc)   => "2021-12-13 12:25:55 UTC"
```

**Oj 3.10.1 _with_ ActiveSupport**
```
> OJ_VERSION=3.10.1 ACTIVE_SUPPORT=t ruby oj_test.rb
Oj: 3.10.1
ActiveSupport: 5.2.6

--- HASH ---
JSON.dump({created_at: Time.now.utc}) => {"created_at":"2021-12-13 12:26:37 UTC"}
Oj.dump({created_at: Time.now.utc})   => {"created_at":"2021-12-13T12:26:37.370Z"}

--- NO HASH ---
JSON.dump(Time.now.utc) => "2021-12-13 12:26:37 UTC"
Oj.dump(Time.now.utc)   => "2021-12-13T12:26:37.370Z"

```

Note how `JSON.dump({created_at: Time.now.utc})` would consistently match the output of `Oj.dump({created_at: Time.now.utc})` (with or without ActiveSupport) until `Oj 3.10.1`.

**Comment by ohler55** [comment]
The first question that comes to mind is why are you setting Oj to rails mode and then comparing that to json instead of compat mode. Next, the version of Oj you are using is more than 2 years old. Have you tried the latest? Finally, looking at the release notes I see that 3.10.1 fixed a bug involving ActiveSupport encoding of time. Is that what you are seeing, the bug fix?

**Comment by ohler55** [comment]
Nice test suite though. You have the case covered very well and clearly.

**Comment by HeyNonster** [comment]
> The first question that comes to mind is why are you setting Oj to rails mode and then comparing that to json instead of compat mode

Good question! 😬 

> Nice test suite though. You have the case covered very well and clearly.

Thank you!

Going to close this and do more testing with other modes and the latest version until I can confidently determine this is an issue or not. 😅

**Comment by HeyNonster** [comment]
Update for anyone that ends up where we did:

My understanding is that with `Oj.optimize_rails` Oj will replace `JSON.dump` && `ActiveSupport::JSON.encode` with faster implementations written in C. Without `Oj.optimize_rails` Oj will provide fast `Oj.dump` methods but otherwise leave everything else alone.

Here's a demonstration with these Oj settings: `Oj.default_options = { mode: :rails, trace: true }`

```
# Oj version 3.10.0

#JSON.dump
JSON.dump(Time.now.utc)                                => "2022-01-11 12:17:36 UTC"

# ActiveSupport::JSON.encode
ActiveSupport::JSON.encode(Time.now.utc)               => "2022-01-11T12:17:36.614Z"

# Oj.dump
#0:      rails.c:1468:Oj:}: dump Time
#0:      rails.c:517:Oj:>:   as_json Time
#0:      rails.c:527:Oj:<:   as_json Time
#0:      rails.c:1468:Oj:}: dump String
#0:      rails.c:1479:Oj:{: dump String
#0:      rails.c:1479:Oj:{: dump Time
Oj.dump(Time.now.utc)                                  => "2022-01-11T12:17:36.614Z"
```

Notice above the `Oj.dump(Time.now.utc)` line. The `trace: true` Oj option gives you a window into what Oj is doing and you can see here that `Oj.dump` utilizes the fast C code. Notably, the file is `rails.c`. This is because we set `mode: :rails` in the `default_options` which tells Oj to render the JSON in the same format that ActiveSupport would.

Now, if we run the same code but add `Oj.optimize_rails`:

```
# Oj version 3.10.0

#JSON.dump
#0:dump_compat.c:940:Oj:}: dump Time
#0:dump_compat.c:965:Oj:{: dump Time
JSON.dump(Time.now.utc)                                => "2022-01-11 12:27:17 UTC"

# ActiveSupport::JSON.encode
#0:      rails.c:1468:Oj:}: dump Time
#0:      rails.c:1479:Oj:{: dump Time
ActiveSupport::JSON.encode(Time.now.utc)               => "2022-01-11T12:27:17.051Z"

# Oj.dump
#0:      rails.c:1468:Oj:}: dump Time
#0:      rails.c:1479:Oj:{: dump Time
Oj.dump(Time.now.utc)                                  => "2022-01-11T12:27:17.051Z"
```

Both `JSON.dump` and `ActiveSupport::JSON.encode` now run through faster C implementations. `JSON.dump`,
 however runs through the file `dump_compat.c` instead of `rails.c`. This is intended so that `JSON.dump` with Oj and `JSON.dump` _without_ Oj return the same time format, the Oj implementation is just faster.
 
 The bug in `Oj < 3.10.1` occured when you passed a Hash with time objects to `JSON.dump`
 
```
# Oj version 3.10.0

# JSON.dump
#0:dump_compat.c:940:Oj:}: dump Hash
#0:dump_compat.c:940:Oj:}:   dump Time
#0:dump_compat.c:123:Oj:>: to_json Time
#0:      rails.c:1468:Oj:}: dump Time
#0:      rails.c:1479:Oj:{: dump Time
#0:dump_compat.c:131:Oj:<: to_json Time
#0:dump_compat.c:965:Oj:{:   dump Time
#0:dump_compat.c:965:Oj:{: dump Hash
JSON.dump({created_at: Time.now.utc})                  => {"created_at":"2022-01-11T12:27:16.966Z"}
```

As you can see in the trace, `JSON.dump({created_at: Time.now.utc})` was running the code through both `dump_compat.c` _and_ `rails.c` and returning the Time in the ActiveSupport format when it was supposed to return the same format that the JSON standard library gem would.

This was fixed in `Oj 3.10.1` as you can see in the below trace:

```
# Oj version 3.10.1

# JSON.dump
#0:dump_compat.c:941:Oj:}: dump Hash
#0:dump_compat.c:941:Oj:}:   dump Time
#0:dump_compat.c:123:Oj:>: to_json Time
#0:dump_compat.c:131:Oj:<: to_json Time
#0:dump_compat.c:966:Oj:{:   dump Time
#0:dump_compat.c:966:Oj:{: dump Hash
JSON.dump({created_at: Time.now.utc})                  => {"created_at":"2022-01-11 12:34:36 UTC"}
```

`JSON.dump({created_at: Time.now.utc})` now exclusively uses the `dump_compat.c` file which was the intended behavior. Unfortunately, we had some code that relied on the time format produced by the buggy version of JSON.dump and that broke some things when we upgraded Oj.

Because Oj has to mimic the JSON standard library gem time format and, separately, mimic the ActiveSupport time format (both of which Oj has no control over, it just needs to adapt) we might write a test that catches whenever one the formats change.

**Comment by ohler55** [comment]
I'd like to keep these notes somewhere that people might see them more easily. I created a discussion topic for Rails and ActiveSupport. Would you mind adding this to that discussion? If not I'l copy it but it would be nice to have your name on it.

**Comment by HeyNonster** [comment]
:) Sure thing!
