### ISSUE TITLE
Serialization issue with Sidekiq

### ISSUE THREAD

**Issue by Pimentoso** [ohler55/oj#752]
Hi,

recent Sidekiq versions occasionally raise a warning about JSON serialization when using oj.

```
Job arguments to MyApp::RealtimeJob do not serialize to JSON safely. This will raise an error in
Sidekiq 7.0. See https://github.com/mperham/sidekiq/wiki/Best-Practices or raise an error today
by calling `Sidekiq.strict_args!` during Sidekiq initialization.
```

This is because the payload that is pushed on sidekiq is something like this

```
        {"queue"=>"development-default",
         "class"=>"MyApp::RealtimeJob",
         "args"=>[{"id"=>684}],
         "jid"=>"d44254e2a44b81570f9c5cd9",
         "created_at"=>1645714939.1176121}
```

And the check that is done to raise the warning is the following

```ruby
    def json_safe?(item)
      JSON.parse(JSON.dump(item["args"])) == item["args"]
    end
```

This is the file: https://github.com/mperham/sidekiq/blob/main/lib/sidekiq/job_util.rb

Using oj will cause the check to fail because the "created_at" float is rounded to 6 decimals
```
        {...
         "created_at"=>1645714939.117612}
```
Checking the code, the created_at value is `item["created_at"] ||= Time.now.to_f` which leads to 5,6, or 7 decimals randomly.

Sorry if this issue is too edge of a case. I was just wondering if something can be done about it or there's no way around the float rounding.

**Comment by ohler55** [comment]
The problem is really that floating points are not a reliable way to encode time. At 16 significant digits rounding sometimes causes an issue. Is there any chance you can change the encoded time to an integer value as the number of micro or nano seconds?

**Comment by Pimentoso** [comment]
Thanks for your reply. By looking at the code on sidekiq, that value seems to only be used to calculate job latency. I will open an issue over there to ask if it can be changed/rounded.
