### ISSUE TITLE
max_depth option behaviour changed in Oj >= v3.13.10

### ISSUE THREAD

**Issue by ggeverae** [ohler55/oj#770]
:wave: Hi! Thanks for sharing this gem!

We're running Oj on Ruby `ruby 2.7.6` together with Rails `6.1.6`. We run `Oj.optimize_rails` in an initializer and proceed to parse JSON data with `ActiveSupport::JSON.decode` further down in the app.

When we try upgrading from v3.13.9, `JSON::NestingError: Too deeply nested`  gets thrown in tests/production where there wasn't any problem before.

We've finally found the time to perform some detailed investigations and this is what came up:

### Change of behaviour in Oj >= v3.13.10

In #720 the option parsing code has been refactored in `oj/ext/oj/mimic_json.c` from:

```c
mimic_parse_core() {
  // ...
  pi.max_depth             = 100;

  if (Qnil != ropts) {
    //...

    // fetch oj_max_nesting_sym option from options hash
    v = rb_hash_lookup(ropts, oj_max_nesting_sym);
    if (Qtrue == v) {
      pi.max_depth = 100;
    } else if (Qfalse == v || Qnil == v) {
      // set max_depth to 0 if option was false, 'nil' or option was omitted
      pi.max_depth = 0;
    } else if (T_FIXNUM == rb_type(v)) {
      pi.max_depth = NUM2INT(v);
    }
    //...
  }
  //...
}
```

to

```c
parse_options_cb() {
  //...

  // check if options hash specifies oj_max_nesting_sym option
  } else if (oj_max_nesting_sym == k) {
    // if it does, override default
    if (Qtrue == v) {
        pi->max_depth = 100;
    } else if (Qfalse == v || Qnil == v) {
        pi->max_depth = 0;
    } else if (T_FIXNUM == rb_type(v)) {
        pi->max_depth = NUM2INT(v);
    }
  }
  //...
}

mimic_parse_core() {
  // ...
  pi.max_depth             = 100;

  if (Qnil != ropts) {
    //...
    rb_hash_foreach(ropts, parse_options_cb, (VALUE)&pi);
    //...
  }
  //...
}
```

The difference in behaviour thus being that calling `JSON.parse` with some options hash not containing a `max_nesting` key would originally reset `max_depth` to 0, whereas now it's kept at the default 100.

The original behaviour was probably an undocumented, internal feature, since the **test_nesting** spec in `oj/test/json_gem/json_parser_test.rb:259` didn't test for this case (passing options without the `max_nesting` key). The first assert (`assert_raise(JSON::NestingError) { JSON.parse too_deep }`) in the test returned on the first if check (checking whether or not an options hash was passed).

In any case, the `ActiveSupport::JSON.decode` method from Rails doesn't accept any params and always calls `JSON::parse` with an options hash sans `max_nesting`; thus being stuck with a max_depth of 100. Our personal solution would be to migrate from `ActiveSupport::JSON.decode` to `JSON.parse` and supply the max_nesting option where necessary. But we thought we'd report this in an issue to get some feedback (perhaps there is a way to set a default `max_nesting` parsing option?).

**Comment by Watson1978** [comment]
If the behavior keep compatible with Ruby standard JSON, then the current state is correct.

```ruby
require 'json'

too_deep = '[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[["Too deep"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]'
p JSON.parse too_deep, {}
```

```
$ ruby stdlib.rb 
/home/watson/.rbenv/versions/3.1.2/lib/ruby/3.1.0/json/common.rb:216:in `parse': nesting of 101 is too deep (JSON::NestingError)
        from /home/watson/.rbenv/versions/3.1.2/lib/ruby/3.1.0/json/common.rb:216:in `parse'
        from stdlib.rb:4:in `<main>'
```

```ruby
require 'oj'
puts "Oj version : #{Oj::VERSION}"
Oj.mimic_JSON

too_deep = '[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[["Too deep"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]'
p JSON.parse too_deep, {}
```

```
$ gem i oj -v 3.13.9
$ ruby oj.rb 
Oj version : 3.13.9
[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[["Too deep"]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
```
