### ISSUE TITLE
Oj.load_file can't open files which names have accented chars

### ISSUE THREAD

**Issue by cvjxendra** [ohler55/oj#772]
Windows 10, 64 bits

>  Oj.load_file 'Conceição1.json'

[1] pry> Oj.load_file 'Conceição1.json'
=> nil
[2] pry> File.exists? 'Conceição1.json'
=> true

**Comment by ohler55** [comment]
I'll look into it.

**Comment by ohler55** [comment]
I don't have a Windows machine to test on but I can say that it worked on MacOS which indicates there is some Windows specific unicode string handling. Are you able to open the file and then pass the file to Oj.load? Does that work as expected?

**Comment by cvjxendra** [comment]
>  Are you able to open the file and then pass the file to Oj.load? 

If I rename 'Conceição1.json' to 'Conceicao1.json', Oj works.
