### ISSUE TITLE
Latest rails 4.1 compatible version?

### ISSUE THREAD

**Issue by mhenrixon** [ohler55/oj#807]
I just tried to update a rails 4.1 project's oj gem to the latest version, but I have a ton of failing tests then. Any pointers towards compatibility or how to set up the gem to work with an older rails version would be much appreciated.

Ruby 2.3 for now.

I am trying to upgrade every dependency so I can eventually upgrade ruby on rails and then ruby. I figured the dependencies like the oj gem would be a great start.

**Comment by ohler55** [comment]
That goes back a ways. The latest version of Oj does not support Ruby 2.3 nor Rails 4.1. Trying to migrate one piece at a time is going to be painful. I'd suggest starting with a newer version of Ruby first followed by a newer rails and then add Oj when you have that completed. Trying to start with a newer Oj when Ruby and Rails are still so far behind is really the wrong way to approach the migration in my opinion.

**Comment by mhenrixon** [comment]
I respectfully disagree with that. Upgrading ruby immediately forces me to update a bunch of gems in the same PR. The I have a FrankenPR which is what I want to avoid. 

What would be the latest version I can use?

**Comment by ohler55** [comment]
I'm really not sure what the latest version that would work is. Looking at the rails releases it appears rails 5 came out in 2016 which was a bit before Oj 3.0.0 was released. I'd try Oj 3.0.4 and if that doesn't work drop back to Oj 2.18.3. Those are my best guesses based on the release notes of both active support and Oj.

**Comment by mhenrixon** [comment]
Thank you @ohler55, I'll give that a try!
