### ISSUE TITLE
Oj::Rails.set_decoder makes Oj.load throw JSON::ParserError

### ISSUE THREAD

**Issue by nametoolong** [ohler55/oj#816]
`Oj::Rails.set_decoder` changes the exception thrown by `Oj.load` to be `JSON::ParserError` under `:compat` or `:rails` mode. This is rather counterintuitive, especially when `Oj.optimize_rails` is called in the middle of the code (a bad practice by itself though). I would like to know if this is the expected behavior or not.

```
[1] pry(main)> Oj::VERSION
=> "3.13.20"
[2] pry(main)> Oj.load(",", mode: :compat)
EncodingError: Empty input (after ) at line 1, column 1 [parse.c:1116] in ',
from (pry):2:in `load'
[3] pry(main)> Oj::Rails.set_decoder
=> nil
[4] pry(main)> Oj.load(",", mode: :compat)
JSON::ParserError: Empty input (after ) at line 1, column 1 [parse.c:1116] in ',
from (pry):4:in `load'
```

**Comment by ohler55** [comment]
Any of the calls to Oj::Rails sets globals that make Oj mimic the JSON gem and Rails. It might have been a bad decision early on to follow the JSON gem and Rails use of globals. With the number of users currently I can't really change that behaviour but a new Oj::Parser was introduced so you can avoid the JSON gem Rails globals issue. Just create and customize the parser the way you like and use that for non-rails things. The new parser is also a bit faster.

**Comment by nametoolong** [comment]
Thanks. The new parser seems very helpful for handling JSON from different sources.
