### ISSUE TITLE
"Unset" Oj

### ISSUE THREAD

**Issue by rwehresmann** [ohler55/oj#820]
Is there a way to unset Oj? Something that reverts `Oj.optimize_rails()` to return to the default encoders. 

I would like to test Oj in some places of my application first instead of the whole app, and I'm looking for the best way to achieve this.

**Comment by ohler55** [comment]
Rails uses globals for the encoders and attaches some directly to the classes. The only way to revert would be to get rails to reapply the changes it makes. I don't think there is an API to do that.
