### ISSUE TITLE
3.13.17 - Oj.load method takes cpu to 100% and doesn't return on malformed JSON strings

### ISSUE THREAD

**Issue by martinwaite** [ohler55/oj#839]
I hit this problem in recent versions of td-agent.  Using the tail component with the Oj parser caused fluentd to become unresponsive when it encountered certain lines in a file - and not even ctrl-C could stop it.

The following case causes irb to become unresponsive and cpu to climb:
```
require 'oj'
s = "{\"f1\":\"data\\nW\x0\"}\r\n"
j = Oj.load(s)
```

I tested this on newer versions up 3.13.23 and 3.14.0 (to the best of my ability), and it seems the problem is in these versions too.

This was tested on a td-agent 4.4.2 environment
`ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-linux]`

**Comment by ohler55** [comment]
I'll take a look this evening and see if the illegal character sequence is causing the issue. I would expect an error to be raised.

**Comment by ohler55** [comment]
Please try the develop branch. It has a fix.

**Comment by martinwaite** [comment]
Thanks - the Develop version has fixed the problem.  

I installed it in td-agent to test it against the datafile that hit the problem, and the file is completely processed with fluentd reporting errors for lines with malformed JSON - as expected.
