### ISSUE TITLE
oj 3.14.1 tests fail on armel/armhf

### ISSUE THREAD

**Issue by boutil** [ohler55/oj#843]
Hi,

Building oj 3.14.1 on Debian architectures gives 22 failing tests on armhf and armel architectures:
https://buildd.debian.org/status/fetch.php?pkg=ruby-oj&arch=armel&ver=3.14.1-1&stamp=1675783705&raw=0

They have either:

`EncodingError: quoted string not terminated (after subtext) ...  [parse.c:243]`
(most of the time)
or

`EncodingError: Empty input (after ) ... [parse.c:1119]`

Let me know if I can help debugging this issue by running additional tests or commands.

**Comment by ohler55** [comment]
Did the tests pass with the previous version of Oj?

**Comment by boutil** [comment]
The previous version uploaded in Debian archive was 3.13.23, and all tests were passing on all architectures.

**Comment by boutil** [comment]
This https://github.com/ohler55/oj/commit/44ba3291a2a6f785a83abe18bd7fdaf0b01daf65 is the last commit with all tests passing on these architecture. The next one https://github.com/ohler55/oj/commit/1aae1245991035cb557f1e289d3682adc5b8221a causes the 22 failures.

**Comment by ohler55** [comment]
Thanks

**Comment by ohler55** [comment]
I created a "Debian-debug" branch with a reversion to one line that might be and issue. Shouldn't be but trying to narrow down the issue. This should effect the CompatJuice#test_parse_large_string test.

**Comment by boutil** [comment]
I could not find this branch on GitHub. Maybe you haven't pushed it yet?

**Comment by boutil** [comment]
With the change on that branch, all tests are now passing on armhf and armel.
Can this change be directly applied as a patch on top of the current version, or do you need to make further adjustments?
(there is a clock ticking on Debian's side: if we want to have 3.14 in the next Debian release, we should upload a fix for the test failures by tomorrow...)

**Comment by ohler55** [comment]
Sadly the change was made to fix an issue with embedded `\0` characters. I need to figure out why that affects Debian. I'll be looking at it tonight.

**Comment by boutil** [comment]
thanks a lot!

**Comment by ohler55** [comment]
Can you check the Makefile that is generated for Debian and see if `OJ_USE_SSE4_2` is defined? If so maybe not defining it will resolve the issue.

**Comment by ohler55** [comment]
Push a change that could fix the issue.

**Comment by pravi** [comment]
Thanks, the tests are passing now https://buildd.debian.org/status/fetch.php?pkg=ruby-oj&arch=armel&ver=3.14.1-3&stamp=1676045200&raw=0

**Comment by ohler55** [comment]
Excellent. I'll release tonight then.

**Comment by ohler55** [comment]
Released
