### ISSUE TITLE
Inconsistent behavior for malformed utf-8

### ISSUE THREAD

**Issue by joshrickardkenna** [ohler55/oj#867]
Hello,

Similar to issue #600 I just wanted to check if this is intended behavior or a bug:

```
"\xAE".to_json
JSON::GeneratorError: source sequence is illegal/malformed utf-8

Oj.optimize_rails
=> nil

"\xAE".to_json
=> "\"\xAE\""
```

Oj version 3.14.2
Ruby 2.7.6p219
Rails 5.2.8.1

Thanks

**Comment by ohler55** [comment]
Oj attempts to be compatible with the most recent versions of rails with the most recent version of ruby. In the most recent of all an exception is raised. I gave up trying to support the various behaviours for all version combinations a while ago. Please try the latest rails and ruby. I just did and an exception was raised as expected.

**Comment by joshrickardkenna** [comment]
> Oj attempts to be compatible with the most recent versions of rails with the most recent version of ruby. In the most recent of all an exception is raised. I gave up trying to support the various behaviours for all version combinations a while ago. Please try the latest rails and ruby. I just did and an exception was raised as expected.

Fair enough, thanks for taking a look!
