### ISSUE TITLE
Dump json string

### ISSUE THREAD

**Issue by PetrKaleta** [ohler55/oj#87]
```
h = { :id => 1, :data => '{"foo":"bar"}' }
```

Is there any way how to tell Oj, that dump of this hash should produce

```
 {"id":1,"data":{"foo":"bar"}}
```

So that `:data` is already JSON string and it should simply take its value... Is there some way, how to do that? I don't want to load that data to be able to dump it the way I need...

**Comment by jviney** [comment]
Is there any way to achieve this when using the :object serialization method?

I have a nested data structure that has some quite large JSON fields. Deserializing and reserializing these fields adds a lot of extra time. Being able to pass through the string which we know is valid JSON would be ideal.

Perhaps the string could be wrapped in some way that signals to Oj it is already JSON encoded?

**Comment by ohler55** [comment]
Oj does support that although maybe not exactly the way you want. If the object responds to `to_raw` and the `use_raw_json` option is true the raw JSON will be written. That means the JSON string will need to implement the `to_raw` so you will have to wrap the string in some way.

The deserialization is tougher since there is no indicator that some portion of the dumped JSON should be treated as a string.

**Comment by jviney** [comment]
Fantastic - that looks great. Does using the :compat mode incur much of a performance penalty over :object? I did a quick benchmark and the answer seems to be no.

**Comment by ohler55** [comment]
Not much difference really. The encoding is different though. There is also the custom mode for more options. One thing that does make a difference is using the `to_json` or `as_json` options as that drops into Ruby to do the encoding. If you are not using Rails I would recommend letting the object mode do the encoding for marshalling.

**Comment by jviney** [comment]
This is in a Rails app, but we are doing a more manual process of data loading and serialization for better performance.

I had been using `mode: :object` with `escape_mode: :xss_safe` but that doesn't support `:use_raw_json`. I switched to 'mode: :compat` but now the XSS escaping doesn't work. For this use case we don't actually need the XSS escaping - I just had it there to more closely match Rails' serialization.

Is there a way to have both `use_raw_json` and XSS escaping?

**Comment by ohler55** [comment]
`:custom` mode has all the options.
