### ISSUE TITLE
Not initialised stack_buffer

### ISSUE THREAD

**Issue by dundee** [ohler55/oj#892]
Hi,
I am sorry for probably very dumb question since I don't know C very well, but we are investigating very weird behaviour of JSON serialisation (data busted randomly) and OJ is the main suspect right now.

Is it ok that [`stack_buffer`](https://github.com/ohler55/oj/blob/904d80c5ea01a57aae795c161641f8164aface73/ext/oj/oj.h#L191) is not initialised inside the [`encode`](https://github.com/ohler55/oj/blob/904d80c5ea01a57aae795c161641f8164aface73/ext/oj/rails.c#L872) function?

I can see a call to `oj_out_init` but `stack_buffer` is not initialised there, it's [used](https://github.com/ohler55/oj/blob/904d80c5ea01a57aae795c161641f8164aface73/ext/oj/dump.c#L947) right away.

Thanks!

**Comment by ohler55** [comment]
It is okay not to be initialized since the pointers to the start of the buffer are set at 0 indicating there is no data in the buffer yet.

Can you give more details about the issue you are seeing?

**Comment by dundee** [comment]
We can see a random string data being inserted into the resulting JSON string. It happened only in few occurrences though.

I probably get what you mean. The dirty data could be there, but since `cur` is set to beginning of the array we doesn't care what is further.

**Comment by ohler55** [comment]
If you can help me recreate the issue I can get it fixed.

**Comment by dundee** [comment]
Closing. If I am able to reproduce it, I will post more details. Thank you!

**Comment by dundee** [comment]
We have found out that the problem was not limited to OJ serialisation. It was a general data corruption issue caused by faulty HW node.
