### ISSUE TITLE
Optimize JSON for pub sub transmission?

### ISSUE THREAD

**Issue by jmb-mage** [ohler55/oj#902]
Request

JSON documents themselves could be optimized when used in a pub sub pattern as transmission packets.
The goal is to create a single json meta data file for serialization and deserialization to be spread to every node.  The json documents that are sent repeatedly are optimized and even compressed

* Serializer methods create a json meta data file 
* Deserializer methods load json meta data file once (and once again if model changes)
* json meta data file aids with serializing and deserializing
* Key mapping exists in json meta data.
* Keys can be replaced with shorter keys, ex: `"UserName": "Jonathan"` becomes `"a": "Jonathan"`. 
* Null or empty values do not need to be serialized and deserializer will assume they are null
* Compression like zip?

**Comment by ohler55** [comment]
This is really out of scope for a JSON parser. It is really an application level feature or at least a library on top of Oj.
