### ISSUE TITLE
Parser options documentation formatting error

### ISSUE THREAD

**Issue by semaperepelitsa** [ohler55/oj#903]
Is it possible to fix the formatting? This is from the official documentation website:
http://www.ohler.com/oj/doc/Oj/Parser.html

![Screenshot 2023-11-21 at 15 30 17](https://github.com/ohler55/oj/assets/347921/2625e676-776d-4f2c-82d7-a3463b148883)

**Comment by ohler55** [comment]
It looks like the clang-formatter and the yardoc don't get along well with each other. I'll see what I can do.

**Comment by ohler55** [comment]
Your suggestion on the combining of foo and foo= makes sense. I'll do that tonight.
