### ISSUE TITLE
BigDecimal 3.1 dependency brings excessive memory usage

### ISSUE THREAD

**Issue by broksonic21** [ohler55/oj#907]
oj 3.1.2 is a patch version, but takes on a new dependency on BigDecimal 3.1. That version has significant memory issues -> we are unable to get any builds done with it due to https://github.com/ruby/bigdecimal/issues/222

Two things:
* my belief is new dependencies shouldn't be introduced by patch versions
* can the version be relaxed so you aren't dependant on a buggy version of BigDecimal?

Thanks!

**Comment by broksonic21** [comment]
Second related ticket: https://github.com/ruby/bigdecimal/issues/271

**Comment by broksonic21** [comment]
On our end, we've had no issues with 3.0. 3.1 is where memory leaks and seg faults come in.

**Comment by ohler55** [comment]
I can relax the requirement to 
```
  s.add_runtime_dependency 'bigdecimal', '>= 3.0'
```

Does that work?

**Comment by broksonic21** [comment]
on my end, yes - thanks!

**Comment by ohler55** [comment]
I'll make a release tonight.

**Comment by ohler55** [comment]
released
