### ISSUE TITLE
How do you get Oj to dump a big decimal as a number not in scientific notation?

### ISSUE THREAD

**Issue by pjb3** [ohler55/oj#917]
Shouldn't this output the value as a number, not a string?

```
$ irb -r oj
>> puts(Oj.dump({ price: BigDecimal("1.25") }, mode: :compat, bigdecimal_as_decimal: true))
{"price":"0.125e1"}
=> nil
>> Oj::VERSION
=> "3.16.3"
>> RUBY_VERSION
=> "3.3.0"
```

And also, how do I get it to output it as `{"price": 1.25}` and not `{"price": 0.125e1}`?

**Comment by ohler55** [comment]
You control that with the options. Check out the `:bigdecimal_as_decimal` option.

**Comment by pjb3** [comment]
@ohler55 But in that code I posted above I'm passing `bigdecimal_as_decimal` as true to that call to dump, right? Shouldn't that make it output as a number and not a string?

**Comment by pjb3** [comment]
Setting it as a default option doesn't seem to be working either:

```
$  irb -r oj
>> Oj.default_options = { mode: :compat, bigdecimal_as_decimal: true }
=> {:mode=>:compat, :bigdecimal_as_decimal=>true}
>> puts(Oj.dump({ price: BigDecimal("1.25") }))
{"price":"0.125e1"}
```

**Comment by ohler55** [comment]
Right but you also specified `:compat` which overrides `: bigdecimal_as_decimal` since the behavior of the JSON gem is to emit a string.

**Comment by pjb3** [comment]
ah, ok but then without that there is a colon in the name of the key:

```
>> puts(Oj.dump({ price: BigDecimal("1.25") }, bigdecimal_as_decimal: true ))
{":price":0.125e1}
```

How do I get rid of that? And also is there a way to get it to output `1.25` instead of `0.125e1`?

**Comment by ohler55** [comment]
Try the other modes. :custom should be more friendly. As for getting BigDecimal to emit non-scientific I'm not sure. That's really a characteristic of BigDecimal.

**Comment by pjb3** [comment]
Ok, this seems to work:

```
$ irb -r oj
>> class BigDecimal; def to_json(*); to_f.to_s; end; end
=> :to_json
>> puts(Oj.dump({ price: BigDecimal("1.25") }, mode: :compat))
{"price":1.25}
```

**Comment by ohler55** [comment]
That would work, yes.

**Comment by pjb3** [comment]
:+1:
