### ISSUE TITLE
Error when dumping Hash with `Time` value and numeric `:indent` option

### ISSUE THREAD

**Issue by fnordfish** [ohler55/oj#933]
I've noticed this issue on v3.11.5, but it is also present in v3.16.5

```
irb(main):001:0> Oj::VERSION
=> "3.16.5"
irb(main):002:0> Oj.dump({foo: "bar"}, indent: 2)
=> "{\n  \"foo\":\"bar\"\n}\n"
irb(main):003:0> Oj.dump({foo: "bar", time: Time.now}, indent: 2)
(irb):3:in `initialize': wrong argument type Integer (expected String) (TypeError)
    from (irb):3:in `new'
    from (irb):3:in `to_json'
    from (irb):3:in `dump'
    from (irb):3:in `<main>'
    from bin/console:11:in `<main>'
irb(main):004:0> Oj.dump({foo: "bar", time: Time.now}, indent: "  ")
=> "{  \"foo\":\"bar\",  \"time\":\"2024-08-09 09:36:19 +0000\"}"
```

```ruby
Oj.default_options
{:indent=>0,
 :second_precision=>9,
 :circular=>false,
 :class_cache=>true,
 :symbol_keys=>false,
 :bigdecimal_as_decimal=>nil,
 :create_additions=>false,
 :use_to_json=>false,
 :use_to_hash=>false,
 :use_as_json=>false,
 :use_raw_json=>false,
 :nilnil=>false,
 :empty_string=>true,
 :allow_gc=>true,
 :quirks_mode=>true,
 :allow_invalid_unicode=>false,
 :allow_nan=>true,
 :trace=>false,
 :safe=>false,
 :float_precision=>16,
 :ignore_under=>false,
 :mode=>:compat,
 :integer_range=>nil,
 :escape_mode=>:json,
 :time_format=>:unix_zone,
 :bigdecimal_load=>:auto,
 :compat_bigdecimal=>false,
 :create_id=>"json_class",
 :space=>nil,
 :space_before=>nil,
 :object_nl=>nil,
 :array_nl=>nil,
 :nan=>:auto,
 :omit_nil=>false,
 :hash_class=>nil,
 :array_class=>nil,
 :ignore=>nil}
```

**Comment by ohler55** [comment]
Looking into it.

**Comment by ohler55** [comment]
I just tested v3.16.5 on MacOS and it worked as expected.

```ruby
Oj.dump({foo: "bar", time: Time.now}, indent: 2)
=> "{\n  \"foo\":\"bar\",\n  \"time\":\"2024-08-10 20:30:43 -0400\"\n}\n"
```

What OS are you using? Lets figure out how our systems are different so I can get this working for you.

**Comment by fnordfish** [comment]
I've tested it on macOS Ruby 3.3 and a docketed Linux Runy 3.0

I have noticed, that it doesn't error in in custom mode, but does in compat. Haven't tested other modes. 

Happy to do some more digging

**Comment by ohler55** [comment]
I just tried Ruby 3.3.4 and MacOS and it worked in :compat mode. I'll be on the road for a couple of days but can try linux after that. 

Have you loaded any other gems or rails?

How about hardware? I've been using an M1.

**Comment by fnordfish** [comment]
No worries.
You are right, it seems to be an issue with my bundle, because that works:

```
ruby -v -roj -e 'puts Oj::VERSION; Oj.default_options = {mode: :compat}; puts Oj.dump({foo: "bar", time: Time.now}, indent: 2)'
ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [aarch64-linux]
3.16.5
{
  "foo":"bar",
  "time":"2024-08-11 16:06:20 +0000"
}
```

I'll try to go through my loads order and see when it breaks and create a minimal reproducible script. 
No Rails, M3 Mac.

**Comment by fnordfish** [comment]
```ruby
require "oj"
require "i18n"

puts "Oj: #{Oj::VERSION}"
puts "I18n: #{I18n::VERSION}"

# This line triggers the error
I18n::Backend::Simple.include(I18n::Backend::Pluralization)

puts Oj.dump({foo: "bar", time: Time.now}, mode: :compat, indent: 2)
```

```
ruby -v tmp/ojtest.rb
ruby 3.3.4 (2024-07-09 revision be1089c8ec) [arm64-darwin23]
Oj: 3.16.3
I18n: 1.14.5
tmp/ojtest.rb:10:in `initialize': wrong argument type Integer (expected String) (TypeError)

puts Oj.dump({foo: "bar", time: Time.now}, mode: :compat, indent: 2)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	from tmp/ojtest.rb:10:in `new'
	from tmp/ojtest.rb:10:in `to_json'
	from tmp/ojtest.rb:10:in `dump'
	from tmp/ojtest.rb:10:in `<main>'
```

**Comment by fnordfish** [comment]
Indeed anything that initializes `I18n` somehow triggers the error.

```ruby
# Instead of
I18n::Backend::Simple.include(I18n::Backend::Pluralization)

# This also triggers
I18n.load_path += [File.expand_path("en.yml", __dir__)]

# Or this
I18n.backend
```

**Comment by ohler55** [comment]
That would explain the behavior. Since `:compat` mode always sets the `:use_to_json` to true as that is required to be JSON gem compatible. Unfortunately Oj started out with the `:indent` option being an integer but the JSON gem has the same option that expects a string. The JSON gem also requires that the arguments to the `to_json` method be the same as those passed to the generate or in this case the dump method. The conflict is then in the monkey patched Time class. There is not a good work around if you want to both pass a string indent to `to_json` and also to Oj. You can however set the indent in the Oj default options which will avoid sending the indent option to the `Time.to_json` call.

**Comment by fnordfish** [comment]
Sadly, that makes a lot of sense. 
I'm pondering if there would be any way to make this more discoverable. Either in the documentation, or printing a special error message when running into this.

Anyways, I think this can be closed then?

**Comment by ohler55** [comment]
Maybe somewhere in the docs although it is pretty obscure and I've found many people skip ready the docs. How about we close this and if you find a place in the docs that it would fit submit a PR with the change.

**Comment by fnordfish** [comment]
👍
