### ISSUE TITLE
Using the :space option in conjunction with the :indent option fails to actually indent in :compat mode

### ISSUE THREAD

**Issue by mainmethod** [ohler55/oj#935]
I'm attempting to format some JSON output to basically be indented with 4 spaces, and to also have a space after the `:` character of the keys.  Since it seems the :compat mode supports both, I'd expect it to add the indents as well as the space, but that doesn't appear to be the case.

```
irb(main):004> obj = {one: 'one', two: ['1', '2'], x: { y: 'y'}}
=> {:one=>"one", :two=>["1", "2"], :x=>{:y=>"y"}}
irb(main):005> output = Oj.dump(obj, mode: :compat, indent: 4)
=> "{\n    \"one\":\"one\",\n    \"two\":[\n        \"1\",\n        \"2\"\n    ],\n    \"x\":{\n        \"y\":\"y\"\n    }\n}\n"
irb(main):006> output = Oj.dump(obj, mode: :compat, indent: 4, space: ' ')
=> "{\"one\": \"one\",\"two\": [\"1\",\"2\"],\"x\": {\"y\": \"y\"}}\n"
```

so for `Oj.dump(obj, mode: :compat, indent: 4, space: ' ')`

Expected output:
```
"{\n    \"one\": \"one\",\n    \"two\": [\n        \"1\",\n        \"2\"\n    ],\n    \"x\" :{\n        \"y\": \"y\"\n    }\n}\n"
```

Actual output:
```
"{\"one\": \"one\",\"two\": [\"1\",\"2\"],\"x\": {\"y\": \"y\"}}\n"
```

`ruby v3.3.0`
`m2 mac pro`

I love the gem, but let me know if there is a way to accomplish what I'm trying to do, or if I'm just missing something obvious.
Thanks!

**Comment by ohler55** [comment]
In all but `:object` mode the following should work:

```ruby
Oj.dump(obj, mode: :compat, indent: '    ', space: ' ', space_before: ' ')
```

**Comment by mainmethod** [comment]
> In all but `:object` mode the following should work:
> 
> ```ruby
> Oj.dump(obj, mode: :compat, indent: '    ', space: ' ', space_before: ' ')
> ```

though it's close, this does not add the proper `\n` characters you receive with `indent: 4`.  also using `indent: '    \n'` does not produce desired results either

```
irb(main):005> Oj.dump(obj, mode: :compat, indent: '    ', space: ' ')
=> "{    \"one\": \"one\",    \"two\": [        \"1\",        \"2\"    ],    \"x\": {        \"y\": \"y\"    }}"
```

```
irb(main):006> Oj.dump(obj, mode: :compat, indent: '    \n', space: ' ')
=> "{    \\n\"one\": \"one\",    \\n\"two\": [    \\n    \\n\"1\",    \\n    \\n\"2\"    \\n],    \\n\"x\": {    \\n    \\n\"y\": \"y\"    \\n}}"
```

**Comment by Watson1978** [comment]
When dealing with characters like \n, Ruby will behave differently depending on whether you use single or double quotes:

```
irb(main):011> puts "abc \n def"
abc 
 def
=> nil
irb(main):012> 
irb(main):013> puts 'abc \n def'
abc \n def
=> nil
```

**Comment by mainmethod** [comment]
> Please take a look at the documentation at https://ohler.com/oj/doc/Oj.html. Search for ".to_json". The options, while not formatted well describe the various options that are available to be compatible with the JSON gem.
> 
> ```ruby
> Oj.dump(obj, mode: :compat, indent: '    ', space: ' ', space_before: ' ', object_nl: "\n", array_nl: "\n")
> ```

`object_nl` and `array_nl` were the missing pieces. thank you!
