### ISSUE TITLE
`Oj::StringWriter#as_json` does not accept the optional argument `options`

### ISSUE THREAD

**Issue by hovsater** [ohler55/oj#938]
The `as_json` interface has an optional argument, `options` that defaults to `nil`. As it stands now, `Oj::StringWriter` can't be used a value as Rails will provide an argument as it calls `as_json` on the writer itself. This causes an error to occur:

```
wrong number of arguments (given 1, expected 0) (ArgumentError)
```

Would it make sense to just accept the argument, but ignoring it completely? By the looks of it, that's how many other data structures handles it.

**Comment by ohler55** [comment]
That is a reasonable request. I can make the #as_json method take variable arguments. Traveling now but will plan on getting to it next week.

**Comment by hovsater** [comment]
Great, @ohler55. Appreciate it. 🙂

**Comment by ohler55** [comment]
Please try the "string-writer-as-json" branch.

**Comment by ohler55** [comment]
Merged the branch into develop. It will go out in the next release. No response here so closing.

**Comment by hovsater** [comment]
@ohler55 sorry for the late response, I read your message last week, and forgot to write back to you. At first glance, it looks like exactly what I was after. I'll report back as I get to work tomorrow. 🙂

Appreciate the effort!

**Comment by hovsater** [comment]
Seems to be working nicely!
